---
permalink: install-ip/concept_considerations_tdm_encryption.html 
sidebar: sidebar 
keywords: differences, eight-node, four-node, fabric-attached, stretch, metrocluster ip, storage, bridges, fc-to-sas, atto, fibrebridge, SAS, local HA, auso, automatic unplanned switchover, array luns, mediator, tiebreaker 
summary: 您应了解在 MetroCluster IP 配置中使用多路复用设备的某些注意事项。 
---
= 将 TDM/xWDM 和加密设备与 MetroCluster IP 配置结合使用
:icons: font
:imagesdir: ../media/


[role="lead"]
您应了解在 MetroCluster IP 配置中使用多路复用设备的某些注意事项。

这些注意事项仅适用于直接的专用 MetroCluster 后端链路和交换机，而不适用于与非 MetroCluster 流量共享的链路。

Hardware Universe 工具提供了一些有关 TDM/xWDM 设备在使用 MetroCluster IP 配置时必须满足的要求的说明。

https://hwu.netapp.com["NetApp Hardware Universe"]



== 对 WDM 或外部加密设备使用加密

在 MetroCluster IP 配置中对 WDM 设备使用加密时，您的环境必须满足以下要求：

* 外部加密设备或 DWDM 设备必须已通过相关交换机的供应商认证。
+
此认证应涵盖操作模式（例如中继和加密）。

* 包括加密在内的整体端到端延迟和抖动不能高于 IMT 或本文档中规定的最大值。




== SFP 注意事项

MetroCluster ISL 支持设备供应商支持的任何 SFP 或 QSFP 。SFP 和 QSFP 可以从 NetApp 或设备供应商处购买。



== ISL 注意事项

一个网络结构上的 ISL 应具有相同的速度和长度。

一个网络结构上的 ISL 都应具有相同的拓扑。例如，它们都应为直接链路，或者如果配置使用 WDM ，则它们都应使用 WDM 。

如果要与非 MetroCluster 网络共享 ISL ，则必须遵循一节中的准则 link:concept_considerations_layer_2.html["共享私有第 2 层网络的注意事项"]。

网络结构 1 和网络结构 2 之间支持的最大距离差为 20 公里
