---
permalink: install-ip/concept_considerations_mediator.html 
sidebar: sidebar 
keywords: differences, eight-node, four-node, fabric-attached, stretch, metrocluster ip, storage, bridges, fc-to-sas, atto, fibrebridge, SAS, local HA, auso, automatic unplanned switchover, array luns, mediator, tiebreaker 
summary: 各种 MetroCluster 配置在所需组件方面存在主要差异。 
---
= ONTAP 调解器与 MetroCluster Tiebreaker 之间的区别
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
从 ONTAP 9.7 开始，您可以在 MetroCluster IP 配置中使用 ONTAP 调解器辅助自动计划外切换（ MAUSO ），也可以使用 MetroCluster Tiebreaker 软件。不需要使用MAUSO或Tieber4软件；但是、如果您选择不使用其中任一服务、则必须使用 link:../disaster-recovery/concept_dr_workflow.html["执行手动恢复"] 发生灾难时。

不同的 MetroCluster 配置会在不同情况下执行自动切换：

* * 使用 AUSO 功能的 MetroCluster FC 配置（在 MetroCluster IP 配置中不存在） *
+
在这些配置中，如果控制器发生故障，但存储（和网桥，如果存在）仍可运行，则会启动 AUSO 。

* *使用 ONTAP Mediator 的 MetroCluster IP 配置（ONTAP 9.7 及更高版本）*
+
在这些配置中， MAUSO 会在与 AUSO 相同的情况下启动，如上所述，也会在站点完全发生故障（控制器，存储和交换机）后启动。

+
link:concept-ontap-mediator-supports-automatic-unplanned-switchover.html["了解ONTAP调解器如何支持自动计划外切换"]。

* * 在活动模式下使用 Tiebreaker 软件的 MetroCluster IP 或 FC 配置 *
+
在这些配置中， Tiebreaker 会在站点完全发生故障后启动计划外切换。

+
在使用 Tiebreaker 软件之前，请查看 link:../tiebreaker/concept_overview_of_the_tiebreaker_software.html["MetroCluster Tiebreaker 软件安装和配置"]





== ONTAP 调解器与其他应用程序和设备的互操作性

您不能使用可与 ONTAP 调解器结合使用触发切换的任何第三方应用程序或设备。此外，使用 ONTAP 调解器时，不支持使用 MetroCluster Tiebreaker 软件监控 MetroCluster 配置。
