---
permalink: install-ip/concept_considerations_drive_assignment.html 
sidebar: sidebar 
keywords: drive auto-assignment, drive, adp, advanced disk partitioning, root disk, unmirrored root, data partition, root partition, shelf-by-shelf, AFF A320, AFF A220, AFF A250, C250, AFF A300, AFF A400, C400, AFF A700, AFF A800, FAS2750, FAS8200, FAS500f, FAS9000 
summary: 从 ONTAP 9.4 开始， MetroCluster IP 配置支持使用 ADP （高级驱动器分区）对 AFF 系统进行新安装。 
---
= ONTAP 9.4 及更高版本中的自动驱动器分配和 ADP 系统注意事项
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
从ONTAP 9.4开始、MetroCluster IP配置支持使用自动磁盘分配和ADP (高级驱动器分区)进行新安装。

在将ADP与MetroCluster IP配置结合使用时、您应注意以下注意事项：

* 要在AFF和ASA系统上将ADP与MetroCluster IP配置结合使用、需要使用ONTAP 9.4及更高版本。
* MetroCluster IP配置支持ADPv2。
* 对于两个站点上的所有节点、根聚合必须位于分区3中。
* 在初始配置MetroCluster站点期间、系统会自动执行分区和磁盘分配。
* 池 0 磁盘分配在出厂时已完成。
* 未镜像的根在出厂时已创建。
* 数据分区分配在设置操作步骤期间在客户站点上完成。
* 大多数情况下，驱动器分配和分区会在设置过程中自动完成。
* 磁盘及其所有分区必须归同一个高可用性(HA)对中的节点所有。单个驱动器中的分区或驱动器所有权不能在本地HA对与灾难恢复(DR)配对节点或DR辅助配对节点之间混合使用。
+
支持的配置示例：

+
|===


| 驱动器/分区 | 所有者 


| 驱动器： | `ClusterA-Node01` 


| 分区1： | `ClusterA-Node01` 


| 分区2： | `ClusterA-Node02` 


| 分区3： | `ClusterA-Node01` 
|===



NOTE: 从 ONTAP 9.4 升级到 9.5 时，系统会识别现有的磁盘分配。



== 自动分区

ADP会在系统初始配置期间自动执行。


NOTE: 从ONTAP 9.5开始、必须使用启用磁盘自动分配 `storage disk option modify -autoassign on` 命令：

必须将ha-config状态设置为 `mccip` 在自动配置之前、请确保选择正确的分区大小、以支持适当的根卷大小。有关详细信息，请参见 link:task_sw_config_verify_haconfig.html["验证组件的 ha-config 状态"]。

在安装期间，最多可以自动对 96 个驱动器进行分区。您可以在初始安装后添加额外的驱动器。

[NOTE]
====
如果您使用的是内部和外部驱动器、则首先使用ADP仅使用内部驱动器初始化MetroCluster。完成安装或设置任务后、您可以手动连接外部磁盘架。

您必须确保内部磁盘架具有中所述的建议的最小驱动器数 <<adp-disk-assign,系统的ADP和磁盘分配差异>>。

对于内部驱动器和外部驱动器、必须按照中所述填充部分已满的磁盘架 <<populate-partially-full-shelves,如何填充部分满的磁盘架>>。

====


== 磁盘架自动分配的工作原理

如果每个站点有四个外部磁盘架，则会将每个磁盘架分配给不同的节点和不同的池，如以下示例所示：

* site_A-shelf_1 上的所有磁盘会自动分配到 node_A_1 的池 0
* site_A-shelf_3 上的所有磁盘会自动分配到 node_A_2 的池 0
* site_B-shelf_1 上的所有磁盘都会自动分配到 node_B_1 的池 0
* site_B-shelf_3 上的所有磁盘都会自动分配到 node_B_2 的池 0
* site_B-shelf_2 上的所有磁盘都会自动分配给 node_A_1 的池 1
* site_B-shelf_4 上的所有磁盘都会自动分配到 node_A_2 的池 1
* site_A-shelf_2 上的所有磁盘都会自动分配到 node_B_1 的池 1
* site_A-shelf_4 上的所有磁盘会自动分配到 node_B_2 的池 1




== 如何填充部分满的磁盘架

如果您的配置使用的磁盘架未完全填充（驱动器托架为空），则必须根据磁盘分配策略在磁盘架中均匀分布驱动器。磁盘分配策略取决于每个 MetroCluster 站点上的磁盘架数量。

如果您在每个站点使用一个磁盘架（或仅使用 AFF A800 系统上的内部磁盘架），则会使用四分之一磁盘架策略分配磁盘。如果磁盘架未完全填充，请在所有季度均匀地安装驱动器。

下表显示了如何在 48 个驱动器内部磁盘架中放置 24 个磁盘的示例。此外，还会显示驱动器的所有权。

|===


| 48 个驱动器托架分为四个部分： | 在每个季度的前六个托架中安装六个驱动器 ... 


 a| 
第 1 季度：托架 0-11
 a| 
托架 0-5



 a| 
第 2 季度：托架 12-23
 a| 
托架 12-17



 a| 
第 3 季度：托架 24-35
 a| 
托架 24-29



 a| 
第四个四等分：托架36－47
 a| 
托架 36 — 41

|===
下表显示了如何在一个包含24个驱动器的内部磁盘架中放置16个磁盘的示例。

|===


| 24个驱动器托架分为四个四等分： | 在每个季度的前四个托架中安装四个驱动器... 


 a| 
四分之一：托架0-5
 a| 
托架0-3



 a| 
第二个四等分：托架6-11
 a| 
托架6-9.



 a| 
第三个四等分：托架12-17
 a| 
托架12-15.



 a| 
第四个四等分：托架18-23
 a| 
托架18-21.

|===
如果您要在每个站点上使用两个外部磁盘架、则会使用半磁盘架策略分配磁盘。如果磁盘架未完全填充，请从磁盘架的任意一端等分安装驱动器。

例如，如果要在一个 24 驱动器架中安装 12 个驱动器，请在托架 0-5 和 18-23 中安装驱动器。



== 手动分配驱动器（ ONTAP 9.5 ）

在 ONTAP 9.5 中，具有以下磁盘架配置的系统需要手动分配驱动器：

* 每个站点三个外部磁盘架。
+
使用半磁盘架分配策略自动分配两个磁盘架，但必须手动分配第三个磁盘架。

* 每个站点四个以上的磁盘架，外部磁盘架总数不是四个的倍数。
+
超过四个中最接近倍数的额外磁盘架将保持未分配状态，并且必须手动分配驱动器。例如，如果站点上有五个外部磁盘架，则必须手动分配磁盘架五。



您只需要在每个未分配的磁盘架上手动分配一个驱动器。然后，系统会自动分配磁盘架上的其余驱动器。



== 手动分配驱动器（ ONTAP 9.4 ）

在 ONTAP 9.4 中，具有以下磁盘架配置的系统需要手动分配驱动器：

* 每个站点少于四个外部磁盘架。
+
必须手动分配驱动器，以确保均衡分配驱动器，每个池具有相同数量的驱动器。

* 每个站点四个以上的外部磁盘架，而外部磁盘架的总数不是四个的倍数。
+
超过四个中最接近倍数的额外磁盘架将保持未分配状态，并且必须手动分配驱动器。



手动分配驱动器时，您应对称分配磁盘，并为每个池分配相同数量的驱动器。例如，如果此配置在每个站点上有两个存储架，则本地 HA 对和远程 HA 对各有一个存储架：

* 将 site_A-shelf_1 上的一半磁盘分配给 node_A_1 的池 0 。
* 将 site_A-shelf_1 上的一半磁盘分配给 node_A_2 的池 0 。
* 将 site_A-shelf_2 上的一半磁盘分配给 node_B_1 的池 1 。
* 将 site_A-shelf_2 上的一半磁盘分配给 node_B_2 的池 1 。
* 将 site_B-shelf_1 上的一半磁盘分配给 node_B_1 的池 0 。
* 将 site_B-shelf_1 上的一半磁盘分配给 node_B_2 的池 0 。
* 将 site_B-shelf_2 上的一半磁盘分配给 node_A_1 的池 1 。
* 将 site_B-shelf_2 上的一半磁盘分配给 node_A_2 的池 1 。




== 将磁盘架添加到现有配置中

自动驱动器分配支持向现有配置对称添加磁盘架。

添加新磁盘架后，系统会对新添加的磁盘架应用相同的分配策略。例如，如果每个站点一个磁盘架，则如果添加了额外的磁盘架，则系统会对新磁盘架应用四分之一磁盘架分配规则。

.相关信息
link:concept_required_mcc_ip_components_and_naming_guidelines_mcc_ip.html["所需的 MetroCluster IP 组件和命名约定"]

https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html["磁盘和聚合管理"^]



== MetroCluster IP 配置中系统的 ADP 和磁盘分配差异

在 MetroCluster IP 配置中，高级驱动器分区（ ADP ）的操作和自动磁盘分配会因系统型号而异。


NOTE: 在使用 ADP 的系统中，聚合是使用分区创建的，其中每个驱动器都分区为 P1 ， P2 和 P3 分区。根聚合使用 P3 分区创建。

您必须满足受支持驱动器数量上限的 MetroCluster 限制以及其他准则。

https://hwu.netapp.com["NetApp Hardware Universe"]



=== AFF A320 系统上的 ADP 和磁盘分配

|===


| 准则 | 每个站点的驱动器数 | 驱动器分配规则 | 根分区的 ADP 布局 


 a| 
建议的最小驱动器数（每个站点）
 a| 
48 个驱动器
 a| 
每个外部磁盘架上的驱动器分为两个相等的组（半个）。每个半架会自动分配给一个单独的池。
 a| 
本地 HA 对使用一个磁盘架。第二个磁盘架由远程 HA 对使用。

每个磁盘架上的分区用于创建根聚合。根聚合中的两个丛中的每个丛都包含以下分区::
+
--
* 八个数据分区
* 两个奇偶校验分区
* 两个备用分区


--




 a| 
支持的最小驱动器数（每个站点）
 a| 
24 个驱动器
 a| 
驱动器分为四个相等的组。每个四分之一架会自动分配给一个单独的池。
 a| 
根聚合中的两个丛中的每个丛都包含以下分区：

* 三个数据分区
* 两个奇偶校验分区
* 一个备用分区


|===


=== AFF A150、ASA A150和AFF A220系统上的ADP和磁盘分配

|===


| 准则 | 每个站点的驱动器数 | 驱动器分配规则 | 根分区的 ADP 布局 


 a| 
建议的最小驱动器数（每个站点）
 a| 
仅限内部驱动器
 a| 
内部驱动器分为四个相等的组。每个组会自动分配给一个单独的池，而每个池会分配给配置中的一个单独的控制器。


NOTE: 在配置 MetroCluster 之前，一半的内部驱动器保持未分配状态。
 a| 
本地 HA 对使用了两个季度。其余两个季度将由远程 HA 对使用。

根聚合在每个丛中包含以下分区：

* 三个数据分区
* 两个奇偶校验分区
* 一个备用分区




 a| 
支持的最小驱动器数（每个站点）
 a| 
16 个内部驱动器
 a| 
驱动器分为四个相等的组。每个四分之一架会自动分配给一个单独的池。

一个磁盘架上的两个季度可以具有相同的池。根据拥有本季度的节点选择池：

* 如果归本地节点所有，则使用 pool0 。
* 如果归远程节点所有，则使用 pool1 。


例如：季度为第 1 季度到第 4 季度的磁盘架可以具有以下分配：

* 第 1 季度： node_A_1 pool0
* 第 2 季度： node_A_2 pool0
* 第 3 季度： node_B_1 pool1
* 第 4 季度： node_B_2 池 1



NOTE: 在配置 MetroCluster 之前，一半的内部驱动器保持未分配状态。
 a| 
根聚合中的两个丛中的每个丛都包含以下分区：

* 两个数据分区
* 两个奇偶校验分区
* 无备用磁盘


|===


=== AFF C250、AFF A250、ASA A250、ASA C250和FAS500f系统上的ADP和磁盘分配

|===


| 准则 | 每个站点的驱动器数 | 驱动器分配规则 | 根分区的 ADP 布局 


 a| 
建议的最小驱动器数（每个站点）
 a| 
48 个驱动器
 a| 
每个外部磁盘架上的驱动器分为两个相等的组（半个）。每个半架会自动分配给一个单独的池。
 a| 
本地 HA 对使用一个磁盘架。第二个磁盘架由远程 HA 对使用。

每个磁盘架上的分区用于创建根聚合。根聚合在每个丛中包含以下分区：

* 八个数据分区
* 两个奇偶校验分区
* 两个备用分区




 a| 
支持的最小驱动器数（每个站点）
 a| 
16 个内部驱动器
 a| 
驱动器分为四个相等的组。每个四分之一架会自动分配给一个单独的池。
 a| 
根聚合中的两个丛中的每个丛都包含以下分区：

* 两个数据分区
* 两个奇偶校验分区
* 无备用分区


|===


=== AFF A300 系统上的 ADP 和磁盘分配

|===


| 准则 | 每个站点的驱动器数 | 驱动器分配规则 | 根分区的 ADP 布局 


 a| 
建议的最小驱动器数（每个站点）
 a| 
48 个驱动器
 a| 
每个外部磁盘架上的驱动器分为两个相等的组（半个）。每个半架会自动分配给一个单独的池。
 a| 
本地 HA 对使用一个磁盘架。第二个磁盘架由远程 HA 对使用。

每个磁盘架上的分区用于创建根聚合。根聚合在每个丛中包含以下分区：

* 八个数据分区
* 两个奇偶校验分区
* 两个备用分区




 a| 
支持的最小驱动器数（每个站点）
 a| 
24 个驱动器
 a| 
驱动器分为四个相等的组。每个四分之一架会自动分配给一个单独的池。
 a| 
根聚合中的两个丛中的每个丛都包含以下分区：

* 三个数据分区
* 两个奇偶校验分区
* 一个备用分区


|===


=== AFF C400、AFF A400、ASA C400和ASA A400系统上的ADP和磁盘分配

|===


| 准则 | 每个站点的驱动器数 | 驱动器分配规则 | 根分区的 ADP 布局 


 a| 
建议的最小驱动器数（每个站点）
 a| 
96 个驱动器
 a| 
驱动器会按磁盘架自动分配。
 a| 
根聚合中的两个丛中的每个丛都包括：

* 20 个数据分区
* 两个奇偶校验分区
* 两个备用分区




 a| 
支持的最小驱动器数（每个站点）
 a| 
24 个驱动器
 a| 
驱动器分为四个相等的组（四个）。每个四分之一架会自动分配给一个单独的池。
 a| 
根聚合中的两个丛中的每个丛都包括：

* 三个数据分区
* 两个奇偶校验分区
* 一个备用分区


|===


=== AFF A700 系统上的 ADP 和磁盘分配

|===


| 准则 | 每个站点的驱动器数 | 驱动器分配规则 | 根分区的 ADP 布局 


 a| 
建议的最小驱动器数（每个站点）
 a| 
96 个驱动器
 a| 
驱动器会按磁盘架自动分配。
 a| 
根聚合中的两个丛中的每个丛都包括：

* 20 个数据分区
* 两个奇偶校验分区
* 两个备用分区




 a| 
支持的最小驱动器数（每个站点）
 a| 
24 个驱动器
 a| 
驱动器分为四个相等的组（四个）。每个四分之一架会自动分配给一个单独的池。
 a| 
根聚合中的两个丛中的每个丛都包括：

* 三个数据分区
* 两个奇偶校验分区
* 一个备用分区


|===


=== AFF C800、ASA C800、ASA A800和AFF A800系统上的ADP和磁盘分配

|===


| 准则 | 每个站点的驱动器数 | 驱动器分配规则 | 根聚合的 ADP 布局 


 a| 
建议的最小驱动器数（每个站点）
 a| 
内部驱动器和 96 个外部驱动器
 a| 
内部分区分为四个相等的组（四个季度）。每个季度都会自动分配给一个单独的池。外部磁盘架上的驱动器会按磁盘架自动分配，每个磁盘架上的所有驱动器都会分配给 MetroCluster 配置中的四个节点之一。
 a| 
创建根聚合时，内部磁盘架上会有 12 个根分区。

根聚合中的两个丛中的每个丛都包括：

* 八个数据分区
* 两个奇偶校验分区
* 两个备用分区




 a| 
支持的最小驱动器数（每个站点）
 a| 
24个内部驱动器
 a| 
内部分区分为四个相等的组（四个季度）。每个季度都会自动分配给一个单独的池。
 a| 
创建根聚合时，内部磁盘架上会有 12 个根分区。

根聚合中的两个丛中的每个丛都包括：

* 三个数据分区
* 两个奇偶校验分区
* 一个备用分区


|===


=== AFF A900和ASA A900系统上的ADP和磁盘分配

|===


| 准则 | 每个站点的磁盘架数 | 驱动器分配规则 | 根分区的 ADP 布局 


 a| 
建议的最小驱动器数（每个站点）
 a| 
96 个驱动器
 a| 
驱动器会按磁盘架自动分配。
 a| 
根聚合中的两个丛中的每个丛都包括：

* 20 个数据分区
* 两个奇偶校验分区
* 两个备用分区




 a| 
支持的最小驱动器数（每个站点）
 a| 
24 个驱动器
 a| 
驱动器分为四个相等的组（四个）。每个四分之一架会自动分配给一个单独的池。
 a| 
根聚合中的两个丛中的每个丛都包括：

* 三个数据分区
* 两个奇偶校验分区
* 一个备用分区


|===


=== 在 FAS2750 系统上分配磁盘

|===


| 准则 | 每个站点的驱动器数 | 驱动器分配规则 | 根分区的 ADP 布局 


 a| 
建议的最小驱动器数（每个站点）
 a| 
24 个内部驱动器和 24 个外部驱动器
 a| 
内部和外部磁盘架分为两个相等的部分。每一半会自动分配到不同的池
 a| 
不适用



 a| 
支持的最小驱动器数（每个站点）（主动 / 被动 HA 配置）
 a| 
仅限内部驱动器
 a| 
需要手动分配
 a| 
不适用

|===


=== 在 FAS8200 系统上分配磁盘

|===


| 准则 | 每个站点的驱动器数 | 驱动器分配规则 | 根分区的 ADP 布局 


 a| 
建议的最小驱动器数（每个站点）
 a| 
48 个驱动器
 a| 
外部磁盘架上的驱动器分为两个相等的组（半个）。每个半架会自动分配给一个单独的池。
 a| 
不适用



 a| 
支持的最小驱动器数（每个站点）（主动 / 被动 HA 配置）
 a| 
24 个驱动器
 a| 
需要手动分配。
 a| 
不适用

|===


=== FAS500f 系统上的磁盘分配

AFF C250和AFF A250系统的磁盘分配准则和规则同样适用于FAS500f系统。有关FAS500f系统上的磁盘分配、请参见 <<ADP_FAS500f>> 表。



=== 在 FAS9000 系统上分配磁盘

|===


| 准则 | 每个站点的驱动器数 | 驱动器分配规则 | 根分区的 ADP 布局 


 a| 
建议的最小驱动器数（每个站点）
 a| 
96 个驱动器
 a| 
驱动器会按磁盘架自动分配。
 a| 
不适用



 a| 
支持的最小驱动器数（每个站点）
 a| 
48 个驱动器
 a| 
磁盘架上的驱动器分为两个相等的组（半个）。每个半架会自动分配给一个单独的池。
 a| 
支持的最小驱动器数（每个站点）（主动 / 被动 HA 配置）

|===


=== 在FAS9500系统上分配磁盘

|===


| 准则 | 每个站点的磁盘架数 | 驱动器分配规则 | 根分区的 ADP 布局 


 a| 
建议的最小驱动器数（每个站点）
 a| 
96 个驱动器
 a| 
驱动器会按磁盘架自动分配。
 a| 
不适用



 a| 
支持的最小驱动器数（每个站点）
 a| 
24 个驱动器
 a| 
驱动器分为四个相等的组（四个）。每个四分之一架会自动分配给一个单独的池。
 a| 
支持的最小驱动器数（每个站点）（主动 / 被动 HA 配置）

|===