---
permalink: install-ip/concept_considerations_unmirrored_aggrs.html 
sidebar: sidebar 
keywords: differences, eight-node, four-node, fabric-attached, stretch, metrocluster ip, storage, bridges, fc-to-sas, atto, fibrebridge, SAS, local HA, auso, automatic unplanned switchover, mediator, tiebreaker 
summary: 如果您的配置包含未镜像聚合，则必须注意在执行切换操作后可能出现的访问问题。 
---
= 了解MetroCluster IP 配置中的非镜像聚合
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您的配置包含未镜像聚合，则必须注意在执行切换操作后可能出现的访问问题。



== 非镜像聚合和分层命名空间

如果您使用的是分层命名空间，则应配置接合路径，以使该路径中的所有卷要么仅位于镜像聚合上，要么仅位于未镜像聚合上。在接合路径中混合配置未镜像聚合和镜像聚合可能会阻止在切换操作后访问未镜像聚合。



== 非镜像聚合和需要关闭电源的维护

如果您执行协商切换以进行维护，而该维护需要关闭整个站点的电源，则应首先手动将灾难站点拥有的任何未镜像的聚合脱机。

如果您未将灾难站点所拥有的未镜像聚合脱机，则正常运行的站点上的节点可能会由于多磁盘崩溃而关闭。如果由于断电或 ISL 丢失导致与灾难站点上的存储连接中断，切换的未镜像聚合脱机或丢失，则可能会发生这种情况。



== 未镜像聚合、CRS 元数据卷和数据 SVM 根卷

配置复制服务（ CRS ）元数据卷和数据 SVM 根卷必须位于镜像聚合上。您不能将这些卷移动到未镜像聚合。如果它们位于非镜像聚合上，则协商切换和切回操作将被否决，并且 `metrocluster check`命令返回警告。



== 未镜像聚合和 SVM

您应该仅在镜像聚合或未镜像聚合上配置 SVM。在未镜像聚合和镜像聚合上混合配置 SVM 可能会导致切换操作超过 120 秒。如果未镜像聚合无法联机，则可能会导致数据中断。



== 非镜像聚合和 SAN

在ONTAP 9.9.1 之前，LUN 不应位于未镜像的聚合上。在未镜像聚合上配置 LUN 可能会导致切换操作超过 120 秒并导致数据中断。



== 为未镜像的聚合添加存储架

如果您添加磁盘架并希望将其用于MetroCluster IP 配置中的未镜像聚合，则必须执行以下操作：

. 在启动操作步骤以添加磁盘架之前，问题描述请执行以下命令：
+
MetroCluster modify -enable-unmirrored-aggr-deployment true`

. 验证自动磁盘分配是否已关闭：
+
`d` 选项显示

. 按照操作步骤中的步骤添加磁盘架。
. 手动将新磁盘架中的所有磁盘分配给将拥有未镜像聚合的节点。
. 创建聚合。
+
`s存储聚合创建`

. 完成操作步骤后问题描述，运行以下命令：
+
MetroCluster modify -enable-unmirrored-aggr-deployment false`

. 验证是否已启用自动磁盘分配：
+
`d` 选项显示


