---
permalink: install-ip/concept_mediator_requirements.html 
sidebar: sidebar 
keywords: ontap, mediator, assist, metrocluster, ip, configuration, perform, automatic, unplan, switchover, physical, repository, status, information, configuring, configure, install, configuring, configure, mtu size, packet loss, bandwidth, firewall, rhel, centos, linux, revert, kernal, upgrade, latency 
summary: 从 ONTAP 9.7 开始，ONTAP Mediator 可以通过提供物理上独立的状态信息存储库来帮助 MetroCluster IP 配置执行自动计划外切换。 
---
= 准备在MetroCluster IP 配置中安装ONTAP调解器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您的环境必须满足某些要求。

以下要求适用于一个灾难恢复组(DR组)。了解更多信息 link:concept_parts_of_an_ip_mcc_configuration_mcc_ip.html#disaster-recovery-dr-groups["DR 组"]。

* 如果您计划更新 Linux 版本，请在安装最新版本的 ONTAP Mediator 之前进行更新。
* ONTAP Mediator 和 MetroCluster Tiebreaker 软件不应同时与相同的 MetroCluster 配置一起使用。
* ONTAP 调解器必须安装在与 MetroCluster 站点不同位置的 Linux 主机上。
+
ONTAP 调解器与每个站点之间的连接必须是两个单独的故障域。

* ONTAP Mediator 最多可同时支持五个 MetroCluster 配置。
* ONTAP 9.7 及更高版本支持自动计划外切换。
* ONTAP调解器不支持IPv6。




== 在 MetroCluster 配置中使用 ONTAP 调解器的网络要求

要在 MetroCluster 配置中安装 ONTAP 调解器，您必须确保该配置满足多个网络要求。

* 延迟
+
最大延迟小于75毫秒(RTT)。

+
抖动不能超过5毫秒。

* MTU
+
MTU 大小必须至少为 1400 。

* 数据包丢失
+
对于Internet控制消息协议(Internet Control Message Protocol、ICMP)和TCP流量、数据包丢失率必须小于0.01%。

* 带宽
+
ONTAP 调解器和一个 DR 组之间的链接必须至少具有 20Mbps 的带宽。

* 独立连接
+
每个站点与ONTAP 调解器之间需要独立连接。一个站点发生故障不能中断其他两个不受影响站点之间的IP连接。





== MetroCluster 配置中 ONTAP 调解器的主机要求

您必须确保配置满足多个主机要求。

* ONTAP 调解器必须安装在与两个ONTAP 集群物理隔离的外部站点上。
* ONTAP 调解器最多支持五个MetroCluster 配置。
* ONTAP 调解器对CPU和内存(RAM)的要求不超过主机操作系统的最低要求。
* 除了主机操作系统的最低要求之外、还必须至少提供30 GB的额外可用磁盘空间。
+
** 每个DR组最多需要200 MB的磁盘空间。






== ONTAP 调解器的防火墙要求

ONTAP 调解器使用多个端口与特定服务进行通信。

如果您使用的是第三方防火墙：

* 必须启用 HTTPS 访问。
* 必须将其配置为允许在端口 31784 和 3260 上进行访问。
+
如果使用默认的 Red Hat 或 CentOS 防火墙，则会在安装调解器期间自动配置防火墙。



下表列出了防火墙中必须允许的端口：

[NOTE]
====
* 只有在MetroCluster IP配置中才需要iSCSI端口。
* 正常操作不需要22/TCP端口、但您可以临时启用该端口进行维护、并在维护会话完成后将其禁用。


====
|===


| 端口 / 服务 | 源 | 方向 | 目标 | 目的 


 a| 
22 TCP
 a| 
管理主机
 a| 
入站
 a| 
ONTAP 调解器
 a| 
SSH / ONTAP调解器管理



 a| 
31784/TCP
 a| 
集群管理和节点管理 LIF
 a| 
入站
 a| 
ONTAP 调解器 Web 服务器
 a| 
REST API （ HTTPS ）



 a| 
3260 TCP
 a| 
节点管理 LIF
 a| 
双向
 a| 
ONTAP 调解器 iSCSI 目标
 a| 
邮箱的 iSCSI 数据连接

|===


== 在 MetroCluster 配置中升级 ONTAP 调解器的指南

如果要升级 ONTAP Mediator，则必须满足 Linux 版本要求并遵循升级指南。

* ONTAP Mediator 可以从前一个版本升级到当前版本。
* 运行 ONTAP 9.7 或更高版本的 MetroCluster IP 配置支持所有调解器版本。


link:https://docs.netapp.com/us-en/ontap/mediator/index.html["安装或升级 ONTAP 调解器"^]



== 升级后

完成调解器和操作系统升级后，您应使用问题描述 `storage iscsi-initiator show` 命令确认调解器连接已启动。
