---
permalink: install-ip/concept_required_mcc_ip_components_and_naming_guidelines_mcc_ip.html 
sidebar: sidebar 
keywords: plan, metrocluster, ip, configuration, planning, require, hardware, software, clarity, conventions, component, documentation, naming, name, requirement, support, redundancy, switch, ontap, cluster, controller, module, gigabit, ethernet, adapter, pool, drive, drive, location, consideration, partial, populate, shelves, shelf, aff, a800, internal, iom12, iom, module, stack, four-node, raid-dp, raid4, AFF A800 internal drives 
summary: 在规划 MetroCluster IP 配置时，您必须了解所需的和支持的硬件和软件组件。为了方便和清晰起见，您还应了解整个文档中的示例中用于组件的命名约定。 
---
= 所需的MetroCluster IP 配置组件和命名约定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在规划 MetroCluster IP 配置时，您必须了解所需的和支持的硬件和软件组件。为了方便和清晰起见，您还应了解整个文档中的示例中用于组件的命名约定。



== 支持的软件和硬件

MetroCluster IP 配置必须支持硬件和软件。

https://hwu.netapp.com["NetApp Hardware Universe"]

使用 AFF 系统时，必须将 MetroCluster 配置中的所有控制器模块配置为 AFF 系统。



== MetroCluster IP 配置中的硬件冗余要求

由于 MetroCluster IP 配置中的硬件冗余，因此每个站点上的每个组件都有两个。系统会任意为站点分配字母 A 和 B ，并为各个组件分配编号 1 和 2 。



== MetroCluster IP 配置中的 ONTAP 集群要求

MetroCluster IP 配置需要两个 ONTAP 集群，每个 MetroCluster 站点一个。

在 MetroCluster 配置中，命名必须是唯一的。

示例名称：

* 站点 A ： cluster_A
* 站点 B ： cluster_B




== MetroCluster IP 配置中的 IP 交换机要求

MetroCluster IP 配置需要四个 IP 交换机。这四个交换机形成两个交换机存储网络结构，在 MetroCluster IP 配置中的每个集群之间提供 ISL 。

IP 交换机还可在每个集群中的控制器模块之间提供集群内通信。

在 MetroCluster 配置中，命名必须是唯一的。

示例名称：

* 站点 A ： cluster_A
+
** IP_switch_A_1
** IP_switch_A_2


* 站点 B ： cluster_B
+
** IP_switch_B_1
** IP_switch_B_2






== MetroCluster IP 配置中的控制器模块要求

MetroCluster IP 配置需要四个或八个控制器模块。

每个站点的控制器模块构成一个 HA 对。每个控制器模块在另一个站点上都有一个 DR 配对节点。

每个控制器模块必须运行相同的 ONTAP 版本。支持的平台型号取决于 ONTAP 版本：

* ONTAP 9.4 不支持在 FAS 系统上安装新的 MetroCluster IP 。
+
FAS 系统上的现有 MetroCluster IP 配置可以升级到 ONTAP 9.4 。

* 从 ONTAP 9.5 开始，支持在 FAS 系统上安装新的 MetroCluster IP 。
* 从 ONTAP 9.4 开始，支持为 ADP 配置的控制器模块。




=== 示例名称

文档中使用了以下示例名称：

* 站点 A ： cluster_A
+
** controller_A_1
** controller_A_2


* 站点 B ： cluster_B
+
** controller_B_1
** controller_B_2






== MetroCluster IP 配置中的千兆以太网适配器要求

MetroCluster IP 配置使用 40/100 Gbps 或 10/25 Gbps 以太网适配器作为 MetroCluster IP 网络结构所用 IP 交换机的 IP 接口。


NOTE: 板载端口内置在控制器硬件(插槽0)中、无法更换、因此适配器所需的插槽不适用。

|===


| 平台型号 | 需要千兆以太网适配器 | 适配器所需的插槽 | 端口 


 a| 
AFF A900、ASA A900和FAS9500
 a| 
X91146A
 a| 
插槽 5 ，插槽 7
 a| 
e5b ， e7b

*注意：*端口 e5a 和 e7a 仅可用于集群间 LIF。不能将这些端口用于数据 LIF。



 a| 
AFF A700 和 FAS9000
 a| 
X91146A-C
 a| 
插槽 5
 a| 
e5a ， e5b



 a| 
AFF A800、AFF C800、ASA A800和ASA C800
 a| 
X1146A/ 板载端口
 a| 
插槽1/不适用于板载端口
 a| 
e0be1b



 a| 
FAS9300、AFF A400、ASA A400、ASA C400和AFF C400
 a| 
X1146A
 a| 
插槽 1
 a| 
e1a ， e1b



 a| 
AFF A300 和 FAS8200
 a| 
X1116A
 a| 
插槽 1
 a| 
e1a ， e1b



 a| 
FAS2750、AFF A150、ASA A150和AFF A220
 a| 
板载端口
 a| 
不适用
 a| 
e0a ， e0b



 a| 
FAS500f、AFF A250、ASA A250、ASA C250和AFF C250
 a| 
板载端口
 a| 
不适用
 a| 
e0c ， e0d



 a| 
AFF A320
 a| 
板载端口
 a| 
不适用
 a| 
e0g ， e0h



 a| 
AFF A70、FAS70
 a| 
X50132A
 a| 
插槽 2
 a| 
e2a、e2b



 a| 
AFF A90、AFF A1K、FAS90、AFF C80
 a| 
X50132A
 a| 
插槽 2 ，插槽 3
 a| 
e2b、e3b

*注：*端口E2A和E3A必须保持未使用状态。不支持将这些端口用于前端网络或对等关系。



 a| 
AFF A50
 a| 
X60134A
 a| 
插槽 2
 a| 
e2a、e2b



 a| 
AFF A30、AFF C30、AFF C60、FAS50
 a| 
X60134A
 a| 
插槽 2
 a| 
e2a、e2b



 a| 
AFF A20
 a| 
X60132A
 a| 
插槽 4 ，插槽 2
 a| 
e2b、e4b

|===
link:concept_considerations_drive_assignment.html["了解MetroCluster IP配置中的自动驱动器分配和ADP系统"]。



== 池和驱动器要求（支持的最低要求）

四节点 MetroCluster IP 配置要求每个站点至少配置以下内容：

* 每个节点在站点上至少有一个本地池和一个远程池。
* 每个池中至少有七个驱动器。
+
在每个节点具有一个镜像数据聚合的四节点 MetroCluster 配置中，站点上的最低配置需要 24 个磁盘。



在支持的最低配置中，每个池都具有以下驱动器布局：

* 三个根驱动器
* 三个数据驱动器
* 一个备用驱动器


在支持的最低配置中，每个站点至少需要一个磁盘架。

MetroCluster 配置支持 RAID-DP、RAID4 和 RAID-TEC。


NOTE: 从ONTAP 9.4开始、MetroCluster IP配置支持使用自动磁盘分配和ADP (高级驱动器分区)进行新安装。有关详细信息、请参见 link:../install-ip/concept_considerations_drive_assignment.html["自动驱动器分配和 ADP 系统的注意事项"] 。



== 部分填充的磁盘架的驱动器位置注意事项

要在使用半填充磁盘架（ 24 驱动器磁盘架中有 12 个驱动器）时正确地自动分配驱动器，驱动器应位于插槽 0-5 和 18-23 中。

在磁盘架部分填充的配置中，驱动器必须均匀分布在磁盘架的四个象限中。



== AFF A800 内部驱动器的驱动器位置注意事项

要正确实施 ADP 功能， AFF A800 系统磁盘插槽必须划分为四分位，并且磁盘必须对称分布在四分位。

AFF A800 系统具有 48 个驱动器托架。托架可以划分为四个季度：

* 第一季度：
+
** 托架 0 - 5
** 托架 24 - 29


* 第二个季度：
+
** 托架 6 - 11
** 托架 30 - 35


* 第三个季度：
+
** 托架 12 - 17
** 托架 36 - 41


* 第四个季度：
+
** 托架 18 - 23
** 托架 42 - 47




如果此系统中安装了 16 个驱动器，则这些驱动器必须对称分布在以下四个四等分之间：

* 第一季度有四个驱动器： 0 ， 1 ， 2 ， 3
* 第二季度有四个驱动器： 6 ， 7 ， 8 ， 9
* 第三季度有四个驱动器： 12 ， 13 ， 14 ， 15
* 第四季度有四个驱动器： 18 ， 19 ， 20 ， 21

