---
permalink: install-ip/concept_mediator_requirements.html 
sidebar: sidebar 
keywords: ontap, mediator, service, assist, metrocluster, ip, configuration, perform, automatic, unplan, switchover, physical, repository, status, information, configuring, configure, install, configuring, configure, mtu size, packet loss, bandwidth, firewall, rhel, centos, linux, revert, kernal, upgrade, latency 
summary: 从 ONTAP 9.7 开始， ONTAP 调解器服务可以通过为状态信息提供物理上独立的存储库来协助 MetroCluster IP 配置执行自动计划外切换。 
---
= 准备安装 ONTAP 调解器服务
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您的环境必须满足以下要求。

[NOTE]
====
* 如果您计划更新 Linux 版本，请在安装最新的 ONTAP 调解器服务之前执行此操作。
* ONTAP 调解器服务和 MetroCluster Tiebreaker 软件不应同时使用相同的 MetroCluster 配置。
* ONTAP 调解器必须安装在与 MetroCluster 站点不同的 Linux 主机上。
* ONTAP 调解器服务最多可同时支持五个 MetroCluster 配置。
* ONTAP 9.7 及更高版本支持自动计划外切换。


====


== 在 MetroCluster 配置中使用调解器的网络要求

要在 MetroCluster 配置中安装 ONTAP 调解器服务，您必须确保此配置满足多个网络要求。

* 延迟
+
往返延迟不得超过75毫秒。

+
抖动不能超过25毫秒。

* MTU
+
MTU 大小必须至少为 1400 。

* 数据包丢失
+
数据包丢失必须小于或等于 0.01% 。

* 带宽
+
调解器服务与MetroCluster 配置之间的链路必须至少具有20 MBps的带宽。





== ONTAP 调解器的防火墙要求

ONTAP 调解器使用多个端口与特定服务进行通信。

如果您使用的是第三方防火墙：

* 必须启用 HTTPS 访问。
* 必须将其配置为允许在端口 31784 和 3260 上进行访问。
+
如果使用默认的 Red Hat 或 CentOS 防火墙，则会在安装调解器期间自动配置防火墙。



下表列出了防火墙中必须允许的端口：

|===


| 端口 / 服务 | 源 | 目标 | 目的 


 a| 
31784/TCP
 a| 
ONTAP 集群管理接口
 a| 
ONTAP 调解器 Web 服务器
 a| 
REST API （ HTTPS ）



 a| 
3260 TCP
 a| 
ONTAP 集群
 a| 
ONTAP 调解器 iSCSI 目标
 a| 
邮箱的 iSCSI 数据连接

|===


== 在 MetroCluster 配置中升级 ONTAP 调解器的准则

如果要升级 ONTAP 调解器，则必须满足 Linux 版本要求并遵循升级准则。

* 可以将调解器服务从早期版本升级到当前版本。
* 运行 ONTAP 9.7 或更高版本的 MetroCluster IP 配置支持所有调解器版本。


link:https://docs.netapp.com/us-en/ontap/mediator/index.html["安装或升级 ONTAP 调解器服务"^]



== 升级后

完成调解器和操作系统升级后，您应使用问题描述 `storage iscsi-initiator show` 命令确认调解器连接已启动。
