---
permalink: install-ip/concept-ontap-mediator-supports-automatic-unplanned-switchover.html 
sidebar: sidebar 
keywords: ontap, mediator, service, assist, metrocluster, ip, configuration, perform, automatic, unplan, switchover, physical, repository, status, information, configuring, configure, install, configuring, configure, forced 
summary:  
---
= ONTAP 调解器如何支持自动计划外切换
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP调解器提供邮箱LUN来存储有关MetroCluster IP节点的状态信息。这些 LUN 与 ONTAP 调解器位于同一位置，该调解器在与 MetroCluster 站点物理隔离的 Linux 主机上运行。MetroCluster IP节点可以使用邮箱信息监控其灾难恢复(DR)配对节点的状态、并在发生灾难时实施调解器辅助计划外切换(MAUSO)。


NOTE: MetroCluster FC 配置不支持 MAUSO 。

当节点检测到需要切换的站点故障时，它会执行相应的步骤来确认切换是否合适，如果是，则会执行切换。默认情况下、在以下情况下会启动MAUSO：

* 每个节点的非易失性缓存的 SyncMirror 镜像和灾难恢复镜像均在运行，并且在发生故障时，缓存和镜像将保持同步。
* 运行正常的站点上的节点均未处于接管状态。
* 发生站点灾难时。站点灾难是指同一站点上的_all_节点发生故障。


在以下关闭情形下、会启动_NOT _ MAUSO：

* 您启动了关闭操作。例如，当您：
+
** 暂停节点
** 重新启动节点




了解每个ONTAP 9版本提供的MAUSO功能。

[cols="1a,5a"]
|===
| 开头为 ... | 说明 


 a| 
ONTAP 9.13.1
 a| 
* 如果是、则会启动MAUSO <<default_scenarios,默认场景>> 如果发生风扇或硬件故障、则会导致环境关闭。硬件故障的示例包括温度过高或过低、或者电源设备、NVRAM电池或服务处理器检测信号故障。
* 在MetroCluster IP配置中、故障域的默认值设置为"Auso-on-dr-group"。对于ONTAP 9.12.1及更早版本、默认值设置为"auuso-on-cluster-퓖 몦"。
+
在八节点MetroCluster IP配置中、如果集群或一个DR组中的HA对发生故障、"auuso-on-dr-group"将触发一个MAUSO。对于HA对、两个节点必须同时发生故障。

+
或者、您也可以使用将故障域设置更改为"auuso-on-cluster-퓖 몦"域 `metrocluster modify -auto-switchover-failure-domain auso-on-cluster-disaster` 仅当两个DR组中的HA节点对都出现故障时才触发MAUSO的命令。

* 您可以更改此行为以强制执行MAUSO、即使发生故障时NVRAM未同步也是如此。




 a| 
[[mauso-9-12-1]] ONTAP 9.12.1
 a| 
您可以使用在MetroCluster IP配置中启用MetroCluster自动强制切换功能 `metrocluster modify -allow-auto-forced-switchover true` 命令：

启用MetroCluster 自动强制切换功能后、检测到站点故障时会自动进行切换。您可以使用此功能来补充MetroCluster IP自动切换功能。

.使用MetroCluster 自动强制切换的风险和限制
如果允许MetroCluster IP配置在自动强制切换模式下运行、则以下已知问题描述可能会导致数据丢失：

* 存储控制器中的非易失性内存不会镜像到配对站点上的远程DR配对节点。


*注意*：您可能会遇到未提及的情形。对于因启用MetroCluster 自动强制切换功能而可能导致的任何数据损坏、数据丢失或其他损坏、NetApp概不负责。如果您无法接受风险和限制、请勿使用MetroCluster 自动强制切换功能。

|===