---
sidebar: sidebar 
permalink: install-ip/set-up-mcc-site-system-manager.html 
keywords: system manager, metrocluster, set up, setup, start, initialize, cluster, config, nodes 
summary: 从ONTAP 9 8开始、您可以使用System Manager设置MetroCluster IP站点。 
---
= 设置MetroCluster IP站点
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
从ONTAP 9 8开始、您可以使用System Manager设置MetroCluster IP站点。

MetroCluster 站点由两个集群组成。通常，集群位于不同的地理位置。

.开始之前
* 您的系统应已根据系统附带的进行安装和布线 https://docs.netapp.com/us-en/ontap-systems/index.html["安装和设置说明"^]。
* 应在每个集群的每个节点上配置集群网络接口，以便进行集群内通信。




== 分配节点管理 IP 地址



=== Windows 系统

您应将 Windows 计算机连接到与控制器相同的子网。此操作会自动为您的系统分配节点管理IP地址。

.步骤
. 在 Windows 系统中，打开 * 网络 * 驱动器以发现节点。
. 双击节点以启动集群设置向导。




=== 其他系统

您应为集群中的一个节点配置节点管理 IP 地址。您可以使用此节点管理 IP 地址启动集群设置向导。

有关分配节点管理IP地址的信息、请参见link:https://docs.netapp.com/us-en/ontap/software_setup/task_create_the_cluster_on_the_first_node.html["在第一个节点上创建集群"^]。



== 初始化和配置集群

您可以通过设置集群的管理密码以及设置集群管理和节点管理网络来初始化集群。您还可以配置域名服务器(DNS)等服务来解析主机名、并配置NTP服务器来同步时间。

.步骤
. 在Web浏览器中、输入已配置的节点管理IP地址："https://node-management-IP"[]
+
System Manager 会自动发现集群中的其余节点。

. 在 * 初始化存储系统 * 窗口中，执行以下操作：
+
.. 输入集群管理网络配置数据。
.. 输入所有节点的节点管理 IP 地址。
.. 提供 DNS 详细信息。
.. 在 * 其他 * 部分中，选中标记为 * 使用时间服务（ NTP ） * 的复选框以添加时间服务器。




单击 * 提交 * 后，请等待创建和配置集群。然后，将执行验证过程。

.下一步是什么？
在设置、初始化和配置两个集群后、执行此link:../install-ip/set-up-mcc-peering-system-manager.html["设置MetroCluster IP对等"]过程。



== 在新的集群视频上配置 ONTAP

video::PiX41bospbQ[youtube,width=848,height=480]