---
permalink: install-ip/task_switch_config_cisco.html 
sidebar: sidebar 
keywords: ip, switch, configuring, configure, factory defaults, cisco, MACsec encryption, 9336C, 9336, forward error correction, fec 
summary: 您必须将 Cisco IP 交换机配置为用作集群互连以及用于后端 MetroCluster IP 连接。 
---
= 配置 Cisco IP 交换机
:allow-uri-read: 


[role="lead"]
您必须将 Cisco IP 交换机配置为用作集群互连以及用于后端 MetroCluster IP 连接。

.关于此任务
本节中的几个过程是独立的，您只需执行引导到您或与您的任务相关的过程即可。



== 将 Cisco IP 交换机重置为出厂默认值

在安装任何 RCF 文件之前，您必须擦除 Cisco 交换机配置并执行基本配置。如果要在先前安装失败后重新安装同一个 RCF 文件，或者要安装新版本的 RCF 文件，则需要此操作步骤 。

.关于此任务
* 您必须对 MetroCluster IP 配置中的每个 IP 交换机重复这些步骤。
* 您必须使用串行控制台连接到交换机。
* 此任务将重置管理网络的配置。


.步骤
. 将交换机重置为出厂默认设置：
+
.. 擦除现有配置：
+
`写入擦除`

.. 重新加载交换机软件：
+
`re负载`

+
系统将重新启动并进入配置向导。在启动期间，如果您收到提示 "`Abort Auto Provisioning and continue with normal setup ？（是 / 否） [n]` " ，您应回答 `是` 以继续。

.. 在配置向导中，输入基本交换机设置：
+
*** 管理员密码
*** 交换机名称
*** 带外管理配置
*** 默认网关
*** SSH 服务（ RSA ）
+
完成配置向导后，交换机将重新启动。



.. 出现提示时，输入用户名和密码以登录到交换机。
+
以下示例显示了配置交换机时的提示和系统响应。尖括号（` <<<` ）显示信息的输入位置。

+
[listing]
----
---- System Admin Account Setup ----
Do you want to enforce secure password standard (yes/no) [y]:y  **<<<**

    Enter the password for "admin": password
  Confirm the password for "admin": password
         ---- Basic System Configuration Dialog VDC: 1 ----

This setup utility will guide you through the basic configuration of
the system. Setup configures only enough connectivity for management
of the system.

Please register Cisco Nexus3000 Family devices promptly with your
supplier. Failure to register may affect response times for initial
service calls. Nexus3000 devices must be registered to receive
entitled support services.

Press Enter at anytime to skip a dialog. Use ctrl-c at anytime
to skip the remaining dialogs.
----
+
您可以在下一组提示中输入基本信息，包括交换机名称，管理地址和网关，然后选择 SSH with RSA 。

+
[listing]
----
Would you like to enter the basic configuration dialog (yes/no): yes
  Create another login account (yes/no) [n]:
  Configure read-only SNMP community string (yes/no) [n]:
  Configure read-write SNMP community string (yes/no) [n]:
  Enter the switch name : switch-name **<<<**
  Continue with Out-of-band (mgmt0) management configuration? (yes/no) [y]:
    Mgmt0 IPv4 address : management-IP-address  **<<<**
    Mgmt0 IPv4 netmask : management-IP-netmask  **<<<**
  Configure the default gateway? (yes/no) [y]: y **<<<**
    IPv4 address of the default gateway : gateway-IP-address  **<<<**
  Configure advanced IP options? (yes/no) [n]:
  Enable the telnet service? (yes/no) [n]:
  Enable the ssh service? (yes/no) [y]: y  **<<<**
    Type of ssh key you would like to generate (dsa/rsa) [rsa]: rsa **<<<**
    Number of rsa key bits <1024-2048> [1024]:
  Configure the ntp server? (yes/no) [n]:
  Configure default interface layer (L3/L2) [L2]:
  Configure default switchport interface state (shut/noshut) [noshut]: shut **<<<**
  Configure CoPP system profile (strict/moderate/lenient/dense) [strict]:
----
+
最后一组提示将完成配置：

+
[listing]
----
The following configuration will be applied:
  password strength-check
  switchname IP_switch_A_1
vrf context management
ip route 0.0.0.0/0 10.10.99.1
exit
  no feature telnet
  ssh key rsa 1024 force
  feature ssh
  system default switchport
  system default switchport shutdown
  copp profile strict
interface mgmt0
ip address 10.10.99.10 255.255.255.0
no shutdown

Would you like to edit the configuration? (yes/no) [n]:

Use this configuration and save it? (yes/no) [y]:
2017 Jun 13 21:24:43 A1 %$ VDC-1 %$ %COPP-2-COPP_POLICY: Control-Plane is protected with policy copp-system-p-policy-strict.

[########################################] 100%
Copy complete.

User Access Verification
IP_switch_A_1 login: admin
Password:
Cisco Nexus Operating System (NX-OS) Software
.
.
.
IP_switch_A_1#
----


. 保存配置：
+
[listing]
----
 IP_switch-A-1# copy running-config startup-config
----
. 重新启动交换机并等待交换机重新加载：
+
[listing]
----
 IP_switch-A-1# reload
----
. 对 MetroCluster IP 配置中的其他三台交换机重复上述步骤。




== 下载并安装 Cisco 交换机 NX-OS 软件

您必须将交换机操作系统文件和 RCF 文件下载到 MetroCluster IP 配置中的每个交换机。

.关于此任务
此任务需要使用文件传输软件，例如 FTP ， TFTP ， SFTP 或 SCP ， 将文件复制到交换机。

必须对 MetroCluster IP 配置中的每个 IP 交换机重复执行这些步骤。

您必须使用支持的交换机软件版本。

https://hwu.netapp.com["NetApp Hardware Universe"]

.步骤
. 下载支持的 NX-OS 软件文件。
+
link:https://software.cisco.com/download/home["Cisco 软件下载"^]

. 将交换机软件复制到交换机：
+
`copy sftp ： //root@server-IP-address/tftpboot/NX-os-file-name bootflash ： vRF management`

+
在此示例中， nxos.7.0.3.I4.6.bin 文件将从 SFTP 服务器 10.10.99.99 复制到本地 bootflash ：

+
[listing]
----
IP_switch_A_1# copy sftp://root@10.10.99.99/tftpboot/nxos.7.0.3.I4.6.bin bootflash: vrf management
root@10.10.99.99's password: password
sftp> progress
Progress meter enabled
sftp> get   /tftpboot/nxos.7.0.3.I4.6.bin  /bootflash/nxos.7.0.3.I4.6.bin
Fetching /tftpboot/nxos.7.0.3.I4.6.bin to /bootflash/nxos.7.0.3.I4.6.bin
/tftpboot/nxos.7.0.3.I4.6.bin                 100%  666MB   7.2MB/s   01:32
sftp> exit
Copy complete, now saving to disk (please wait)...
----
. 在每个交换机上验证交换机 NX-OS 文件是否位于每个交换机的 bootflash 目录中：
+
`d的 bootflash ：`

+
以下示例显示文件位于 ip_switch_A_1 上：

+
[listing]
----
IP_switch_A_1# dir bootflash:
                  .
                  .
                  .
  698629632    Jun 13 21:37:44 2017  nxos.7.0.3.I4.6.bin
                  .
                  .
                  .

Usage for bootflash://sup-local
 1779363840 bytes used
13238841344 bytes free
15018205184 bytes total
IP_switch_A_1#
----
. 安装交换机软件：
+
`安装所有 nxos bootflash ： nxos.version-number.bin`

+
安装交换机软件后，交换机将自动重新加载（重新启动）。

+
以下示例显示了 IP_switch_A_1 上的软件安装：

+
[listing]
----
IP_switch_A_1# install all nxos bootflash:nxos.7.0.3.I4.6.bin
Installer will perform compatibility check first. Please wait.
Installer is forced disruptive

Verifying image bootflash:/nxos.7.0.3.I4.6.bin for boot variable "nxos".
[####################] 100% -- SUCCESS

Verifying image type.
[####################] 100% -- SUCCESS

Preparing "nxos" version info using image bootflash:/nxos.7.0.3.I4.6.bin.
[####################] 100% -- SUCCESS

Preparing "bios" version info using image bootflash:/nxos.7.0.3.I4.6.bin.
[####################] 100% -- SUCCESS       [####################] 100%            -- SUCCESS

Performing module support checks.            [####################] 100%            -- SUCCESS

Notifying services about system upgrade.     [####################] 100%            -- SUCCESS



Compatibility check is done:
Module  bootable          Impact  Install-type  Reason
------  --------  --------------  ------------  ------
     1       yes      disruptive         reset  default upgrade is not hitless



Images will be upgraded according to following table:
Module       Image   Running-Version(pri:alt)         New-Version   Upg-Required
------  ----------   ------------------------  ------------------   ------------
     1        nxos                7.0(3)I4(1)         7.0(3)I4(6)   yes
     1        bios         v04.24(04/21/2016)  v04.24(04/21/2016)   no


Switch will be reloaded for disruptive upgrade.
Do you want to continue with the installation (y/n)?  [n] y


Install is in progress, please wait.

Performing runtime checks.         [####################] 100%    -- SUCCESS

Setting boot variables.
[####################] 100% -- SUCCESS

Performing configuration copy.
[####################] 100% -- SUCCESS

Module 1: Refreshing compact flash and upgrading bios/loader/bootrom.
Warning: please do not remove or power off the module at this time.
[####################] 100% -- SUCCESS


Finishing the upgrade, switch will reboot in 10 seconds.
IP_switch_A_1#
----
. 等待交换机重新加载，然后登录到交换机。
+
交换机重新启动后，将显示登录提示：

+
[listing]
----
User Access Verification
IP_switch_A_1 login: admin
Password:
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2017, Cisco and/or its affiliates.
All rights reserved.
.
.
.
MDP database restore in progress.
IP_switch_A_1#

The switch software is now installed.
----
. 验证是否已安装交换机软件： + `show version`
+
以下示例显示了输出：

+
[listing]
----
IP_switch_A_1# show version
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2017, Cisco and/or its affiliates.
All rights reserved.
.
.
.

Software
  BIOS: version 04.24
  NXOS: version 7.0(3)I4(6)   **<<< switch software version**
  BIOS compile time:  04/21/2016
  NXOS image file is: bootflash:///nxos.7.0.3.I4.6.bin
  NXOS compile time:  3/9/2017 22:00:00 [03/10/2017 07:05:18]


Hardware
  cisco Nexus 3132QV Chassis
  Intel(R) Core(TM) i3- CPU @ 2.50GHz with 16401416 kB of memory.
  Processor Board ID FOC20123GPS

  Device name: A1
  bootflash:   14900224 kB
  usb1:               0 kB (expansion flash)

Kernel uptime is 0 day(s), 0 hour(s), 1 minute(s), 49 second(s)

Last reset at 403451 usecs after  Mon Jun 10 21:43:52 2017

  Reason: Reset due to upgrade
  System version: 7.0(3)I4(1)
  Service:

plugin
  Core Plugin, Ethernet Plugin
IP_switch_A_1#
----
. 对 MetroCluster IP 配置中的其余三个 IP 交换机重复上述步骤。




== 下载并安装 Cisco IP RCF 文件

您必须将 RCF 文件下载到 MetroCluster IP 配置中的每个交换机。

.关于此任务
此任务需要使用文件传输软件，例如 FTP ， TFTP ， SFTP 或 SCP ， 将文件复制到交换机。

必须对 MetroCluster IP 配置中的每个 IP 交换机重复执行这些步骤。

您必须使用支持的交换机软件版本。

https://hwu.netapp.com["NetApp Hardware Universe"]

有四个 RCF 文件， MetroCluster IP 配置中的四个交换机中的每个交换机一个。您必须为所使用的交换机型号使用正确的 RCF 文件。

|===


| 交换机 | RCF 文件 


 a| 
IP_switch_A_1
 a| 
NX3232_v1.80_Switch-A1.txt



 a| 
IP_switch_A_2
 a| 
NX3232_v1.80_Switch-A2.txt



 a| 
IP_switch_B_1
 a| 
NX3232_v1.80_Switch-B1.txt



 a| 
IP_switch_B_2
 a| 
NX3232_v1.80_Switch-B2.txt

|===
.步骤
. 下载 MetroCluster IP RCF 文件。
+

NOTE: 不支持在下载后修改RCF文件。

. 将 RCF 文件复制到交换机：
+
.. 将 RCF 文件复制到第一个交换机：
+
`copy sftp ： //root@ftp-server-ip-address/tftpboot/switch-specific — rCF bootflash ： vrf management`

+
在此示例中， NX3232_v1.80_Switch-A1.txt RCF 文件将从位于 10.10.99.99 的 SFTP 服务器复制到本地 bootflash 。您必须使用 TFTP/SFTP 服务器的 IP 地址以及需要安装的 RCF 文件的文件名。

+
[listing]
----
IP_switch_A_1# copy sftp://root@10.10.99.99/tftpboot/NX3232_v1.80_Switch-A1.txt bootflash: vrf management
root@10.10.99.99's password: password
sftp> progress
Progress meter enabled
sftp> get   /tftpboot/NX3232_v1.80_Switch-A1.txt /bootflash/NX3232_v1.80_Switch-A1.txt
Fetching /tftpboot/NX3232_v1.80_Switch-A1.txt to /bootflash/NX3232_v1.80_Switch-A1.txt
/tftpboot/NX3232_v1.80_Switch-A1.txt          100% 5141     5.0KB/s   00:00
sftp> exit
Copy complete, now saving to disk (please wait)...
IP_switch_A_1#
----
.. 对其他三个交换机中的每一个交换机重复上述子步骤，确保将匹配的 RCF 文件复制到相应的交换机。


. 在每个交换机上验证 RCF 文件是否位于每个交换机的 bootflash 目录中：
+
`d的 bootflash ：`

+
以下示例显示文件位于 ip_switch_A_1 上：

+
[listing]
----
IP_switch_A_1# dir bootflash:
                  .
                  .
                  .
5514    Jun 13 22:09:05 2017  NX3232_v1.80_Switch-A1.txt
                  .
                  .
                  .

Usage for bootflash://sup-local
1779363840 bytes used
13238841344 bytes free
15018205184 bytes total
IP_switch_A_1#
----
. 在 Cisco 3132Q-V 和 Cisco 3232C 交换机上配置 TCAM 区域。
+

NOTE: 如果您没有 Cisco 3132Q-V 或 Cisco 3232C 交换机，请跳过此步骤。

+
.. 在 Cisco 3132Q-V 交换机上，设置以下 TCAM 区域：
+
[listing]
----
conf t
hardware access-list tcam region span 0
hardware access-list tcam region racl 256
hardware access-list tcam region e-racl 256
hardware access-list tcam region qos 256
----
.. 在 Cisco 3232C 交换机上，设置以下 TCAM 区域：
+
[listing]
----
conf t
hardware access-list tcam region span 0
hardware access-list tcam region racl-lite 0
hardware access-list tcam region racl 256
hardware access-list tcam region e-racl 256
hardware access-list tcam region qos 256
----
.. 设置 TCAM 区域后，保存配置并重新加载交换机：
+
[listing]
----
copy running-config startup-config
reload
----


. 将匹配的 RCF 文件从本地 bootflash 复制到每个交换机上的运行配置：
+
`copy bootflash ： switch-specific-RCF.txt running-config`

. 将 RCF 文件从正在运行的配置复制到每个交换机上的启动配置：
+
`copy running-config startup-config`

+
您应看到类似于以下内容的输出：

+
[listing]
----
IP_switch_A_1# copy bootflash:NX3232_v1.80_Switch-A1.txt running-config
IP_switch-A-1# copy running-config startup-config
----
. 重新加载交换机：
+
`re负载`

+
[listing]
----
IP_switch_A_1# reload
----
. 对 MetroCluster IP 配置中的其他三台交换机重复上述步骤。




== 为使用 25 Gbps 连接的系统设置正向错误更正

如果您的系统配置为使用 25 Gbps 连接，则在应用 RCF 文件后，您需要手动将正向错误更正（ FEC ）参数设置为关闭。RCF 文件不应用此设置。

.关于此任务
在执行此操作步骤之前，必须为 25 Gbps 端口布线。

link:port_usage_3232c_9336c.html["Cisco 3232C 或 Cisco 9336C 交换机的平台端口分配"]

此任务仅限使用 25-Gbps 连接的适用场景 平台：

* AFF A300
* FAS 8200
* FAS 500f
* AFF A250


必须对 MetroCluster IP 配置中的所有四台交换机执行此任务。

.步骤
. 在连接到控制器模块的每个 25 Gbps 端口上将 FEC 参数设置为 off ，然后将正在运行的配置复制到启动配置：
+
.. 进入配置模式： `config t`
.. 指定要配置的 25-Gbps 接口： `interface interface-ID`
.. 将 FEC 设置为 off ： `fEC off`
.. 对交换机上的每个 25 Gbps 端口重复上述步骤。
.. 退出配置模式： `exit`
+
以下示例显示了针对交换机 IP_switch_A_1 上的接口 Ethernet1/2/1 的命令：

+
[listing]
----
IP_switch_A_1# conf t
IP_switch_A_1(config)# interface Ethernet1/25/1
IP_switch_A_1(config-if)# fec off
IP_switch_A_1(config-if)# exit
IP_switch_A_1(config-if)# end
IP_switch_A_1# copy running-config startup-config
----


. 对 MetroCluster IP 配置中的其他三台交换机重复上述步骤。




== 禁用未使用的ISL端口和端口通道

NetApp建议禁用未使用的ISL端口和端口通道、以避免发出不必要的运行状况警报。

. 确定未使用的ISL端口和端口通道：
+
`s如何使用接口简介`

. 禁用未使用的ISL端口和端口通道。
+
您必须对每个已确定的未使用端口或端口通道运行以下命令。

+
[listing]
----
SwitchA_1# config t
Enter configuration commands, one per line. End with CNTL/Z.
SwitchA_1(config)# int Eth1/14
SwitchA_1(config-if)# shutdown
SwitchA_12(config-if)# exit
SwitchA_1(config-if)# copy running-config startup-config
[########################################] 100%
Copy complete, now saving to disk (please wait)...
Copy complete.
----

