---
permalink: install-ip/task_remove_unconfigure_mediator.html 
sidebar: sidebar 
keywords: ontap, mediator, assist, remove, unconfigure, requirements, mediator requirements 
summary: 您可以从 MetroCluster IP 配置中删除 ONTAP 调解器。 
---
= 从MetroCluster IP 配置中删除ONTAP调解器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以从 MetroCluster IP 配置中取消配置 ONTAP 调解器。

.开始之前
您必须已在两个 MetroCluster 站点均可访问的网络位置上成功安装和配置 ONTAP 调解器。

.步骤
. 使用以下命令取消配置 ONTAP 调解器：
+
`MetroCluster configuration-settings mediator remove`

+
系统会提示您输入ONTAP调解器管理员用户帐户的用户名和密码。

+

NOTE: 如果 ONTAP 调解器发生故障，  `metrocluster configuration-settings mediator remove`命令仍会提示您输入 ONTAP Mediator 管理员用户帐户的用户名和密码，并从 MetroCluster 配置中删除 ONTAP Mediator。

+
.. 使用以下命令检查是否存在任何损坏的磁盘：
+
`d`显示-broken

+
* 示例 *

+
....
There are no entries matching your query.
....


. 如果您使用的是使用 HTTPS 进行通信的 ONTAP Mediator，请在删除 ONTAP Mediator 后删除 CA 证书：
+
.. 显示已安装的 CA 证书：
+
`security certificate show -common-name ONTAPMediatorCA`

.. 删除已安装的根证书和中间证书：
+
`security certificate delete -vserver cluster-A -common-name ONTAPMediatorCA -cert-name <root_certificate_name> -type server-ca -ca "ONTAP Mediator CA"`

+
`security certificate delete -vserver cluster-A -common-name ONTAPMediatorCA -cert-name <intermediate_certificate_name> -type server-ca -ca "ONTAP Mediator CA"`



. 通过在两个群集上运行以下命令，确认已从 MetroCluster 配置中删除 ONTAP Mediator：
+
.. `metrocluster configuration-settings mediator show`
+
* 示例 *

+
[listing]
----
This table is currently empty.
----



