---
permalink: install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html 
sidebar: sidebar 
keywords: metrocluster, mediator, configure 
summary: 必须在 ONTAP 节点上配置 ONTAP 调解器才能在 MetroCluster IP 配置中使用。 
---
= 为MetroCluster IP 配置设置ONTAP调解器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
要在MetroCluster IP 配置中使用ONTAP Mediator，必须在ONTAP节点上配置 ONTAP Mediator。

.开始之前
* ONTAP 调解器必须已成功安装在两个 MetroCluster 站点均可访问的网络位置上。
+
link:https://docs.netapp.com/us-en/ontap/mediator/index.html["安装或升级 ONTAP 调解器"^]

* 您必须拥有运行 ONTAP Mediator 的主机的 IP 地址。
* 您必须拥有 ONTAP Mediator 的用户名和密码。
* MetroCluster IP 配置的所有节点都必须联机。



CAUTION: 从ONTAP 9.12.1开始、您可以在MetroCluster IP配置中启用MetroCluster 自动强制切换功能。此功能是调解器辅助计划外切换的扩展。启用此功能之前、请查看 link:concept-ontap-mediator-supports-automatic-unplanned-switchover.html#mauso-9-12-1["使用MetroCluster 自动强制切换的风险和限制"]。

.关于此任务
* 默认情况下，此任务会启用自动计划外切换。
* 此任务可在 MetroCluster IP 配置中任何节点的 ONTAP 接口上执行。
* 从ONTAP 9.18.1 和ONTAP Mediator 1.11 开始，单个ONTAP Mediator 实例可以同时管理多达 10 个MetroCluster配置。在早期版本中， ONTAP Mediator 可以同时支持最多五个MetroCluster配置。


.步骤
. 将ONTAP Mediator 添加到ONTAP。具体步骤取决于您要使用 IPv4 地址还是 IPv6 地址。
+
[NOTE]
====
** 要使用 IPv6，您必须运行ONTAP 9.18.1 或更高版本以及ONTAP Mediator 1.11 或更高版本。
** 如果在集群上启用 IPv6，则以后无法禁用。


====
+
[role="tabbed-block"]
====
.使用 IPv4
--
.. 运行以下命令添加ONTAP中介器：
+
`metrocluster configuration-settings mediator add -mediator-address <mediator_host_ip_address>`

+

NOTE: 系统会提示您输入 Mediator 管理员用户帐户的用户名和密码。



--
.使用 IPv6
--
.. 在两个集群上运行以下命令：
+
`network options ipv6 modify -enabled true`

.. 在所有四个节点上配置节点管理 IP 地址，使用 IPv6 地址。
.. 添加ONTAP中介器：
+
`metrocluster configuration-settings mediator add -mediator-address <mediator_host_ipv6_ip_address>`

+

NOTE: 系统会提示您输入 Mediator 管理员用户帐户的用户名和密码。



--
====
. 验证是否已启用自动切换功能：
+
`MetroCluster show`

. 验证调解器当前是否正在运行。
+
.. 显示调解器虚拟磁盘：
+
`storage disk show -container-type mediator`

+
....
 cluster_A::> storage disk show -container-type mediator
                        Usable           Disk    Container   Container
 Disk                   Size Shelf Bay Type    Type        Name      Owner
 ---------------- ---------- ----- --- ------- ----------- --------- --------
 NET-1.5                   -     -   - VMDISK  mediator    -         node_A_2
 NET-1.6                   -     -   - VMDISK  mediator    -         node_B_1
 NET-1.7                   -     -   - VMDISK  mediator    -         node_B_2
 NET-1.8                   -     -   - VMDISK  mediator    -         node_A_1
....
.. 将权限模式设置为高级：
+
`set advanced`

+
....
 cluster_A::> set advanced
....
.. 显示标记为调解器的启动程序：
+
`storage iscsi-initiator show -label mediator`

+
....
 cluster_A::*> storage iscsi-initiator show -label mediator
   (storage iscsi-initiator show)
  +                                                                     Status
 Node Type Label    Target Portal      Target Name                      Admin/Op
 ---- ---- -------- ------------------ -------------------------------- --------
 node_A_1
      mailbox
           mediator 1.1.1.1       iqn.2012-05.local:mailbox.target.6616cd3f-9ef1-11e9-aada-00a098ccf5d8:a05e1ffb-9ef1-11e9-8f68- 00a098cbca9e:1 up/up
 node_A_2
      mailbox
           mediator 1.1.1.1       iqn.2012-05.local:mailbox.target.6616cd3f-9ef1-11e9-aada-00a098ccf5d8:a05e1ffb-9ef1-11e9-8f68-00a098cbca9e:1 up/up
....
.. 验证自动计划外切换(Automatic Unun已 计划切换、AUSO)故障域的状态：
+
`MetroCluster show`

+

NOTE: 以下示例输出 适用场景 ONTAP 9.13.1.及更高版本。对于ONTAP 9.12.1及更早版本、USO故障域状态应为 `auso-on-cluster-disaster`。

+
[listing]
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-dr-group-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-dr-group-disaster
----


. (可选)配置MetroCluster自动强制切换。
+
您只能在高级权限级别下使用以下命令。

+

IMPORTANT: 使用此命令之前、请查看 link:concept-ontap-mediator-supports-automatic-unplanned-switchover.html#mauso-9-12-1["使用MetroCluster 自动强制切换的风险和限制"]。

+
`metrocluster modify -allow-auto-forced-switchover true`

+
....
cluster_A::*> metrocluster modify -allow-auto-forced-switchover true
....

