---
permalink: install-ip/task-configure-end-to-end-encryption.html 
sidebar: sidebar 
keywords: metrocluster, ip, encryption, end-to-end, backend, aff a400, fas8300, fas8700, encrypt, enable, disable 
summary:  
---
= 在MetroCluster IP配置中配置端到端加密
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
从ONTAP 9.15.1 开始，您可以在支持的系统上配置端到端加密，以加密MetroCluster IP 配置中的站点之间的后端流量，例如 NVlog 和存储复制数据。

.关于此任务
* 您必须是集群管理员才能执行此任务。
* 在配置端到端加密之前、您必须先配置 link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/configure-external-key-management-concept.html["配置外部密钥管理"^]。
* 查看在MetroCluster IP配置中配置端到端加密所需的受支持系统和最低ONTAP版本：
+
[cols="2*"]
|===
| 最低ONTAP版本 | 支持的系统 


 a| 
ONTAP 9.17.1
 a| 
** AFF A800和AFF C800
** AFF A20、 AFF A30、 AFF C30、 AFF A50、 AFF C60
** AFF A70、 AFF A90、 AFF A1K、 AFF C80
** FAS50、FAS70、FAS90




 a| 
ONTAP 9.15.1.
 a| 
** AFF A400
** AFF C400
** FAS8300
** FAS8700


|===




== 启用端到端加密

执行以下步骤以启用端到端加密。

.步骤
. 验证 MetroCluster 配置的运行状况。
+
.. 验证 MetroCluster 组件是否运行正常：
+
[source, cli]
----
metrocluster check run
----
+
[listing]
----
cluster_A::*> metrocluster check run
----
+
此操作将在后台运行。

.. 在之后 `metrocluster check run` 操作完成、运行：
+
[source, cli]
----
metrocluster check show
----
+
大约五分钟后，将显示以下结果：

+
[listing]
----
cluster_A:::*> metrocluster check show

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
clusters            ok
connections         ok
volumes             ok
7 entries were displayed.
----
.. 检查正在运行的 MetroCluster 检查操作的状态：
+
[source, cli]
----
metrocluster operation history show -job-id <id>
----
.. 验证是否没有运行状况警报：
+
[source, cli]
----
system health alert show
----


. 验证是否已在两个集群上配置外部密钥管理：
+
[source, cli]
----
security key-manager external show-status
----
. 为每个DR组启用端到端加密：
+
[source, cli]
----
metrocluster modify -is-encryption-enabled true -dr-group-id <dr_group_id>
----
+
* 示例 *

+
[listing]
----
cluster_A::*> metrocluster modify -is-encryption-enabled true -dr-group-id 1
Warning: Enabling encryption for a DR Group will secure NVLog and Storage
         replication data sent between MetroCluster nodes and have an impact on
         performance. Do you want to continue? {y|n}: y
[Job 244] Job succeeded: Modify is successful.
----
+
对配置中的每个DR组重复此步骤。

. 验证是否已启用端到端加密：
+
[source, cli]
----
metrocluster node show -fields is-encryption-enabled
----
+
* 示例 *

+
[listing]
----
cluster_A::*> metrocluster node show -fields is-encryption-enabled

dr-group-id cluster    node      configuration-state is-encryption-enabled
----------- ---------- --------  ------------------- -----------------
1           cluster_A  node_A_1  configured          true
1           cluster_A  node_A_2  configured          true
1           cluster_B  node_B_1  configured          true
1           cluster_B  node_B_2  configured          true
4 entries were displayed.
----




== 禁用端到端加密

执行以下步骤以禁用端到端加密。

.步骤
. 验证 MetroCluster 配置的运行状况。
+
.. 验证 MetroCluster 组件是否运行正常：
+
[source, cli]
----
metrocluster check run
----
+
[listing]
----
cluster_A::*> metrocluster check run

----
+
此操作将在后台运行。

.. 在之后 `metrocluster check run` 操作完成、运行：
+
[source, cli]
----
metrocluster check show
----
+
大约五分钟后，将显示以下结果：

+
[listing]
----
cluster_A:::*> metrocluster check show

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
clusters            ok
connections         ok
volumes             ok
7 entries were displayed.
----
.. 检查正在运行的 MetroCluster 检查操作的状态：
+
[source, cli]
----
metrocluster operation history show -job-id <id>
----
.. 验证是否没有运行状况警报：
+
[source, cli]
----
system health alert show
----


. 验证是否已在两个集群上配置外部密钥管理：
+
[source, cli]
----
security key-manager external show-status
----
. 在每个DR组上禁用端到端加密：
+
[source, cli]
----
metrocluster modify -is-encryption-enabled false -dr-group-id <dr_group_id>
----
+
* 示例 *

+
[listing]
----
cluster_A::*> metrocluster modify -is-encryption-enabled false -dr-group-id 1
[Job 244] Job succeeded: Modify is successful.
----
+
对配置中的每个DR组重复此步骤。

. 验证是否已禁用端到端加密：
+
[source, cli]
----
metrocluster node show -fields is-encryption-enabled
----
+
* 示例 *

+
[listing]
----
cluster_A::*> metrocluster node show -fields is-encryption-enabled

dr-group-id cluster    node      configuration-state is-encryption-enabled
----------- ---------- --------  ------------------- -----------------
1           cluster_A  node_A_1  configured          false
1           cluster_A  node_A_2  configured          false
1           cluster_B  node_B_1  configured          false
1           cluster_B  node_B_2  configured          false
4 entries were displayed.
----

