---
permalink: install-ip/task_switch_config_broadcom.html 
sidebar: sidebar 
keywords: ip, switch, connection, configuring, configure, broadcom, factory defaults 
summary: 您必须将 Broadcom IP 交换机配置为用作集群互连并用于后端 MetroCluster IP 连接。 
---
= 配置 Broadcom IP 交换机


[role="lead"]
您必须将 Broadcom IP 交换机配置为用作集群互连并用于后端 MetroCluster IP 连接。



= 将 Broadcom IP 交换机重置为出厂默认值

[role="lead"]
在安装新的交换机软件版本和 RCF 之前，您必须擦除 Broadcom 交换机设置并执行基本配置。

.关于此任务
* 您必须对 MetroCluster IP 配置中的每个 IP 交换机重复这些步骤。
* 您必须使用串行控制台连接到交换机。
* 此任务将重置管理网络的配置。


.步骤
. 更改为提升的命令提示符（` #` ）：
+
`启用`

+
[listing]
----
(Routing)> enable
(Routing) #
----
. 擦除启动配置：
+
`erase startup-config`

+
[listing]
----
(Routing) #erase startup-config
Are you sure you want to clear the configuration? (y/n) y


(Routing) #
----
+
此命令不会擦除横幅。

. 重新启动交换机：
+
`re负载`

+
[listing]
----
(IP_switch_A_1) #reload

Are you sure you would like to reset the system? (y/n) y
----
+

NOTE: 如果系统在重新加载交换机之前询问是保存未保存的配置还是更改的配置，请选择 * 否 * 。

. 等待交换机重新加载，然后登录到交换机。
+
默认用户为 "`admin` " ，未设置密码。此时将显示类似于以下内容的提示：

+
[listing]
----
(Routing)>
----
. 更改为提升后的命令提示符：
+
`启用`

+
[listing]
----
Routing)> enable
(Routing) #
----
. 将服务端口协议设置为 `none` ：
+
`s服务端口协议无`

+
[listing]
----
(Routing) #serviceport protocol none
Changing protocol mode will reset ip configuration.
Are you sure you want to continue? (y/n) y

(Routing) #
----
. 将 IP 地址分配给服务端口：
+
`serviceport IP _IP-address_ _netmask_ _gateway_`

+
以下示例显示了一个服务端口分配的 IP 地址 10.10.10.10 ，子网为 255.255.255.0 ，网关为 10.10.10.1 ：

+
[listing]
----
(Routing) #serviceport ip 10.10.10.10 255.255.255.0 10.10.10.1
----
. 验证服务端口是否配置正确：
+
`s如何使用 serviceport`

+
以下示例显示端口已启动，并且已分配正确的地址：

+
[listing]
----
(Routing) #show serviceport

Interface Status............................... Up
IP Address..................................... 10.10.10.10
Subnet Mask.................................... 255.255.255.0
Default Gateway................................ 10.10.10.1
IPv6 Administrative Mode....................... Enabled
IPv6 Prefix is ................................ fe80::dac4:97ff:fe56:87d7/64
IPv6 Default Router............................ fe80::222:bdff:fef8:19ff
Configured IPv4 Protocol....................... None
Configured IPv6 Protocol....................... None
IPv6 AutoConfig Mode........................... Disabled
Burned In MAC Address.......................... D8:C4:97:56:87:D7

(Routing) #
----
. 如果需要，请配置 SSH 服务器。
+

NOTE: RCF 文件将禁用 Telnet 协议。如果不配置 SSH 服务器，则只能使用串行端口连接访问网桥。

+
.. 生成 RSA 密钥。
+
[listing]
----
(Routing) #configure
(Routing) (Config)#crypto key generate rsa
----
.. 生成 DSA 密钥。
+
[listing]
----
(Routing) #configure
(Routing) (Config)#crypto key generate dsa
----
.. 启用 SSH 服务器。
+
如有必要，退出配置上下文。

+
[listing]
----
(Routing) (Config)#end
(Routing) #ip ssh server enable
----
+

NOTE: 如果密钥已存在，则可能会要求您覆盖这些密钥。



. 如果需要，请配置域和名称服务器：
+
`配置`

+
以下示例显示了 `ip domain` 和 `ip name server` 命令：

+
[listing]
----
(Routing) # configure
(Routing) (Config)#ip domain name lab.netapp.com
(Routing) (Config)#ip name server 10.99.99.1 10.99.99.2
(Routing) (Config)#exit
(Routing) (Config)#
----
. 如果需要，请配置时区和时间同步（ SNTP ）。
+
以下示例显示了 `sntp` 命令，用于指定 SNTP 服务器的 IP 地址和相对时区。

+
[listing]
----
(Routing) #
(Routing) (Config)#sntp client mode unicast
(Routing) (Config)#sntp server 10.99.99.5
(Routing) (Config)#clock timezone -7
(Routing) (Config)#exit
(Routing) (Config)#
----
. 配置交换机名称：
+
`主机名 ip_switch_A_1`

+
交换机提示符将显示新名称：

+
[listing]
----
(Routing) # hostname IP_switch_A_1

(IP_switch_A_1) #
----
. 保存配置：
+
`写入内存`

+
您将收到类似于以下示例的提示和输出：

+
[listing]
----
(IP_switch_A_1) #write memory

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully .


Configuration Saved!

(IP_switch_A_1) #
----
. 对 MetroCluster IP 配置中的其他三台交换机重复上述步骤。




== 下载并安装 Broadcom 交换机 EFOS 软件

您必须将交换机操作系统文件和 RCF 文件下载到 MetroCluster IP 配置中的每个交换机。

必须对 MetroCluster IP 配置中的每个交换机重复执行此任务。

.步骤
. 将交换机软件复制到交换机：
+
`copy sftp ： //user@50.50.50.50 switchsoftware/EFOS-3.4.3.1.stk backup`

+
在此示例中，将 EFOS-3.4.3.1.stk 操作系统文件从位于 "50.050.50" 的 SFTP 服务器复制到备份分区。您需要使用 TFTP/SFTP 服务器的 IP 地址以及需要安装的 RCF 文件的文件名。

+
[listing]
----
(IP_switch_A_1) #copy sftp://user@50.50.50.50/switchsoftware/efos-3.4.3.1.stk backup
Remote Password:*************

Mode........................................... SFTP
Set Server IP.................................. 50.50.50.50
Path........................................... /switchsoftware/
Filename....................................... efos-3.4.3.1.stk
Data Type...................................... Code
Destination Filename........................... backup

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y

File transfer in progress. Management access will be blocked for the duration of the transfer. Please wait...
SFTP Code transfer starting...


File transfer operation completed successfully.

(IP_switch_A_1) #
----
. 将交换机设置为在下次重新启动交换机时从备份分区启动：
+
`启动系统备份`

+
[listing]
----
(IP_switch_A_1) #boot system backup
Activating image backup ..

(IP_switch_A_1) #
----
. 验证新启动映像是否将在下次启动时处于活动状态：
+
`s如何启动 var`

+
[listing]
----
(IP_switch_A_1) #show bootvar

Image Descriptions

 active :
 backup :


 Images currently available on Flash

 ----  -----------  --------  ---------------  ------------
 unit       active    backup   current-active   next-active
 ----  -----------  --------  ---------------  ------------

	1       3.4.3.0      3.4.3.1      3.4.3.0          3.4.3.1

(IP_switch_A_1) #
----
. 保存配置：
+
`写入内存`

+
[listing]
----
(IP_switch_A_1) #write memory

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y


Configuration Saved!

(IP_switch_A_1) #
----
. 重新启动交换机：
+
`re负载`

+
[listing]
----
(IP_switch_A_1) #reload

Are you sure you would like to reset the system? (y/n) y
----
. 等待交换机重新启动。
. 对 MetroCluster IP 配置中的其余三个 IP 交换机重复上述步骤。




== 下载并安装 Broadcom RCF 文件

您必须将交换机 RCF 文件下载并安装到 MetroCluster IP 配置中的每个交换机。

此任务需要使用文件传输软件，例如 FTP ， TFTP ， SFTP 或 SCP ， 将文件复制到交换机。

必须对 MetroCluster IP 配置中的每个 IP 交换机重复执行这些步骤。

有四个 RCF 文件， MetroCluster IP 配置中的四个交换机中的每个交换机一个。您必须为所使用的交换机型号使用正确的 RCF 文件。

|===


| 交换机 | RCF 文件 


 a| 
IP_switch_A_1
 a| 
BES-53248_v1.32_Switch-A1.txt



 a| 
IP_switch_A_2
 a| 
BES-53248_v1.32_Switch-A2.txt



 a| 
IP_switch_B_1
 a| 
BES-53248_v1.32_Switch-B1.txt



 a| 
IP_switch_B_2
 a| 
BES-53248_v1.32_Switch-B2.txt

|===
.步骤
. 下载 Broadcom 交换机的 MetroCluster IP RCF 文件。
+
https://mysupport.netapp.com/NOW/download/software/metrocluster_ip/rcfs/download.shtml["适用于 MetroCluster IP 的 Broadcom 集群和管理网络交换机参考配置文件下载"]

. 将 RCF 文件复制到交换机：
+
.. 将 RCF 文件复制到第一个交换机： `copy sftp ： //user@ftp-server-IP-address/RcfFiles/switch-Specific -RCF NVRAM ： script BES-53248_v1.32_Switch-A1.txt nvram ： script BES-53248_v1.32_Switch-A1.SCR`
+
在此示例中，将 "BES-53248_v1.32_Switch-A1.txt" RCF 文件从位于 "50.050.50" 的 SFTP 服务器复制到本地 bootflash 。您需要使用 TFTP/SFTP 服务器的 IP 地址以及需要安装的 RCF 文件的文件名。

+
[listing]
----
(IP_switch_A_1) #copy sftp://user@50.50.50.50/RcfFiles/BES-53248_v1.32_Switch-A1.txt nvram:script BES-53248_v1.32_Switch-A1.scr

Remote Password:*************

Mode........................................... SFTP
Set Server IP.................................. 50.50.50.50
Path........................................... /RcfFiles/
Filename....................................... BES-53248_v1.32_Switch-A1.txt
Data Type...................................... Config Script
Destination Filename........................... BES-53248_v1.32_Switch-A1.scr

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y

File transfer in progress. Management access will be blocked for the duration of the transfer. Please wait...
File transfer operation completed successfully.


Validating configuration script...

config

set clibanner "********************************************************************************

* NetApp Reference Configuration File (RCF)

*

* Switch    : BES-53248


...
The downloaded RCF is validated. Some output is being logged here.
...


Configuration script validated.
File transfer operation completed successfully.

(IP_switch_A_1) #
----
.. 验证 RCF 文件是否已保存为脚本：
+
`s记录列表`

+
[listing]
----
(IP_switch_A_1) #script list

Configuration Script Name        Size(Bytes)  Date of Modification
-------------------------------  -----------  --------------------
BES-53248_v1.32_Switch-A1.scr             852   2019 01 29 18:41:25

1 configuration script(s) found.
2046 Kbytes free.
(IP_switch_A_1) #
----
.. 应用 RCF 脚本：
+
`s记录应用 BES-53248_v1.32_Switch-A1.SCR`

+
[listing]
----
(IP_switch_A_1) #script apply BES-53248_v1.32_Switch-A1.scr

Are you sure you want to apply the configuration script? (y/n) y


config

set clibanner "********************************************************************************

* NetApp Reference Configuration File (RCF)

*

* Switch    : BES-53248

...
The downloaded RCF is validated. Some output is being logged here.
...

Configuration script 'BES-53248_v1.32_Switch-A1.scr' applied.

(IP_switch_A_1) #
----
.. 保存配置：
+
`写入内存`

+
[listing]
----
(IP_switch_A_1) #write memory

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y


Configuration Saved!

(IP_switch_A_1) #
----
.. 重新启动交换机：
+
`re负载`

+
[listing]
----
(IP_switch_A_1) #reload

Are you sure you would like to reset the system? (y/n) y
----
.. 对其他三个交换机中的每一个交换机重复上述步骤，确保将匹配的 RCF 文件复制到相应的交换机。


. 重新加载交换机：
+
`re负载`

+
[listing]
----
IP_switch_A_1# reload
----
. 对 MetroCluster IP 配置中的其他三台交换机重复上述步骤。

