---
permalink: install-ip/task_switch_config_broadcom.html 
sidebar: sidebar 
keywords: ip, switch, connection, configuring, configure, broadcom, factory defaults 
summary: 您必须将 Broadcom IP 交换机配置为用作集群互连并用于后端 MetroCluster IP 连接。 
---
= 配置 Broadcom IP 交换机
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须将 Broadcom IP 交换机配置为用作集群互连并用于后端 MetroCluster IP 连接。


NOTE: 在以下情况下、您的配置需要额外的许可证(6个100-GB端口许可证)：

* 您可以使用端口53和54作为40-Gbps或100-Gbps MetroCluster ISL。
* 您可以使用一个平台将本地集群和MetroCluster 接口连接到端口49 - 52。




== 将 Broadcom IP 交换机重置为出厂默认值

在安装新的交换机软件版本和 RCF 之前，您必须擦除 Broadcom 交换机设置并执行基本配置。

.关于此任务
* 您必须对 MetroCluster IP 配置中的每个 IP 交换机重复这些步骤。
* 您必须使用串行控制台连接到交换机。
* 此任务将重置管理网络的配置。


.步骤
. 更改为提升的命令提示符（` #` ）： `enable`
+
[listing]
----
(IP_switch_A_1)> enable
(IP_switch_A_1) #
----
. 擦除启动配置并删除横幅
+
.. 擦除启动配置：
+
*`擦除启动配置` *

+
[listing]
----
(IP_switch_A_1) #erase startup-config

Are you sure you want to clear the configuration? (y/n) y

(IP_switch_A_1) #
----
+
此命令不会擦除横幅。

.. 删除横幅：
+
*`无设置剪贴画` *

+
[listing]
----
(IP_switch_A_1) #configure
(IP_switch_A_1)(Config) # no set clibanner
(IP_switch_A_1)(Config) #
----


. 重新启动交换机： *` （ IP_switch_A_1 ） #reload *`
+
[listing]
----
Are you sure you would like to reset the system? (y/n) y
----
+

NOTE: 如果系统在重新加载交换机之前询问是保存未保存的配置还是更改的配置，请选择 * 否 * 。

. 等待交换机重新加载，然后登录到交换机。
+
默认用户为 "`admin` " ，未设置密码。此时将显示类似于以下内容的提示：

+
[listing]
----
(Routing)>
----
. 更改为提升后的命令提示符：
+
`启用`

+
[listing]
----
Routing)> enable
(Routing) #
----
. 将服务端口协议设置为 `none` ：
+
`s服务端口协议无`

+
[listing]
----
(Routing) #serviceport protocol none
Changing protocol mode will reset ip configuration.
Are you sure you want to continue? (y/n) y

(Routing) #
----
. 将 IP 地址分配给服务端口：
+
`serviceport IP _IP-address_ _netmask_ _gateway_`

+
以下示例显示了一个服务端口分配的 IP 地址 10.10.10.10 ，子网为 255.255.255.0 ，网关为 10.10.10.1 ：

+
[listing]
----
(Routing) #serviceport ip 10.10.10.10 255.255.255.0 10.10.10.1
----
. 验证服务端口是否配置正确：
+
`s如何使用 serviceport`

+
以下示例显示端口已启动，并且已分配正确的地址：

+
[listing]
----
(Routing) #show serviceport

Interface Status............................... Up
IP Address..................................... 10.10.10.10
Subnet Mask.................................... 255.255.255.0
Default Gateway................................ 10.10.10.1
IPv6 Administrative Mode....................... Enabled
IPv6 Prefix is ................................ fe80::dac4:97ff:fe56:87d7/64
IPv6 Default Router............................ fe80::222:bdff:fef8:19ff
Configured IPv4 Protocol....................... None
Configured IPv6 Protocol....................... None
IPv6 AutoConfig Mode........................... Disabled
Burned In MAC Address.......................... D8:C4:97:56:87:D7

(Routing) #
----
. 如果需要，请配置 SSH 服务器。
+

NOTE: RCF 文件将禁用 Telnet 协议。如果不配置 SSH 服务器，则只能使用串行端口连接访问网桥。

+
.. 生成 RSA 密钥。
+
[listing]
----
(Routing) #configure
(Routing) (Config)#crypto key generate rsa
----
.. 生成 DSA 密钥（可选）
+
[listing]
----
(Routing) #configure
(Routing) (Config)#crypto key generate dsa
----
.. 如果您使用的是符合 FIPS 的 EFOS 版本，请生成 ECDSA 密钥。以下示例将创建长度为 256 的密钥。有效值为 256 ， 384 或 521 。
+
[listing]
----
(Routing) #configure
(Routing) (Config)#crypto key generate ecdsa 256
----
.. 启用 SSH 服务器。
+
如有必要，退出配置上下文。

+
[listing]
----
(Routing) (Config)#end
(Routing) #ip ssh server enable
----
+

NOTE: 如果密钥已存在，则可能会要求您覆盖这些密钥。



. 如果需要，请配置域和名称服务器：
+
`配置`

+
以下示例显示了 `ip domain` 和 `ip name server` 命令：

+
[listing]
----
(Routing) # configure
(Routing) (Config)#ip domain name lab.netapp.com
(Routing) (Config)#ip name server 10.99.99.1 10.99.99.2
(Routing) (Config)#exit
(Routing) (Config)#
----
. 如果需要，请配置时区和时间同步（ SNTP ）。
+
以下示例显示了 `sntp` 命令，用于指定 SNTP 服务器的 IP 地址和相对时区。

+
[listing]
----
(Routing) #
(Routing) (Config)#sntp client mode unicast
(Routing) (Config)#sntp server 10.99.99.5
(Routing) (Config)#clock timezone -7
(Routing) (Config)#exit
(Routing) (Config)#
----
. 配置交换机名称：
+
`主机名 ip_switch_A_1`

+
交换机提示符将显示新名称：

+
[listing]
----
(Routing) # hostname IP_switch_A_1

(IP_switch_A_1) #
----
. 保存配置：
+
`写入内存`

+
您将收到类似于以下示例的提示和输出：

+
[listing]
----
(IP_switch_A_1) #write memory

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully .


Configuration Saved!

(IP_switch_A_1) #
----
. 对 MetroCluster IP 配置中的其他三台交换机重复上述步骤。




== 下载并安装 Broadcom 交换机 EFOS 软件

您必须将交换机操作系统文件和 RCF 文件下载到 MetroCluster IP 配置中的每个交换机。

.关于此任务
必须对 MetroCluster IP 配置中的每个交换机重复执行此任务。

[]
====
* 请注意以下事项： *

* 从 EFOS 3.4.x.x 升级到 EFOS 3.7.x.x 或更高版本时，交换机必须运行 EFOS 3.4.4.6 （或更高版本 3.4.x.x ）。如果您运行的是之前的版本，请先将交换机升级到 EFOS 3.4.4.6 （或更高版本 3.4.x.x ），然后再将交换机升级到 EFOS 3.7.x.x 或更高版本。
* EFOS 3.4.x.x 和 3.7.x.x 或更高版本的配置有所不同。要将 EFOS 版本从 3.4.x.x 更改为 3.7.x.x 或更高版本，或者反之，则需要将交换机重置为出厂默认值，并重新应用相应 EFOS 版本的 RCF 文件。此操作步骤需要通过串行控制台端口进行访问。
* 从 EFOS 3.7.x.x 或更高版本开始，可以使用非 FIPS 兼容版本和 FIPS 兼容版本。从不符合 FIPS 的版本迁移到符合 FIPS 的版本时，需执行不同的步骤，反之亦然。将 EFOS 从不符合 FIPS 的版本更改为符合 FIPS 的版本，或者反之，则会将交换机重置为出厂默认值。此操作步骤需要通过串行控制台端口进行访问。


====
.步骤
. 使用`show FIPS status`命令检查您的EFOS版本是否符合FIPS或非FIPS。在以下示例中、`IP_switch_A_1`正在使用符合FIPS的EFOS、而`IP_switch_A_2`正在使用不符合FIPS的EFOS。
+
*示例1*

+
[listing]
----
IP_switch_A_1 #show fips status

System running in FIPS mode

IP_switch_A_1 #
----
+
*示例2*

+
[listing]
----
IP_switch_A_2 #show fips status
                     ^
% Invalid input detected at `^` marker.

IP_switch_A_2 #
----
. 使用下表确定必须遵循的方法：
+
|===


| * 操作步骤 * | * 当前 EFOS 版本 * | * 新 EFOS 版本 * | * 高级步骤 * 


 a| 
在两个（非） FIPS 兼容版本之间升级 EFOS 的步骤
 a| 
3.4.x.x
 a| 
3.4.x.x
 a| 
使用方法 1 安装新的 EFOS 映像）配置和许可证信息将保留



 a| 
3.4.4.6 （或更高版本 3.4.x.x ）
 a| 
不符合 FIPS 的 3.7.x.x 或更高版本
 a| 
使用方法 1 升级 EFOS 。将交换机重置为出厂默认设置，并对 EFOS 3.7.x.x 或更高版本应用 RCF 文件



.2+| 不符合 FIPS 的 3.7.x.x 或更高版本  a| 
3.4.4.6 （或更高版本 3.4.x.x ）
 a| 
使用方法 1 降级 EFOS 。将交换机重置为出厂默认设置，并对 EFOS 3.4.x.x 应用 RCF 文件



 a| 
不符合 FIPS 的 3.7.x.x 或更高版本
 a| 
使用方法 1 安装新的 EFOS 映像。配置和许可证信息会保留下来



 a| 
符合 3.7.x.x 或更高版本 FIPS
 a| 
符合 3.7.x.x 或更高版本 FIPS
 a| 
使用方法 1 安装新的 EFOS 映像。配置和许可证信息会保留下来



 a| 
升级到 / 从 FIPS 兼容 EFOS 版本的步骤
 a| 
不符合 FIPS
 a| 
符合 FIPS
 a| 
使用方法 2 安装 EFOS 映像。交换机配置和许可证信息将丢失。



 a| 
符合 FIPS
 a| 
不符合 FIPS

|===
+
** 方法 1 ： <<通过将软件映像下载到备份启动分区来升级 EFOS 的步骤>>
** 方法 2 ： <<使用 ONIE 操作系统安装升级 EFOS 的步骤>>






=== 通过将软件映像下载到备份启动分区来升级 EFOS 的步骤

只有当两个 EFOS 版本均不符合 FIPS 或两个 EFOS 版本均符合 FIPS 时，才能执行以下步骤。


NOTE: 如果一个版本符合 FIPS ，而另一个版本不符合 FIPS ，请勿使用这些步骤。

.步骤
. 将交换机软件复制到交换机： ` +copy sftp ： //user@50.50.50.50 switchsoftware/EFOS-3.4.6.stk backup+`
+
在此示例中， EFOS-3.4.6.stk 操作系统文件将从地址为 50.5 的 SFTP 服务器复制到备份分区。您需要使用 TFTP/SFTP 服务器的 IP 地址以及需要安装的 RCF 文件的文件名。

+
[listing]
----
(IP_switch_A_1) #copy sftp://user@50.50.50.50/switchsoftware/efos-3.4.4.6.stk backup
Remote Password:*************

Mode........................................... SFTP
Set Server IP.................................. 50.50.50.50
Path........................................... /switchsoftware/
Filename....................................... efos-3.4.4.6.stk
Data Type...................................... Code
Destination Filename........................... backup

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y

File transfer in progress. Management access will be blocked for the duration of the transfer. Please wait...
SFTP Code transfer starting...


File transfer operation completed successfully.

(IP_switch_A_1) #
----
. 将交换机设置为在下次重新启动交换机时从备份分区启动：
+
`启动系统备份`

+
[listing]
----
(IP_switch_A_1) #boot system backup
Activating image backup ..

(IP_switch_A_1) #
----
. 验证新启动映像是否将在下次启动时处于活动状态：
+
`s如何启动 var`

+
[listing]
----
(IP_switch_A_1) #show bootvar

Image Descriptions

 active :
 backup :


 Images currently available on Flash

 ----  -----------  --------  ---------------  ------------
 unit       active    backup   current-active   next-active
 ----  -----------  --------  ---------------  ------------

	1       3.4.4.2    3.4.4.6      3.4.4.2        3.4.4.6

(IP_switch_A_1) #
----
. 保存配置：
+
`写入内存`

+
[listing]
----
(IP_switch_A_1) #write memory

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y


Configuration Saved!

(IP_switch_A_1) #
----
. 重新启动交换机：
+
`re负载`

+
[listing]
----
(IP_switch_A_1) #reload

Are you sure you would like to reset the system? (y/n) y
----
. 等待交换机重新启动。
+

NOTE: 在极少数情况下，交换机可能无法启动。按照 <<使用 ONIE 操作系统安装升级 EFOS 的步骤>> 以安装新映像。

. 如果将交换机从 EFOS 3.4.x.x 更改为 EFOS 3.7.x.x 或反之，请按照以下两个过程应用正确的配置（ RCF ）：
+
.. <<将 Broadcom IP 交换机重置为出厂默认值>>
.. <<下载并安装 Broadcom RCF 文件>>


. 对 MetroCluster IP 配置中的其余三个 IP 交换机重复上述步骤。




=== 使用 ONIE 操作系统安装升级 EFOS 的步骤

如果一个 EFOS 版本符合 FIPS ，而另一个 EFOS 版本不符合 FIPS ，则可以执行以下步骤。如果交换机无法启动，可通过以下步骤从 ONIE 安装非 FIPS 或 FIPS 兼容 EFOS 3.7.x.x 映像。

.步骤
. 将交换机启动至 ONIE 安装模式。
+
在启动期间，如果出现以下屏幕，请选择 ONIE ：

+
[listing]
----
 +--------------------------------------------------------------------+
 |EFOS                                                                |
 |*ONIE                                                               |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 +--------------------------------------------------------------------+

----
+
选择 "ONIE" 后，交换机将加载并向您提供以下选项：

+
[listing]
----
 +--------------------------------------------------------------------+
 |*ONIE: Install OS                                                   |
 | ONIE: Rescue                                                       |
 | ONIE: Uninstall OS                                                 |
 | ONIE: Update ONIE                                                  |
 | ONIE: Embed ONIE                                                   |
 | DIAG: Diagnostic Mode                                              |
 | DIAG: Burn-In Mode                                                 |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 +--------------------------------------------------------------------+

----
+
此时，交换机将启动至 ONIE 安装模式。

. 停止 ONIE 发现并配置以太网接口
+
出现以下消息后，按 <ENTER> 以调用 ONIE 控制台：

+
[listing]
----
 Please press Enter to activate this console. Info: eth0:  Checking link... up.
 ONIE:/ #
----
+

NOTE: ONIE 发现将继续，并将消息打印到控制台。

+
[listing]
----
Stop the ONIE discovery
ONIE:/ # onie-discovery-stop
discover: installer mode detected.
Stopping: discover... done.
ONIE:/ #
----
. 配置以太网接口并使用 `ifconfig eth0 <ipAddress> netmask <netmask> up` 和 `route add default gw <gatewayAddress>` 添加路由
+
[listing]
----
ONIE:/ # ifconfig eth0 10.10.10.10 netmask 255.255.255.0 up
ONIE:/ # route add default gw 10.10.10.1
----
. 验证托管 ONIE 安装文件的服务器是否可访问：
+
[listing]
----
ONIE:/ # ping 50.50.50.50
PING 50.50.50.50 (50.50.50.50): 56 data bytes
64 bytes from 50.50.50.50: seq=0 ttl=255 time=0.429 ms
64 bytes from 50.50.50.50: seq=1 ttl=255 time=0.595 ms
64 bytes from 50.50.50.50: seq=2 ttl=255 time=0.369 ms
^C
--- 50.50.50.50 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.369/0.464/0.595 ms
ONIE:/ #
----
. 安装新的交换机软件
+
[listing]
----

ONIE:/ # onie-nos-install http:// 50.50.50.50/Software/onie-installer-x86_64
discover: installer mode detected.
Stopping: discover... done.
Info: Fetching http:// 50.50.50.50/Software/onie-installer-3.7.0.4 ...
Connecting to 50.50.50.50 (50.50.50.50:80)
installer            100% |*******************************| 48841k  0:00:00 ETA
ONIE: Executing installer: http:// 50.50.50.50/Software/onie-installer-3.7.0.4
Verifying image checksum ... OK.
Preparing image archive ... OK.
----
+
软件将安装并重新启动交换机。让交换机正常重新启动到新的 EFOS 版本。

. 验证是否已安装新的交换机软件
+
* `s如何 bootvar` *

+
[listing]
----

(Routing) #show bootvar
Image Descriptions
active :
backup :
Images currently available on Flash
---- 	----------- -------- --------------- ------------
unit 	active 	   backup   current-active  next-active
---- 	----------- -------- --------------- ------------
1 	3.7.0.4     3.7.0.4  3.7.0.4         3.7.0.4
(Routing) #
----
. 完成安装
+
交换机将在未应用任何配置的情况下重新启动，并重置为出厂默认值。按照以下两个文档所述，按照两个过程配置交换机基本设置并应用 RCF 文件：

+
.. 配置交换机基本设置。按照步骤 4 及更高版本进行操作： <<将 Broadcom IP 交换机重置为出厂默认值>>
.. 创建并应用 RCF 文件，如中所述 <<下载并安装 Broadcom RCF 文件>>






== 下载并安装 Broadcom RCF 文件

您必须将交换机 RCF 文件下载并安装到 MetroCluster IP 配置中的每个交换机。

.开始之前
此任务需要使用文件传输软件，例如 FTP ， TFTP ， SFTP 或 SCP ， 将文件复制到交换机。

.关于此任务
必须对 MetroCluster IP 配置中的每个 IP 交换机重复执行这些步骤。

有四个 RCF 文件， MetroCluster IP 配置中的四个交换机中的每个交换机一个。您必须为所使用的交换机型号使用正确的 RCF 文件。

|===


| 交换机 | RCF 文件 


 a| 
IP_switch_A_1
 a| 
v1.32_Switch-A1.txt



 a| 
IP_switch_A_2
 a| 
v1.32_Switch-A2.txt



 a| 
IP_switch_B_1
 a| 
v1.32_Switch-B1.txt



 a| 
IP_switch_B_2
 a| 
v1.32_Switch-B2.txt

|===

NOTE: EFOS 3.4.4.6 或更高版本 3.4.x.x 的 RCF 文件版本和 EFOS 版本 3.7.0.4 不同。您需要确保为交换机运行的 EFOS 版本创建了正确的 RCF 文件。

|===


| EFOS 版本 | RCF 文件版本 


| 3.4.x.x | v1.3x ， v1.4x 


| 3.7.x.x | v2.x 
|===
.步骤
. 为 MetroCluster IP 生成 Broadcom RCF 文件。
+
.. 下载 https://mysupport.netapp.com/site/tools/tool-eula/rcffilegenerator["适用于 MetroCluster IP 的 RcfFileGenerator"]
.. 使用适用于MetroCluster IP的RcfFileGenerator为您的配置生成RCF文件。
+

NOTE: 不支持在下载后修改RCF文件。



. 将 RCF 文件复制到交换机：
+
.. 将RCF文件复制到第一个交换机：`copy sftp：//user@ftp-server-IP-address/RcfFiles/switch-specific RCF/BES-53248_v1.32_Switch-A1.txt nvram：script BES-53248_v1.32_Switch-A1.SCR`
+
在此示例中，将 "BES-53248_v1.32_Switch-A1.txt" RCF 文件从位于 "50.050.50" 的 SFTP 服务器复制到本地 bootflash 。您需要使用 TFTP/SFTP 服务器的 IP 地址以及需要安装的 RCF 文件的文件名。

+
[listing]
----
(IP_switch_A_1) #copy sftp://user@50.50.50.50/RcfFiles/BES-53248_v1.32_Switch-A1.txt nvram:script BES-53248_v1.32_Switch-A1.scr

Remote Password:*************

Mode........................................... SFTP
Set Server IP.................................. 50.50.50.50
Path........................................... /RcfFiles/
Filename....................................... BES-53248_v1.32_Switch-A1.txt
Data Type...................................... Config Script
Destination Filename........................... BES-53248_v1.32_Switch-A1.scr

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y

File transfer in progress. Management access will be blocked for the duration of the transfer. Please wait...
File transfer operation completed successfully.


Validating configuration script...

config

set clibanner "***************************************************************************

* NetApp Reference Configuration File (RCF)

*

* Switch    : BES-53248


...
The downloaded RCF is validated. Some output is being logged here.
...


Configuration script validated.
File transfer operation completed successfully.

(IP_switch_A_1) #
----
.. 验证 RCF 文件是否已保存为脚本：
+
`s记录列表`

+
[listing]
----
(IP_switch_A_1) #script list

Configuration Script Name        Size(Bytes)  Date of Modification
-------------------------------  -----------  --------------------
BES-53248_v1.32_Switch-A1.scr             852   2019 01 29 18:41:25

1 configuration script(s) found.
2046 Kbytes free.
(IP_switch_A_1) #
----
.. 应用 RCF 脚本：
+
`s记录应用 BES-53248_v1.32_Switch-A1.SCR`

+
[listing]
----
(IP_switch_A_1) #script apply BES-53248_v1.32_Switch-A1.scr

Are you sure you want to apply the configuration script? (y/n) y


config

set clibanner "********************************************************************************

* NetApp Reference Configuration File (RCF)

*

* Switch    : BES-53248

...
The downloaded RCF is validated. Some output is being logged here.
...

Configuration script 'BES-53248_v1.32_Switch-A1.scr' applied.

(IP_switch_A_1) #
----
.. 保存配置：
+
`写入内存`

+
[listing]
----
(IP_switch_A_1) #write memory

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y


Configuration Saved!

(IP_switch_A_1) #
----
.. 重新启动交换机：
+
`re负载`

+
[listing]
----
(IP_switch_A_1) #reload

Are you sure you would like to reset the system? (y/n) y
----
.. 对其他三个交换机中的每一个交换机重复上述步骤，确保将匹配的 RCF 文件复制到相应的交换机。


. 重新加载交换机：
+
`re负载`

+
[listing]
----
IP_switch_A_1# reload
----
. 对 MetroCluster IP 配置中的其他三台交换机重复上述步骤。

