---
permalink: install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html 
sidebar: sidebar 
keywords: metrocluster, mediator, configure 
summary: 必须在 ONTAP 节点上配置 ONTAP 调解器服务，才能在 MetroCluster IP 配置中使用。 
---
= 从 MetroCluster IP 配置配置 ONTAP 调解器服务
:icons: font
:imagesdir: ../media/


[role="lead"]
必须在 ONTAP 节点上配置 ONTAP 调解器服务，才能在 MetroCluster IP 配置中使用。

* 开始之前 *

* ONTAP 调解器必须已成功安装在两个 MetroCluster 站点均可访问的网络位置上。
* 您必须具有运行 ONTAP 调解器服务的主机的 IP 地址。
* 您必须具有 ONTAP 调解器服务的用户名和密码。
* MetroCluster IP 配置的所有节点都必须联机。


* 关于此任务 *

* 默认情况下，此任务会启用自动计划外切换。
* 此任务可在 MetroCluster IP 配置中任何节点的 ONTAP 接口上执行。
* 一次安装 ONTAP 调解器服务时，最多可以配置五个 MetroCluster IP 配置。


* 操作步骤 *

. 使用以下命令将 ONTAP 调解器服务添加到 ONTAP ： MetroCluster configuration-settings mediator add -mediate-address IP-address-o-o-medier-host
+
注意：系统将提示您输入调解器管理员用户帐户的用户名和密码。

. 验证中的自动切换功能是否已启用： MetroCluster show
. 验证调解器当前是否正在运行。
+
.. 显示调解器虚拟磁盘： storage disk show -container-type mediator
+
....
cluster_A::> storage disk show -container-type mediator
                       Usable           Disk    Container   Container
Disk                   Size Shelf Bay Type    Type        Name      Owner
---------------- ---------- ----- --- ------- ----------- --------- --------
NET-1.5                   -     -   - VMDISK  mediator    -         node_A_2
NET-1.6                   -     -   - VMDISK  mediator    -         node_B_1
NET-1.7                   -     -   - VMDISK  mediator    -         node_B_2
NET-1.8                   -     -   - VMDISK  mediator    -         node_A_1
....
.. 将权限模式设置为高级：设置高级
+
....
cluster_A::> set advanced
....
.. 显示标记为调解器的启动程序： storage iscsi-initiator show -label mediator
+
....
cluster_A::*> storage iscsi-initiator show -label mediator
  (storage iscsi-initiator show)
 +                                                                     Status
Node Type Label    Target Portal      Target Name                      Admin/Op
---- ---- -------- ------------------ -------------------------------- --------
node_A_1
     mailbox
          mediator 1.1.1.1       iqn.2012-05.local:mailbox.target.6616cd3f-9ef1-11e9-aada-00a098ccf5d8:a05e1ffb-9ef1-11e9-8f68- 00a098cbca9e:1 up/up
node_A_2
     mailbox
          mediator 1.1.1.1       iqn.2012-05.local:mailbox.target.6616cd3f-9ef1-11e9-aada-00a098ccf5d8:a05e1ffb-9ef1-11e9-8f68-00a098cbca9e:1 up/up
....



