---
permalink: disaster-recovery/task_reassign_pool1_disastersite_mcip.html 
sidebar: sidebar 
keywords: metrocluster, disaster, site, replacement, controller, module, reassign, ownership 
summary: 如果在灾难站点上更换了控制器模块或 NVRAM 卡，则必须将属于根聚合的磁盘重新分配给更换用的控制器模块。 
---
= 为灾难站点上的池 1 磁盘重新分配磁盘所有权（ MetroCluster IP 配置）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果在灾难站点上更换了一个或两个控制器模块或 NVRAM 卡，则系统 ID 已更改，您必须将属于根聚合的磁盘重新分配给更换用的控制器模块。

.关于此任务
由于节点处于切换模式，因此在此任务中仅会重新分配包含灾难站点的 pool1 根聚合的磁盘。此时，它们是唯一仍归旧系统 ID 所有的磁盘。

此任务将在灾难站点的替代节点上执行。

此任务在维护模式下执行。

这些示例假设以下条件：

* 站点 A 是灾难站点。
* node_A_1 已更换。
* node_A_2 已更换。
* 站点 B 是正常运行的站点。
* node_B_1 运行状况良好。
* node_B_2 运行状况良好。


旧的和新的系统 ID 在中进行了标识 link:../disaster-recovery/task_replace_hardware_and_boot_new_controllers.html#determining-the-system-ids-of-the-replacement-controller-modules["确定替代控制器模块的新系统 ID"]。

此操作步骤中的示例使用具有以下系统 ID 的控制器：

|===


| 节点 | 原始系统 ID | 新系统 ID 


 a| 
node_A_1
 a| 
4068741258
 a| 
1574774970



 a| 
node_A_2
 a| 
4068741260
 a| 
1574774991



 a| 
node_B_1
 a| 
4068741254
 a| 
未更改



 a| 
node_B_2
 a| 
4068741256
 a| 
未更改

|===
.步骤
. 在替代节点处于维护模式的情况下，根据您的系统是否配置了 ADP 和 ONTAP 版本，使用正确的命令重新分配根聚合磁盘。
+
出现提示时，您可以继续重新分配。

+
|===


| 如果系统正在使用 ADP ... | 使用此命令重新分配磁盘 ... 


 a| 
是（ ONTAP 9.8 ）
 a| 
`dreassign -s old-system-ID -d new-system-ID -r dr-partner-system-ID`



 a| 
是（ ONTAP 9.7.x 及更早版本）
 a| 
`dreassign -s old-system-ID -d new-system-ID -p old-partner-system-ID`



 a| 
否
 a| 
`dreassign -s old-system-ID -d new-system-ID`

|===
+
以下示例显示了在非 ADP 系统上重新分配驱动器的情况：

+
[listing]
----
*> disk reassign -s 4068741256 -d 1574774970
Partner node must not be in Takeover mode during disk reassignment from maintenance mode.
Serious problems could result!!
Do not proceed with reassignment if the partner is in takeover mode. Abort reassignment (y/n)? n

After the node becomes operational, you must perform a takeover and giveback of the HA partner node to ensure disk reassignment is successful.
Do you want to continue (y/n)? y
Disk ownership will be updated on all disks previously belonging to Filer with sysid 537037643.
Do you want to continue (y/n)? y
disk reassign parameters: new_home_owner_id 537070473 , new_home_owner_name
Disk 0m.i0.3L14 will be reassigned.
Disk 0m.i0.1L6 will be reassigned.
Disk 0m.i0.1L8 will be reassigned.
Number of disks to be reassigned: 3
----
. 销毁邮箱磁盘的内容：
+
`m邮箱销毁本地`

+
出现提示时，您可以继续执行销毁操作。

+
以下示例显示了 mailbox destroy local 命令的输出：

+
[listing]
----
*> mailbox destroy local
Destroying mailboxes forces a node to create new empty mailboxes,
which clears any takeover state, removes all knowledge
of out-of-date plexes of mirrored volumes, and will prevent
management services from going online in 2-node cluster
HA configurations.
Are you sure you want to destroy the local mailboxes? y
...............Mailboxes destroyed.
*>
----
. 如果更换了磁盘，则会出现故障的本地丛，必须将其删除。
+
.. 显示聚合状态：
+
`聚合状态`

+
在以下示例中，丛 node_A_1_aggr0/plex0 出现故障。

+
[listing]
----
*> aggr status
Aug 18 15:00:07 [node_B_1:raid.vol.mirror.degraded:ALERT]: Aggregate node_A_1_aggr0 is
   mirrored and one plex has failed. It is no longer protected by mirroring.
Aug 18 15:00:07 [node_B_1:raid.debug:info]: Mirrored aggregate node_A_1_aggr0 has plex0
   clean(-1), online(0)
Aug 18 15:00:07 [node_B_1:raid.debug:info]: Mirrored aggregate node_A_1_aggr0 has plex2
   clean(0), online(1)
Aug 18 15:00:07 [node_B_1:raid.mirror.vote.noRecord1Plex:error]: WARNING: Only one plex
   in aggregate node_A_1_aggr0 is available. Aggregate might contain stale data.
Aug 18 15:00:07 [node_B_1:raid.debug:info]: volobj_mark_sb_recovery_aggrs: tree:
   node_A_1_aggr0 vol_state:1 mcc_dr_opstate: unknown
Aug 18 15:00:07 [node_B_1:raid.fsm.commitStateTransit:debug]: /node_A_1_aggr0 (VOL):
   raid state change UNINITD -> NORMAL
Aug 18 15:00:07 [node_B_1:raid.fsm.commitStateTransit:debug]: /node_A_1_aggr0 (MIRROR):
   raid state change UNINITD -> DEGRADED
Aug 18 15:00:07 [node_B_1:raid.fsm.commitStateTransit:debug]: /node_A_1_aggr0/plex0
   (PLEX): raid state change UNINITD -> FAILED
Aug 18 15:00:07 [node_B_1:raid.fsm.commitStateTransit:debug]: /node_A_1_aggr0/plex2
   (PLEX): raid state change UNINITD -> NORMAL
Aug 18 15:00:07 [node_B_1:raid.fsm.commitStateTransit:debug]: /node_A_1_aggr0/plex2/rg0
   (GROUP): raid state change UNINITD -> NORMAL
Aug 18 15:00:07 [node_B_1:raid.debug:info]: Topology updated for aggregate node_A_1_aggr0
   to plex plex2
*>
----
.. 删除故障丛：
+
`aggr destroy plex-id`

+
[listing]
----
*> aggr destroy node_A_1_aggr0/plex0
----


. 暂停节点以显示 LOADER 提示符：
+
`halt`

. 在灾难站点的另一个节点上重复上述步骤。

