---
permalink: disaster-recovery/task_reassign_roots_mcfc.html 
sidebar: sidebar 
keywords: reassign, ownership, nvram, system, id, replaced 
summary: 如果在灾难站点上更换了一个或两个控制器模块或 NVRAM 卡，则必须将属于根聚合的磁盘重新分配给更换用的控制器模块。 
---
= 将根聚合的磁盘所有权重新分配给更换用的控制器模块（ MetroCluster FC 配置）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果在灾难站点上更换了一个或两个控制器模块或 NVRAM 卡，则系统 ID 已更改，您必须将属于根聚合的磁盘重新分配给更换用的控制器模块。

.关于此任务
由于节点处于切换模式且已完成修复，因此，本节仅会重新分配包含灾难站点的 pool1 根聚合的磁盘。此时，它们是唯一仍归旧系统 ID 所有的磁盘。

本节提供了双节点和四节点配置的示例。对于双节点配置，您可以忽略对每个站点上第二个节点的引用。对于八节点配置，您必须考虑第二个 DR 组上的其他节点。这些示例假设以下条件：

* 站点 A 是灾难站点。
+
** node_A_1 已更换。
** node_A_2 已更换。
+
仅存在于四节点 MetroCluster 配置中。



* 站点 B 是正常运行的站点。
+
** node_B_1 运行状况良好。
** node_B_2 运行状况良好。
+
仅存在于四节点 MetroCluster 配置中。





旧的和新的系统ID在中进行了标识 link:task_replace_hardware_and_boot_new_controllers.html["更换硬件并启动新控制器"]。

此操作步骤中的示例使用具有以下系统 ID 的控制器：

|===


| 节点数 | 节点 | 原始系统 ID | 新系统 ID 


.4+| 四个  a| 
node_A_1
 a| 
4068741258
 a| 
1574774970



 a| 
node_A_2
 a| 
4068741260
 a| 
1574774991



 a| 
node_B_1
 a| 
4068741254
 a| 
未更改



 a| 
node_B_2
 a| 
4068741256
 a| 
未更改



 a| 
两个
 a| 
node_A_1
 a| 
4068741258
 a| 
1574774970

|===
.步骤
. 在替代节点处于维护模式的情况下，重新分配根聚合磁盘：
+
`dreassign -s old-system-ID -d new-system-ID`

+
[listing]
----
*> disk reassign -s 4068741258 -d 1574774970
----
. 查看磁盘以确认灾难站点的 pool1 根聚合磁盘的所有权已更改为替代节点：
+
`d展示`

+
输出可能会显示更多或更少的磁盘，具体取决于根聚合中的磁盘数量以及这些磁盘中是否有任何磁盘发生故障并已更换。如果更换了磁盘，则 Pool0 磁盘将不会显示在输出中。

+
现在，应将灾难站点的 pool1 根聚合磁盘分配给替代节点。

+
[listing]
----
*> disk show
Local System ID: 1574774970

  DISK             OWNER                POOL   SERIAL NUMBER   HOME                DR HOME
------------       -------------        -----  -------------   -------------       -------------
sw_A_1:6.126L19    node_A_1(1574774970) Pool0  serial-number   node_A_1(1574774970)
sw_A_1:6.126L3     node_A_1(1574774970) Pool0  serial-number   node_A_1(1574774970)
sw_A_1:6.126L7     node_A_1(1574774970) Pool0  serial-number   node_A_1(1574774970)
sw_B_1:6.126L8     node_A_1(1574774970) Pool1  serial-number   node_A_1(1574774970)
sw_B_1:6.126L24    node_A_1(1574774970) Pool1  serial-number   node_A_1(1574774970)
sw_B_1:6.126L2     node_A_1(1574774970) Pool1  serial-number   node_A_1(1574774970)

*> aggr status
         Aggr State           Status
 node_A_1_root online          raid_dp, aggr
                               mirror degraded
                               64-bit
*>
----
. 查看聚合状态：
+
`聚合状态`

+
输出可能会显示更多或更少的磁盘，具体取决于根聚合中的磁盘数量以及这些磁盘中是否有任何磁盘发生故障并已更换。如果更换了磁盘，则 Pool0 磁盘将不会显示在输出中。

+
[listing]
----
*> aggr status
          Aggr State           Status
  node_A_1_root online          raid_dp, aggr
                                mirror degraded
                                64-bit
*>
----
. 删除邮箱磁盘的内容：
+
`m邮箱销毁本地`

. 如果聚合未联机，请将其联机：
+
`aggr online aggr_name`

. 暂停节点以显示 LOADER 提示符：
+
`halt`


