---
permalink: disaster-recovery/task_config_switches_mcip.html 
sidebar: sidebar 
keywords: metrocluster, ip, configuration, switchback, operation 
summary: 您必须配置已更换的任何 IP 交换机。 
---
= 配置 IP 交换机（ MetroCluster IP 配置）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须配置已更换的任何 IP 交换机。

.关于此任务
此任务仅限适用场景 MetroCluster IP 配置。

必须在两台交换机上执行此操作。在配置第一台交换机后，验证运行正常的站点上的存储访问是否不受影响。


NOTE: 如果正常运行的站点上的存储访问受到影响，则不能继续使用第二个交换机。

.步骤
. 请参见 link:../install-ip/concept_considerations_differences.html["MetroCluster IP 安装和配置：： ONTAP MetroCluster 配置之间的差异"] 有关为替代交换机布线和配置交换机的过程。
+
您可以使用以下各节中的过程：

+
** 为 IP 交换机布线
** 配置 IP 交换机


. 如果在正常运行的站点上禁用了 ISL ，请启用这些 ISL 并验证这些 ISL 是否联机。
+
.. 在第一台交换机上启用 ISL 接口：
+
`无关闭`

+
以下示例显示了适用于 Broadcom IP 交换机或 Cisco IP 交换机的命令。

+
|===


| 交换机供应商 | 命令 


 a| 
Broadcom
 a| 
[listing]
----
(IP_Switch_A_1)> enable
(IP_switch_A_1)# configure
(IP_switch_A_1)(Config)# interface 0/13-0/16
(IP_switch_A_1)(Interface 0/13-0/16 )# no shutdown
(IP_switch_A_1)(Interface 0/13-0/16 )# exit
(IP_switch_A_1)(Config)# exit
----


 a| 
Cisco
 a| 
[listing]
----
IP_switch_A_1# conf t
IP_switch_A_1(config)# int eth1/15-eth1/20
IP_switch_A_1(config)# no shutdown
IP_switch_A_1(config)# copy running startup
IP_switch_A_1(config)# show interface brief
----
|===
.. 在配对交换机上启用 ISL 接口：
+
`无关闭`

+
以下示例显示了适用于 Broadcom IP 交换机或 Cisco IP 交换机的命令。

+
|===


| 交换机供应商 | 命令 


 a| 
Broadcom
 a| 
[listing]
----
(IP_Switch_A_2)> enable
(IP_switch_A_2)# configure
(IP_switch_A_2)(Config)# interface 0/13-0/16
(IP_switch_A_2)(Interface 0/13-0/16 )# no shutdown
(IP_switch_A_2)(Interface 0/13-0/16 )# exit
(IP_switch_A_2)(Config)# exit
----


 a| 
Cisco
 a| 
[listing]
----
IP_switch_A_2# conf t
IP_switch_A_2(config)# int eth1/15-eth1/20
IP_switch_A_2(config)# no shutdown
IP_switch_A_2(config)# copy running startup
IP_switch_A_2(config)# show interface brief
----
|===
.. 验证接口是否已启用：
+
`s如何使用接口简介`

+
以下示例显示了 Cisco 交换机的输出。

+
[listing]
----
IP_switch_A_2(config)# show interface brief

--------------------------------------------------------
Port VRF Status IP Address Speed MTU
--------------------------------------------------------
mt0 -- up 10.10.99.10 100 1500
--------------------------------------------------------
Ethernet    VLAN Type Mode    Status Reason Speed   Port
Interface                                           Ch
#
--------------------------------------------------------
.
.
.
Eth1/15    10   eth   access  up     none   40G(D)  --
Eth1/16    10   eth   access  up     none   40G(D)  --
Eth1/17    10   eth   access  down   none   auto(D) --
Eth1/18    10   eth   access  down   none   auto(D) --
Eth1/19    10   eth   access  down   none   auto(D) --
Eth1/20    10   eth   access  down   none   auto(D) --
.
.
.
IP_switch_A_2#
----



