---
permalink: disaster-recovery/task_boot_new_mcfc.html 
sidebar: sidebar 
keywords: boot, controller, modules, fc 
summary: 数据聚合和根聚合的聚合修复完成后，您必须启动灾难站点上的一个或多个节点。 
---
= 启动新控制器模块（ MetroCluster FC 配置）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
数据聚合和根聚合的聚合修复完成后，您必须启动灾难站点上的一个或多个节点。

此任务从显示 LOADER 提示符的节点开始。

.步骤
. 显示启动菜单：
+
`boot_ontap 菜单`

. 在启动菜单中，选择选项 6 * 从备份配置更新闪存 * 。
. 对以下提示回答 `y` ：
+
`此操作将使用上次备份到磁盘来替换所有基于闪存的配置。确实要继续？： y`

+
系统将启动两次，第二次加载新配置。

+

NOTE: 如果未清除已用替代控制器的 NVRAM 内容，则可能会出现崩溃，并显示以下消息： `panic ： NVRAM contents are invalid...` 如果发生这种情况，请重复 <<step2>> 将系统启动至 ONTAP 提示符。然后、您需要 <<Reset-the-boot-recovery,重置启动恢复和rdb_Corrupt bootargs>>

. 在丛 0 上镜像根聚合：
+
.. 将三个 pool0 磁盘分配给新控制器模块。
.. 镜像根聚合 pool1 丛：
+
`aggr mirror root-aggr-name`

.. 将无主磁盘分配给本地节点上的 pool0


. 如果您使用的是四节点配置，请在灾难站点的另一个节点上重复上述步骤。
. 刷新 MetroCluster 配置：
+
.. 进入高级权限模式：
+
`set -privilege advanced`

.. 刷新配置：
+
`MetroCluster configure -refresh true`

.. 返回到管理权限模式：
+
`set -privilege admin`



. 确认灾难站点上的替代节点已做好切回准备：
+
`MetroCluster node show`

+
替代节点应处于 "`Waiting for switchback recovery` " 模式。如果它们处于 "`normal` " 模式，则可以重新启动替代节点。启动后，节点应处于 "`Waiting for switchback recovery` " 模式。

+
以下示例显示替代节点已做好切回准备：

+
....

cluster_B::> metrocluster node show
DR                    Configuration  DR
Grp Cluster Node      State          Mirroring Mode
--- ------- --------- -------------- --------- --------------------
1   cluster_B
            node_B_1  configured     enabled   switchover completed
            node_B_2  configured     enabled   switchover completed
    cluster_A
            node_A_1  configured     enabled   waiting for switchback recovery
            node_A_2  configured     enabled   waiting for switchback recovery
4 entries were displayed.

cluster_B::>
....


继续执行 link:../disaster-recovery/task_complete_recovery.html["完成灾难恢复过程"]。



=== 重置boot_recovery和rdb_Corrupt bootargs

[role="lead"]
如果需要、您可以重置boot_recovery和rdb_Corrupt_bootargs

.步骤
. 将节点暂停回LOADER提示符：
+
[listing]
----
node_A_1::*> halt -node _node-name_
----
. 检查是否已设置以下bootarg：
+
[listing]
----
LOADER> printenv bootarg.init.boot_recovery
LOADER> printenv bootarg.rdb_corrupt
----
. 如果已将任一bootarg设置为值、请取消设置并启动ONTAP ：
+
[listing]
----
LOADER> unsetenv bootarg.init.boot_recovery
LOADER> unsetenv bootarg.rdb_corrupt
LOADER> saveenv
LOADER> bye
----

