---
settings:
  name: ONTAP MetroCluster
  harmony_integration: maestro
  platform: ''
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-cn,us-en,ja-jp,ko-kr,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: MetroCluster 文档
    url: "/index.html"
  - section: releasenotes
  - section: install-fc
  - section: install-ip
  - section: install-stretch
  - section: tiebreaker
  - title: 了解 MetroCluster 数据保护和灾难恢复
    entries:
    - title: MetroCluster 如何保护数据并提供灾难恢复
      url: "/manage/concept_understanding_mcc_data_protection_and_disaster_recovery.html"
  - section: manage
  - section: maintain
  - section: transition
  - section: upgrade
  - section: disaster-recovery
  - title: 法律声明
    url: "/legal-notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
