---
permalink: transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html 
sidebar: sidebar 
keywords: nondisruptive, transition, fc, ip 
summary: 从ONTAP 9.13.1开始、您可以将工作负载和数据从现有八节点MetroCluster FC配置无中断过渡到新的MetroCluster IP配置。 
---
= 无中断地从 MetroCluster FC 过渡到 MetroCluster IP 配置（ ONTAP 9.8 及更高版本）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以将工作负载和数据从现有MetroCluster FC配置无中断过渡到新的MetroCluster IP配置。

从ONTAP 9.13.1开始、MetroCluster IP配置支持此操作步骤、其中MetroCluster和驱动器架连接到相同的IP交换机(共享存储交换机配置)。

从ONTAP 9.13.1开始、您可以将工作负载和数据从现有八节点MetroCluster FC配置无中断过渡到新的MetroCluster IP配置。

从ONTAP 9.8开始、您可以将工作负载和数据从现有四节点MetroCluster FC配置无中断过渡到新的MetroCluster IP配置。

* 此操作步骤无中断。
+
在此操作期间， MetroCluster 配置可以继续提供数据。

* 此操作步骤 仅适用于四节点和八节点MetroCluster FC配置。
+
如果您使用的是双节点 MetroCluster FC 配置，请参见 link:concept_choosing_your_transition_procedure_mcc_transition.html["选择过渡操作步骤"]。

* 本操作步骤 介绍了过渡一个四节点FC DR组所需的步骤。如果您使用的是八节点配置(两个FC DR组)、则必须对每个FC DR组重复整个操作步骤。
* 您必须满足所有要求并按照操作步骤中的所有步骤进行操作。




== 启用控制台日志记录

NetApp强烈建议您在使用的设备上启用控制台日志记录、并在执行此过程时执行以下操作：

* 在维护期间保持AutoSupport处于启用状态。
* 在维护前后触发维护AutoSupport消息、以便在维护活动期间禁用案例创建。
+
请参阅知识库文章 link:https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92["如何在计划的维护时段禁止自动创建案例"^]。

* 为任何命令行界面会话启用会话日志记录。有关如何启用会话日志记录的说明，请查看知识库文章中的“日志记录会话输出”部分 link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["如何配置PuTTY以优化与ONTAP系统的连接"^]。

