---
permalink: transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html 
sidebar: sidebar 
keywords: nondisruptive, transition, fc, ip 
summary: 从ONTAP 9.13.1开始、您可以将工作负载和数据从现有八节点MetroCluster FC配置无中断过渡到新的MetroCluster IP配置。 
---
= 无中断地从 MetroCluster FC 过渡到 MetroCluster IP 配置（ ONTAP 9.8 及更高版本）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以将工作负载和数据从现有MetroCluster FC配置无中断过渡到新的MetroCluster IP配置。

从ONTAP 9.13.1开始、MetroCluster IP配置支持此操作步骤、其中MetroCluster和驱动器架连接到相同的IP交换机(共享存储交换机配置)。

从ONTAP 9.13.1 开始，您可以将工作负载和数据从现有的八节点MetroCluster FC 配置无中断地迁移到新的八节点MetroCluster IP 配置。您可以使用此过程转换一个四节点 FC DR 组，删除空的 FC DR 组，然后对第二个 FC DR 组重复此过程。 

从ONTAP 9.8 开始，您可以将工作负载和数据从现有的四节点MetroCluster FC 配置无中断地迁移到新的四节点MetroCluster IP 配置。完成过渡后，如果需要，您可以扩展到八节点MetroCluster IP 配置。看link:../upgrade/task_expand_a_four_node_mcc_ip_configuration.html["扩展MetroCluster IP配置"]。

* 此操作步骤无中断。
+
在此操作期间， MetroCluster 配置可以继续提供数据。

* 此操作步骤 仅适用于四节点和八节点MetroCluster FC配置。
+
如果您使用的是双节点 MetroCluster FC 配置，请参见 link:concept_choosing_your_transition_procedure_mcc_transition.html["选择过渡操作步骤"]。

* 本操作步骤 介绍了过渡一个四节点FC DR组所需的步骤。如果您使用的是八节点配置(两个FC DR组)、则必须对每个FC DR组重复整个操作步骤。
+

NOTE: 当您按照此流程添加或删除 DR 组时，必须先验证 DR 组的添加或删除是否成功，然后再添加或删除另一个 DR 组。

* 您必须满足所有要求并按照操作步骤中的所有步骤进行操作。


.如果您要添加较旧的平台模型，则需要注意以下重要信息
以下指导针对一种不常见的情况，即您需要将较旧的平台模型（ ONTAP 9.15.1 之前发布的平台）添加到包含较新平台模型（ ONTAP 9.15.1 或更高版本中发布的平台）的现有MetroCluster配置中。对于八节点 FC 到 IP 的过渡，如果您已将第一个 FC DR 组过渡到ONTAP 9.15.1 或更高版本中引入的平台模型，并计划将第二个 DR 组过渡到ONTAP 9.15.1 之前引入的平台，则本指南适用。

如果您现有的MetroCluster配置包含使用 *共享集群/HA 端口* 的平台（ ONTAP 9.15.1 或更高版本中发布的平台），则如果不将配置中的所有节点升级到ONTAP 9.15.1P11 或ONTAP 9.16.1P4 或更高版本，则无法添加使用 *共享MetroCluster/HA 端口* 的平台（ ONTAP 9.15.1 之前发布的平台）。

[CAUTION]
====
将使用 *共享/ MetroCluster HA 端口* 的旧平台模型添加到包含使用 *共享集群/HA 端口* 的新平台模型的MetroCluster是一种不常见的情况，大多数组合不会受到影响。

====
使用下表来验证您的组合是否受到影响。如果第一列列出了您现有的平台，而第二列列出了要添加到配置中的平台，则配置中的所有节点都必须运行ONTAP 9.15.1P11 或ONTAP 9.16.1P4 或更高版本才能添加新的 DR 组。

[cols="20,20,20,20,20"]
|===
2+| 如果您现有的 MetroCluster 包含... 2+| 您要添加的平台是... | 那么 ... 


 a| 
使用*共享集群/HA 端口*的 AFF 系统：

* AFF A20
* AFF A30
* AFF C30
* AFF A50
* AFF C60
* AFF C80
* AFF A70
* AFF A90
* AFF A1K

 a| 
使用*共享集群/HA 端口*的 FAS 系统：

* FAS50
* FAS70
* FAS90

 a| 
使用*共享 MetroCluster/HA 端口*的 AFF 系统：

* AFF A150、ASA A150
* AFF A220
* AFF C250、ASA C250
* AFF A250、ASA A250
* AFF A300
* AFF A320
* AFF C400、ASA C400
* AFF A400、ASA A400
* AFF A700
* AFF C800、ASA C800
* AFF A800、ASA A800
* AFF A900、ASA A900

 a| 
使用*共享 MetroCluster/HA 端口*的 FAS 系统：

* FAS2750
* FAS500f
* FAS8200
* FAS8300
* FAS8700
* FAS9000
* FAS9500

| 在将新平台添加到现有 MetroCluster 配置之前，请将现有配置和新配置中的所有节点升级到 ONTAP 9.15.1P11 或 ONTAP 9.16.1P4 或更高版本。 
|===