---
permalink: transition/task_apply_rcfs.html 
sidebar: sidebar 
keywords: Generating and applying RCFs to the new IP switches, review, requirement, preparing, prepare, transition, perform, procedure, order, completing, complete, step, task, moving, move, controller, storage, shelves, shelf, exist, configuration, direct, metrocluster, fc, ip, verify, health, removing, remove, tiebreaker, monitor, software, generating, generate, apply, rcf, switch, controller, configure, prepare, preparing 
summary: 如果要在 MetroCluster IP 配置中使用新的 IP 交换机，则必须使用自定义 RCF 文件配置这些交换机。 
---
= 生成 RCF 并将其应用于新的 IP 交换机
:icons: font
:imagesdir: ../media/


[role="lead"]
如果要在 MetroCluster IP 配置中使用新的 IP 交换机，则必须使用自定义 RCF 文件配置这些交换机。

如果使用的是新交换机，则需要执行此任务。

如果您使用的是现有交换机，请继续执行 xref:task_transition_from_mcc_fc_to_mcc_ip_configurations.adoc[移动本地集群连接]。

. 安装新 IP 交换机并将其装入机架。
. 准备 IP 交换机以应用新的 RCF 文件。
+
按照中适用于您的交换机供应商的一节中的步骤进行操作 link:../install-ip/index.html["《 MetroCluster IP 安装和配置指南》"]

+
** link:../install-ip/task_install_and_cable_the_mcc_components.html#resetting-the-broadcom-ip-switch-to-factory-defaults["将 Broadcom IP 交换机重置为出厂默认值"]
** link:../install-ip/task_install_and_cable_the_mcc_components.html#resetting-the-cisco-ip-switch-to-factory-defaults["将 Cisco IP 交换机重置为出厂默认值"]


. 如有必要，将交换机上的固件更新为支持的版本。
. 使用 RCF 生成器工具根据交换机供应商和平台型号创建 RCF 文件，然后使用该文件更新交换机。
+
按照 _IP MetroCluster 安装和配置指南 _ 中适用于您的交换机供应商一节中的步骤进行操作。

+
link:../install-ip/index.html["MetroCluster IP 安装和配置"]

+
** link:../install-ip/task_install_and_cable_the_mcc_components.html#downloading-and-installing-the-broadcom-rcf-files["下载并安装 Broadcom IP RCF 文件"]
** link:../install-ip/task_install_and_cable_the_mcc_components.html#downloading-and-installing-the-cisco-ip-rcf-files["下载并安装 Cisco IP RCF 文件"]



