---
permalink: transition/task_move_cluster_connections.html 
sidebar: sidebar 
keywords: transition, cluster connections 
summary: 在查看所有要求并为过渡做准备之后，您可以执行过渡操作步骤。您必须按顺序执行每个任务，完成每个任务中的所有步骤，然后再转到下一个任务。在发出指示之前，不应将新控制器或存储架连接到现有配置。 
---
= 移动本地集群连接
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须将 MetroCluster FC 配置的集群接口移至 IP 交换机。



== 移动 MetroCluster FC 节点上的集群连接

[role="lead"]
您必须将 MetroCluster FC 节点上的集群连接移动到 IP 交换机。这些步骤取决于您使用的是现有 IP 交换机还是新的 IP 交换机。

您必须在两个 MetroCluster 站点上执行此任务。



=== 要移动哪些连接

以下任务假定控制器模块使用两个端口进行集群连接。某些控制器模块型号使用四个或更多端口进行集群连接。在这种情况下，在本示例中，端口划分为两个组，在这两个组之间交替使用端口

下表显示了此任务中使用的示例端口。

|===


| 控制器模块上的集群连接数 | 组 A 端口 | 组 B 端口 


 a| 
两个
 a| 
e0a
 a| 
e0b



 a| 
四个
 a| 
e0a ， e0c
 a| 
e0b ， e0d

|===
* 组 A 端口连接到本地交换机 switch_x_1-IP 。
* 组 B 端口连接到本地交换机 switch_x_2-IP 。


下表显示了 FC 节点连接到的交换机端口。对于 Broadcom BES-53248 交换机，端口使用情况取决于 MetroCluster IP 节点的型号。

|===


| 交换机型号 | MetroCluster IP 节点型号 | 交换机端口 | 连接到 


.2+| Cisco 3132Q-V、3232C或9336C-x2 .2+| 任意  a| 
5.
 a| 
FC节点上的本地集群接口



 a| 
6.
 a| 
FC节点上的本地集群接口



.6+| Broadcom BES-53248  a| 
FAS500f/A250
 a| 
1 - 6
 a| 
FC节点上的本地集群接口



 a| 
FAS8200/A300
 a| 
3、4、9、10、11、 12
 a| 
FC节点上的本地集群接口



 a| 
FAS8300/A400/FAS8700
 a| 
1 - 6
 a| 
FC节点上的本地集群接口

|===


=== 使用新 IP 交换机时移动本地集群连接

如果您使用的是新的 IP 交换机，则必须将现有 MetroCluster FC 节点的集群连接物理移至新交换机。

. 将 MetroCluster FC 节点组 A 集群连接移动到新的 IP 交换机。
+
使用中所述的端口 <<要移动哪些连接>>。

+
.. 断开所有组 A 端口与交换机的连接，或者，如果 MetroCluster FC 配置为无交换机集群，则断开它们与配对节点的连接。
.. 断开组 A 端口与 node_A_1-FC 和 node_A_2-FC 的连接。
.. 将 node_A_1-FC 的组 A 端口连接到 switch_A_1-IP 上 FC 节点的交换机端口
.. 将 node_A_2-FC 的组 A 端口连接到 switch_A_1-IP 上 FC 节点的交换机端口


. 验证所有集群端口是否均已启动：
+
`network port show -ipspace cluster`

+
....
cluster_A::*> network port show -ipspace Cluster

Node: node_A_1-FC

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

Node: node_A_2-FC

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

4 entries were displayed.

cluster_A::*>
....
. 验证站点间交换机间链路(ISL)是否已启动且端口通道是否正常运行：
+
`s如何使用接口简介`

+
在以下示例中、对于远程站点链路、ISL端口"Eth1/15"到"Eth1/20"配置为"Po10"、而对于本地集群ISL、"Eth1/7"到"Eth1/8"的配置为"PO1"。"Eth1/15"到"Eth1/20"、"Eth1/7"到"Eth1/8"、"Po10"和"PO1"的状态应为"up"。

+
[listing]
----
IP_switch_A_1# show interface brief

--------------------------------------------------------------
Port   VRF          Status   IP Address        Speed      MTU
--------------------------------------------------------------
mgmt0  --            up        100.10.200.20    1000      1500
--------------------------------------------------------------------------------
Ethernet     VLAN   Type Mode    Status     Reason              Speed    Port
Interface                                    Ch #
--------------------------------------------------------------------------------

...

Eth1/7        1     eth  trunk    up        none                100G(D)    1
Eth1/8        1     eth  trunk    up        none                100G(D)    1

...

Eth1/15       1     eth  trunk    up        none                100G(D)    10
Eth1/16       1     eth  trunk    up        none                100G(D)    10
Eth1/17       1     eth  trunk    up        none                100G(D)    10
Eth1/18       1     eth  trunk    up        none                100G(D)    10
Eth1/19       1     eth  trunk    up        none                100G(D)    10
Eth1/20       1     eth  trunk    up        none                100G(D)    10

--------------------------------------------------------------------------------
Port-channel VLAN  Type Mode   Status   Reason         Speed    Protocol
Interface
--------------------------------------------------------------------------------
Po1          1     eth  trunk   up      none            a-100G(D) lacp
Po10         1     eth  trunk   up      none            a-100G(D) lacp
Po11         1     eth  trunk   down    No operational  auto(D)   lacp
                                        members
IP_switch_A_1#
----
. 验证所有接口在 "`is Home` " 列中是否均显示 true ：
+
`network interface show -vserver cluster`

+
完成此操作可能需要几分钟时间。

+
....
cluster_A::*> network interface show -vserver cluster

            Logical      Status     Network          Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node_A_1_FC_clus1
                       up/up      169.254.209.69/16  node_A_1_FC   e0a     true
            node_A_1-FC_clus2
                       up/up      169.254.49.125/16  node_A_1-FC   e0b     true
            node_A_2-FC_clus1
                       up/up      169.254.47.194/16  node_A_2-FC   e0a     true
            node_A_2-FC_clus2
                       up/up      169.254.19.183/16  node_A_2-FC   e0b     true

4 entries were displayed.

cluster_A::*>
....
. 在两个节点（ node_A_1-FC 和 node_A_2-FC ）上执行上述步骤，以移动集群接口的组 B 端口。
. 对配对集群 "`cluster_B` " 重复上述步骤。




=== 重复使用现有 IP 交换机时移动本地集群连接

如果要重复使用现有 IP 交换机，则必须更新固件，使用正确的参考配置文件（ Reference Configure Files ， RCF ）重新配置交换机，并将连接移动到正确的端口，一次一个交换机。

只有当 FC 节点已连接到现有 IP 交换机且您要重复使用这些交换机时，才需要执行此任务。

. 断开连接到 switch_A_1_IP 的本地集群连接
+
.. 断开组 A 端口与现有 IP 交换机的连接。
.. 断开 switch_A_1_IP 上的 ISL 端口。
+
您可以查看平台的安装和设置说明，以查看集群端口使用情况。

+
https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-a320-install-setup/home.html["AFF A320 系统：安装和设置"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2842666["《 AFF A220/FAS2700 系统安装和设置说明》"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2842668["《 AFF A800 系统安装和设置说明》"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2469722["《 AFF A300 系统安装和设置说明》"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2316769["《 FAS8200 系统安装和设置说明》"^]



. 使用为您的平台组合和过渡生成的 RCF 文件重新配置 switch_A_1_IP 。
+
按照 _MetroCluster IP 安装和配置 _ 中适用于您的交换机供应商的操作步骤中的步骤进行操作：

+
link:../install-ip/concept_considerations_differences.html["MetroCluster IP 安装和配置"]

+
.. 如果需要，请下载并安装新的交换机固件。
+
您应使用 MetroCluster IP 节点支持的最新固件。

+
*** link:../install-ip/task_switch_config_broadcom.html["下载并安装 Broadcom 交换机 EFOS 软件"]
*** link:../install-ip/task_switch_config_cisco.html["下载并安装 Cisco 交换机 NX-OS 软件"]


.. 准备 IP 交换机以应用新的 RCF 文件。
+
*** link:../install-ip/task_switch_config_broadcom.html["将 Broadcom IP 交换机重置为出厂默认值"] *
*** link:https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_switch_config_broadcom.html["将 Cisco IP 交换机重置为出厂默认值"]


.. 根据交换机供应商的不同，下载并安装 IP RCF 文件。
+
*** link:../install-ip/task_switch_config_broadcom.html["下载并安装 Broadcom IP RCF 文件"]
*** link:../install-ip/task_switch_config_cisco.html["下载并安装 Cisco IP RCF 文件"]




. 将组 A 的端口重新连接到 switch_A_1_IP 。
+
使用中所述的端口 <<要移动哪些连接>>。

. 验证所有集群端口是否均已启动：
+
`network port show -ipspace cluster`

+
....
Cluster-A::*> network port show -ipspace cluster

Node: node_A_1_FC

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

Node: node_A_2_FC

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

4 entries were displayed.

Cluster-A::*>
....
. 验证所有接口是否均位于其主端口上：
+
`network interface show -vserver cluster`

+
....
Cluster-A::*> network interface show -vserver Cluster

            Logical      Status     Network          Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node_A_1_FC_clus1
                       up/up      169.254.209.69/16  node_A_1_FC   e0a     true
            node_A_1_FC_clus2
                       up/up      169.254.49.125/16  node_A_1_FC   e0b     true
            node_A_2_FC_clus1
                       up/up      169.254.47.194/16  node_A_2_FC   e0a     true
            node_A_2_FC_clus2
                       up/up      169.254.19.183/16  node_A_2_FC   e0b     true

4 entries were displayed.

Cluster-A::*>
....
. 对 switch_A_2_IP 重复上述所有步骤。
. 重新连接本地集群 ISL 端口。
. 在 site_B 上对交换机 B_1_IP 和交换机 B_2_IP 重复上述步骤。
. 在站点之间连接远程 ISL 。




== 验证集群连接是否已移动且集群运行状况良好

要确保连接正确且配置已准备好继续过渡过程，您必须验证集群连接是否已正确移动，集群交换机是否已识别且集群运行状况良好。

. 验证所有集群端口是否均已启动且正在运行：
+
`network port show -ipspace cluster`

+
....
Cluster-A::*> network port show -ipspace Cluster

Node: Node-A-1-FC

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

Node: Node-A-2-FC

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

4 entries were displayed.

Cluster-A::*>
....
. 验证所有接口是否均位于其主端口上：
+
`network interface show -vserver cluster`

+
完成此操作可能需要几分钟时间。

+
以下示例显示所有接口在 "`is Home` " 列中均显示 true 。

+
....
Cluster-A::*> network interface show -vserver Cluster

            Logical      Status     Network          Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            Node-A-1_FC_clus1
                       up/up      169.254.209.69/16  Node-A-1_FC   e0a     true
            Node-A-1-FC_clus2
                       up/up      169.254.49.125/16  Node-A-1-FC   e0b     true
            Node-A-2-FC_clus1
                       up/up      169.254.47.194/16  Node-A-2-FC   e0a     true
            Node-A-2-FC_clus2
                       up/up      169.254.19.183/16  Node-A-2-FC   e0b     true

4 entries were displayed.

Cluster-A::*>
....
. 验证节点是否已发现两个本地 IP 交换机：
+
`network device-discovery show -protocol cdp`

+
....
Cluster-A::*> network device-discovery show -protocol cdp

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
Node-A-1-FC
           /cdp
            e0a    Switch-A-3-IP             1/5/1             N3K-C3232C
            e0b    Switch-A-4-IP             0/5/1             N3K-C3232C
Node-A-2-FC
           /cdp
            e0a    Switch-A-3-IP             1/6/1             N3K-C3232C
            e0b    Switch-A-4-IP             0/6/1             N3K-C3232C

4 entries were displayed.

Cluster-A::*>
....
. 在 IP 交换机上，验证两个本地 IP 交换机是否均已发现 MetroCluster IP 节点：
+
`s如何使用 cdp 邻居`

+
您必须对每个交换机执行此步骤。

+
此示例显示了如何验证是否已在 Switch-A-3-IP 上发现节点。

+
....
(Switch-A-3-IP)# show cdp neighbors

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
Node-A-1-FC         Eth1/5/1       133    H         FAS8200       e0a
Node-A-2-FC         Eth1/6/1       133    H         FAS8200       e0a
Switch-A-4-IP(FDO220329A4)
                    Eth1/7         175    R S I s   N3K-C3232C    Eth1/7
Switch-A-4-IP(FDO220329A4)
                    Eth1/8         175    R S I s   N3K-C3232C    Eth1/8
Switch-B-3-IP(FDO220329B3)
                    Eth1/20        173    R S I s   N3K-C3232C    Eth1/20
Switch-B-3-IP(FDO220329B3)
                    Eth1/21        173    R S I s   N3K-C3232C    Eth1/21

Total entries displayed: 4

(Switch-A-3-IP)#
....
+
此示例显示了如何验证是否已在 Switch-A-4-IP 上发现节点。

+
....
(Switch-A-4-IP)# show cdp neighbors

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
Node-A-1-FC         Eth1/5/1       133    H         FAS8200       e0b
Node-A-2-FC         Eth1/6/1       133    H         FAS8200       e0b
Switch-A-3-IP(FDO220329A3)
                    Eth1/7         175    R S I s   N3K-C3232C    Eth1/7
Switch-A-3-IP(FDO220329A3)
                    Eth1/8         175    R S I s   N3K-C3232C    Eth1/8
Switch-B-4-IP(FDO220329B4)
                    Eth1/20        169    R S I s   N3K-C3232C    Eth1/20
Switch-B-4-IP(FDO220329B4)
                    Eth1/21        169    R S I s   N3K-C3232C    Eth1/21

Total entries displayed: 4

(Switch-A-4-IP)#
....

