---
permalink: upgrade/task_assign_disk_ownership_to_non_aff_systems_mcc.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, assign, disk, ownership, aff, systems 
summary: 如果 MetroCluster 节点未正确分配磁盘，或者您在配置中使用的是 DS460C 磁盘架，则必须按磁盘架为 MetroCluster 配置中的每个节点分配磁盘。您将创建一种配置，其中每个节点的本地和远程磁盘池中的磁盘数相同。 
---
= 在非 AFF 系统中分配磁盘所有权
:icons: font
:imagesdir: ../media/


[role="lead"]
如果 MetroCluster 节点未正确分配磁盘，或者您在配置中使用的是 DS460C 磁盘架，则必须按磁盘架为 MetroCluster 配置中的每个节点分配磁盘。您将创建一种配置，其中每个节点的本地和远程磁盘池中的磁盘数相同。

存储控制器必须处于维护模式。

如果您的配置不包括 DS460C 磁盘架，则在从工厂收到磁盘时，如果磁盘已正确分配，则无需执行此任务。

[NOTE]
====
池 0 始终包含与拥有磁盘的存储系统位于同一站点的磁盘。

池 1 中的磁盘始终位于拥有这些磁盘的存储系统的远程位置。

====
如果您的配置包含 DS460C 磁盘架，则应按照以下准则为每个 12 磁盘抽盒手动分配磁盘：

|===


| 在抽盒中分配这些磁盘 ... | 到此节点和池 ... 


 a| 
0 - 2
 a| 
本地节点的池 0



 a| 
3 - 5
 a| 
HA 配对节点的池 0



 a| 
6 - 8.
 a| 
本地节点的池 1 的 DR 配对节点



 a| 
9 - 11
 a| 
HA 配对节点池 1 的 DR 配对节点

|===
此磁盘分配模式可确保在抽盒脱机时聚合受到的影响最小。

.步骤
. 如果尚未启动，请将每个系统启动至维护模式。
. 将磁盘架分配给位于第一个站点（站点 A ）的节点：
+
与节点位于同一站点的磁盘架分配给池 0 ，而位于配对站点的磁盘架分配给池 1 。

+
您应为每个池分配相同数量的磁盘架。

+
.. 在第一个节点上，系统地将本地磁盘架分配给池 0 ，并将远程磁盘架分配给池 1 ：
+
`dassign -shelf _local-switch-name ： shelf-name.port_ -p _pool_`

+
如果存储控制器 Controller_A_1 有四个磁盘架，则问题描述以下命令：

+
[listing]
----
*> disk assign -shelf FC_switch_A_1:1-4.shelf1 -p 0
*> disk assign -shelf FC_switch_A_1:1-4.shelf2 -p 0

*> disk assign -shelf FC_switch_B_1:1-4.shelf1 -p 1
*> disk assign -shelf FC_switch_B_1:1-4.shelf2 -p 1
----
.. 对本地站点的第二个节点重复此过程，系统地将本地磁盘架分配给池 0 ，并将远程磁盘架分配给池 1 ：
+
`dassign -shelf _local-switch-name ： shelf-name.port_ -p _pool_`

+
如果存储控制器 Controller_A_2 有四个磁盘架，则问题描述以下命令：

+
[listing]
----
*> disk assign -shelf FC_switch_A_1:1-4.shelf3 -p 0
*> disk assign -shelf FC_switch_B_1:1-4.shelf4 -p 1

*> disk assign -shelf FC_switch_A_1:1-4.shelf3 -p 0
*> disk assign -shelf FC_switch_B_1:1-4.shelf4 -p 1
----


. 将磁盘架分配给位于第二个站点（站点 B ）的节点：
+
与节点位于同一站点的磁盘架分配给池 0 ，而位于配对站点的磁盘架分配给池 1 。

+
您应为每个池分配相同数量的磁盘架。

+
.. 在远程站点的第一个节点上，系统地将本地磁盘架分配给池 0 ，并将远程磁盘架分配给池 1 ：
+
`dassign -shelf _local-switch-namelf-name_ -p _pool_`

+
如果存储控制器 Controller_B_1 有四个磁盘架，则问题描述以下命令：

+
[listing]
----
*> disk assign -shelf FC_switch_B_1:1-5.shelf1 -p 0
*> disk assign -shelf FC_switch_B_1:1-5.shelf2 -p 0

*> disk assign -shelf FC_switch_A_1:1-5.shelf1 -p 1
*> disk assign -shelf FC_switch_A_1:1-5.shelf2 -p 1
----
.. 对远程站点的第二个节点重复此过程，系统地将其本地磁盘架分配给池 0 ，并将其远程磁盘架分配给池 1 ：
+
`d` assign -shelf _shelf-name_ -p _pool_

+
如果存储控制器 Controller_B_2 有四个磁盘架，则问题描述以下命令：

+
[listing]
----
*> disk assign -shelf FC_switch_B_1:1-5.shelf3 -p 0
*> disk assign -shelf FC_switch_B_1:1-5.shelf4 -p 0

*> disk assign -shelf FC_switch_A_1:1-5.shelf3 -p 1
*> disk assign -shelf FC_switch_A_1:1-5.shelf4 -p 1
----


. 确认磁盘架分配：
+
`s存储显示磁盘架`

. 退出维护模式：
+
`halt`

. 显示启动菜单：
+
`boot_ontap 菜单`

. 在每个节点上，选择选项 * 。 4* 以初始化所有磁盘。

