---
permalink: upgrade/task_prepare_cluster_ports_on_the_exist_controller.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, prepare, cluster, ports, existing, controller, module 
summary: 在安装新控制器模块之前，您必须在现有控制器模块上配置集群端口，以便集群端口可以提供与新控制器模块的集群通信。 
---
= 正在准备现有控制器模块上的集群端口
:icons: font
:imagesdir: ../media/


[role="lead"]
在安装新控制器模块之前，您必须在现有控制器模块上配置集群端口，以便集群端口可以提供与新控制器模块的集群通信。

如果要创建双节点无交换机集群（无集群网络交换机），则必须启用无交换机集群网络模式。

有关 ONTAP 中端口， LIF 和网络配置的详细信息，请参见 link:https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/home.html["《网络管理指南》"]。

.步骤
. 确定应使用哪些端口作为节点的集群端口。
+
有关您的平台的默认端口角色列表，请参见 https://hwu.netapp.com/["Hardware Universe"]

+
NetApp 支持站点上适用于您的平台的 _Installation and Setup Instructions_包含 有关用于集群网络连接的端口的信息。

. 对于每个集群端口，确定端口角色： ` * network port show*`
+
在以下示例中，必须将端口 e0a ， e0b ， e0c 和 e0d 更改为集群端口：

+
[listing]
----
cluster_A::> network port show

Node: controller_A_1
Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link  MTU    Admin/Oper  Status
--------- ------------ ---------------- ----  ----   ----------- --------
e0M       Default      mgmt_bd_1500     up    1500   auto/1000   healthy
e0a       Default      Default          up    1500   auto/10000  healthy
e0b       Default      Default          up    1500   auto/10000  healthy
e0c       Default      Default          up    1500   auto/10000  healthy
e0d       Default      Default          up    1500   auto/10000  healthy
e0i       Default      Default          down  1500   auto/10     -
e0j       Default      Default          down  1500   auto/10     -
e0k       Default      Default          down  1500   auto/10     -
e0l       Default      Default          down  1500   auto/10     -
e2a       Default      Default          up    1500   auto/10000  healthy
e2b       Default      Default          up    1500   auto/10000  healthy
e4a       Default      Default          up    1500   auto/10000  healthy
e4b       Default      Default          up    1500   auto/10000  healthy
13 entries were displayed.
----
. 对于使用集群端口作为主端口或当前端口的任何数据 LIF ，请修改 LIF 以使用数据端口作为其主端口： `network interface modif*`
+
以下示例将数据 LIF 的主端口更改为数据端口：

+
[listing]
----
cluster1::> network interface modify -lif datalif1 -vserver vs1 -home-port e1b
----
. 对于您修改的每个 LIF ，将 LIF 还原到其新的主端口： ` * 网络接口 revert *`
+
以下示例将 LIF datalif1 还原到其新的主端口 e1b ：

+
[listing]
----
cluster1::> network interface revert -lif datalif1 -vserver vs1
----
. 删除使用集群端口作为成员端口的所有 VLAN 端口，以及使用集群端口作为成员端口的 ifgrp 。
+
.. 删除 VLAN 端口： + ` * 网络端口 vlan delete -node _node-name_ -vlan-name _portID-vlandid_*`
+
例如：

+
[listing]
----
network port vlan delete -node node1 -vlan-name e1c-80
----
.. 从接口组中删除物理端口：
+
`network port ifgrp remove-port -node _node-name_ -ifgrp _interface-group-name_ -port _portID_`

+
例如：

+
[listing]
----
network port ifgrp remove-port -node node1 -ifgrp a1a -port e0d
----
.. 从广播域中删除 VLAN 和接口组端口：
+
`network port broadcast-domain remove-ports -ipspace _ipspace_ -broadcast-domain _broadcast-domain-name_ -ports _nodename ： portname ， nodename ： portname_ ， ...`

.. 根据需要修改接口组端口以使用其他物理端口作为成员。： + `ifgrp add-port -node _node-name_ -ifgrp _interface-group-name_ -port _port-id_`


. 验证端口角色是否已更改： ` * network port show*`
+
以下示例显示端口 e0a ， e0b ， e0c 和 e0d 现在是集群端口：

+
[listing]
----
Node: controller_A_1
Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link  MTU    Admin/Oper  Status
--------- ------------ ---------------- ----  ----   ----------- --------
e0M       Default      mgmt_bd_1500     up    1500   auto/1000   healthy
e0a       Cluster      Cluster          up    9000   auto/10000  healthy
e0b       Cluster      Cluster          up    9000   auto/10000  healthy
e0c       Cluster      Cluster          up    9000   auto/10000  healthy
e0d       Cluster      Cluster          up    9000   auto/10000  healthy
e0i       Default      Default          down  1500   auto/10 -
e0j       Default      Default          down  1500   auto/10 -
e0k       Default      Default          down  1500   auto/10 -
e0l       Default      Default          down  1500   auto/10 -
e2a       Default      Default          up    1500   auto/10000  healthy
e2b       Default      Default          up    1500   auto/10000  healthy
e4a       Default      Default          up    1500   auto/10000  healthy
e4b       Default      Default          up    1500   auto/10000  healthy
13 entries were displayed.
----
. 将端口添加到集群广播域： `` * 广播域添加端口 -ipspace cluster -broadcast-domain cluster -ports _port-id_ ， _port-id_ ， _port-id_ ， _port-id_ …``
+
例如：



[listing]
----
broadcast-domain add-ports -ipspace Cluster -broadcast-domain Cluster -ports cluster1-01:e0a
----
. 如果您的系统属于交换集群，请在集群端口上创建集群 LIF ： ` * 网络接口 cre*`
+
以下示例将在节点的一个集群端口上创建集群 LIF 。` -auto` 参数可将 LIF 配置为使用链路本地 IP 地址。

+
[listing]
----
cluster1::> network interface create -vserver Cluster -lif clus1 -role cluster -home-node node0 -home-port e1a -auto true
----
. 如果要创建双节点无交换机集群，请启用无交换机集群网络模式：
+
.. 从任一节点更改为高级权限级别：
+
` * 设置 -privilege advanced*`

+
当系统提示您是否要继续进入高级模式时，您可以回答 `y` 。此时将显示高级模式提示符（` * >` ）。

.. 启用无交换机集群网络模式： ` * 网络选项 switchless-cluster modify -enabled true*`
.. 返回到管理权限级别： ` * 设置 -privilege admin*`


+

IMPORTANT: 在通过对新控制器模块进行网络启动完成集群设置后，为双节点无交换机集群系统中的现有节点创建集群接口。


