---
permalink: upgrade/task_boot_the_new_controllers_and_join_them_to_the_cluster.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, boot, new, controller, join, cluster 
summary: 要将新控制器加入集群，您必须启动每个新控制器模块，并使用 ONTAP 集群设置向导确定要加入的集群。 
---
= 启动新控制器并将其加入集群
:icons: font
:imagesdir: ../media/


[role="lead"]
要将新控制器加入集群，您必须启动每个新控制器模块，并使用 ONTAP 集群设置向导确定要加入的集群。

您必须已为 MetroCluster 配置布线。

在执行此任务之前，不得配置服务处理器。

必须对 MetroCluster 配置中两个集群上的每个新控制器执行此任务。

.步骤
. 如果尚未启动，请启动每个节点并让其完全启动。
+
如果系统处于维护模式，请问题描述 `halt` 命令退出维护模式，然后问题描述从加载程序提示符处运行以下命令：

+
`boot_ontap`

+
控制器模块进入节点设置向导。

+
输出应类似于以下内容：

+
[listing]
----
Welcome to node setup

You can enter the following commands at any time:
  "help" or "?" - if you want to have a question clarified,
  "back" - if you want to change previously answered questions, and
  "exit" or "quit" - if you want to quit the setup wizard.
				Any changes you made before quitting will be saved.

To accept a default or omit a question, do not enter a value.
.
.
.
----
. 按照系统提供的说明启用 AutoSupport 工具。
. 响应提示以配置节点管理接口。
+
这些提示类似于以下内容：

+
[listing]
----
Enter the node management interface port: [e0M]:
Enter the node management interface IP address: 10.228.160.229
Enter the node management interface netmask: 225.225.252.0
Enter the node management interface default gateway: 10.228.160.1
----
. 确认节点已配置为高可用性模式：
+
`s存储故障转移 show -fields mode`

+
如果不是，则必须在每个节点上执行问题描述以下命令，然后重新启动节点：

+
`storage failover modify -mode ha -node localhost`

+
此命令可配置高可用性模式，但不会启用存储故障转移。在配置过程的稍后部分问题描述 the `MetroCluster configure` 命令时，存储故障转移会自动启用。

. 确认已将四个端口配置为集群互连：
+
`network port show`

+
以下示例显示了 cluster_A 中两个控制器的输出如果是双节点 MetroCluster 配置，则输出仅显示一个节点。

+
[listing]
----
cluster_A::> network port show
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
node_A_1
       **e0a       Cluster      Cluster          up       1500  auto/1000
       e0b       Cluster      Cluster          up       1500  auto/1000**
       e0c       Default      Default          up       1500  auto/1000
       e0d       Default      Default          up       1500  auto/1000
       e0e       Default      Default          up       1500  auto/1000
       e0f       Default      Default          up       1500  auto/1000
       e0g       Default      Default          up       1500  auto/1000
node_A_2
       **e0a       Cluster      Cluster          up       1500  auto/1000
       e0b       Cluster      Cluster          up       1500  auto/1000**
       e0c       Default      Default          up       1500  auto/1000
       e0d       Default      Default          up       1500  auto/1000
       e0e       Default      Default          up       1500  auto/1000
       e0f       Default      Default          up       1500  auto/1000
       e0g       Default      Default          up       1500  auto/1000
14 entries were displayed.
----
. 由于您正在使用命令行界面设置集群，请退出节点设置向导：
+
`退出`

. 使用 `admin` 用户名登录到 admin 帐户。
. 启动集群设置向导，然后加入现有集群：
+
`集群设置`

+
[listing]
----
::> cluster setup

Welcome to the cluster setup wizard.

You can enter the following commands at any time:
  "help" or "?" - if you want to have a question clarified,
  "back" - if you want to change previously answered questions, and
  "exit" or "quit" - if you want to quit the cluster setup wizard.
     Any changes you made before quitting will be saved.

You can return to cluster setup at any time by typing "cluster setup".
To accept a default or omit a question, do not enter a value.


Do you want to create a new cluster or join an existing cluster? {create, join}:`join`
----
. 完成 * 集群设置 * 向导并退出后，验证集群是否处于活动状态且节点是否运行正常：
+
`cluster show`

+
以下示例显示了一个集群，其中第一个节点（ cluster1-01 ）运行状况良好且符合参与条件：

+
[listing]
----
cluster_A::> cluster show
Node               Health  Eligibility
------------------ ------- ------------
node_A_1           true    true
node_A_2           true    true
node_A_3           true    true
----
+
如果需要更改为管理 SVM 或节点 SVM 输入的任何设置，您可以使用 `cluster setup 命令` 访问 * 集群设置 * 向导。


