---
permalink: upgrade/task_apply_the_rcf_files_and_recable_the_switches.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, apply, rcf, files, recable, switches 
summary: 您必须应用 RCF 文件来重新配置分区以容纳新节点。 
---
= 应用 RCF 文件并重新为交换机布线
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须应用 RCF 文件来重新配置分区以容纳新节点。

.步骤
. 找到适用于您的配置的 RCF 文件。
+
对于八节点配置，必须使用与您的交换机型号匹配的 RCF 文件。

. 按照下载页面上的说明应用 RCF 文件，并根据需要调整 ISL 设置。
. 确保已保存交换机配置。
. 重新启动 FC 交换机。
. 使用先前创建的布线布局，使用缆线将原有的和新的 FC-SAS 网桥连接到 FC 交换机。
+
FC 交换机端口使用情况必须与中所述的 MetroCluster 八节点使用情况匹配 link:../install-fc/index.html["光纤连接的 MetroCluster 安装和配置"] 以便可以使用参考配置文件（ Reference Configuration Files ， RCF ）。

+

NOTE: 如果您的环境无法使用 RCF 文件进行布线，请联系技术支持。如果布线无法使用 RCF 文件，请勿使用此操作步骤。

. 使用适用于您的交换机的正确命令验证端口是否联机。
+
|===


| 交换机供应商 | 命令 


 a| 
Brocade
 a| 
switchshow



 a| 
Cisco
 a| 
显示接口简介

|===
. 使用中的操作步骤 link:../install-fc/index.html["光纤连接的 MetroCluster 安装和配置"] 使用先前创建的布线布局为现有控制器和新控制器中的 FC-VI 端口布线。
+
FC 交换机端口使用情况必须与中所述的 MetroCluster 八节点使用情况匹配 link:../install-fc/index.html["光纤连接的 MetroCluster 安装和配置"] 以便可以使用参考配置文件（ Reference Configuration Files ， RCF ）。

+

NOTE: 如果您的环境无法使用 RCF 文件进行布线，请联系技术支持。如果布线无法使用 RCF 文件，请勿使用此操作步骤。

. 从现有节点中，验证 FC-VI 端口是否联机：
+
`MetroCluster 互连适配器 show`

+
`MetroCluster 互连镜像显示`

. 为当前控制器和新控制器中的 HBA 端口布线。
. 在现有控制器模块上，启用连接到正在维护的交换机网络结构的端口：
+
`storage port enable -node _node-name_ -port _port-ID_`

. 启动新控制器并将其启动至维护模式：
+
`boot_ontap maint`

. 验证新控制器模块是否只能看到新 DR 组要使用的存储。
+
其他 DR 组使用的任何存储都不应可见。

. 返回到此过程的开头，为第二个交换机网络结构重新布线。

