---
permalink: upgrade/task_upgrade_controllers_system_control_commands_in_a_four_node_mcc_ip.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, controllers, switchover, switchback, ip, configuration, net, boot, root, aggregate, system, commands, mcc 
summary: 您可以使用此引导式自动MetroCluster 切换操作对四节点MetroCluster IP配置执行无中断控制器升级。 
---
= 使用带有system controller Replace命令的切换和切回升级四节点MetroCluster IP配置中的控制器(ONTAP 9.13.1及更高版本)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用此引导式自动MetroCluster 切换操作在四节点MetroCluster IP配置上执行无中断控制器升级。无法在此操作步骤中升级其他组件（例如存储架或交换机）。



== 支持的平台组合

此操作步骤 支持FAS8200到FAS9500以及AFF A300到AFF A900控制器升级。

有关平台升级组合的详细信息、请查看中的MetroCluster IP升级表 link:concept_choosing_controller_upgrade_mcc.html#supported-metrocluster-ip-controller-upgrades["选择控制器升级操作步骤"]。

请参见 https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/concept_choosing_an_upgrade_method_mcc.html["选择升级或刷新方法"] 以了解其他过程。



== 关于此任务

* 此操作步骤只能用于控制器升级。
+
无法同时升级配置中的其他组件，例如存储架或交换机。

* 此 操作步骤 适用场景 控制器模块采用运行ONTAP 9.13.1或更高版本的四节点MetroCluster IP配置。
+
https://hwu.netapp.com["NetApp Hardware Universe"^]

* MetroCluster 系统必须在两个站点上运行相同版本的ONTAP。
* 您可以使用此操作步骤 通过基于NSO的自动切换和切回来升级四节点MetroCluster IP配置中的控制器。
+

NOTE: 四节点MetroCluster IP配置不支持使用聚合重新定位(ARL)和"system controller Replace commands"(system controller Replace命令)执行升级。

* 您必须使用自动化NSO控制器升级操作步骤 按顺序升级两个站点上的控制器。
* 此基于 NSO 的自动控制器升级操作步骤使您能够对 MetroCluster 灾难恢复（ DR ）站点启动控制器更换。一次只能在一个站点启动控制器更换。
* 要在站点 A 启动控制器更换，您需要从站点 B 运行 controller replacement start 命令此操作仅会指导您更换站点 A 上两个节点的控制器。要更换站点 B 的控制器，您需要从站点 A 运行 controller replacement start 命令此时将显示一条消息，指出要更换控制器的站点。


此操作步骤使用以下示例名称：

* site_A
+
** 升级前：
+
*** node_A_1-old
*** node_A_2-old


** 升级后：
+
*** node_A_1-new
*** node_A_2-new




* 站点 B
+
** 升级前：
+
*** node_B_1-old
*** node_B_2-old


** 升级后：
+
*** node_B_1-new
*** node_B_2-new








== 准备升级。

要为控制器升级做准备，您需要执行系统预检并收集配置信息。

在启动预检之前、如果安装了ONTAP 调解器、则会自动检测并删除该调解器。要确认删除、系统会提示您输入用户名和密码。完成升级后、或者如果预检失败或您选择不继续升级、则必须执行此操作 link:task_upgrade_controllers_system_control_commands_in_a_four_node_mcc_ip.html#reconfigure-ontap-mediator["手动重新配置ONTAP 调解器"]。

在升级期间的任何阶段，您都可以从站点 A 运行 `ssystem controller replace show` 或 `ssystem controller replace show-details` 命令来检查状态。如果这些命令返回空白输出，请等待几分钟，然后重新运行此命令。

.步骤
. 从站点 A 启动自动控制器更换操作步骤，以更换站点 B 的控制器：
+
`system controller replace start -nso true`

+
自动操作将执行预检。如果未发现任何问题，此操作将暂停，以便您可以手动收集与配置相关的信息。

+
[NOTE]
====
** 如果不运行 `system controller replace start -nso true` 命令时、控制器升级操作步骤 会选择基于NSO的自动切换和切回作为MetroCluster IP系统上的默认操作步骤。
** 此时将显示当前源系统和所有兼容的目标系统。如果您将源控制器更换为 ONTAP 版本不同或平台不兼容的控制器，则在启动新节点后，自动化操作将暂停并报告错误。要将集群恢复为运行状况良好的状态，您需要按照手动恢复操作步骤进行操作。
+
`scontroller replace start` 命令可能会报告以下预检错误：

+
[listing]
----
Cluster-A::*>system controller replace show
Node        Status         Error-Action
----------- -------------- ------------------------------------
Node-A-1    Failed         MetroCluster check failed. Reason : MCC check showed errors in component aggregates
----
+
检查此错误是否是由于未镜像聚合或其他聚合问题描述而发生的。验证所有镜像聚合是否运行正常，并且未降级或镜像降级。如果此错误仅由未镜像聚合引起，则可以通过在 `ssystem controller replace start` 命令中选择 ` skip-metrocluster-check true` 选项来覆盖此错误。如果可以访问远程存储，则未镜像聚合会在切换后联机。如果远程存储链路发生故障，未镜像的聚合将无法联机。



====
. `s站点 B 并按照控制台消息中列出的命令在` system controller replace show `s或` system controller replace show-details 命令下手动收集配置信息。




=== 升级前收集信息

在升级之前，如果根卷已加密，则必须收集备份密钥和其他信息以使用旧的加密根卷启动新控制器。

.关于此任务
此任务将对现有MetroCluster IP配置执行。

.步骤
. 为现有控制器的缆线贴上标签，以便在设置新控制器时轻松识别缆线。
. 显示用于捕获备份密钥和其他信息的命令：
+
`ssystem controller replace show`

+
从配对集群运行 `show` 命令下列出的命令。

+
。 `show` 命令输出显示三个表、其中包含MetroCluster 接口IP、系统ID和系统UID。稍后、要在启动新节点时设置bootargs、需要在操作步骤 中提供此信息。

. 收集 MetroCluster 配置中节点的系统 ID ：
+
--
`MetroCluster node show -fields node-systemID ， dr-partner-systemID`

在更换操作步骤期间，您将使用新控制器模块的系统 ID 替换这些系统 ID 。

在此示例中、对于四节点MetroCluster IP配置、将检索以下旧系统ID：

** node_A_1-old ： 4068741258
** node_A_2-old ： 4068741260
** node_B_1-old ： 4068741254
** node_B_2-old ： 4068741256


[listing]
----
metrocluster-siteA::> metrocluster node show -fields node-systemid,ha-partner-systemid,dr-partner-systemid,dr-auxiliary-systemid
dr-group-id        cluster           node            node-systemid     ha-partner-systemid     dr-partner-systemid    dr-auxiliary-systemid
-----------        ---------------   ----------      -------------     -------------------     -------------------    ---------------------
1                    Cluster_A       Node_A_1-old    4068741258        4068741260              4068741256             4068741256
1                    Cluster_A       Node_A_2-old    4068741260        4068741258              4068741254             4068741254
1                    Cluster_B       Node_B_1-old    4068741254        4068741256              4068741258             4068741260
1                    Cluster_B       Node_B_2-old    4068741256        4068741254              4068741260             4068741258
4 entries were displayed.
----
在此双节点MetroCluster IP配置示例中、检索到以下旧系统ID：

** node_A_1 ： 4068741258
** node_B_1 ： 4068741254


[listing]
----
metrocluster node show -fields node-systemid,dr-partner-systemid

dr-group-id cluster    node          node-systemid dr-partner-systemid
----------- ---------- --------      ------------- ------------
1           Cluster_A  Node_A_1-old  4068741258    4068741254
1           Cluster_B  node_B_1-old  -             -
2 entries were displayed.
----
--
. 收集每个节点的端口和 LIF 信息。
+
您应收集每个节点的以下命令输出：

+
** `network interface show -role cluster ， node-mgmt`
** `network port show -node _node-name_ -type physical`
** `network port vlan show -node _node-name_`
** `network port ifgrp show -node _node_name_ -instance`
** `network port broadcast-domain show`
** `网络端口可访问性 show -detail`
** `network IPspace show`
** `volume show`
** `s存储聚合显示`
** `ssystem node run -node _node-name_ sysconfig -a`


. 如果 MetroCluster 节点采用 SAN 配置，请收集相关信息。
+
您应收集以下命令的输出：

+
** `fcp adapter show -instance`
** `fcp interface show -instance`
** `iscsi interface show`
** `ucadmin show`


. 如果根卷已加密，请收集并保存用于 key-manager 的密码短语：
+
`security key-manager backup show`

. 如果 MetroCluster 节点对卷或聚合使用加密，请复制有关密钥和密码短语的信息。
+
对于追加信息，请参见 https://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/GUID-1677AE0A-FEF7-45FA-8616-885AA3283BCF.html["手动备份板载密钥管理信息"^]。

+
.. 如果配置了板载密钥管理器：
+
`s安全密钥管理器板载 show-backup`

+
您稍后将在升级操作步骤中需要此密码短语。

.. 如果配置了企业密钥管理（ KMIP ），请问题描述执行以下命令：
+
`security key-manager external show -instance`

+
`s安全密钥管理器密钥查询`



. 收集完配置信息后，恢复此操作：
+
`s系统控制器更换恢复`





=== 从 Tiebreaker 或其他监控软件中删除现有配置

如果使用 MetroCluster Tiebreaker 配置或其他可启动切换的第三方应用程序（例如 ClusterLion ）监控现有配置，则在更换旧控制器之前，必须先从 Tiebreaker 或其他软件中删除 MetroCluster 配置。

.步骤
. http://docs.netapp.com/ontap-9/topic/com.netapp.doc.hw-metrocluster-tiebreaker/GUID-34C97A45-0BFF-46DD-B104-2AB2805A983D.html["删除现有 MetroCluster 配置"^] 来自 Tiebreaker 软件。
. 从可以启动切换的任何第三方应用程序中删除现有 MetroCluster 配置。
+
请参见该应用程序的文档。





== 更换旧控制器并启动新控制器

收集信息并恢复操作后，自动化将继续执行切换操作。

.关于此任务
此自动化操作将启动切换操作。完成这些操作后、此操作会在*暂停以供用户干预*、以便您可以将控制器装入机架并进行安装、启动配对控制器、以及使用从闪存备份将根聚合磁盘重新分配给新控制器模块 `sysids` 已提前收集。

.开始之前
在启动切换之前，自动化操作将暂停，以便您可以手动验证站点 B 上的所有 LIF 是否为 "`up` "如有必要，请将任何 " `down` " 移至 "`up` " ，然后使用 `ssystem controller replace resume` 命令恢复自动化操作。



=== 准备旧控制器的网络配置

要确保新控制器上的网络连接恢复正常，必须将 LIF 移动到一个通用端口，然后删除旧控制器的网络配置。

.关于此任务
* 必须对每个旧节点执行此任务。
* 您将使用中收集的信息 <<正在准备升级>>。


.步骤
. 启动旧节点，然后登录到这些节点：
+
`boot_ontap`

. 将旧控制器上所有数据 LIF 的主端口分配给新旧控制器模块上相同的通用端口。
+
.. 显示 LIF ：
+
`network interface show`

+
包括 SAN 和 NAS 在内的所有数据 LIF 都将为 admin "`up` " 和 Operationally "`down` " ，因为这些 LIF 在切换站点（ cluster_A ）上已启动。

.. 查看输出以查找未用作集群端口的旧控制器和新控制器上相同的通用物理网络端口。
+
例如， "`e0d` " 是旧控制器上的物理端口，也存在于新控制器上。"`e0d` " 不会用作集群端口，也不会在新控制器上使用。

+
有关平台型号的端口使用情况，请参见 https://hwu.netapp.com/["NetApp Hardware Universe"^]

.. 修改所有数据 LIF 以使用通用端口作为主端口：
+
`network interface modify -vserver _svm-name_ -lif _data-lif_ -home-port _port-id_`

+
在以下示例中，此值为 "`e0d` " 。

+
例如：

+
[listing]
----
network interface modify -vserver vs0 -lif datalif1 -home-port e0d
----


. 修改广播域以删除需要删除的 VLAN 和物理端口：
+
`broadcast-domain remove-ports -broadcast-domain _broadcast-domain-name_ -ports _node-name ： port-id_`

+
对所有 VLAN 和物理端口重复此步骤。

. 删除使用集群端口作为成员端口的所有 VLAN 端口，以及使用集群端口作为成员端口的接口组。
+
.. 删除 VLAN 端口：
+
`network port vlan delete -node _node-name_ -vlan-name _portID-vlandid_`

+
例如：

+
[listing]
----
network port vlan delete -node node1 -vlan-name e1c-80
----
.. 从接口组中删除物理端口：
+
`network port ifgrp remove-port -node _node-name_ -ifgrp _interface-group-name_ -port _portID_`

+
例如：

+
[listing]
----
network port ifgrp remove-port -node node1 -ifgrp a1a -port e0d
----
.. 从广播域中删除 VLAN 和接口组端口：
+
`network port broadcast-domain remove-ports -ipspace _ipspace_ -broadcast-domain _broadcast-domain-name_ -ports _nodename ： portname ， nodename ： portname_ ， ...`

.. 根据需要修改接口组端口以使用其他物理端口作为成员。：
+
`ifgrp add-port -node _node-name_ -ifgrp _interface-group-name_ -port _port-id_`



. 暂停节点：
+
`halt -inhibit-takeover true -node _node-name_`

+
必须在两个节点上执行此步骤。





=== 设置新控制器

您必须将新控制器装入机架并进行布线。

.步骤
. 根据需要规划新控制器模块和存储架的位置。
+
机架空间取决于控制器模块的平台型号，交换机类型以及配置中的存储架数量。

. 正确接地。
. 在机架或机柜中安装控制器模块。
+
https://docs.netapp.com/us-en/ontap-systems/index.html["AFF 和 FAS 文档中心"^]

. 如果新控制器模块未附带自身的 FC-VI 卡，并且旧控制器中的 FC-VI 卡在新控制器上兼容，请交换 FC-VI 卡并将其安装在正确的插槽中。
+
请参见 link:https://hwu.netapp.com["NetApp Hardware Universe"^] 有关 FC-VI 卡的插槽信息。

. 按照 _MetroCluster 安装和配置指南 _ 中所述，为控制器的电源，串行控制台和管理连接布线。
+
此时，请勿连接与旧控制器断开连接的任何其他缆线。

+
https://docs.netapp.com/us-en/ontap-systems/index.html["AFF 和 FAS 文档中心"^]

. 打开新节点的电源，并在系统提示显示 LOADER 提示符时按 Ctrl-C 。




=== 通过网络启动新控制器

安装新节点后，您需要通过网络启动来确保新节点运行的 ONTAP 版本与原始节点相同。术语 netboot 表示从远程服务器上存储的 ONTAP 映像启动。在准备网络启动时，您必须将 ONTAP 9 启动映像的副本放在系统可以访问的 Web 服务器上。

此任务将对每个新控制器模块执行。

.步骤
. 访问 https://mysupport.netapp.com/site/["NetApp 支持站点"^] 下载用于执行系统网络启动的文件。
. 从 NetApp 支持站点的软件下载部分下载相应的 ONTAP 软件，并将 ontap-version_image.tgz 文件存储在可通过 Web 访问的目录中。
. 转到可通过 Web 访问的目录，并验证所需文件是否可用。
+
您的目录列表应包含一个包含内核文件 ontap-version_image.tgz 的 netboot 文件夹

+
您不需要提取 ontap-version_image.tgz 文件。

. 在 LOADER 提示符处，为管理 LIF 配置网络启动连接：
+
** 如果 IP 地址为 DHCP ，请配置自动连接：
+
`ifconfig e0M -auto`

** 如果 IP 地址是静态的，请配置手动连接：
+
`ifconfig e0M -addr=ip_addr -mask=netmask` ` gw=gateway`



. 执行网络启动。
+
** 如果平台是 80xx 系列系统，请使用以下命令：
+
`netboot \http://web_server_ip/path_to_web-accessible_directory/netboot/kernel`

** 如果平台是任何其他系统，请使用以下命令：
+
`netboot \http://web_server_ip/path_to_web-accessible_directory/ontap-version_image.tgz`



. 从启动菜单中，选择选项 * （ 7 ） Install new software first* ，将新软件映像下载并安装到启动设备。
+
 Disregard the following message: "This procedure is not supported for Non-Disruptive Upgrade on an HA pair". It applies to nondisruptive upgrades of software, not to upgrades of controllers.
. 如果系统提示您继续运行操作步骤，请输入 `y` ，然后在系统提示您输入软件包时，输入映像文件的 URL ： ` \http://web_server_ip/path_to_web-accessible_directory/ontap-version_image.tgz`
+
....
Enter username/password if applicable, or press Enter to continue.
....
. 当您看到类似以下内容的提示时，请务必输入 `n` 以跳过备份恢复：
+
....
Do you want to restore the backup configuration now? {y|n}
....
. 当您看到类似以下内容的提示时，输入 `y` 以重新启动：
+
....
The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}
....




=== 清除控制器模块上的配置

[role="lead"]
在 MetroCluster 配置中使用新控制器模块之前，必须清除现有配置。

.步骤
. 如有必要，暂停节点以显示 LOADER 提示符：
+
`halt`

. 在 LOADER 提示符处，将环境变量设置为默认值：
+
`set-defaults`

. 保存环境：
+
`saveenv`

. 在 LOADER 提示符处，启动启动菜单：
+
`boot_ontap 菜单`

. 在启动菜单提示符处，清除配置：
+
`wipeconfig`

+
对确认提示回答 `yes` 。

+
节点将重新启动，并再次显示启动菜单。

. 在启动菜单中，选择选项 * 5* 将系统启动至维护模式。
+
对确认提示回答 `yes` 。





=== 还原 HBA 配置

根据控制器模块中是否存在 HBA 卡以及 HBA 卡的配置，您需要根据站点的使用情况正确配置这些卡。

.步骤
. 在维护模式下，为系统中的任何 HBA 配置设置：
+
.. 检查端口的当前设置： `ucadmin show`
.. 根据需要更新端口设置。


+
|===


| 如果您具有此类型的 HBA 和所需模式 ... | 使用此命令 ... 


 a| 
CNA FC
 a| 
`ucadmin modify -m fc -t initiator _adapter-name_`



 a| 
CNA 以太网
 a| 
`ucadmin modify -mode cna _adapter-name_`



 a| 
FC 目标
 a| 
`fcadmin config -t target _adapter-name_`



 a| 
FC 启动程序
 a| 
`fcadmin config -t initiator _adapter-name_`

|===
. 退出维护模式：
+
`halt`

+
运行此命令后，请等待，直到节点停留在 LOADER 提示符处。

. 将节点重新启动至维护模式，以使配置更改生效：
+
`boot_ontap maint`

. 验证所做的更改：
+
|===


| 如果您使用的是此类型的 HBA... | 使用此命令 ... 


 a| 
CNA
 a| 
`ucadmin show`



 a| 
FC
 a| 
`fcadmin show`

|===




=== 在新控制器和机箱上设置 HA 状态

您必须验证控制器和机箱的 HA 状态，并在必要时更新此状态以匹配您的系统配置。

.步骤
. 在维护模式下，显示控制器模块和机箱的 HA 状态：
+
`ha-config show`

+
所有组件的 HA 状态均应为 `mCCIP` 。

. 如果显示的控制器或机箱系统状态不正确，请设置 HA 状态：
+
`ha-config modify controller mccip`

+
`ha-config modify chassis mccip`

. 暂停节点： `halt`
+
节点应停止在 `loader>` 提示符处。

. 在每个节点上，检查系统日期，时间和时区： `show date`
. 如有必要，请以 UTC 或 GMT 格式设置日期： `set date <MM/dd/yyy>`
. 在启动环境提示符处使用以下命令检查时间： `show time`
. 如有必要，请以 UTC 或 GMT 格式设置时间： `set time <hh ： mm ： ss>`
. 保存设置： `saveenv`
. 收集环境变量： `printenv`




=== 更新交换机 RCF 文件以适应新平台

您必须将交换机更新为支持新平台型号的配置。

.关于此任务
您可以在包含当前正在升级的控制器的站点上执行此任务。在此操作步骤中显示的示例中，我们首先升级 site_B 。

当 site_A 上的控制器升级后， site_A 上的交换机将进行升级。

.步骤
. 准备 IP 交换机以应用新的 RCF 文件。
+
按照 _IP MetroCluster 安装和配置 _ 部分中适用于您的交换机供应商一节中的步骤进行操作。

+
link:../install-ip/index.html["MetroCluster IP 安装和配置"]

+
** link:../install-ip/task_switch_config_broadcom.html#resetting-the-broadcom-ip-switch-to-factory-defaults["将 Broadcom IP 交换机重置为出厂默认值"]
** link:../install-ip/task_switch_config_broadcom.html#resetting-the-cisco-ip-switch-to-factory-defaults["将 Cisco IP 交换机重置为出厂默认值"]


. 下载并安装 RCF 文件。
+
按照中适用于您的交换机供应商的一节中的步骤进行操作 link:../install-ip/index.html["MetroCluster IP 安装和配置"]。

+
** link:../install-ip/task_switch_config_broadcom.html#downloading-and-installing-the-broadcom-rcf-files["下载并安装 Broadcom RCF 文件"]
** link:../install-ip/task_switch_config_broadcom.html#downloading-and-installing-the-cisco-ip-rcf-files["下载并安装 Cisco IP RCF 文件"]






=== 设置 MetroCluster IP bootarg 变量

必须在新控制器模块上配置某些 MetroCluster IP bootarg 值。这些值必须与旧控制器模块上配置的值匹配。

.关于此任务
在此任务中，您将使用先前在中的升级操作步骤中标识的 UUID 和系统 ID link:task_upgrade_controllers_in_a_four_node_ip_mcc_us_switchover_and_switchback_mcc_ip.html#gathering-information-before-the-upgrade["升级前收集信息"]。

.步骤
. 在 `loader>` 提示符处，在 site_B 的新节点上设置以下 bootarg ：
+
`setenv bootarg.mcc.port_a_ip_config _local-ip-address/local-ip-mask ， 0 ， ha-partner-ip-address ， DR-partner-ip-address ， DR-aux-partnerip-address ， vlan-id_`

+
`setenv bootarg.mcc.port_b_ip_config _local-ip-address/local-ip-mask ， 0 ， ha-partner-ip-address ， DR-partner-ip-address ， DR-aux-partnerip-address ， vlan-id_`

+
以下示例将使用VLAN 120 (第一个网络)和VLAN 130 (第二个网络)为NODE_B_1设置值：

+
[listing]
----
setenv bootarg.mcc.port_a_ip_config 172.17.26.10/23,0,172.17.26.11,172.17.26.13,172.17.26.12,120
setenv bootarg.mcc.port_b_ip_config 172.17.27.10/23,0,172.17.27.11,172.17.27.13,172.17.27.12,130
----
+
以下示例将使用VLAN 120 (第一个网络)和VLAN 130 (第二个网络)为NODE_B_2设置值：

+
[listing]
----
setenv bootarg.mcc.port_a_ip_config 172.17.26.11/23,0,172.17.26.10,172.17.26.12,172.17.26.13,120
setenv bootarg.mcc.port_b_ip_config 172.17.27.11/23,0,172.17.27.10,172.17.27.12,172.17.27.13,130
----
. 在新节点的 `LOADER` 提示符处，设置 UUID ：
+
`setenv bootarg.mgwd.partner_cluster_uuid _partner-cluster-UUUID_`

+
`setenv bootarg.mgwd.cluster_uuid _local-cluster-UUUID_`

+
`setenv bootarg.mcc.pri_partner_uuid _DR-partner-node-UUUID_`

+
`setenv bootarg.mcc.aux_partner_uuid _DR-aux-partner-node-UUUUID_`

+
`setenv bootarg.mcc_iscsi.node_uuid _local-node-UUUUID_`

+
.. 设置NODE_B_1上的UID。
+
以下示例显示了用于设置NODE_B_1上的UID的命令：

+
[listing]
----
setenv bootarg.mgwd.cluster_uuid ee7db9d5-9a82-11e7-b68b-00a098908039
setenv bootarg.mgwd.partner_cluster_uuid 07958819-9ac6-11e7-9b42-00a098c9e55d
setenv bootarg.mcc.pri_partner_uuid f37b240b-9ac1-11e7-9b42-00a098c9e55d
setenv bootarg.mcc.aux_partner_uuid bf8e3f8f-9ac4-11e7-bd4e-00a098ca379f
setenv bootarg.mcc_iscsi.node_uuid f03cb63c-9a7e-11e7-b68b-00a098908039
----
.. 设置NODE_B_2上的UID：
+
以下示例显示了用于设置NODE_B_2上的UID的命令：

+
[listing]
----
setenv bootarg.mgwd.cluster_uuid ee7db9d5-9a82-11e7-b68b-00a098908039
setenv bootarg.mgwd.partner_cluster_uuid 07958819-9ac6-11e7-9b42-00a098c9e55d
setenv bootarg.mcc.pri_partner_uuid bf8e3f8f-9ac4-11e7-bd4e-00a098ca379f
setenv bootarg.mcc.aux_partner_uuid f37b240b-9ac1-11e7-9b42-00a098c9e55d
setenv bootarg.mcc_iscsi.node_uuid aa9a7a7a-9a81-11e7-a4e9-00a098908c35
----


. 如果原始系统配置了 ADP ，请在每个替代节点的 LOADER 提示符处启用 ADP ：
+
`setenv bootarg.mcc.ADP 启用 true`

. 设置以下变量：
+
`setenv bootarg.mcc.local_config_id _original-sys-id_`

+
`setenv bootarg.mcc.dr_partner _dr-partner-sys-id_`

+

NOTE: 。 `setenv bootarg.mcc.local_config_id` 变量必须设置为*ORIGINATI*控制器模块NODE_B_1的sys-id。

+
.. 在NODE_B_1上设置变量。
+
以下示例显示了用于设置NODE_B_1上的值的命令：

+
[listing]
----
setenv bootarg.mcc.local_config_id 537403322
setenv bootarg.mcc.dr_partner 537403324
----
.. 在NODE_B_2上设置变量。
+
以下示例显示了用于设置NODE_B_2上的值的命令：

+
[listing]
----
setenv bootarg.mcc.local_config_id 537403321
setenv bootarg.mcc.dr_partner 537403323
----


. 如果对外部密钥管理器使用加密，请设置所需的 boottargets ：
+
`setenv bootarg.kmip.init.ipaddr`

+
`setenv bootarg.kmip.kmip.init.netmask`

+
`setenv bootarg.kmip.kmip.init.gateway`

+
`setenv bootarg.kmip.kmip.init.interface`





=== 重新分配根聚合磁盘

使用先前收集的 `sysids` 将根聚合磁盘重新分配给新控制器模块

.关于此任务
此任务在维护模式下执行。

旧系统 ID 在中进行了标识 link:task_upgrade_controllers_system_control_commands_in_a_four_node_mcc_ip.html#gathering-information-before-the-upgrade["升级前收集信息"]。

此操作步骤中的示例使用具有以下系统 ID 的控制器：

|===


| 节点 | 旧系统 ID | 新系统 ID 


 a| 
node_B_1
 a| 
4068741254
 a| 
1574774970

|===
.步骤
. 使用缆线将所有其他连接连接到新控制器模块（ FC-VI ，存储，集群互连等）。
. 暂停系统并从 LOADER 提示符启动到维护模式：
+
`boot_ontap maint`

. 显示 node_B_1-old 拥有的磁盘：
+
`d` 展示 -A

+
命令输出将显示新控制器模块（ 1574774970 ）的系统 ID 。但是，根聚合磁盘仍归旧系统 ID （ 4068741254 ）所有。此示例不显示 MetroCluster 配置中其他节点拥有的驱动器。

+
[listing]
----
*> disk show -a
Local System ID: 1574774970

  DISK         OWNER                     POOL   SERIAL NUMBER    HOME                      DR HOME
------------   -------------             -----  -------------    -------------             -------------
...
rr18:9.126L44 node_B_1-old(4068741254)   Pool1  PZHYN0MD         node_B_1-old(4068741254)  node_B_1-old(4068741254)
rr18:9.126L49 node_B_1-old(4068741254)   Pool1  PPG3J5HA         node_B_1-old(4068741254)  node_B_1-old(4068741254)
rr18:8.126L21 node_B_1-old(4068741254)   Pool1  PZHTDSZD         node_B_1-old(4068741254)  node_B_1-old(4068741254)
rr18:8.126L2  node_B_1-old(4068741254)   Pool0  S0M1J2CF         node_B_1-old(4068741254)  node_B_1-old(4068741254)
rr18:8.126L3  node_B_1-old(4068741254)   Pool0  S0M0CQM5         node_B_1-old(4068741254)  node_B_1-old(4068741254)
rr18:9.126L27 node_B_1-old(4068741254)   Pool0  S0M1PSDW         node_B_1-old(4068741254)  node_B_1-old(4068741254)
...
----
. 将驱动器架上的根聚合磁盘重新分配给新控制器：
+
`dreassign -s _old-sysid_ -d _new-sysid_`

+

NOTE: 如果您的MetroCluster IP系统配置了高级磁盘分段功能、则必须通过运行来包含DR配对系统ID `disk reassign -s old-sysid -d new-sysid -r dr-partner-sysid` 命令：

+
以下示例显示了驱动器的重新分配：

+
[listing]
----
*> disk reassign -s 4068741254 -d 1574774970
Partner node must not be in Takeover mode during disk reassignment from maintenance mode.
Serious problems could result!!
Do not proceed with reassignment if the partner is in takeover mode. Abort reassignment (y/n)? n

After the node becomes operational, you must perform a takeover and giveback of the HA partner node to ensure disk reassignment is successful.
Do you want to continue (y/n)? Jul 14 19:23:49 [localhost:config.bridge.extra.port:error]: Both FC ports of FC-to-SAS bridge rtp-fc02-41-rr18:9.126L0 S/N [FB7500N107692] are attached to this controller.
y
Disk ownership will be updated on all disks previously belonging to Filer with sysid 4068741254.
Do you want to continue (y/n)? y
----
. 检查是否已按预期重新分配所有磁盘：
+
`d展示`

+
[listing]
----
*> disk show
Local System ID: 1574774970

  DISK        OWNER                      POOL   SERIAL NUMBER   HOME                      DR HOME
------------  -------------              -----  -------------   -------------             -------------
rr18:8.126L18 node_B_1-new(1574774970)   Pool1  PZHYN0MD        node_B_1-new(1574774970)  node_B_1-new(1574774970)
rr18:9.126L49 node_B_1-new(1574774970)   Pool1  PPG3J5HA        node_B_1-new(1574774970)  node_B_1-new(1574774970)
rr18:8.126L21 node_B_1-new(1574774970)   Pool1  PZHTDSZD        node_B_1-new(1574774970)  node_B_1-new(1574774970)
rr18:8.126L2  node_B_1-new(1574774970)   Pool0  S0M1J2CF        node_B_1-new(1574774970)  node_B_1-new(1574774970)
rr18:9.126L29 node_B_1-new(1574774970)   Pool0  S0M0CQM5        node_B_1-new(1574774970)  node_B_1-new(1574774970)
rr18:8.126L1  node_B_1-new(1574774970)   Pool0  S0M1PSDW        node_B_1-new(1574774970)  node_B_1-new(1574774970)
*>
----
. 显示聚合状态：
+
`聚合状态`

+
[listing]
----
*> aggr status
           Aggr            State       Status           Options
aggr0_node_b_1-root        online      raid_dp, aggr    root, nosnap=on,
                           mirrored                     mirror_resync_priority=high(fixed)
                           fast zeroed
                           64-bit
----
. 在配对节点（ node_B_2-new ）上重复上述步骤。




=== 启动新控制器

您必须从启动菜单重新启动控制器，才能更新控制器闪存映像。如果配置了加密，则需要执行其他步骤。

您可以重新配置 VLAN 和接口组。如果需要，请在使用 `ssystem controller replace resume` 命令恢复操作之前手动修改集群 LIF 的端口和广播域详细信息。

.关于此任务
必须对所有新控制器执行此任务。

.步骤
. 暂停节点：
+
`halt`

. 如果配置了外部密钥管理器，请设置相关的 boottargets ：
+
`setenv bootarg.kmip.init.ipaddr _ip-address_`

+
`setenv bootarg.kmip.init.netmask _netmask_`

+
`setenv bootarg.kmip.init.gateway _gateway-address_`

+
`setenv bootarg.kmip.init.interface _interface-id_`

. 显示启动菜单：
+
`boot_ontap 菜单`

. 如果使用根加密，请为密钥管理配置选择启动菜单选项。
+
|===


| 如果您使用的是 ... | 选择此启动菜单选项 ... 


 a| 
板载密钥管理
 a| 
选项 "`10` "

按照提示提供恢复和还原密钥管理器配置所需的输入。



 a| 
外部密钥管理
 a| 
选项 "`11` "

按照提示提供恢复和还原密钥管理器配置所需的输入。

|===
. 从启动菜单中，运行选项 "`6` " 。
+

NOTE: 选项 "`6` " 将在完成前重新启动节点两次。

+
对系统 ID 更改提示回答 "`y` " 。等待第二条重新启动消息：

+
[listing]
----
Successfully restored env file from boot media...

Rebooting to load the restored env file...
----
+
在选项"`6`"后的一次重新启动期间、将显示确认提示 `Override system ID? {y|n}` 显示。输入 ... `y`。

. 如果使用根加密，请为密钥管理配置再次选择启动菜单选项。
+
|===


| 如果您使用的是 ... | 选择此启动菜单选项 ... 


 a| 
板载密钥管理
 a| 
选项 "`10` "

按照提示提供恢复和还原密钥管理器配置所需的输入。



 a| 
外部密钥管理
 a| 
选项 "`11` "

按照提示提供恢复和还原密钥管理器配置所需的输入。

|===
+
根据密钥管理器设置，执行恢复操作步骤的方法是在第一个启动菜单提示符处选择选项 "`10` " 或选项 "`11` " ，然后选择选项 "`6` " 。要完全启动节点，您可能需要重复恢复操作步骤，然后选择 "`1` " （正常启动）。

. 启动节点：
+
`boot_ontap`

. 等待更换的节点启动。
+
如果任一节点处于接管模式，请使用 `storage failover giveback` 命令执行交还。

. 验证所有端口是否都位于广播域中：
+
.. 查看广播域：
+
`network port broadcast-domain show`

.. 根据需要向广播域添加任何端口。
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-003BDFCD-58A3-46C9-BF0C-BA1D1D1475F9.html["从广播域添加或删除端口"^]

.. 将用于托管集群间LIF的物理端口添加到相应的广播域中。
.. 修改集群间 LIF 以使用新的物理端口作为主端口。
.. 集群间 LIF 启动后，检查集群对等状态，并根据需要重新建立集群对等关系。
+
您可能需要重新配置集群对等关系。

+
link:../install-ip/task_sw_config_configure_clusters.html#peering-the-clusters["创建集群对等关系"]

.. 根据需要重新创建 VLAN 和接口组。
+
VLAN 和接口组成员资格可能与旧节点不同。

+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-8929FCE2-5888-4051-B8C0-E27CAF3F2A63.html["创建 VLAN"^]

+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-DBC9DEE2-EAB7-430A-A773-4E3420EE2AA1.html["组合物理端口以创建接口组"^]

.. 验证配对集群是否可访问、以及配置是否已在配对集群上成功重新同步：
+
`metrocluster switchback -simulate true`



. 如果使用加密，请使用适用于您的密钥管理配置的正确命令还原密钥。
+
|===


| 如果您使用的是 ... | 使用此命令 ... 


 a| 
板载密钥管理
 a| 
`sSecurity key-manager 板载同步`

有关详细信息，请参见 https://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/GUID-E4AB2ED4-9227-4974-A311-13036EB43A3D.html["还原板载密钥管理加密密钥"^]。



 a| 
外部密钥管理
 a| 
`sSecurity key-manager external restore -vserver _svm_ -node _node_-key-server _host_name_ip_address ： port_ -key-id key_id -key-tag key_tag _node-name_`

有关详细信息，请参见 https://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/GUID-32DA96C3-9B04-4401-92B8-EAF323C3C863.html["还原外部密钥管理加密密钥"^]。

|===
. 在恢复此操作之前，请验证是否已正确配置 MetroCluster 。检查节点状态：
+
`MetroCluster node show`

+
验证新节点（ site_B ）是否处于 * 正在等待 site_A 的切回状态 *

. 恢复操作：
+
`s系统控制器更换恢复`





== 正在完成升级

此自动化操作将运行验证系统检查，然后暂停，以便您可以验证网络可访问性。验证后，将启动资源重新获取阶段，自动化操作将在站点 A 执行切回，并在升级后检查时暂停。恢复自动化操作后，它将执行升级后检查，如果未检测到错误，则会将升级标记为完成。

.步骤
. 按照控制台消息验证网络可访问性。
. 完成验证后，恢复此操作：
+
`s系统控制器更换恢复`

. 此时将执行自动化操作 `heal-aggregate`， `heal-root-aggregate`和站点A上的切回操作以及升级后检查。操作暂停后，手动检查 SAN LIF 状态，并按照控制台消息验证网络配置。
. 完成验证后，恢复此操作：
+
`s系统控制器更换恢复`

. 检查升级后检查状态：
+
`ssystem controller replace show`

+
如果升级后检查未报告任何错误，则说明升级已完成。

. 完成控制器升级后，登录站点 B 并验证是否已正确配置更换的控制器。




=== 重新配置ONTAP 调解器

手动配置在开始升级之前自动删除的ONTAP 调解器。

. 使用中的步骤 link:../install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html["从 MetroCluster IP 配置配置 ONTAP 调解器服务"]。




=== 正在还原 Tiebreaker 监控

如果先前已将 MetroCluster 配置配置为由 Tiebreaker 软件监控，则可以还原 Tiebreaker 连接。

. 使用中的步骤 http://docs.netapp.com/ontap-9/topic/com.netapp.doc.hw-metrocluster-tiebreaker/GUID-7259BCA4-104C-49C6-BAD0-1068CA2A3DA5.html["正在添加 MetroCluster 配置"]。

