---
permalink: upgrade/task_verify_the_health_of_the_mcc_configuration.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, health, verify, conofiguration 
summary: 您应检查 MetroCluster 配置的运行状况以验证是否正常运行。 
---
= 验证 MetroCluster 配置的运行状况
:icons: font
:imagesdir: ../media/


[role="lead"]
您应检查 MetroCluster 配置的运行状况以验证是否正常运行。

.步骤
. 检查每个集群上是否已配置 MetroCluster 并处于正常模式：
+
`MetroCluster show`

+
[listing]
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
----
. 检查是否已在每个节点上启用镜像：
+
`MetroCluster node show`

+
[listing]
----
cluster_A::> metrocluster node show
DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              node_A_1       configured     enabled   normal
      cluster_B
              node_B_1       configured     enabled   normal
2 entries were displayed.
----
. 检查 MetroCluster 组件是否运行正常：
+
`MetroCluster check run`

+
[listing]
----
cluster_A::> metrocluster check run

Last Checked On: 10/1/2014 16:03:37

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
4 entries were displayed.

Command completed. Use the "metrocluster check show -instance" command or sub-commands in "metrocluster check" directory for detailed results.
To check if the nodes are ready to do a switchover or switchback operation, run "metrocluster switchover -simulate" or "metrocluster switchback -simulate", respectively.
----
. 检查是否没有运行状况警报：
+
`s系统运行状况警报显示`

. 模拟切换操作：
+
.. 在任何节点的提示符处，更改为高级权限级别： + `set -privilege advanced`
+
当系统提示您继续进入高级模式并显示高级模式提示符（ * > ）时，您需要使用 ` * y*` 进行响应。

.. 使用 -simulate 参数执行切换操作： + MetroCluster switchover -simulate`
.. 返回到管理权限级别： + `set -privilege admin`



