---
permalink: upgrade/task_implement_the_mcc_configuration_mcc_refresh_mcc_expansion.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, implement, configuration 
summary: 您必须运行 MetroCluster configure -refresh true 命令对已添加到 MetroCluster 配置的节点启动数据保护。 
---
= 实施 MetroCluster 配置
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须运行 `MetroCluster configure -refresh true` 命令在已添加到 MetroCluster 配置的节点上启动数据保护。

.关于此任务
您可以在新添加的一个节点上问题描述一次 `MetroCluster configure -refresh true` 命令，以刷新 MetroCluster 配置。您无需在每个站点或节点上对命令执行问题描述。

使用 `MetroCluster configure -refresh true` 命令可自动将两个集群中每个集群中系统 ID 最低的两个节点配对为灾难恢复（ DR ）配对节点。在四节点 MetroCluster 配置中，存在两个 DR 配对节点对。第二个 DR 对是从系统 ID 较高的两个节点创建的。

.步骤
. 刷新 MetroCluster 配置：
+
.. 进入高级权限模式：
+
`set -privilege advanced`

.. 在一个新节点上刷新 MetroCluster 配置： + MetroCluster configure -refresh true`
+
以下示例显示了在两个 DR 组上刷新的 MetroCluster 配置：

+
[listing]
----
controller_A_2::*> metrocluster configure -refresh true

[Job 726] Job succeeded: Configure is successful.
----
+
[listing]
----
controller_A_4::*> metrocluster configure -refresh true

[Job 740] Job succeeded: Configure is successful.
----
.. 返回到管理权限模式：
+
`set -privilege admin`



. 验证站点 A 上的网络连接状态：
+
`network port show`

+
以下示例显示了四节点 MetroCluster 配置中的网络端口使用情况：

+
[listing]
----
cluster_A::> network port show
                                                          Speed (Mbps)
Node   Port      IPspace   Broadcast Domain Link   MTU    Admin/Oper
------ --------- --------- ---------------- ----- ------- ------------
controller_A_1
       e0a       Cluster   Cluster          up     9000  auto/1000
       e0b       Cluster   Cluster          up     9000  auto/1000
       e0c       Default   Default          up     1500  auto/1000
       e0d       Default   Default          up     1500  auto/1000
       e0e       Default   Default          up     1500  auto/1000
       e0f       Default   Default          up     1500  auto/1000
       e0g       Default   Default          up     1500  auto/1000
controller_A_2
       e0a       Cluster   Cluster          up     9000  auto/1000
       e0b       Cluster   Cluster          up     9000  auto/1000
       e0c       Default   Default          up     1500  auto/1000
       e0d       Default   Default          up     1500  auto/1000
       e0e       Default   Default          up     1500  auto/1000
       e0f       Default   Default          up     1500  auto/1000
       e0g       Default   Default          up     1500  auto/1000
14 entries were displayed.
----
. 从 MetroCluster 配置中的两个站点验证 MetroCluster 配置：
+
.. 从站点 A 验证配置：
+
`MetroCluster show`

+
[listing]
----
cluster_A::> metrocluster show

Configuration: IP fabric

Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_A         Configuration state configured
                          Mode                normal
Remote: cluster_B         Configuration state configured
                          Mode                normal
----
.. 从站点 B 验证配置： + MetroCluster show`
+
[listing]
----
cluster_B::> metrocluster show

Configuration: IP fabric

Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_B         Configuration state configured
                          Mode                normal
Remote: cluster_A         Configuration state configured
                          Mode                normal
----



