---
permalink: upgrade/upgrade-mcc-ip-system-controller-replace-restore-hba-set-ha.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, controllers, switchover, switchback, ip, configuration, net, boot, root, aggregate, system, commands, mcc 
summary: 在控制器模块中配置HBA卡、并验证和设置控制器和机箱的HA状态。 
---
= 还原HBA配置并设置MetroCluster IP控制器和机箱的HA状态
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在控制器模块中配置HBA卡、并验证和设置控制器和机箱的HA状态。



== 还原 HBA 配置

根据控制器模块中是否存在HBA卡以及HBA卡的配置、您需要为站点正确配置HBA卡。

.步骤
. 在维护模式下、为系统中的任何HBA配置设置：
+
.. 检查端口的当前设置： `ucadmin show`
.. 根据需要更新端口设置。


+
|===


| 如果您具有此类型的 HBA 和所需模式 ... | 使用此命令 ... 


 a| 
CNA FC
 a| 
`ucadmin modify -m fc -t initiator <adapter-name>`



 a| 
CNA 以太网
 a| 
`ucadmin modify -mode cna <adapter-name>`



 a| 
FC 目标
 a| 
`fcadmin config -t target <adapter-name>`



 a| 
FC 启动程序
 a| 
`fcadmin config -t initiator <adapter-name>`

|===
. 退出维护模式：
+
`halt`

+
运行命令后、请等待、直到节点停留在提示符处 `LOADER` 。

. 将节点启动回维护模式以应用配置更改：
+
`boot_ontap maint`

. 验证所做的更改：
+
|===


| 如果您使用的是此类型的 HBA... | 使用此命令 ... 


 a| 
CNA
 a| 
`ucadmin show`



 a| 
FC
 a| 
`fcadmin show`

|===




== 在新控制器和机箱上设置 HA 状态

您必须验证控制器和机箱的 HA 状态，并在必要时更新此状态以匹配您的系统配置。

.步骤
. 在维护模式下，显示控制器模块和机箱的 HA 状态：
+
`ha-config show`

+
所有组件的 HA 状态均应为 `mCCIP` 。

. 如果显示的控制器或机箱系统状态不正确，请设置 HA 状态：
+
`ha-config modify controller mccip`

+
`ha-config modify chassis mccip`

. 验证并修改连接到NS224磁盘架或存储交换机的以太网端口。
+
.. 验证连接到NS224磁盘架或存储交换机的以太网端口：
+
`storage port show`

.. 将连接到以太网磁盘架或存储交换机的所有以太网端口(包括用于存储和集群的共享交换机)设置为 `storage` 模式：
+
`storage port modify -p <port> -m storage`

+
示例：

+
[listing]
----
*> storage port modify -p e5b -m storage
Changing NVMe-oF port e5b to storage mode
----
+

NOTE: 要成功升级、必须在所有受影响的端口上设置此值。

+
输出将报告连接到以太网端口的磁盘架中的磁盘 `sysconfig -v` 。

+
有关要升级到的系统的存储端口的信息、请参见 link:https://hwu.netapp.com["Hardware Universe"^] 。

.. 验证是否 `storage` 已设置模式、并确认端口是否处于联机状态：
+
`storage port show`



. 暂停节点： `halt`
+
节点应停止在 `loader>` 提示符处。

. 在每个节点上，检查系统日期，时间和时区： `show date`
. 如有必要，请以 UTC 或 GMT 格式设置日期： `set date <MM/dd/yyy>`
. 在启动环境提示符处使用以下命令检查时间： `show time`
. 如有必要，请以 UTC 或 GMT 格式设置时间： `set time <hh ： mm ： ss>`
. 保存设置： `saveenv`
. 收集环境变量： `printenv`




== 从新控制器的机箱中移除内部驱动器

当您从仅有外部驱动器的系统升级到具有外部和内部驱动器（同一机箱中的磁盘和控制器）的系统时，您需要从新系统中删除或取消安装所有内部驱动器，直到升级完成。


CAUTION: 此任务对于受影响系统上的控制器成功升级是必需的。

要确定您的升级组合是否受到影响，请参阅link:upgrade-mcc-ip-system-controller-replace-supported-platforms.html["支持使用system controller Replace命令升级MetroCluster IP控制器"] 。如果您的升级组合标有*注释 2*，则必须从新系统中移除或移除内部驱动器。

完成此任务后，任何内部驱动器都不应可访问。您将在稍后的步骤中将这些驱动器添加到新的控制器。

.下一步是什么？
link:upgrade-mcc-ip-system-controller-replace-apply-rcf-set-bootarg.html["更新交换机RC框架 文件并设置MetroCluster IP启动程序值"](英文)
