---
permalink: tiebreaker/concept_configuring_the_tiebreaker_software.html 
sidebar: sidebar 
keywords: installation, tiebreaker, software, add, modify, metrocluster, configuration, remove, configuring, configure, launch, cli, add, command, modify, removing 
summary: 安装 Tiebreaker 软件后，您可以添加或修改 MetroCluster 配置，或者将其从 Tiebreaker 软件中删除。 
---
= 配置MetroCluster决胜软件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
安装 Tiebreaker 软件后，您可以添加或修改 MetroCluster 配置，或者将其从 Tiebreaker 软件中删除。



== 启动 Tiebreaker 软件 CLI

安装Tiebreaker软件后、您必须启动其命令行界面来配置该软件。

. 从安装该软件的主机的提示符启动命令行界面：
+
`NetApp-MetroCluster-Tiebreaker 软件 -CLI`

. 安装后以及首次启动期间、输入Tiebreaker用户访问数据库的密码。这是您在安装期间为数据库用户指定的密码。




== 添加 MetroCluster 配置

安装 NetApp MetroCluster Tiebreaker 软件后，您可以添加更多 MetroCluster 配置，一次添加一个。

.关于此任务
* 您必须已在 ONTAP 环境中安装 MetroCluster 配置并启用软件中的设置。
* 具体步骤和预期命令输出取决于您运行的 Tiebreaker 版本。


[role="tabbed-block"]
====
.决胜局 1.5 或更早
--
.步骤
. 使用 Tiebreaker 命令行界面（ CLI ） monitor add 命令添加 MetroCluster 配置。
+
如果使用的是主机名，则该主机名必须是完全限定域名（ FQDN ）。

+
以下示例显示了 cluster_A 的配置：

+
.示例
[%collapsible]
=====
[listing]
----

NetApp MetroCluster Tiebreaker :> monitor add wizard
Enter monitor Name: <monitor_name>
Enter Cluster IP Address: <cluster_ip_value>
Enter Cluster Username: admin
Enter Cluster Password:
Enter Cluster IP Address: <peer_cluster_ip_value>
Enter Peer Cluster Username: admin
Enter Peer Cluster Password:
Successfully added monitor to NetApp MetroCluster Tiebreaker software.
----
=====
. 使用 Tiebreaker CLI `monitor show -status` 命令确认已正确添加 MetroCluster 配置。
+
[listing]
----

NetApp MetroCluster Tiebreaker :> monitor show -status
----
. 禁用观察模式，以便 Tiebreaker 软件在检测到站点故障后自动启动切换：
+
`monitor modify -monitor-name <monitor_name> -observer-mode false`

+
[listing]
----
NetApp MetroCluster Tiebreaker :> monitor modify -monitor-name 8pack -observer-mode false
Warning: If you are turning observer-mode to false, make sure to review the 'risks and limitations'
as described in the MetroCluster Tiebreaker installation and configuration.
Are you sure you want to enable automatic switchover capability for monitor "8pack"? [Y/N]: y
----


--
.Tieb破碎 机1.6或更高版本
--
.步骤
. 使用 Tiebreaker 命令行界面（ CLI ） monitor add 命令添加 MetroCluster 配置。
+
如果使用的是主机名，则该主机名必须是完全限定域名（ FQDN ）。

+
以下示例显示了 cluster_A 的配置：

+
.示例
[%collapsible]
=====
[listing]
----
NetApp MetroCluster Tiebreaker :> monitor add wizard
Enter Monitor Name: cluster_A
Enter Cluster IP Address: <cluster_ip_value>
Enter Cluster Username: admin
Enter Cluster Password:
Enter Peer Cluster IP Address: <peer_cluster_ip_value>
Enter Peer Cluster Username: admin
Enter Peer Cluster Password:

 NOTE: Before enabling automatic switchover capability, make sure to review the 'risks and limitations' as described in the MetroCluster Tiebreaker Installation and Configuration Guide.

Do you want to enable automatic switchover capability for monitor(Y/N): y
Successfully added monitor to NetApp MetroCluster Tiebreaker software.
Verifying SSL certificate chain from cluster_A...

===============================================
Warning missing SSL certificates
===============================================

Cluster: cluster_A

IP Address: <cluster_ip_value>

Result:

The MetroCluster Tiebreaker is unable to verify the SSL certificate chain.

Recommended Actions:

Run the following command to identify missing certificates:

monitor switchover-simulate

Import any missing certificates as indicated by the command output.

For detailed instructions, please refer to the MetroCluster Tiebreaker documentation, or contact NetApp Support for assistance.

Note:

Missing certificates will prevent the MetroCluster Tiebreaker from issuing a switchover request in the event of a site failure.

================================================================================================================================
Verifying SSL certificate chain from cluster_B...

SSL certificate chain is valid
----
=====
. 使用 Tiebreaker CLI `monitor show -status` 命令确认已正确添加 MetroCluster 配置。
+
[listing]
----

NetApp MetroCluster Tiebreaker :> monitor show -status
----
. 请按照适用于您的 Tiebreaker 版本的步骤导入缺失的证书。<<import-certificates-tb17,进口证书>> 。


--
====
.相关信息
link:concept_risks_and_limitation_of_using_mcc_tiebreaker_in_active_mode.html["在主动模式下使用 MetroCluster Tiebreaker 的风险和限制"]



== 进口证书

要在 Tiebreaker 1.6 或更高版本中启用无缝监控，您需要将服务器安全套接字层 (SSL) 证书、中间证书（如果存在）和根证书从ONTAP导入到 Java 虚拟机 (JVM) 中的密钥库。

.关于此任务
* 此任务在 Tiebreaker 1.6 或更高版本中是必需的。
* 成功将MetroCluster配置添加到 Tiebreaker 后，或者证书过期后，您需要执行此任务。
* 在 Tiebreaker 1.7 或更高版本中，您可以执行切换模拟来检查是否需要导入证书。如果切换模拟失败，则需要将证书从ONTAP导入到 Java 虚拟机 (JVM) 中的密钥库。


[role="tabbed-block"]
====
.决胜规则 1.7 或更高版本
--
.步骤
. 运行切换模拟以检查是否需要导入证书。
+
.. 查看决胜局监控状态：
`monitor show -status`
+
.示例
[%collapsible]
=====
[listing]
----
NetApp MetroCluster Tiebreaker :> monitor show -status
MetroCluster: A700
    Disaster: false
    Monitor State: Normal
    Observer Mode: false
    Silent Period: 5
    Override Vetoes: false
    Cluster: ClusterA_siteA(UUID:713e5ab2-b4e8-11f0-91aa-00a098ef36a2)
        Reachable: true
        Intersite Connectivity Available: true
            Node: node_A1(UUID:9f6cecbf-b4e4-11f0-9d0f-00a098ef36a2)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
            Node: node_A2(UUID:2719bb56-b4e7-11f0-996c-00a09897caa3)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
    Cluster: ClusterB_siteB(UUID:72839591-b4e8-11f0-b688-00a09897cb73)
        Reachable: true
        Intersite Connectivity Available: true
            Node: node_B1(UUID:abfeab89-b4e4-11f0-a077-00a09897cb73)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
            Node: node_B2(UUID:31e395bf-b4e7-11f0-bf99-00a09897cb2f)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
----
=====
.. 触发切换模拟：
+
`monitor switchover-simulate -monitor-name <monitor_name> -cluster <cluster_name>`

+
如果需要将证书导入 JVM，该命令将返回以下输出：

+
[listing]
----
Failed to trigger Switchover Simulation. Please check Metrocluster Tiebreaker logs for further information or contact NetApp support.
----


. 对需要导入的每个证书（SSL 服务器证书、中间证书或根证书）运行以下命令。
+
`/opt/netapp/java/bin/keytool -import -trustcacerts -file <certificate_file_name> -keystore "/opt/netapp/java/lib/security/cacerts" -alias <certificate>`

+
** 这 `<certificate_file_name>` value 指定要导入的证书的文件名。
** 这 `-alias <certificate>` value 指定将证书导入 JVM 后要存储的名称。
+
以下示例展示了如何导入文件名为“root certificate”的根证书。 `root.crt` 以及文件名为 `ssl_cert.crt`：

+
[listing]
----
/opt/netapp/java/bin/keytool -import -trustcacerts -file root.crt -keystore "/opt/netapp/java/lib/security/cacerts" -alias root

/opt/netapp/java/bin/keytool -import -trustcacerts -file ssl_cert.crt -keystore "/opt/netapp/java/lib/security/cacerts" -alias ssl_cert
----


. 重启决胜程序软件：
+
`systemctl restart netapp-metrocluster-tiebreaker-software`

. 再次执行切换模拟检查：
+
.. 查看决胜局监控状态：
`monitor show -status`
+
.示例
[%collapsible]
=====
[listing]
----
NetApp MetroCluster Tiebreaker :> monitor show -status
MetroCluster: A700
    Disaster: false
    Monitor State: Normal
    Observer Mode: false
    Silent Period: 5
    Override Vetoes: false
    Cluster: ClusterA_siteA(UUID:713e5ab2-b4e8-11f0-91aa-00a098ef36a2)
        Reachable: true
        Intersite Connectivity Available: true
            Node: node_A1(UUID:9f6cecbf-b4e4-11f0-9d0f-00a098ef36a2)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
            Node: node_A2(UUID:2719bb56-b4e7-11f0-996c-00a09897caa3)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
    Cluster: ClusterB_siteB(UUID:72839591-b4e8-11f0-b688-00a09897cb73)
        Reachable: true
        Intersite Connectivity Available: true
            Node: node_B1(UUID:abfeab89-b4e4-11f0-a077-00a09897cb73)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
            Node: node_B2(UUID:31e395bf-b4e7-11f0-bf99-00a09897cb2f)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
----
=====
.. 触发切换模拟：
+
`monitor switchover-simulate -monitor-name <monitor_name> -cluster <cluster_name>`

+
[listing]
----
Successfully triggered Switchover Simulation. Please check the status of the Switchover Simulation on the ONTAP cluster using command "metrocluster operation history show"
----




--
.平局决胜 1.6 或 1.6P1
--
.步骤
. 从ONTAP导入所有证书。对需要导入的每个证书（SSL 服务器证书、中间证书或根证书）运行以下命令。
+
`/opt/netapp/java/bin/keytool -import -trustcacerts -file <certificate_file_name> -keystore "/opt/netapp/java/lib/security/cacerts" -alias <certificate>`

+
** 这 `<certificate_file_name>` value 指定要导入的证书的文件名。
** 这 `-alias <certificate>` value 指定将证书导入 JVM 后要存储的名称。
+
以下示例展示了如何导入文件名为“root certificate”的根证书。 `root.crt` 以及文件名为 `ssl_cert.crt`：

+
[listing]
----
/opt/netapp/java/bin/keytool -import -trustcacerts -file root.crt -keystore "/opt/netapp/java/lib/security/cacerts" -alias root

/opt/netapp/java/bin/keytool -import -trustcacerts -file ssl_cert.crt -keystore "/opt/netapp/java/lib/security/cacerts" -alias ssl_cert
----


. 重启决胜程序软件：
+
`systemctl restart netapp-metrocluster-tiebreaker-software`



--
====


== 用于修改 MetroCluster Tiebreaker 配置的命令

您可以在需要更改设置时修改 MetroCluster 配置。

Tiebreaker CLI monitor modify 命令可与以下任一选项结合使用。您可以使用 monitor show -status 命令确认所做的更改。

[cols="30,70"]
|===


| 选项 | 说明 


 a| 
-monitor-name
 a| 
MetroCluster 配置的名称



 a| 
-enable-monitor
 a| 
启用和禁用对 MetroCluster 配置的监控



 a| 
-silent-period
 a| 
检测到站点故障后， MetroCluster Tiebreaker 软件等待确认站点故障的时间段（以秒为单位）



 a| 
-observer 模式
 a| 
观察模式（ true ）仅提供监控功能，如果发生站点灾难，则不会触发切换。如果发生站点灾难，联机模式（ false ）将触发切换。

* link:concept_overview_of_the_tiebreaker_software.html["Tiebreaker 软件如何检测站点故障"]
* link:concept_risks_and_limitation_of_using_mcc_tiebreaker_in_active_mode.html["在主动模式下使用 MetroCluster Tiebreaker 的风险和限制"]


|===
以下示例将更改配置的静默期限。

[listing]
----

NetApp MetroCluster Tiebreaker :> monitor modify -monitor-name cluster_A -silent-period 15
Successfully modified monitor in NetApp MetroCluster Tiebreaker
software.
----
可以使用 Tiebreaker CLI `debug` 命令更改日志记录模式。

[cols="30,70"]
|===


| 命令 | 说明 


 a| 
调试状态
 a| 
显示调试模式的状态



 a| 
启用调试
 a| 
启用日志记录调试模式



 a| 
禁用调试
 a| 
禁用日志记录的调试模式

|===
在运行Tiebreaker 1.4及更早版本的系统中、使用Tiebreaker CLI `update-mcctb-password` 命令可用于更新用户密码。此命令在Tiebreaker 1.5及更高版本中已弃用。

[cols="30,70"]
|===


| 命令 | 说明 


 a| 
update-mcctb-password
 a| 
已成功更新用户密码

|===


== 删除 MetroCluster 配置

如果您不再需要监控 MetroCluster 配置，则可以删除 Tiebreaker 软件正在监控的 MetroCluster 配置。

. 使用 Tiebreaker CLI `monitor remove` 命令删除 MetroCluster 配置。
+
在以下示例中，从软件中删除了 "`cluster_A` " ：

+
[listing]
----

NetApp MetroCluster Tiebreaker :> monitor remove -monitor-name cluster_A
Successfully removed monitor from NetApp MetroCluster Tiebreaker
software.
----
. 使用 Tiebreaker cli `monitor show -status` 命令确认已正确删除 MetroCluster 配置。
+
[listing]
----

NetApp MetroCluster Tiebreaker :> monitor show -status
----

