---
permalink: tiebreaker/install_tiebreaker_package.html 
sidebar: sidebar 
keywords: install, tiebreaker, software, monitor, capabilities, capability, cluster, storage, environment, snmp, notification, event, node, connectivity, issue, site, disaster, system, install, upgrade, upgrading, software, dependencies, dependency, package, ntp, requirements, requirements for tiebreaker, tiebreaker requirements, mysql, mariadb, autostart, database 
summary: 在主机Linux操作系统上全新安装或升级到Tieb破碎 机1.5、以监控MetroCluster配置。 
---
= 安装或升级到Tieb破碎 机1.5
:allow-uri-read: 


[role="lead"]
在主机Linux操作系统上全新安装或升级到Tieb破碎 机1.5、以监控MetroCluster配置。

.关于此任务
* 存储系统必须运行受支持的ONTAP版本。请参见 link:install_prepare.html#software-requirements["软件要求"] 表以了解更多详细信息。
* 您必须已使用安装OpenJDK `yum install java-x.x.x-openjdk` 命令：Tieber1.5及更高版本支持OpenJDK 17、18或19。
* 您可以使用具有足够管理权限的非root用户身份安装MetroCluster Tieb破碎 镐、以便执行Tieb破碎 镐安装、创建表和用户以及设置用户密码。


.步骤
. 下载MetroCluster Tieb破碎 机软件和MetroCluster_Tieb破碎 机_RPM_GPG密钥。
+

NOTE: 可以从NetApp 支持站点 上下载Tieb破碎 机1.5软件包的同一页面下载MetroCluster_Tieb破碎 机_RPM_GPG密钥。

+
https://mysupport.netapp.com/site/products/all/details/metrocluster-tiebreaker/downloads-tab["MetroCluster Tieb破碎 机(下载)—NetApp 支持站点"^]

. 以 root 用户身份登录到主机。
. 创建非root用户和 `mcctbgrp` 组。
+
.. 创建非root用户并设置密码。
+
以下示例命令将创建一个名为的非root用户 `mcctbuser1`：

+
[listing]
----
[root@mcctb ~]# useradd mcctbuser1
[root@mcctb ~]# passwd mcctbuser1
Changing password for user mcctbuser1.
New password:
Retype new password:
passwd: all authentication tokens updated successfully.
----
.. 创建一个名为的组 `mcctbgrp`：
+
`[root@mcctb ~~]# groupadd mcctbgrp`

.. 将您创建的非root用户添加到 `mcctbgrp` 组。
+
以下命令将添加 `mcctbuser1` 到 `mcctbgrp` 组：

+
`[root@mcctb ~]# usermod -a -G mcctbgrp mcctbuser1`



. 验证RPM文件。
+
从包含RPM密钥的目录运行以下子步骤。

+
.. 下载并导入RPM密钥文件：
+
[listing]
----
[root@mcctb ~]# rpm --import MetroCluster_Tiebreaker_RPM_GPG.key
----
.. 通过检查指纹来验证是否导入了正确的密钥。
+
以下示例显示了正确的密钥指纹：

+
[listing]
----
root@mcctb:~/signing/mcctb-rpms# gpg --show-keys --with-fingerprint MetroCluster_Tiebreaker_RPM_GPG.key
pub   rsa3072 2022-11-17 [SCEA] [expires: 2025-11-16]
      65AC 1562 E28A 1497 7BBD  7251 2855 EB02 3E77 FAE5
uid                      MCCTB-RPM (mcctb RPM production signing) <mcctb-rpm@netapp.com>
----
.. 验证签名： `rpm --checksig NetApp-MetroCluster-Tiebreaker-Software-1.5-1.x86_64.rpm`
+
[listing]
----
NetApp-MetroCluster-Tiebreaker-Software-1.5-1.x86_64.rpm: digests OK
----
+

NOTE: 只有在成功验证签名后、才能继续安装。



. 【安装- Tiebreaker】安装或升级Tiebreaker软件：
+

NOTE: 只有在从Tiebreaker 1.4版升级时、才能升级到Tiebreaker 1.5版。不支持从早期版本升级到Tiebreaker 1.5。

+
根据您是执行新安装还是升级现有安装、选择正确的操作步骤。

+
[role="tabbed-block"]
====
.执行新安装
--
.. 检索并记录Java的绝对路径：
+
[listing]
----
[root@mcctb ~]# readlink -f /usr/bin/java
/usr/lib/jvm/java-19-openjdk-19.0.0.0.36-2.rolling.el8.x86_64/bin/java
----
.. 运行以下命令：
`rpm -ivh NetApp-MetroCluster-Tiebreaker-Software-1.5-1.x86_64.rpm`
+
成功安装时，系统将显示以下输出：

+

NOTE: 在安装期间出现提示时、请提供您先前创建并分配给的非root用户 `mcctbgrp` 组。

+
[listing]
----
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:NetApp-MetroCluster-Tiebreaker-So################################# [100%]
Enter the absolute path for Java : /usr/lib/jvm/java-19-openjdk-19.0.0.0.36-2.rolling.el8.x86_64/bin/java
Verifying if Java exists...
Found Java. Proceeding with the installation.
Enter host user account to use for the installation:
mcctbuser1
User account mcctbuser1 found. Proceeding with the installation
Enter database user name:
root
Please enter database password for root
Enter password:
Sealed          false
Do you wish to auto unseal vault(y/n)?y
Enter the key1:
Enter the key2:
Enter the key3:
Success! Uploaded policy: mcctb-policy
Error enabling approle auth: Error making API request.
URL: POST http://127.0.0.1:8200/v1/sys/auth/approle
Code: 400. Errors:
* path is already in use at approle/
Success! Enabled the kv secrets engine at: mcctb/
Success! Data written to: auth/approle/role/mcctb-app
Password updated successfully in the vault.
Synchronizing state of netapp-metrocluster-tiebreaker-software.service with SysV service script with /usr/lib/systemd/systemd-sysv-install.
Executing: /usr/lib/systemd/systemd-sysv-install enable netapp-metrocluster-tiebreaker-software
Created symlink /etc/systemd/system/multi-user.target.wants/netapp-metrocluster-tiebreaker-software.service → /etc/systemd/system/netapp-metrocluster-tiebreaker-software.service.
Attempting to start NetApp MetroCluster Tiebreaker software services
Started NetApp MetroCluster Tiebreaker software services
Successfully installed NetApp MetroCluster Tiebreaker software version 1.5.

----


--
.升级现有安装
--
.. 验证是否已安装受支持的OpenJDK版本、以及是否为主机上的当前Java版本。
+

NOTE: 要升级到Tiebreaker 1.5、您必须安装OpenJDK 17、18或19版。

+
[listing]
----
[root@mcctb ~]# readlink -f /usr/bin/java
/usr/lib/jvm/java-19-openjdk-19.0.0.0.36-2.rolling.el8.x86_64/bin/java
----
.. 验证存储服务是否已取消密封并正在运行： `vault status`
+
[listing]
----
[root@mcctb ~]# vault status
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    5
Threshold       3
Version         1.12.2
Build Date      2022-11-23T12:53:46Z
Storage Type    file
Cluster Name    vault
Cluster ID      <cluster_id>
HA Enabled      false
----
.. 升级Tiebreaker软件。
+
[listing]
----
[root@mcctb ~]# rpm -Uvh NetApp-MetroCluster-Tiebreaker-Software-1.5-1.x86_64.rpm
----
+
成功升级后，系统将显示以下输出：

+
[listing]
----

Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:NetApp-MetroCluster-Tiebreaker-So################################# [ 50%]

Enter the absolute path for Java : /usr/lib/jvm/java-19-openjdk-19.0.0.0.36-2.rolling.el8.x86_64/bin/java
Verifying if Java exists...
Found Java. Proceeding with the installation.
Enter host user account to use for the installation:
mcctbuser1
User account mcctbuser1 found. Proceeding with the installation
Sealed          false
Do you wish to auto unseal vault(y/n)?y
Enter the key1:
Enter the key2:
Enter the key3:
Success! Uploaded policy: mcctb-policy
Error enabling approle auth: Error making API request.
URL: POST http://127.0.0.1:8200/v1/sys/auth/approle
Code: 400. Errors:
* path is already in use at approle/
Success! Enabled the kv secrets engine at: mcctb/
Success! Data written to: auth/approle/role/mcctb-app
Enter database user name : root
Please enter database password for root
Enter password:
Password updated successfully in the database.
Password updated successfully in the vault.
Synchronizing state of netapp-metrocluster-tiebreaker-software.service with SysV service script with /usr/lib/systemd/systemd-sysv-install.
Executing: /usr/lib/systemd/systemd-sysv-install enable netapp-metrocluster-tiebreaker-software
Attempting to start NetApp MetroCluster Tiebreaker software services
Started NetApp MetroCluster Tiebreaker software services
Successfully upgraded NetApp MetroCluster Tiebreaker software to version 1.5.
Cleaning up / removing...
   2:NetApp-MetroCluster-Tiebreaker-So################################# [100%]
----


--
====
+

NOTE: 如果输入的 MySQL root 密码不正确， Tiebreaker 软件会指示已成功安装该密码，但会显示 Access Denied 消息。要解决问题描述问题，您必须使用 `rpm -e` 命令卸载 Tiebreaker 软件，然后使用正确的 MySQL root 密码重新安装该软件。

. 通过打开从Tiebreaker主机到每个节点管理LIF和集群管理LIF的SSH连接、检查Tiebreaker与MetroCluster 软件的连接。


.相关信息
https://mysupport.netapp.com/site/["NetApp 支持"^]
