---
permalink: tiebreaker/install_prepare.html 
sidebar: sidebar 
keywords: install, tiebreaker, software, monitor, capabilities, capability, cluster, storage, environment, snmp, notification, event, node, connectivity, issue, site, disaster, system, install, upgrade, upgrading, software, dependencies, dependency, package, ntp, requirements, requirements for tiebreaker, tiebreaker requirements, mysql, mariadb, autostart, database 
summary: Tiebreaker 软件可为集群存储环境提供监控功能。此外，它还会在发生节点连接问题和站点灾难时发送 SNMP 通知。 
---
= 查看要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Tiebreaker 软件可为集群存储环境提供监控功能。此外，它还会在发生节点连接问题和站点灾难时发送 SNMP 通知。

必须安装和配置Tiebreaker软件。



== 软件要求

您必须满足以下软件要求、具体取决于您正在安装的Tieb破碎 机版本。

[cols="1,1,1,2"]
|===


| ONTAP Tieb破碎 机版本 | 支持的ONTAP版本 | 支持的 Linux 版本 | Java/MariaDB要求 


 a| 
1.5
 a| 
ONTAP 9.8及更高版本
 a| 
* Red Hat Enterprise Linux 8.1至8.7

 a| 
对于Red Hat Enterprise Linux 8.1至8.7：

* MariaDB 10.x (使用使用"yum install MariaDB-server.x86_64 "安装的默认版本)
* OpenJDK 17、18或19




 a| 
1.4.
 a| 
ONTAP 9.2及更高版本
 a| 
* Red Hat Enterprise Linux 8.1至8.7
* Red Hat Enterprise Linux 7至7.9
* CentOS 7到7.9 (64位)

 a| 
使用CentOS：

* MariaDB 5.5.52.x/MySQL Server 5.6x
* 4 GB RAM
* 打开JRE 8


对于Red Hat Enterprise Linux 8.1至8.7：

*MariaDB 10.x (使用使用"yum install MariaDB-server.x86_64 "安装的默认版本)
*JRE 8.

|===


== 其他要求

您必须注意以下附加要求：

* Tiebreaker 软件安装在第三个站点上，该软件可以区分交换机间链路（ ISL ）故障（站点间链路关闭时）和站点故障。在本地计算机上安装或升级 Tiebreaker 软件以监控 MetroCluster 配置之前，主机系统必须满足特定要求。
* 要安装MetroCluster Tiebreaker软件和相关软件包、您必须具有"root"权限。
* 每个MetroCluster 配置只能使用一个MetroCluster Tiebreaker监控器、以避免与多个Tiebreaker监控器发生任何冲突。
* 在为Tieb破碎 机软件选择网络时间协议(Network Time Protocol、NTP)源时、必须使用本地NTP源。Tieb破碎 机软件不应使用与Tieb破碎 机软件监控的MetroCluster站点相同的源。


* 磁盘容量： 8 GB
* 防火墙：
+
** 直接访问以设置 AutoSupport 消息
** SSH （端口 22/TCP ）， HTTPS （端口 443/TCP ）和 ping （ ICMP ）



