---
permalink: install-fc/concept_port_assignments_for_systems_using_two_initiator_ports.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, port, assignments, systems, two, initiator, ports 
summary: 您可以使用每个网络结构的一个启动程序端口和每个控制器的两个启动程序端口来配置 FAS8020 ， AFF8020 ， FAS8200 和 AFF A300 系统。 
---
= 使用两个启动程序端口的系统的端口分配
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用每个结构的单个启动器端口和每个控制器的两个启动器端口来配置FAS8200和AFF A300系统。

您可以按照 FibreBridge 7600N 网桥的布线方法，仅使用一个 FC 端口（FC1 或 FC2）。无需使用四个启动器，只需连接两个启动器，并将连接到交换机端口的另外两个启动器留空。

如果手动执行分区，则请遵循使用一个 FC 端口（FC1 或 FC2）的 FibreBridge 7600N 网桥的分区方法。在这种情况下，每个网络结构中的每个区域成员都会添加一个启动器端口，而不是两个。

您可以使用中的操作步骤更改分区或从一个光纤桥6500 N升级到一个光纤桥7500 N link:../maintain/task_replace_a_sle_fc_to_sas_bridge.html#hot_swap_6500n["热插拔 FibreBridge 6500N 网桥和 FibreBridge 7600N 或 7500N 网桥"]。

下表显示了当每个结构使用一个启动器端口并且每个控制器使用两个启动器端口时Brocade FC 交换机的端口分配。

[cols="2a,2a,2a,2a"]
|===
4+| 仅使用一个FC端口(FC1或FC2)的光纤网桥7500N或7600N的配置 


 a| 
* MetroCluster 1 或 DR 组 1*



 a| 
* 组件 *
 a| 
* 端口 *
 a| 
*6505、6510、6520、7840、G620、G630、G610、G710、G720、G730 和 DCX 8510-8*



 a| 
* 连接到 FC 交换机 ...*
 a| 
* 连接到交换机端口 ...*



 a| 
controller_x_1
 a| 
FC-VI 端口 A
 a| 
1.
 a| 
0



 a| 
FC-VI 端口 b
 a| 
2.
 a| 
0



 a| 
FC-VI 端口 c
 a| 
1.
 a| 
1.



 a| 
FC-VI 端口 d
 a| 
2.
 a| 
1.



 a| 
HBA 端口 A
 a| 
1.
 a| 
2.



 a| 
HBA 端口 b
 a| 
2.
 a| 
2.



 a| 
HBA 端口 c
 a| 
-
 a| 
-



 a| 
HBA 端口 d
 a| 
-
 a| 
-



 a| 
堆栈 1
 a| 
bridge_x_1a
 a| 
1.
 a| 
8.



 a| 
bridge_x_1b
 a| 
2.
 a| 
8.



 a| 
堆栈 y
 a| 
bridge_x_ya
 a| 
1.
 a| 
11.



 a| 
bridge_x_YB
 a| 
2.
 a| 
11.

|===