---
permalink: install-fc/concept_port_assignments_for_systems_using_two_initiator_ports.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, port, assignments, systems, two, initiator, ports 
summary: 您可以使用每个网络结构的一个启动程序端口和每个控制器的两个启动程序端口来配置 FAS8020 ， AFF8020 ， FAS8200 和 AFF A300 系统。 
---
= 使用两个启动程序端口的系统的端口分配
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用每个网络结构的一个启动程序端口和每个控制器的两个启动程序端口来配置 FAS8020 ， AFF8020 ， FAS8200 和 AFF A300 系统。

您只能使用一个 FC 端口（ FC1 或 FC2 ）对 FibreBridge 6500N 网桥或 FibreBridge 7500N 或 7600N 网桥进行布线。请仅连接两个启动程序，而不使用四个启动程序，并将连接到交换机端口的另外两个启动程序留空。

您必须为 FibreBridge 6500N 网桥的配置应用正确的 RCF 文件。

如果手动执行分区，则按照使用一个 FC 端口（ FC1 或 FC2 ）的 FibreBridge 6500N 或 FibreBridge 7500N 或 7600N 网桥所使用的分区进行操作。在这种情况下，每个网络结构的每个分区成员都会添加一个启动程序端口，而不是两个。

您可以从中使用 FibreBridge 6500N 网桥热插拔操作步骤 _FibreBridge 6500N 网桥并使用 FibreBridge 7500N 或 7600N 网桥 _ 更改分区或从 FibreBridge 6500 升级到 FibreBridge 7500 https://docs.netapp.com/us-en/ontap-metrocluster/maintain/index.html["维护 MetroCluster 组件"]。

下表显示了使用 ONTAP 9.1 及更高版本时 FC 交换机的端口分配。

|===


4+| 仅使用一个 FC 端口（ FC1 或 FC2 ）的 FibreBridge 6500N 网桥或 FibreBridge 7500N 或 7600N 配置 


4+| * MetroCluster 1 或 DR 组 1* 


.2+| * 组件 * .2+| * 端口 * 2+| * Brocade 交换机型号 6505 ， 6510 ， 6520 ， 7840 ， G620 ， G610 和 DCX 8510-8* 


| * 连接到 FC 交换机 ...* | * 连接到交换机端口 ...* 


.8+| controller_x_1  a| 
FC-VI 端口 A
 a| 
1.
 a| 
0



 a| 
FC-VI 端口 b
 a| 
2.
 a| 
0



 a| 
FC-VI 端口 c
 a| 
1.
 a| 
1.



 a| 
FC-VI 端口 d
 a| 
2.
 a| 
1.



 a| 
HBA 端口 A
 a| 
1.
 a| 
2.



 a| 
HBA 端口 b
 a| 
2.
 a| 
2.



 a| 
HBA 端口 c
 a| 
-
 a| 
-



 a| 
HBA 端口 d
 a| 
-
 a| 
-



 a| 
堆栈 1
 a| 
bridge_x_1a
 a| 
1.
 a| 
8.



 a| 
bridge_x_1b
 a| 
2.
 a| 
8.



 a| 
堆栈 y
 a| 
bridge_x_ya
 a| 
1.
 a| 
11.



 a| 
bridge_x_YB
 a| 
2.
 a| 
11.

|===
下表显示了使用 ONTAP 9.0 时 FC 交换机的端口分配。

|===


4+| * MetroCluster 双节点配置 * 


.2+| * 组件 * .2+| * 端口 * 2+| * Brocade 6505 ， 6510 或 DCX 8510-8* 


| * FC_switch_x_1* | * FC_switch_x_2* 


 a| 
controller_x_1
 a| 
FC-VI 端口 A
 a| 
0
 a| 
-



 a| 
FC-VI 端口 b
 a| 
-
 a| 
0



 a| 
HBA 端口 A
 a| 
1.
 a| 
-



 a| 
HBA 端口 b
 a| 
-
 a| 
1.



 a| 
HBA 端口 c
 a| 
2.
 a| 
-



 a| 
HBA 端口 d
 a| 
-
 a| 
2.

|===