---
permalink: install-fc/concept_considerations_for_implementing_a_mcc_configuration_with_disks_and_array_luns.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, considerations, configuration, disks, array, luns 
summary: 在规划用于磁盘和阵列 LUN 的 MetroCluster 配置时，必须考虑各种因素，例如设置存储访问权限的顺序，根聚合位置以及 FC 启动程序端口，交换机和 FC-SAS 网桥的使用情况。 
---
= 使用磁盘和阵列 LUN 实施 MetroCluster 配置时的注意事项
:icons: font
:imagesdir: ../media/


[role="lead"]
在规划用于磁盘和阵列 LUN 的 MetroCluster 配置时，必须考虑各种因素，例如设置存储访问权限的顺序，根聚合位置以及 FC 启动程序端口，交换机和 FC-SAS 网桥的使用情况。

在规划配置时，请考虑下表中的信息：

|===
| 注意事项 | 准则 


 a| 
设置存储访问权限的顺序
 a| 
您可以先设置对磁盘或阵列 LUN 的访问权限。您必须完成此类型存储的所有设置，并验证是否已正确设置，然后再设置其他类型的存储。



 a| 
根聚合的位置
 a| 
* 如果要设置同时包含磁盘和阵列 LUN 的 _new_ MetroCluster 部署，则必须在原生磁盘上创建根聚合。
+
执行此操作时，请确保在每个站点上至少设置了一个磁盘架（具有 24 个磁盘驱动器）。

* 如果要将原生磁盘添加到 MetroCluster 使用阵列 LUN 的 _exist_LUN 配置中，则根聚合可以保留在阵列 LUN 上。




 a| 
使用交换机和 FC-SAS 网桥
 a| 
在四节点配置和双节点光纤连接配置中，需要使用 FC-SAS 网桥才能通过交换机将 ONTAP 系统连接到磁盘架。

您必须使用相同的交换机连接到存储阵列和 FC-SAS 网桥。



 a| 
使用 FC 启动程序端口
 a| 
用于连接到 FC-SAS 网桥的启动程序端口必须与用于连接到交换机的端口不同，这些端口会连接到存储阵列。要将 ONTAP 系统同时连接到磁盘和阵列 LUN ，至少需要八个启动程序端口。

|===
* 相关信息 *

link:task_fcsw_configure_the_cisco_or_brocade_fc_switches_manually.html["手动配置 Cisco 或 Brocade FC 交换机"]

link:concept_example_of_switch_zoning_in_a_four_node_mcc_configuration_with_array_luns.html["使用阵列 LUN 的四节点 MetroCluster 配置中的交换机分区示例"]

link:concept_example_of_switch_zoning_in_an_eight_node_mcc_configuration_with_array_luns.html["使用阵列 LUN 的八节点 MetroCluster 配置中的交换机分区示例"]

link:task_fb_new_install.html["安装 FC-SAS 网桥和 SAS 磁盘架"]

https://hwu.netapp.com["NetApp Hardware Universe"]
