---
permalink: install-fc/task_reset_the_cisco_fc_switch_to_factory_defaults.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, reset, cisco, fc, switch, factory, defaults 
summary: 在安装新软件版本和 RCF 之前，必须擦除 Cisco 交换机配置并执行基本配置。 
---
= 将 Cisco FC 交换机重置为出厂默认值
:icons: font
:imagesdir: ../media/


[role="lead"]
在安装新软件版本和 RCF 之前，必须擦除 Cisco 交换机配置并执行基本配置。

您必须对 MetroCluster 网络结构配置中的每个 FC 交换机重复这些步骤。


NOTE: 显示的输出适用于 Cisco IP 交换机；但是，这些步骤也适用于 Cisco FC 交换机。

.步骤
. 将交换机重置为出厂默认设置：
+
.. 擦除现有配置： + ` * 写入擦除 *`
.. 重新加载交换机软件： + ` * reload *`
+
系统将重新启动并进入配置向导。在启动期间，如果您收到提示 Abort Auto Provisioning and continue with normal setup ？（ yes/no ） [n] ，则应回答 ` * yes*` 以继续。

.. 在配置向导中，输入基本交换机设置：
+
*** 管理员密码
*** 交换机名称
*** 带外管理配置
*** 默认网关
*** SSH 服务（远程支持代理）完成配置向导后，交换机将重新启动。


.. 出现提示时，输入用户名和密码以登录到交换机。
+
以下示例显示了登录到交换机时的提示和系统响应。尖括号（` *<<*` ）显示信息的输入位置。

+
[listing]
----
---- System Admin Account Setup ----
Do you want to enforce secure password standard (yes/no) [y]:y  **<<<**

    Enter the password for "admin": password  **<<<**
  Confirm the password for "admin": password  **<<<**
         ---- Basic System Configuration Dialog VDC: 1 ----

This setup utility will guide you through the basic configuration of
the system. Setup configures only enough connectivity for management
of the system.

Please register Cisco Nexus3000 Family devices promptly with your
supplier. Failure to register may affect response times for initial
service calls. Nexus3000 devices must be registered to receive
entitled support services.

Press Enter at anytime to skip a dialog. Use ctrl-c at anytime
to skip the remaining dialogs.
----
.. 在下一组提示中输入基本信息，包括交换机名称，管理地址和网关，然后为 SSH 密钥输入 ` * rs*` ，如示例所示：
+
[listing]
----
Would you like to enter the basic configuration dialog (yes/no): yes
  Create another login account (yes/no) [n]:
  Configure read-only SNMP community string (yes/no) [n]:
  Configure read-write SNMP community string (yes/no) [n]:
  Enter the switch name : switch-name **<<<**
  Continue with Out-of-band (mgmt0) management configuration? (yes/no) [y]:
    Mgmt0 IPv4 address : management-IP-address  **<<<**
    Mgmt0 IPv4 netmask : management-IP-netmask  **<<<**
  Configure the default gateway? (yes/no) [y]: y **<<<**
    IPv4 address of the default gateway : gateway-IP-address  **<<<**
  Configure advanced IP options? (yes/no) [n]:
  Enable the telnet service? (yes/no) [n]:
  Enable the ssh service? (yes/no) [y]: y  **<<<**
    Type of ssh key you would like to generate (dsa/rsa) [rsa]: rsa **<<<**
    Number of rsa key bits <1024-2048> [1024]:
  Configure the ntp server? (yes/no) [n]:
  Configure default interface layer (L3/L2) [L2]:
  Configure default switchport interface state (shut/noshut) [noshut]: shut **<<<**
  Configure CoPP system profile (strict/moderate/lenient/dense) [strict]:
----
+
最后一组提示符用于完成配置：

+
[listing]
----
The following configuration will be applied:
  password strength-check
  switchname IP_switch_A_1
vrf context management
ip route 0.0.0.0/0 10.10.99.1
exit
  no feature telnet
  ssh key rsa 1024 force
  feature ssh
  system default switchport
  system default switchport shutdown
  copp profile strict
interface mgmt0
ip address 10.10.99.10 255.255.255.0
no shutdown

Would you like to edit the configuration? (yes/no) [n]:

Use this configuration and save it? (yes/no) [y]:
2017 Jun 13 21:24:43 A1 %$ VDC-1 %$ %COPP-2-COPP_POLICY: Control-Plane is protected with policy copp-system-p-policy-strict.

[########################################] 100%
Copy complete.

User Access Verification
IP_switch_A_1 login: admin
Password:
Cisco Nexus Operating System (NX-OS) Software
.
.
.
IP_switch_A_1#
----


. 保存配置：
+
[listing]
----
IP_switch_A_1# copy running-config startup-config
----
. 重新启动交换机并等待交换机重新加载：
+
[listing]
----
IP_switch_A_1# reload
----
. 对 MetroCluster 网络结构配置中的其他三台交换机重复上述步骤。

