---
permalink: install-fc/task_verify_the_ha_state_of_components_is_mcc_or_mcc_2n_in_maintenance_mode.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, verify, ha, state, components, maintenance, mode 
summary: 在 MetroCluster 配置中配置存储系统时，必须确保控制器模块和机箱组件的高可用性状态为 mcc 或 mcc-2n ，以便这些组件可以正常启动。 
---
= 在维护模式下验证和配置组件的 HA 状态
:icons: font
:imagesdir: ../media/


[role="lead"]
在 MetroCluster 配置中配置存储系统时，您必须确保控制器模块和机箱组件的高可用性（ HA ）状态为 "mcc" 或 "mcc-2n" ，以便这些组件可以正常启动。

系统必须处于维护模式。

从工厂收到的系统不需要执行此任务。

.步骤
. 在维护模式下，显示控制器模块和机箱的 HA 状态：
+
`ha-config show`

+
正确的 HA 状态取决于您的 MetroCluster 配置。

+
|===


| MetroCluster 配置中的控制器数量 | 所有组件的 HA 状态应为 ... 


 a| 
八节点或四节点 MetroCluster FC 配置
 a| 
MCC



 a| 
双节点 MetroCluster FC 配置
 a| 
MCC-2n



 a| 
MetroCluster IP 配置
 a| 
mccip

|===
. 如果显示的控制器系统状态不正确，请设置控制器模块的 HA 状态：
+
|===


| MetroCluster 配置中的控制器数量 | 命令 


 a| 
八节点或四节点 MetroCluster FC 配置
 a| 
`ha-config modify controller mcc`



 a| 
双节点 MetroCluster FC 配置
 a| 
`ha-config modify controller mcc-2n`



 a| 
MetroCluster IP 配置
 a| 
`ha-config modify controller mccip`

|===
. 如果显示的机箱系统状态不正确，请设置机箱的 HA 状态：
+
|===


| MetroCluster 配置中的控制器数量 | 命令 


 a| 
八节点或四节点 MetroCluster FC 配置
 a| 
`ha-config modify chassis mcc`



 a| 
双节点 MetroCluster FC 配置
 a| 
`ha-config modify chassis mcc-2n`



 a| 
MetroCluster IP 配置
 a| 
`ha-config modify chassis mccip`

|===
. 将节点启动至 ONTAP ：
+
`boot_ontap`

. 对 MetroCluster 配置中的每个节点重复上述步骤。

