---
permalink: install-fc/task_configure_ontap_on_a_system_that_uses_only_array_luns.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, array luns, ontap 
summary: 如果要配置 ONTAP 以与阵列 LUN 结合使用，则必须配置根聚合和根卷，为诊断和恢复操作预留空间以及设置集群。 
---
= 在仅使用阵列 LUN 的系统上配置 ONTAP
:icons: font
:imagesdir: ../media/


[role="lead"]
如果要配置 ONTAP 以与阵列 LUN 结合使用，则必须配置根聚合和根卷，为诊断和恢复操作预留空间以及设置集群。

* ONTAP 系统必须连接到存储阵列。
* 存储阵列管理员必须已创建 LUN 并将其提供给 ONTAP 。
* 存储阵列管理员必须已配置 LUN 安全性。


您必须配置要与阵列 LUN 结合使用的每个节点。如果节点位于 HA 对中，则必须先在一个节点上完成配置过程，然后再在配对节点上继续进行配置。

.步骤
. 打开主节点的电源，并在控制台上看到以下消息时按 Ctrl-C 中断启动过程：按 CTRL-C 可查看特殊启动菜单。
. 在启动菜单上选择选项 4 （ Clean configuration and initialize all disks ）。
+
此时将显示可供 ONTAP 使用的阵列 LUN 的列表。此外，还指定了创建根卷所需的阵列 LUN 大小。创建根卷所需的大小因 ONTAP 系统而异。

+
** 如果先前未分配任何阵列 LUN ，则 ONTAP 会检测并显示可用的阵列 LUN ，如以下示例所示：
+
[listing]
----
mcc8040-ams1::> disk show  NET-1.6 -instance
                  Disk: NET-1.6
        Container Type: aggregate
            Owner/Home: mcc8040-ams1-01 / mcc8040-ams1-01
               DR Home: -
    Stack ID/Shelf/Bay: -  / -  / -
                   LUN: 0
                 Array: NETAPP_INF_1
                Vendor: NETAPP
                 Model: INF-01-00
         Serial Number: 60080E50004317B4000003B158E35974
                   UID: 60080E50:004317B4:000003B1:58E35974:00000000:00000000:00000000:00000000:00000000:00000000
                   BPS: 512
         Physical Size: 87.50GB
              Position: data
Checksum Compatibility: block
             Aggregate: eseries
                  Plex: plex0
Paths:
                                LUN  Initiator Side        Target Side                                                        Link
Controller         Initiator     ID  Switch Port           Switch Port           Acc Use  Target Port                TPGN    Speed      I/O KB/s          IOPS
------------------ ---------  -----  --------------------  --------------------  --- ---  -----------------------  ------  -------  ------------  ------------
mcc8040-ams1-01    2c             0  mccb6505-ams1:16      mccb6505-ams1:18      AO  INU  20330080e54317b4              1   4 Gb/S             0             0
mcc8040-ams1-01    2a             0  mccb6505-ams1:17      mccb6505-ams1:19      ANO RDY  20320080e54317b4              0   4 Gb/S             0             0

Errors:
-
----
** 如果先前已通过维护模式分配阵列 LUN ，则这些阵列 LUN 会在可用阵列 LUN 列表中标记为 local 或 partner ，具体取决于这些阵列 LUN 是从安装 ONTAP 的节点中选择的，还是从其 HA 配对节点中选择的：
+
在此示例中，索引编号为 3 和 6 的阵列 LUN 将标记为 local ，因为它们以前是从此特定节点分配的：

+
[listing]
----

**********************************************************************
* No disks are owned by this node, but array LUNs are assigned.      *
* You can use the following information to verify connectivity from  *
* HBAs to switch ports.  If the connectivity of HBAs to switch ports *
* does not match your expectations, configure your SAN and rescan.   *
* You can rescan by entering 'r' at the prompt for selecting         *
* array LUNs below.

**********************************************************************
             HBA  HBA WWPN           Switch port      Switch port WWPN
              ---  --------           -----------      ----------------
              0e 500a098001baf8e0  vgbr6510s203:25      20190027f88948dd
              0f 500a098101baf8e0 vgci9710s202:1-17      2011547feeead680
              0g 500a098201baf8e0  vgbr6510s203:27      201b0027f88948dd
              0h 500a098301baf8e0 vgci9710s202:1-18      2012547feeead680


No native disks were detected, but array LUNs were detected.
You will need to select an array LUN to be used to create the root aggregate and root volume.

The array LUNs visible to the system are listed below.  Select one array LUN to be used to
create the root aggregate and root volume.  **The root volume requires 350.0 GB of space.**

 Warning: The contents of the array LUN you select will be erased by ONTAP prior to their use.

Index  Array LUN Name           Model   Vendor    Size    Owner   Checksum  Serial Number
-----  -----------------------  ------  ------  --------  ------  --------  ------------------------
   0   vgci9710s202:2-24.0L19   RAID5   DGC     217.3 GB          Block     6006016083402B0048E576D7
   1   vgbr6510s203:30.126L20   RAID5   DGC     217.3 GB          Block     6006016083402B0049E576D7
   2   vgci9710s202:2-24.0L21   RAID5   DGC     217.3 GB          Block     6006016083402B004AE576D7
   3   vgbr6510s203:30.126L22   RAID5   DGC     405.4 GB  local   Block     6006016083402B004BE576D7
   4   vgci9710s202:2-24.0L23   RAID5   DGC     217.3 GB          Block     6006016083402B004CE576D7
   5   vgbr6510s203:30.126L24   RAID5   DGC     217.3 GB          Block     6006016083402B004DE576D7
   6   vgbr6510s203:30.126L25   RAID5   DGC     423.5 GB  local   Block     6006016083402B003CF93694
   7   vgci9710s202:2-24.0L26   RAID5   DGC     423.5 GB          Block     6006016083402B003DF93694
----


. 选择与要分配为根卷的阵列 LUN 对应的索引编号。
+
阵列 LUN 的大小必须足以创建根卷。

+
为创建根卷而选择的阵列 LUN 将标记为 local （ root ）。

+
在以下示例中，索引编号为 3 的阵列 LUN 会标记为用于创建根卷：

+
[listing]
----

The root volume will be created on switch 0:5.183L33.

**ONTAP requires that 11.0 GB of space be reserved for use in diagnostic and recovery
operations.**  Select one array LUN to be used as spare for diagnostic and recovery operations.

Index Array LUN Name    Model       Vendor    Size   Owner           Checksum  Serial Number
----- ----------------- ----------  ------  -------- --------------  --------  ------------------------
   0  switch0:5.183L1   SYMMETRIX   EMC     266.1 GB                 Block     600604803436313734316631
   1  switch0:5.183L3   SYMMETRIX   EMC     266.1 GB                 Block     600604803436316333353837
   2  switch0:5.183L31  SYMMETRIX   EMC     266.1 GB                 Block     600604803436313237643666
   3  switch0:5.183L33  SYMMETRIX   EMC     658.3 GB local  (root)   Block     600604803436316263613066
   4  switch0:7.183L0   SYMMETRIX   EMC     173.6 GB                 Block     600604803436313261356235
   5  switch0:7.183L2   SYMMETRIX   EMC     173.6 GB                 Block     600604803436313438396431
   6  switch0:7.183L4   SYMMETRIX   EMC     658.3 GB                 Block     600604803436313161663031
   7  switch0:7.183L30  SYMMETRIX   EMC     173.6 GB                 Block     600604803436316538353834
   8  switch0:7.183L32  SYMMETRIX   EMC     266.1 GB                 Block     600604803436313237353738
   9  switch0:7.183L34  SYMMETRIX   EMC     658.3 GB                 Block     600604803436313737333662
----
. 选择与要分配以在诊断和恢复选项中使用的阵列 LUN 对应的索引编号。
+
阵列 LUN 的大小必须足以用于诊断和恢复选项。如果需要，您还可以选择多个阵列 LUN ，这些阵列 LUN 的总大小可以大于或等于指定大小。要选择多个条目，必须输入与要为诊断和恢复选项选择的阵列 LUN 对应的所有索引编号的逗号分隔值。

+
以下示例显示了为创建根卷以及为诊断和恢复选项选择的阵列 LUN 的列表：

+
[listing]
----

Here is a list of the selected array LUNs
Index Array LUN Name     Model      Vendor    Size    Owner          Checksum  Serial Number
----- -----------------  ---------  ------  --------  -------------  --------  ------------------------
   2  switch0:5.183L31   SYMMETRIX  EMC     266.1 GB  local          Block     600604803436313237643666
   3  switch0:5.183L33   SYMMETRIX  EMC     658.3 GB  local   (root) Block     600604803436316263613066
   4  switch0:7.183L0    SYMMETRIX  EMC     173.6 GB  local          Block     600604803436313261356235
   5  switch0:7.183L2    SYMMETRIX  EMC     173.6 GB  local          Block     600604803436313438396431
Do you want to continue (yes|no)?
----
+

NOTE: 选择 "`no` " 将清除 LUN 选择。

. 在系统提示时输入 ` * y*` 继续安装过程。
+
此时将创建根聚合和根卷，其余安装过程将继续进行。

. 输入所需的详细信息以创建节点管理接口。
+
以下示例显示了节点管理接口屏幕，其中包含一条消息，用于确认创建节点管理接口：

+
[listing]
----
Welcome to node setup.

You can enter the following commands at any time:
  "help" or "?" - if you want to have a question clarified,
  "back" - if you want to change previously answered questions, and
  "exit" or "quit" - if you want to quit the setup wizard.
     Any changes you made before quitting will be saved.

To accept a default or omit a question, do not enter a value.

Enter the node management interface port [e0M]:
Enter the node management interface IP address: 192.0.2.66

Enter the node management interface netmask: 255.255.255.192
Enter the node management interface default gateway: 192.0.2.7
A node management interface on port e0M with IP address 192.0.2.66 has been created.

This node has its management address assigned and is ready for cluster setup.
----


在要与阵列 LUN 结合使用的所有节点上配置 ONTAP 后，您应完成集群设置过程。

https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-ssg/home.html["软件设置"]

* 相关信息 *

https://docs.netapp.com/ontap-9/topic/com.netapp.doc.vs-irrg/home.html["FlexArray 虚拟化安装要求和参考"]
