---
permalink: install-fc/task_fmc_mcc_transition_ensure_isls_are_in_the_same_port_group_and_configure_zon.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, ensure, port, group, configure, zoning 
summary: 您必须确保交换机间链路（ ISL ）位于同一端口组中，并为 MetroCluster 配置配置配置分区以成功共享交换机网络结构。 
---
= 确保 ISL 位于同一端口组中并配置分区
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须确保交换机间链路（ ISL ）位于同一端口组中，并为 MetroCluster 配置配置配置分区以成功共享交换机网络结构。

.步骤
. 如果 ISL 不在同一端口组中，请将其中一个 ISL 端口移至与另一个 ISL 端口相同的端口组。
+
您可以使用除 32 到 45 之外的任何可用端口，这些端口将由新的 MetroCluster 配置使用。建议的 ISL 端口为 46 和 47 。

. 按照在 Brocade FC 交换机上配置分区一节中的步骤启用中继和 QoS 分区。
+
xref:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.adoc[在 Brocade FC 交换机上配置分区]

+
共享网络结构时的端口号与一节中显示的端口号不同。共享时，请使用端口 46 和 47 作为 ISL 端口。如果移动了 ISL 端口，则需要使用在 Brocade FC 交换机上配置 E 端口（ ISL 端口）一节中的操作步骤来配置这些端口。

+
xref:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.adoc[在 Brocade FC 交换机上配置 E 端口（ ISL 端口）]

. 按照在 Brocade 交换机上配置非 E 端口一节中的步骤配置非 E 端口。
+
xref:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.adoc[在 Brocade 交换机上配置非 E 端口]

. 请勿删除后端交换机（对于 7- 模式网络结构 MetroCluster ）中已存在的分区或分区集，但步骤 3 中的流量隔离（ TI ）分区除外。
. 按照在 Brocade FC 交换机上配置 E 端口（ ISL 端口）一节中的步骤，将新 MetroCluster 所需的分区添加到现有分区集。
+
xref:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.adoc[在 Brocade FC 交换机上配置 E 端口（ ISL 端口）]

+
以下示例显示了用于创建分区的命令和系统输出：

+
[listing]
----
Brocade-6510-2K0GG:admin> zonecreate "QOSH2_FCVI_1", "2,32; 2,35; 1,32; 1,35"

Brocade-6510-2K0GG:admin> zonecreate "STOR_A_2_47", "2,33; 2,34; 2,36; 2,37; 1,33; 1,34; 1,36; 1,37; 1,47"

Brocade-6510-2K0GG:admin> zonecreate "STOR_B_2_47", "2,33; 2,34; 2,36; 2,37; 1,33; 1,34; 1,36; 1,37; 2,47"


Brocade-6510-2K0GG:admin> cfgadd config_1_FAB2, "QOSH2_FCVI_1; STOR_A_2_47; STOR_B_2_47"

Brocade-6510-2K0GG:admin> cfgenable "config_1_FAB2"
You are about to enable a new zoning configuration.
This action will replace the old zoning configuration with the
current configuration selected. If the update includes changes
to one or more traffic isolation zones, the update may result in
localized disruption to traffic on ports associated with
the traffic isolation zone changes
Do you want to enable 'config_1_FAB2' configuration  (yes, y, no, n): [no] yes

Brocade-6510-2K0GG:admin> cfgsave
You are about to save the Defined zoning configuration. This
action will only save the changes on Defined configuration.
Do you want to save the Defined zoning configuration only?  (yes, y, no, n): [no] yes
Nothing changed: nothing to save, returning ...
Brocade-6510-2K0GG:admin>
----

