---
permalink: install-fc/task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html 
sidebar: sidebar 
keywords: MetroCluster configurations 
summary:  
---
= 手动配置 Brocade FC 交换机
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须配置 MetroCluster 配置中的每个 Brocade 交换机网络结构。

.开始之前
* 您必须拥有可通过 Telnet 或安全 Shell （ SSH ）访问 FC 交换机的 PC 或 UNIX 工作站。
* 您必须使用四个受支持的 Brocade 交换机，这些交换机的型号必须相同，并且具有相同的 Brocade Fabric Operating System （ FOS ）版本和许可。
+
https://mysupport.netapp.com/matrix["NetApp 互操作性表工具"]

+
在 IMT 中，您可以使用 Storage 解决方案字段选择 MetroCluster 解决方案。您可以使用 * 组件资源管理器 * 来选择组件和 ONTAP 版本以细化搜索范围。您可以单击 * 显示结果 * 以显示与此条件匹配的受支持配置列表。

* 四个受支持的 Brocade 交换机必须连接到两个网络结构，每个网络结构各有两个交换机，每个网络结构跨越两个站点。
* 每个存储控制器必须有四个启动程序端口可用于连接到交换机网络结构。每个存储控制器与每个网络结构之间必须连接两个启动程序端口。
+

NOTE: 如果满足以下所有条件，您可以为 FAS8020 ， AFF8020 ， FAS8200 和 AFF A300 系统配置每个控制器两个启动程序端口（每个网络结构一个启动程序端口）：

+
** 可用于连接磁盘存储的 FC 启动程序端口少于四个，并且不能将任何其他端口配置为 FC 启动程序。
** 所有插槽均已使用，无法添加 FC 启动程序卡。




.关于此任务
* 如果链路支持交换机间链路（ ISL ）中继，则应启用该中继。
+
link:concept_tdm_wdm.html["在光纤连接 MetroCluster 配置中使用 TDM/WDM 设备的注意事项"]

* 在一个网络结构中，所有 ISL 都必须具有相同的长度和速度。
+
不同的网络结构可以使用不同的长度。所有网络结构都必须使用相同的速度。

* 不支持 Metro-E 和 TDM （ SONET/SDH ），也不支持任何非 FC 原生帧传输或信号传输。
+
Metro-E 表示以太网帧传输或信号传输在城域范围内以本机方式进行，或者通过某些分时多路复用（ TDM ），多协议标签交换（ MPLS ）或波长分多路复用（ WDM ）进行。

* MetroCluster FC 交换机网络结构不支持 TDM ， FCR （原生 FC 路由）或 FCIP 扩展。
* MetroCluster FC 交换机网络结构中的某些交换机支持加密或压缩，有时也支持这两者。
+
https://mysupport.netapp.com/matrix["NetApp 互操作性表工具（ IMT ）"]

+
在 IMT 中，您可以使用 Storage 解决方案字段选择 MetroCluster 解决方案。您可以使用 * 组件资源管理器 * 来选择组件和 ONTAP 版本以细化搜索范围。您可以单击 * 显示结果 * 以显示与此条件匹配的受支持配置列表。

* 不支持 Brocade 虚拟网络结构（ VF ）功能。
* 支持基于域端口的 FC 分区，但不支持基于全球通用名称（ WWN ）的分区。




== 查看 Brocade 许可证要求

MetroCluster 配置中的交换机需要特定许可证。您必须在所有四台交换机上安装这些许可证。

MetroCluster 配置具有以下 Brocade 许可证要求：

* 建议使用多个 ISL 的系统使用中继许可证。
* Extended Fabric 许可证（适用于 6 公里以上的 ISL 距离）
* 适用于具有多个 ISL 且 ISL 距离超过 6 公里的站点的企业许可证
+
企业许可证包括 Brocade Network Advisor 以及除其他端口许可证之外的所有许可证。



.步骤
. 验证是否已安装许可证：
+
`许可说明`

+
如果您没有这些许可证，应先联系您的销售代表，然后再继续操作。





== 将 Brocade FC 交换机值设置为出厂默认值

您必须将交换机设置为出厂默认值，以确保配置成功。您还必须为每个交换机分配一个唯一的名称。

在此操作步骤的示例中，网络结构由 BrocadeSwitchA 和 BrocadeSwitchB 组成。

.步骤
. 建立控制台连接并登录到一个网络结构中的两个交换机。
. 持久禁用交换机：
+
`sswitchcfgpersistentdisable`

+
这样可确保交换机在重新启动或快速启动后仍保持禁用状态。如果此命令不可用，请使用 `sswitchDisable` 命令。

+
以下示例显示了对 BrocadeSwitchA 执行的命令：

+
[listing]
----
BrocadeSwitchA:admin> switchcfgpersistentdisable
----
+
以下示例显示了对 BrocadeSwitchB 执行的命令：

+
[listing]
----
BrocadeSwitchB:admin> switchcfgpersistentdisable
----
. 设置交换机名称：
+
`sswitchname switch_name`

+
每个交换机都应具有唯一的名称。设置名称后，提示符将相应地发生更改。

+
以下示例显示了对 BrocadeSwitchA 执行的命令：

+
[listing]
----
BrocadeSwitchA:admin> switchname "FC_switch_A_1"
FC_switch_A_1:admin>
----
+
以下示例显示了对 BrocadeSwitchB 执行的命令：

+
[listing]
----
BrocadeSwitchB:admin> switchname "FC_Switch_B_1"
FC_switch_B_1:admin>
----
. 将所有端口设置为其默认值：
+
`portcfgdefault`

+
必须对交换机上的所有端口执行此操作。

+
以下示例显示了对 FC_switch_A_1 执行的命令：

+
[listing]
----
FC_switch_A_1:admin> portcfgdefault 0
FC_switch_A_1:admin> portcfgdefault 1
...
FC_switch_A_1:admin> portcfgdefault 39
----
+
以下示例显示了对 FC_switch_B_1 执行的命令：

+
[listing]
----
FC_switch_B_1:admin> portcfgdefault 0
FC_switch_B_1:admin> portcfgdefault 1
...
FC_switch_B_1:admin> portcfgdefault 39
----
. 清除分区信息：
+
`cfgdisable`

+
`cfgclear`

+
`cfgsave`

+
以下示例显示了对 FC_switch_A_1 执行的命令：

+
[listing]
----
FC_switch_A_1:admin> cfgdisable
FC_switch_A_1:admin> cfgclear
FC_switch_A_1:admin> cfgsave
----
+
以下示例显示了对 FC_switch_B_1 执行的命令：

+
[listing]
----
FC_switch_B_1:admin> cfgdisable
FC_switch_B_1:admin> cfgclear
FC_switch_B_1:admin> cfgsave
----
. 将常规交换机设置设置为默认值：
+
`configdefault`

+
以下示例显示了对 FC_switch_A_1 执行的命令：

+
[listing]
----
FC_switch_A_1:admin> configdefault
----
+
以下示例显示了对 FC_switch_B_1 执行的命令：

+
[listing]
----
FC_switch_B_1:admin> configdefault
----
. 将所有端口设置为非中继模式：
+
`sswitchcfgtrunk 0`

+
以下示例显示了对 FC_switch_A_1 执行的命令：

+
[listing]
----
FC_switch_A_1:admin> switchcfgtrunk 0
----
+
以下示例显示了对 FC_switch_B_1 执行的命令：

+
[listing]
----
FC_switch_B_1:admin> switchcfgtrunk 0
----
. 在 Brocade 6510 交换机上，禁用 Brocade 虚拟网络结构（ VF ）功能：
+
`fosconfig 选项`

+
以下示例显示了对 FC_switch_A_1 执行的命令：

+
[listing]
----
FC_switch_A_1:admin> fosconfig --disable vf
----
+
以下示例显示了对 FC_switch_B_1 执行的命令：

+
[listing]
----
FC_switch_B_1:admin> fosconfig --disable vf
----
. 清除管理域（ AD ）配置：
+
`AD 选项`

+
以下示例显示了对 FC_switch_A_1 执行的命令：

+
[listing]
----
FC_switch_A_1:admin> switch:admin> ad --select AD0
FC_switch_A_1:> defzone --noaccess
FC_switch_A_1:> cfgsave
FC_switch_A_1:> exit
FC_switch_A_1:admin> ad --clear -f
FC_switch_A_1:admin> ad --apply
FC_switch_A_1:admin> ad --save
FC_switch_A_1:admin> exit
----
+
以下示例显示了对 FC_switch_B_1 执行的命令：

+
[listing]
----
FC_switch_B_1:admin> switch:admin> ad --select AD0
FC_switch_A_1:> defzone --noaccess
FC_switch_A_1:> cfgsave
FC_switch_A_1:> exit
FC_switch_B_1:admin> ad --clear -f
FC_switch_B_1:admin> ad --apply
FC_switch_B_1:admin> ad --save
FC_switch_B_1:admin> exit
----
. 重新启动交换机：
+
`re启动`

+
以下示例显示了对 FC_switch_A_1 执行的命令：

+
[listing]
----
FC_switch_A_1:admin> reboot
----
+
以下示例显示了对 FC_switch_B_1 执行的命令：

+
[listing]
----
FC_switch_B_1:admin> reboot
----




== 配置基本交换机设置

您必须为 Brocade 交换机配置基本全局设置，包括域 ID 。

此任务包含必须在两个 MetroCluster 站点的每个交换机上执行的步骤。

在此操作步骤中，您可以为每个交换机设置唯一的域 ID ，如以下示例所示。在此示例中，域 ID 5 和 7 构成 fabric_1 ，域 ID 6 和 8 构成 fabric_2 。

* FC_switch_A_1 已分配给域 ID 5
* FC_switch_A_2 已分配给域 ID 6
* FC_switch_B_1 已分配给域 ID 7
* FC_switch_B_2 已分配给域 ID 8


.步骤
. 进入配置模式：
+
`配置`

. 按照提示继续操作：
+
.. 设置交换机的域 ID 。
.. 按 * 输入 * 以响应提示，直到进入 "RDP 轮询周期 " ，然后将该值设置为 `0` 以禁用轮询。
.. 按 * 输入 * ，直到返回到交换机提示符。
+
[listing]
----
FC_switch_A_1:admin> configure
Fabric parameters = y
Domain_id = 5
.
.

RSCN Transmission Mode [yes, y, no, no: [no] y

End-device RSCN Transmission Mode
 (0 = RSCN with single PID, 1 = RSCN with multiple PIDs, 2 = Fabric RSCN): (0..2) [1]
Domain RSCN To End-device for switch IP address or name change
 (0 = disabled, 1 = enabled): (0..1) [0] 1

.
.
RDP Polling Cycle(hours)[0 = Disable Polling]: (0..24) [1] 0
----


. 如果每个网络结构使用两个或更多 ISL ，则可以配置帧的按顺序交付（ IOD ）或帧的无序交付（ OOD ）。
+

NOTE: 建议使用标准 IOD 设置。只有在必要时，才应配置 OOD 。

+
link:concept_prepare_for_the_mcc_installation.html["在光纤连接 MetroCluster 配置中使用 TDM/WDM 设备的注意事项"]

+
.. 要配置帧的 IOD ，必须对每个交换机网络结构执行以下步骤：
+
... 启用 IOD ：
+
`iodset`

... 将高级性能调整（ APT ）策略设置为 1 ：
+
`aptpolicy 1`

... 禁用动态负载共享（ DLS ）：
+
`dlsreset`

... 使用 `iodshow` ， `aptpolicy` 和 `dlsshow` 命令验证 IOD 设置。
+
例如，对 FC_switch_A_1 执行问题描述命令：

+
[listing]
----
FC_switch_A_1:admin> iodshow
    IOD is set

    FC_switch_A_1:admin> aptpolicy
    Current Policy: 1 0(ap)

    3 0(ap) : Default Policy
    1: Port Based Routing Policy
    3: Exchange Based Routing Policy
         0: AP Shared Link Policy
         1: AP Dedicated Link Policy
    command aptpolicy completed

    FC_switch_A_1:admin> dlsshow
    DLS is not set
----
... 对第二个交换机网络结构重复上述步骤。


.. 要配置帧的 OOD ，必须对每个交换机网络结构执行以下步骤：
+
... 启用 OOD ：
+
`定期重置`

... 将高级性能调整（ APT ）策略设置为 3 ：
+
`aptpolicy 3`

... 禁用动态负载共享（ DLS ）：
+
`dlsreset`

... 验证 OOD 设置：
+
`iodshow`

+
`aptpolicy`

+
`dlsshow`

+
例如，对 FC_switch_A_1 执行问题描述命令：

+
[listing]
----
FC_switch_A_1:admin> iodshow
    IOD is not set

    FC_switch_A_1:admin> aptpolicy
    Current Policy: 3 0(ap)
    3 0(ap) : Default Policy
    1: Port Based Routing Policy
    3: Exchange Based Routing Policy
    0: AP Shared Link Policy
    1: AP Dedicated Link Policy
    command aptpolicy completed


    FC_switch_A_1:admin> dlsshow
    DLS is set by default with current routing policy
----
... 对第二个交换机网络结构重复上述步骤。
+

NOTE: 在控制器模块上配置 ONTAP 时，必须在 MetroCluster 配置中的每个控制器模块上明确配置 OOD 。

+
https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/concept_configure_the_mcc_software_in_ontap.html#configuring-in-order-delivery-or-out-of-order-delivery-of-frames-on-ontap-software["在 ONTAP 软件上配置帧的按顺序交付或无序交付"]





. 验证交换机是否正在使用动态端口许可方法。
+
.. 运行 license 命令：
+
--
`licensePort -show`

[listing]
----
FC_switch_A_1:admin> licenseport -show
24 ports are available in this switch
Full POD license is installed
Dynamic POD method is in use
----

NOTE: Brocade FabricOS 8.0 之前的版本运行以下命令，因为 admin 和 8.0 及更高版本以 root 身份运行这些命令。

--
.. 启用 root 用户。
+
如果 Brocade 已禁用 root 用户，请启用 root 用户，如以下示例所示：

+
[listing]
----
FC_switch_A_1:admin> userconfig --change root -e yes
FC_switch_A_1:admin> rootaccess --set consoleonly
----
.. 运行 license 命令：
+
`licensePort -show`

+
[listing]
----
FC_switch_A_1:root> licenseport -show
24 ports are available in this switch
Full POD license is installed
Dynamic POD method is in use
----
.. 将许可证方法更改为动态：
+
`licenseport -method dynamic`

+

NOTE: 如果未使用动态许可证方法（如果此方法为静态），则必须将此许可证方法更改为动态。如果正在使用动态许可证方法，请跳过此步骤。

+
[listing]
----
FC_switch_A_1:admin> licenseport --method dynamic
The POD method has been changed to dynamic.
Please reboot the switch now for this change to take effect
----


. 启用 T11-FC-ZONE-SERVER-MIB 陷阱，以便为 ONTAP 中的交换机提供成功的运行状况监控：
+
.. 启用 T11-FC-ZONE-SERVER-MIB ：
+
`snmpconfig -set mibCapability -mib_name T11-FC-Zone-Server-MiB -bitmask 0x3f`

.. 启用 T11-FC-ZONE-SERVER-MIB 陷阱：
+
`snmpconfig -enable mibcapability -mib_name sw-mib -trap_name swZoneConfigChangeTrap`

.. 对第二个交换机网络结构重复上述步骤。


. * 可选 * ：如果将社区字符串设置为非公有值，则必须使用指定的社区字符串配置 ONTAP 运行状况监控器：
+
.. 更改现有社区字符串：
+
`snmpconfig -set SNMPv1`

.. 按 * 输入 * ，直到显示 "Community （ ro ）：公有 " 文本。
.. 输入所需的社区字符串。
+
在 FC_switch_A_1 上：

+
[listing]
----
FC_switch_A_1:admin> snmpconfig --set snmpv1
SNMP community and trap recipient configuration:
Community (rw): [Secret C0de]
Trap Recipient's IP address : [0.0.0.0]
Community (rw): [OrigEquipMfr]
Trap Recipient's IP address : [0.0.0.0]
Community (rw): [private]
Trap Recipient's IP address : [0.0.0.0]
Community (ro): [public] mcchm     <<<<<< change the community string to the desired value,
Trap Recipient's IP address : [0.0.0.0]    in this example it is set to "mcchm"
Community (ro): [common]
Trap Recipient's IP address : [0.0.0.0]
Community (ro): [FibreChannel]
Trap Recipient's IP address : [0.0.0.0]
Committing configuration.....done.
FC_switch_A_1:admin>
----
+
在 FC_switch_B_1 上：

+
[listing]
----
FC_switch_B_1:admin> snmpconfig --set snmpv1
SNMP community and trap recipient configuration:
Community (rw): [Secret C0de]
Trap Recipient's IP address : [0.0.0.0]
Community (rw): [OrigEquipMfr]
Trap Recipient's IP address : [0.0.0.0]
Community (rw): [private]
Trap Recipient's IP address : [0.0.0.0]
Community (ro): [public] mcchm      <<<<<< change the community string to the desired value,
Trap Recipient's IP address : [0.0.0.0]     in this example it is set to "mcchm"
Community (ro): [common]
Trap Recipient's IP address : [0.0.0.0]
Community (ro): [FibreChannel]
Trap Recipient's IP address : [0.0.0.0]
Committing configuration.....done.
FC_switch_B_1:admin>
----


. 重新启动交换机：
+
`re启动`

+
在 FC_switch_A_1 上：

+
[listing]
----
FC_switch_A_1:admin> reboot
----
+
在 FC_switch_B_1 上：

+
[listing]
----
FC_switch_B_1:admin> reboot
----
. 持久启用交换机：
+
`sswitchcfgpersistentenable`

+
在 FC_switch_A_1 上：

+
[listing]
----
FC_switch_A_1:admin> switchcfgpersistentenable
----
+
在 FC_switch_B_1 上：

+
[listing]
----
FC_switch_B_1:admin> switchcfgpersistentenable
----




== 在 Brocade DCX 8510-8 交换机上配置基本交换机设置

您必须为 Brocade 交换机配置基本全局设置，包括域 ID 。

您必须对两个 MetroCluster 站点的每个交换机执行这些步骤。在此操作步骤中，您可以为每个交换机设置域 ID ，如以下示例所示：

* FC_switch_A_1 已分配给域 ID 5
* FC_switch_A_2 已分配给域 ID 6
* FC_switch_B_1 已分配给域 ID 7
* FC_switch_B_2 已分配给域 ID 8


在上一示例中，域 ID 5 和 7 构成 fabric_1 ，域 ID 6 和 8 构成 fabric_2 。


NOTE: 如果每个站点仅使用一个 DCX 8510-8 交换机，则也可以使用此操作步骤配置交换机。

使用此操作步骤，您应在每个 Brocade DCX 8510-8 交换机上创建两个逻辑交换机。在两个 Brocade DCX8510-8 交换机上创建的两个逻辑交换机将形成两个逻辑网络结构，如以下示例所示：

* 逻辑网络结构 1 ：交换机 1/Blade1 和交换机 2 刀片 1
* 逻辑网络结构 2 ：交换机 1/Blade2 和交换机 2 刀片 2


.步骤
. 进入命令模式：
+
`配置`

. 按照提示继续操作：
+
.. 设置交换机的域 ID 。
.. 继续选择 * 输入 * ，直到进入 "RDP 轮询周期 " ，然后将此值设置为 `0` 以禁用轮询。
.. 选择 * 输入 * ，直到返回到交换机提示符。
+
[listing]
----
FC_switch_A_1:admin> configure
Fabric parameters = y
Domain_id = `5


RDP Polling Cycle(hours)[0 = Disable Polling]: (0..24) [1] 0
`
----


. 对 fabric_1 和 fabric_2 中的所有交换机重复上述步骤。
. 配置虚拟网络结构。
+
.. 在交换机上启用虚拟网络结构：
+
`fosconfig -enableevf`

.. 将系统配置为在所有逻辑交换机上使用相同的基本配置：
+
`配置机箱`

+
以下示例显示了 `configurechassis` 命令的输出：

+
[listing]
----
System (yes, y, no, n): [no] n
cfgload attributes (yes, y, no, n): [no] n
Custom attributes (yes, y, no, n): [no] y
Config Index (0 to ignore): (0..1000) [3]:
----


. 创建并配置逻辑交换机：
+
`scfg -create fabricID`

. 将所有端口从刀片式服务器添加到虚拟网络结构：
+
`lscfg -config fabricID -slot slot -port lowest-port - Highest-port`

+

NOTE: 构成逻辑网络结构的刀片式服务器（例如 交换机 1 刀片式服务器 1 和交换机 3 刀片式服务器 1 ）需要具有相同的网络结构 ID 。

+
[listing]
----
setcontext fabricid
switchdisable
configure
<configure the switch per the above settings>
switchname unique switch name
switchenable
----


link:concept_prepare_for_the_mcc_installation.html["使用 Brocade DCX 8510-8 交换机的要求"]



== 使用 FC 端口在 Brocade FC 交换机上配置 E 端口

对于使用 FC 端口配置交换机间链路（ ISL ）的 Brocade 交换机，必须在连接 ISL 的每个交换机网络结构上配置交换机端口。这些 ISL 端口也称为 E 端口。

.开始之前
* FC 交换机网络结构中的所有 ISL 都必须配置相同的速度和距离。
* 交换机端口和小型可插拔（ Small Form-Factor Pluggable ， SFP ）的组合必须支持此速度。
* 支持的 ISL 距离取决于 FC 交换机型号。
+
https://mysupport.netapp.com/matrix["NetApp 互操作性表工具"]

+
在 IMT 中，您可以使用 Storage 解决方案字段选择 MetroCluster 解决方案。您可以使用 * 组件资源管理器 * 来选择组件和 ONTAP 版本以细化搜索范围。您可以单击 * 显示结果 * 以显示与此条件匹配的受支持配置列表。

* ISL 链路必须具有专用 lambda ，并且 Brocade 必须支持此链路的距离，交换机类型和网络结构操作系统（ FOS ）。


发出 `portCfgLongDistance` 命令时，不能使用 L0 设置。而是应使用 LE 或 LS 设置为 Brocade 交换机上的距离配置最小 LE 距离级别。

在使用 xWDM/TDM 设备时，发出 `portCfgLongDistance` 命令时，不得使用 LD 设置。而是应使用 LE 或 LS 设置来配置 Brocade 交换机上的距离。

您必须对每个 FC 交换机网络结构执行此任务。

下表显示了运行 ONTAP 9.1 或 9.2 的配置中不同交换机的 ISL 端口以及不同数量的 ISL 。本节所示的示例适用于 Brocade 6505 交换机。您应修改示例以使用适用于您的交换机类型的端口。

如果您的配置运行的是 ONTAP 9.0 或更早版本，请参见 link:install-fc/concept_port_assignments_for_fc_switches_when_using_ontap_9_0.html["使用 ONTAP 9.0 时 FC 交换机的端口分配"]。

您必须为配置使用所需数量的 ISL 。

|===


| 交换机型号 | ISL 端口 | 交换机端口 


.4+| Brocade 6520 | ISL 端口 1 | 23 


| ISL 端口 2 | 47 


| ISL 端口 3 | 71. 


| ISL 端口 4 | 95 


.4+| Brocade 6505 | ISL 端口 1 | 20 


| ISL 端口 2 | 21 


| ISL 端口 3 | 22. 


| ISL 端口 4 | 23 


.8+| Brocade 6510 和 Brocade DCX 8510-8 | ISL 端口 1 | 40 


| ISL 端口 2 | 41. 


| ISL 端口 3 | 42 


| ISL 端口 4 | 43 


| ISL 端口 5 | 44 


| ISL 端口 6 | 45 


| ISL 端口 7 | 46 


| ISL 端口 8 | 47 


.6+| Brocade 7810  a| 
ISL 端口 1
 a| 
GE2 （ 10-Gbps ）



 a| 
ISL 端口 2
 a| 
ge3 （ 10-Gbps ）



 a| 
ISL 端口 3
 a| 
GE4 （ 10-Gbps ）



 a| 
ISL 端口 4
 a| 
GE5 （ 10-Gbps ）



 a| 
ISL 端口 5
 a| 
ge6 （ 10-Gbps ）



 a| 
ISL 端口 6
 a| 
ge7 （ 10-Gbps ）



.4+| Brocade 7840 * 注： * Brocade 7840 交换机支持每个交换机使用两个 40 Gbps VE 端口或最多四个 10 Gbps VE 端口来创建 FCIP ISL 。  a| 
ISL 端口 1
 a| 
ge0 （ 40-Gbps ）或 ge2 （ 10-Gbps ）



 a| 
ISL 端口 2
 a| 
ge1 （ 40-Gbps ）或 ge3 （ 10-Gbps ）



 a| 
ISL 端口 3
 a| 
ge10 （ 10-Gbps ）



 a| 
ISL 端口 4
 a| 
ge11 （ 10-Gbps ）



.4+| Brocade G610  a| 
ISL 端口 1
 a| 
20



 a| 
ISL 端口 2
 a| 
21



 a| 
ISL 端口 3
 a| 
22.



 a| 
ISL 端口 4
 a| 
23



.7+| Brocade G620 ， G620-1 ， G630 ， G630-1 ， G720  a| 
ISL 端口 1
 a| 
40



 a| 
ISL 端口 2
 a| 
41.



 a| 
ISL 端口 3
 a| 
42



 a| 
ISL 端口 4
 a| 
43



 a| 
ISL 端口 5
 a| 
44



 a| 
ISL 端口 6
 a| 
45



 a| 
ISL 端口 7
 a| 
46

|===
.步骤
. 【 ｛ step1_Brocade_config]] 配置端口速度：
+
`portcfgspeed port-numberspeed`

+
您必须使用路径中的组件支持的最高通用速度。

+
在以下示例中，每个网络结构有两个 ISL ：

+
[listing]
----
FC_switch_A_1:admin> portcfgspeed 20 16
FC_switch_A_1:admin> portcfgspeed 21 16

FC_switch_B_1:admin> portcfgspeed 20 16
FC_switch_B_1:admin> portcfgspeed 21 16
----
. 为每个 ISL 配置中继模式：
+
`portcfgtrunkport port-number`

+
** 如果要为中继（ IOD ）配置 ISL ，请将 portcfgtrunk port-numberport-number 设置为 1 ，如以下示例所示：
+
[listing]
----
FC_switch_A_1:admin> portcfgtrunkport 20 1
FC_switch_A_1:admin> portcfgtrunkport 21 1
FC_switch_B_1:admin> portcfgtrunkport 20 1
FC_switch_B_1:admin> portcfgtrunkport 21 1
----
** 如果您不想为 ISL 配置中继（ OOD ），请将 portcfgtrunkport-number 设置为 0 ，如以下示例所示：
+
[listing]
----
FC_switch_A_1:admin> portcfgtrunkport 20 0
FC_switch_A_1:admin> portcfgtrunkport 21 0
FC_switch_B_1:admin> portcfgtrunkport 20 0
FC_switch_B_1:admin> portcfgtrunkport 21 0
----


. 为每个 ISL 端口启用 QoS 流量：
+
`portcfgqos -enable port-number`

+
在以下示例中，每个交换机网络结构有两个 ISL ：

+
[listing]
----
FC_switch_A_1:admin> portcfgqos --enable 20
FC_switch_A_1:admin> portcfgqos --enable 21

FC_switch_B_1:admin> portcfgqos --enable 20
FC_switch_B_1:admin> portcfgqos --enable 21
----
. 验证设置：
+
`portCfgShow 命令`

+
以下示例显示了使用两个 ISL 连接到端口 20 和端口 21 的配置的输出。对于 IOD ， "Trunk Port" 设置应为 "On" ，而对于 OOD ，则应为 "Off" ：

+
[listing]
----

Ports of Slot 0   12  13   14 15    16  17  18  19   20  21 22  23    24  25  26  27
----------------+---+---+---+---+-----+---+---+---+----+---+---+---+-----+---+---+---
Speed             AN  AN  AN  AN    AN  AN  8G  AN   AN  AN  16G  16G    AN  AN  AN  AN
Fill Word         0   0   0   0     0   0   3   0    0   0   3   3     3   0   0   0
AL_PA Offset 13   ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Trunk Port        ..  ..  ..  ..    ..  ..  ..  ..   ON  ON  ..  ..    ..  ..  ..  ..
Long Distance     ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
VC Link Init      ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Locked L_Port     ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Locked G_Port     ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Disabled E_Port   ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Locked E_Port     ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
ISL R_RDY Mode    ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
RSCN Suppressed   ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Persistent Disable..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
LOS TOV enable    ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
NPIV capability   ON  ON  ON  ON    ON  ON  ON  ON   ON  ON  ON  ON    ON  ON  ON  ON
NPIV PP Limit    126 126 126 126   126 126 126 126  126 126 126 126   126 126 126 126
QOS E_Port        AE  AE  AE  AE    AE  AE  AE  AE   AE  AE  AE  AE    AE  AE  AE  AE
Mirror Port       ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Rate Limit        ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Credit Recovery   ON  ON  ON  ON    ON  ON  ON  ON   ON  ON  ON  ON    ON  ON  ON  ON
Fport Buffers     ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Port Auto Disable ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
CSCTL mode        ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..

Fault Delay       0  0  0  0    0  0  0  0   0  0  0  0    0  0  0  0
----
. 计算 ISL 距离。
+
由于 FC-VI 的行为，此距离必须设置为实际距离的 1.5 倍，最小距离为 10 公里（使用 LE 距离级别）。

+
ISL 的距离计算如下，并取整为下一个完整公里：

+
1.5 × Real_distance = 距离

+
如果距离为 3 公里，则 1.5 × 3 公里 = 4.5 公里此距离小于 10 公里，因此 ISL 必须设置为 LE 距离级别。

+
如果距离为 20 公里，则 1.5 × 20 公里 = 30 公里ISL 必须设置为 30 公里，并且必须使用 LS 距离级别。

. 设置每个 ISL 端口上的距离：
+
`portcfglongdistance _portdistance-level_ vc_link_init _distance_`

+
a `vc_link_init` 值 `1` 使用 ARB 填充字（默认）。值 `0` 将使用空闲。所需值可能取决于所使用的链路。必须对每个 ISL 端口重复执行这些命令。

+
如果 ISL 距离为 3 公里，则设置为 4.5 公里，默认值为 `vc_link_init` 值 `1` 。由于设置为 4.5 公里的距离小于 10 公里，因此需要将端口设置为 LE 距离级别：

+
[listing]
----
FC_switch_A_1:admin> portcfglongdistance 20 LE 1

FC_switch_B_1:admin> portcfglongdistance 20 LE 1
----
+
如果 ISL 距离为 20 公里，如上一步的示例所示，则设置为 30 公里，默认的 vc_link_init 值为 `1` ：

+
[listing]
----
FC_switch_A_1:admin> portcfglongdistance 20 LS 1 -distance 30

FC_switch_B_1:admin> portcfglongdistance 20 LS 1 -distance 30
----
. 验证距离设置：
+
`portbuffershow`

+
LE 的距离级别显示为 10 公里

+
以下示例显示了在端口 20 和端口 21 上使用 ISL 的配置的输出：

+
[listing]
----
FC_switch_A_1:admin> portbuffershow

User  Port     Lx      Max/Resv    Buffer Needed    Link      Remaining
Port  Type    Mode     Buffers     Usage  Buffers   Distance  Buffers
----  ----    ----     -------     ------ -------   --------- ---------
...
 20     E      -          8         67      67       30km
 21     E      -          8         67      67       30km
...
 23            -          8          0      -        -        466
----
. 验证两个交换机是否形成一个网络结构：
+
`sswitchshow`

+
以下示例显示了在端口 20 和端口 21 上使用 ISL 的配置的输出：

+
[listing]
----
FC_switch_A_1:admin> switchshow
switchName: FC_switch_A_1
switchType: 109.1
switchState:Online
switchMode: Native
switchRole: Subordinate
switchDomain:       5
switchId:   fffc01
switchWwn:  10:00:00:05:33:86:89:cb
zoning:             OFF
switchBeacon:       OFF

Index Port Address Media Speed State  Proto
===========================================
...
20   20  010C00   id    16G  Online FC  LE E-Port  10:00:00:05:33:8c:2e:9a "FC_switch_B_1" (downstream)(trunk master)
21   21  010D00   id    16G  Online FC  LE E-Port  (Trunk port, master is Port 20)
...

FC_switch_B_1:admin> switchshow
switchName: FC_switch_B_1
switchType: 109.1
switchState:Online
switchMode: Native
switchRole: Principal
switchDomain:       7
switchId:   fffc03
switchWwn:  10:00:00:05:33:8c:2e:9a
zoning:             OFF
switchBeacon:       OFF

Index Port Address Media Speed State Proto
==============================================
...
20   20  030C00   id    16G  Online  FC  LE E-Port  10:00:00:05:33:86:89:cb "FC_switch_A_1" (downstream)(Trunk master)
21   21  030D00   id    16G  Online  FC  LE E-Port  (Trunk port, master is Port 20)
...
----
. 确认网络结构的配置：
+
`fabricshow`

+
[listing]
----
FC_switch_A_1:admin> fabricshow
   Switch ID   Worldwide Name      Enet IP Addr FC IP Addr Name
-----------------------------------------------------------------
1: fffc01 10:00:00:05:33:86:89:cb 10.10.10.55  0.0.0.0    "FC_switch_A_1"
3: fffc03 10:00:00:05:33:8c:2e:9a 10.10.10.65  0.0.0.0   >"FC_switch_B_1"
----
+
[listing]
----
FC_switch_B_1:admin> fabricshow
   Switch ID   Worldwide Name     Enet IP Addr FC IP Addr   Name
----------------------------------------------------------------
1: fffc01 10:00:00:05:33:86:89:cb 10.10.10.55  0.0.0.0     "FC_switch_A_1"

3: fffc03 10:00:00:05:33:8c:2e:9a 10.10.10.65  0.0.0.0    >"FC_switch_B_1
----
. 【第 10 步 _Brocade_config]] 确认 ISL 的中继：
+
`Trunkshow`

+
** 如果要配置 ISL 以进行中继（ IOD ），则应看到类似于以下内容的输出：
+
[listing]
----
FC_switch_A_1:admin> trunkshow
 1: 20-> 20 10:00:00:05:33:ac:2b:13 3 deskew 15 MASTER
    21-> 21 10:00:00:05:33:8c:2e:9a 3 deskew 16
 FC_switch_B_1:admin> trunkshow
 1: 20-> 20 10:00:00:05:33:86:89:cb 3 deskew 15 MASTER
    21-> 21 10:00:00:05:33:86:89:cb 3 deskew 16
----
** 如果您不是为中继（ OOD ）配置 ISL ，则应看到类似于以下内容的输出：
+
[listing]
----
FC_switch_A_1:admin> trunkshow
 1: 20-> 20 10:00:00:05:33:ac:2b:13 3 deskew 15 MASTER
 2: 21-> 21 10:00:00:05:33:8c:2e:9a 3 deskew 16 MASTER
FC_switch_B_1:admin> trunkshow
 1: 20-> 20 10:00:00:05:33:86:89:cb 3 deskew 15 MASTER
 2: 21-> 21 10:00:00:05:33:86:89:cb 3 deskew 16 MASTER
----


. 重复 <<step1_brocade_config,第 1 步>> 到 <<step10_brocade_config,第 10 步>> 用于第二个 FC 交换机网络结构。


link:concept_port_assignments_for_fc_switches_when_using_ontap_9_1_and_later.html["使用 ONTAP 9.1 及更高版本时 FC 交换机的端口分配"]



== 在 Brocade FC 7840 交换机上配置 10 Gbps VE 端口

如果要对 ISL 使用 10 Gbps VE 端口（使用 FCIP ），则必须在每个端口上创建 IP 接口，并在每个通道中配置 FCIP 通道和电路。

必须对 MetroCluster 配置中的每个交换机网络结构执行此操作步骤。

此操作步骤中的示例假定两个 Brocade 7840 交换机具有以下 IP 地址：

* FC_switch_A_1 为本地。
* FC_switch_B_1 为远程交换机。


.步骤
. 为网络结构中两台交换机上的 10 Gbps 端口创建 IP 接口（ ipif ）地址：
+
`portcfg ipif FC_switch1_namefirst_port_name create FC_switch1_IP_address netmask netmask_number VLAN 2 MTU auto`

+
以下命令将在 FC_switch_A_1 的端口 ge2.dp0 和 ge3.dp0 上创建 ipif 地址：

+
[listing]
----
portcfg ipif  ge2.dp0 create  10.10.20.71 netmask 255.255.0.0 vlan 2 mtu auto
portcfg ipif  ge3.dp0 create  10.10.21.71 netmask 255.255.0.0 vlan 2 mtu auto
----
+
以下命令将在 FC_switch_B_1 的端口 ge2.dp0 和 ge3.dp0 上创建 ipif 地址：

+
[listing]
----
portcfg ipif  ge2.dp0 create  10.10.20.72 netmask 255.255.0.0 vlan 2 mtu auto
portcfg ipif  ge3.dp0 create  10.10.21.72 netmask 255.255.0.0 vlan 2 mtu auto
----
. 验证是否已在两台交换机上成功创建 ipif 地址：
+
`portShow ipif all`

+
以下命令显示交换机 FC_switch_A_1 上的 ipif 地址：

+
[listing]
----
FC_switch_A_1:root> portshow ipif all

 Port         IP Address                     / Pfx  MTU   VLAN  Flags
--------------------------------------------------------------------------------
 ge2.dp0      10.10.20.71                    / 24   AUTO  2     U R M I
 ge3.dp0      10.10.21.71                    / 20   AUTO  2     U R M I
--------------------------------------------------------------------------------
Flags: U=Up B=Broadcast D=Debug L=Loopback P=Point2Point R=Running I=InUse
       N=NoArp PR=Promisc M=Multicast S=StaticArp LU=LinkUp X=Crossport
----
+
以下命令显示交换机 FC_switch_B_1 上的 ipif 地址：

+
[listing]
----
FC_switch_B_1:root> portshow ipif all

 Port         IP Address                     / Pfx  MTU   VLAN  Flags
--------------------------------------------------------------------------------
 ge2.dp0      10.10.20.72                    / 24   AUTO  2     U R M I
 ge3.dp0      10.10.21.72                    / 20   AUTO  2     U R M I
--------------------------------------------------------------------------------
Flags: U=Up B=Broadcast D=Debug L=Loopback P=Point2Point R=Running I=InUse
       N=NoArp PR=Promisc M=Multicast S=StaticArp LU=LinkUp X=Crossport
----
. 使用 DP0 上的端口创建两个 FCIP 通道中的第一个通道：
+
`portcfg fciptunnel`

+
此命令将创建具有单个电路的通道。

+
以下命令将在交换机 FC_switch_A_1 上创建通道：

+
[listing]
----
portcfg fciptunnel 24 create -S 10.10.20.71  -D 10.10.20.72 -b 10000000 -B 10000000
----
+
以下命令将在交换机 FC_switch_B_1 上创建通道：

+
[listing]
----
portcfg fciptunnel 24 create -S 10.10.20.72  -D 10.10.20.71 -b 10000000 -B 10000000
----
. 验证是否已成功创建 FCIP 通道：
+
`portShow fciptunnel all`

+
以下示例显示已创建通道且电路已启动：

+
[listing]
----
FC_switch_B_1:root>

 Tunnel Circuit  OpStatus  Flags    Uptime  TxMBps  RxMBps ConnCnt CommRt Met/G
--------------------------------------------------------------------------------
 24    -         Up      ---------     2d8m    0.05    0.41   3      -       -
--------------------------------------------------------------------------------
 Flags (tunnel): i=IPSec f=Fastwrite T=TapePipelining F=FICON r=ReservedBW
                 a=FastDeflate d=Deflate D=AggrDeflate P=Protocol
                 I=IP-Ext
----
. 为 DP0 创建一个额外电路。
+
以下命令会在交换机 FC_switch_A_1 上为 DP0 创建一个电路：

+
[listing]
----
portcfg fcipcircuit 24 create 1 -S 10.10.21.71 -D 10.10.21.72  --min-comm-rate 5000000 --max-comm-rate 5000000
----
+
以下命令会在交换机 FC_switch_B_1 上为 DP0 创建一个电路：

+
[listing]
----
portcfg fcipcircuit 24 create 1 -S 10.10.21.72 -D 10.10.21.71  --min-comm-rate 5000000 --max-comm-rate 5000000
----
. 验证是否已成功创建所有电路：
+
`portShow fcipcircuit all`

+
以下命令显示电路及其状态：

+
[listing]
----
FC_switch_A_1:root> portshow fcipcircuit all

 Tunnel Circuit  OpStatus  Flags    Uptime  TxMBps  RxMBps ConnCnt CommRt Met/G
--------------------------------------------------------------------------------
 24    0 ge2     Up      ---va---4    2d12m    0.02    0.03   3 10000/10000 0/-
 24    1 ge3     Up      ---va---4    2d12m    0.02    0.04   3 10000/10000 0/-
--------------------------------------------------------------------------------
 Flags (circuit): h=HA-Configured v=VLAN-Tagged p=PMTU i=IPSec 4=IPv4 6=IPv6
                 ARL a=Auto r=Reset s=StepDown t=TimedStepDown  S=SLA
----




== 在 Brocade 7810 和 7840 FC 交换机上配置 40 Gbps VE 端口

如果要对 ISL 使用两个 40 GbE VE 端口（使用 FCIP ），则必须在每个端口上创建 IP 接口，并在每个通道中配置 FCIP 通道和电路。

必须对 MetroCluster 配置中的每个交换机网络结构执行此操作步骤。

此操作步骤中的示例使用两个交换机：

* FC_switch_A_1 为本地。
* FC_switch_B_1 为远程交换机。


.步骤
. 为网络结构中两台交换机上的 40 Gbps 端口创建 IP 接口（ ipif ）地址：
+
`portcfg ipif FC_switch_name first_port_name create FC_switch_ip_address netmask netmask_number vlan 2 MTU auto`

+
以下命令将在 FC_switch_A_1 的端口 ge0.dp0 和 ge1.dp0 上创建 ipif 地址：

+
[listing]
----
portcfg ipif  ge0.dp0 create  10.10.82.10 netmask 255.255.0.0 vlan 2 mtu auto
portcfg ipif  ge1.dp0 create  10.10.82.11 netmask 255.255.0.0 vlan 2 mtu auto
----
+
以下命令将在 FC_switch_B_1 的端口 ge0.dp0 和 ge1.dp0 上创建 ipif 地址：

+
[listing]
----
portcfg ipif  ge0.dp0 create  10.10.83.10 netmask 255.255.0.0 vlan 2 mtu auto
portcfg ipif  ge1.dp0 create  10.10.83.11 netmask 255.255.0.0 vlan 2 mtu auto
----
. 验证是否已在两台交换机上成功创建 ipif 地址：
+
`portShow ipif all`

+
以下示例显示了 FC_switch_A_1 上的 IP 接口：

+
[listing]
----
Port         IP Address                     / Pfx  MTU   VLAN  Flags
---------------------------------------------------------------------------
-----
 ge0.dp0      10.10.82.10                    / 16   AUTO  2     U R M
 ge1.dp0      10.10.82.11                    / 16   AUTO  2     U R M
--------------------------------------------------------------------------------
Flags: U=Up B=Broadcast D=Debug L=Loopback P=Point2Point R=Running I=InUse
       N=NoArp PR=Promisc M=Multicast S=StaticArp LU=LinkUp X=Crossport
----
+
以下示例显示了 FC_switch_B_1 上的 IP 接口：

+
[listing]
----
Port         IP Address                     / Pfx  MTU   VLAN  Flags
--------------------------------------------------------------------------------
 ge0.dp0      10.10.83.10                    / 16   AUTO  2     U R M
 ge1.dp0      10.10.83.11                    / 16   AUTO  2     U R M
--------------------------------------------------------------------------------
Flags: U=Up B=Broadcast D=Debug L=Loopback P=Point2Point R=Running I=InUse
       N=NoArp PR=Promisc M=Multicast S=StaticArp LU=LinkUp X=Crossport
----
. 在两台交换机上创建 FCIP 通道：
+
`portcfig fciptunnel`

+
以下命令将在 FC_switch_A_1 上创建通道：

+
[listing]
----
portcfg fciptunnel 24 create -S 10.10.82.10  -D 10.10.83.10 -b 10000000 -B 10000000
----
+
以下命令将在 FC_switch_B_1 上创建通道：

+
[listing]
----
portcfg fciptunnel 24 create -S 10.10.83.10  -D 10.10.82.10 -b 10000000 -B 10000000
----
. 验证是否已成功创建 FCIP 通道：
+
`portShow fciptunnel all`

+
以下示例显示已创建通道且电路已启动：

+
[listing]
----
FC_switch_A_1:root>

 Tunnel Circuit  OpStatus  Flags    Uptime  TxMBps  RxMBps ConnCnt CommRt Met/G
--------------------------------------------------------------------------------
 24    -         Up      ---------     2d8m    0.05    0.41   3      -       -
 --------------------------------------------------------------------------------
 Flags (tunnel): i=IPSec f=Fastwrite T=TapePipelining F=FICON r=ReservedBW
                 a=FastDeflate d=Deflate D=AggrDeflate P=Protocol
                 I=IP-Ext
----
. 在每个交换机上创建一个额外的电路：
+
`portcfg fcipcircuit 24 create 1 -S source-ip-address -D destination-ip-address -min-comm-rate 10000000 -max-comm-rate 10000000`

+
以下命令会在交换机 FC_switch_A_1 上为 DP0 创建一个电路：

+
[listing]
----
portcfg fcipcircuit 24  create 1 -S 10.10.82.11 -D 10.10.83.11  --min-comm-rate 10000000 --max-comm-rate 10000000
----
+
以下命令会在交换机 FC_switch_B_1 上为 DP1 创建一个电路：

+
[listing]
----
portcfg fcipcircuit 24 create 1  -S 10.10.83.11 -D 10.10.82.11  --min-comm-rate 10000000 --max-comm-rate 10000000
----
. 验证是否已成功创建所有电路：
+
`portShow fcipcircuit all`

+
以下示例列出了这些电路，并显示其 OpStatus 为 up ：

+
[listing]
----
FC_switch_A_1:root> portshow fcipcircuit all

 Tunnel Circuit  OpStatus  Flags    Uptime  TxMBps  RxMBps ConnCnt CommRt Met/G
--------------------------------------------------------------------------------
 24    0 ge0     Up      ---va---4    2d12m    0.02    0.03   3 10000/10000 0/-
 24    1 ge1     Up      ---va---4    2d12m    0.02    0.04   3 10000/10000 0/-
 --------------------------------------------------------------------------------
 Flags (circuit): h=HA-Configured v=VLAN-Tagged p=PMTU i=IPSec 4=IPv4 6=IPv6
                 ARL a=Auto r=Reset s=StepDown t=TimedStepDown  S=SLA
----




== 在 Brocade 交换机上配置非 E 端口

您必须在 FC 交换机上配置非 E 端口。在 MetroCluster 配置中，这些端口用于将交换机连接到 HBA 启动程序， FC-VI 互连和 FC-SAS 网桥。必须对每个端口执行这些步骤。

在以下示例中，这些端口用于连接 FC-SAS 网桥：

--
* 站点 A 的 FC_FC_switch_A_1 上的端口 6
* 站点 B 的 FC_FC_switch_B_1 上的端口 6


--
.步骤
. 配置每个非 E 端口的端口速度：
+
`portcfgspeed portspeed`

+
您应使用最高通用速度，即数据路径中的所有组件均支持的最高速度： SFP ，安装 SFP 的交换机端口以及连接的设备（ HBA ，网桥等）。

+
例如，这些组件可能支持以下速度：

+
** SFP 支持 4 GB ， 8 GB 或 16 GB 。
** 交换机端口支持 4 GB ， 8 GB 或 16 GB 。
** 连接的 HBA 最大速度为 16 GB 。在这种情况下，最高通用速度为 16 GB ，因此应将端口的速度配置为 16 GB 。
+
[listing]
----
FC_switch_A_1:admin> portcfgspeed 6 16

FC_switch_B_1:admin> portcfgspeed 6 16
----


. 验证设置：
+
`portcfgshow`

+
[listing]
----
FC_switch_A_1:admin> portcfgshow

FC_switch_B_1:admin> portcfgshow
----
+
在示例输出中，端口 6 具有以下设置；速度设置为 16G ：

+
[listing]
----
Ports of Slot 0                     0   1   2   3   4   5   6   7   8
-------------------------------------+---+---+---+--+---+---+---+---+--
Speed                               16G 16G 16G 16G 16G 16G 16G 16G 16G
AL_PA Offset 13                     ..  ..  ..  ..  ..  ..  ..  ..  ..
Trunk Port                          ..  ..  ..  ..  ..  ..  ..  ..  ..
Long Distance                       ..  ..  ..  ..  ..  ..  ..  ..  ..
VC Link Init                        ..  ..  ..  ..  ..  ..  ..  ..  ..
Locked L_Port                       -   -   -   -   -  -   -   -   -
Locked G_Port                       ..  ..  ..  ..  ..  ..  ..  ..  ..
Disabled E_Port                     ..  ..  ..  ..  ..  ..  ..  ..  ..
Locked E_Port                       ..  ..  ..  ..  ..  ..  ..  ..  ..
ISL R_RDY Mode                      ..  ..  ..  ..  ..  ..  ..  .. ..
RSCN Suppressed                     ..  ..  ..  ..  ..  ..  ..  .. ..
Persistent Disable                  ..  ..  ..  ..  ..  ..  ..  .. ..
LOS TOV enable                      ..  ..  ..  ..  ..  ..  ..  .. ..
NPIV capability                     ON  ON  ON  ON  ON  ON  ON  ON  ON
NPIV PP Limit                       126 126 126 126 126 126 126 126 126
QOS Port                            AE  AE  AE  AE  AE  AE  AE  AE  ON
EX Port                             ..  ..  ..  ..  ..  ..  ..  ..  ..
Mirror Port                         ..  ..  ..  ..  ..  ..  ..  ..  ..
Rate Limit                          ..  ..  ..  ..  ..  ..  ..  ..  ..
Credit Recovery                     ON  ON  ON  ON  ON  ON  ON  ON  ON
Fport Buffers                       ..  ..  ..  ..  ..  ..  ..  ..  ..
Eport Credits                       ..  ..  ..  ..  ..  ..  ..  ..  ..
Port Auto Disable                   ..  ..  ..  ..  ..  ..  ..  ..  ..
CSCTL mode                          ..  ..  ..  ..  ..  ..  ..  ..  ..
D-Port mode                         ..  ..  ..  ..  ..  ..  ..  ..  ..
D-Port over DWDM                    ..  ..  ..  ..  ..  ..  ..  ..  ..
FEC                                 ON  ON  ON  ON  ON  ON  ON  ON  ON
Fault Delay                         0   0   0   0   0   0   0   0   0
Non-DFE                             ..  ..  ..  ..  ..  ..  ..  ..  ..
----




== 在 Brocade G620 交换机的 ISL 端口上配置数据压缩

如果您使用的是 Brocade G620 交换机并在 ISL 上启用了数据压缩，则必须在交换机上的每个 E 端口上对其进行配置。

必须使用 ISL 对两个交换机上的 ISL 端口执行此任务。

.步骤
. 禁用要配置数据压缩的端口：
+
`portdisable port-id`

. 在端口上启用数据压缩：
+
`portCfgCompress -enable port-id`

. 启用端口以激活数据压缩配置：
+
`portEnable port-id`

. 确认设置已更改：
+
`portcfgshow port-id`



以下示例将在端口 0 上启用数据压缩。

[listing]
----
FC_switch_A_1:admin> portdisable 0
FC_switch_A_1:admin> portcfgcompress --enable 0
FC_switch_A_1:admin> portenable 0
FC_switch_A_1:admin> portcfgshow 0
Area Number: 0
Octet Speed Combo: 3(16G,10G)
(output truncated)
D-Port mode: OFF
D-Port over DWDM ..
Compression: ON
Encryption: ON
----
您可以使用 islShow 命令检查 E_PORT 是否已联机，并且已配置加密或压缩并处于活动状态。

[listing]
----
FC_switch_A_1:admin> islshow
  1: 0-> 0 10:00:c4:f5:7c:8b:29:86   5 FC_switch_B_1
sp: 16.000G bw: 16.000G TRUNK QOS CR_RECOV ENCRYPTION COMPRESSION
----
您可以使用 portEncCompShow 命令查看哪些端口处于活动状态。在此示例中，您可以看到加密和压缩已在端口 0 上配置并处于活动状态。

[listing]
----
FC_switch_A_1:admin> portenccompshow
User	  Encryption		           Compression	         Config
Port   Configured    Active   Configured   Active  Speed
----   ----------    -------  ----------   ------  -----
  0	   Yes	          Yes	     Yes	         Yes	    16G
----


== 在 Brocade FC 交换机上配置分区

您必须将交换机端口分配给不同的分区，以隔离控制器和存储流量。根据您使用的是 FibreBridge 7500N 网桥还是 FibreBridge 6500N 网桥，操作步骤会有所不同。



=== FC-VI 端口的分区

对于 MetroCluster 中的每个 DR 组，您必须为 FC-VI 连接配置两个分区，以允许控制器到控制器的流量。这些分区包含连接到控制器模块 FC-VI 端口的 FC 交换机端口。这些分区是服务质量（ QoS ）分区。

QoS 分区名称以前缀 QOSHid_ 开头，后跟用户定义的字符串，以便与常规分区区分开。无论所使用的 FibreBridge 网桥型号如何，这些 QoS 分区都是相同的。

每个分区包含所有 FC-VI 端口，每个控制器的每个 FC-VI 缆线一个。这些分区配置为高优先级。

下表显示了两个 DR 组的 FC-VI 分区。

* DR 组 1 ： FC-VI 端口 a/c* 的 QOSH1 FC-VI 分区

|===
| FC 交换机 | 站点 | 交换机域 | 6505/6510 端口 | 6520 端口 | G620 端口 | 连接到 ... 


| FC_switch_A_1 | 答 | 5. | 0 | 0 | 0 | controller_A_1 端口 FC-VI a 


| FC_switch_A_1 | 答 | 5. | 1. | 1. | 1. | controller_A_1 端口 FC-VI c 


| FC_switch_A_1 | 答 | 5. | 4. | 4. | 4. | controller_A_2 端口 FC-VI a 


| FC_switch_A_1 | 答 | 5. | 5. | 5. | 5. | controller_A_2 端口 FC-VI c 


| FC_switch_B_1 | B | 7. | 0 | 0 | 0 | controller_B_1 端口 FC-VI A 


| FC_switch_B_1 | B | 7. | 1. | 1. | 1. | controller_B_1 端口 FC-VI c 


| FC_switch_B_1 | B | 7. | 4. | 4. | 4. | controller_B_2 端口 FC-VI A 


| FC_switch_B_1 | B | 7. | 5. | 5. | 5. | controller_B_2 端口 FC-VI c 
|===
|===


| Fabric_1 中的分区 | 成员端口 


| QOSH1_MC1_FAB_1_FCVI | 5 ， 0 ； 5 ， 1 ； 5 ， 4 ； 5 ， 5 ； 7 ， 0 ； 7 ， 1 ； 7 ， 4 ； 7 ， 5 
|===
* DR 组 1 ： FC-VI 端口 b/d* 的 QOSH1 FC-VI 分区

|===
| FC 交换机 | 站点 | 交换机域 | 6505/6510 端口 | 6520 端口 | G620 端口 | 连接到 ... 


| FC_switch_A_2 | 答 | 6. | 0 | 0 | 0 | controller_A_1 端口 FC-VI b 


|  |  |  | 1. | 1. | 1. | controller_A_1 端口 FC-VI d 


|  |  |  | 4. | 4. | 4. | controller_A_2 端口 FC-VI b 


|  |  |  | 5. | 5. | 5. | controller_A_2 端口 FC-VI d 


| FC_switch_B_2 | B | 8. | 0 | 0 | 0 | controller_B_1 端口 FC-VI b 


|  |  |  | 1. | 1. | 1. | controller_B_1 端口 FC-VI d 


|  |  |  | 4. | 4. | 4. | controller_B_2 端口 FC-VI b 


|  |  |  | 5. | 5. | 5. | controller_B_2 端口 FC-VI d 
|===
|===


| Fabric_1 中的分区 | 成员端口 


| QOSH1_MC1_FAB_2_FCVI | 6 ， 0 ； 6 ， 1 ； 6 ， 4 ； 6 ， 5 ； 8 ， 0 ； 8 ， 1 ； 8 ， 4 ； 8 ， 5 
|===
* DR 组 2 ： FC-VI 端口 a/c* 的 QOSH2 FC-VI 分区

|===
| FC 交换机 | 站点 | 交换机域 | 交换机端口 |  |  | 连接到 ... 


|  |  |  | 6510 | 6520 | G620 |  


| FC_switch_A_1 | 答 | 5. | 24 | 48 | 18 | controller_A_3 端口 FC-VI a 


|  |  |  | 25. | 49 | 19 | controller_A_3 端口 FC-VI c 


|  |  |  | 28 | 52 | 22. | controller_A_4 端口 FC-VI a 


|  |  |  | 29 | 53. | 23 | controller_A_4 端口 FC-VI c 


| FC_switch_B_1 | B | 7. | 24 | 48 | 18 | controller_B_3 端口 FC-VI A 


|  |  |  | 25. | 49 | 19 | controller_B_3 端口 FC-VI c 


|  |  |  | 28 | 52 | 22. | controller_B_4 端口 FC-VI A 


|  |  |  | 29 | 53. | 23 | controller_B_4 端口 FC-VI c 
|===
|===


| Fabric_1 中的分区 | 成员端口 


| QOSH2_MC2_FAB_1_FCVI （ 6510 ） | 5 ， 24 ； 5 ， 25 ； 5 ， 28 ； 5 ， 29 ； 7 ， 24 ； 7 ， 25 ； 7 ， 28 ； 7 ， 29 


| QOSH2_MC2_FAB_1_FCVI （ 6520 ） | 5 ， 48 ； 5 ， 49 ； 5 ， 52 ； 5 ， 53 ； 7 ， 48 ； 7 ， 49 ； 7 ， 52 ； 7 ， 53 
|===
* DR 组 2 ： FC-VI 端口 b/d* 的 QOSH2 FC-VI 分区

|===
| FC 交换机 | 站点 | 交换机域 | 6510 端口 | 6520 端口 | G620 端口 | 连接到 ... 


| FC_switch_A_2 | 答 | 6. | 24 | 48 | 18 | controller_A_3 端口 FC-VI b 


| FC_switch_A_2 | 答 | 6. | 25. | 49 | 19 | controller_A_3 端口 FC-VI d 


| FC_switch_A_2 | 答 | 6. | 28 | 52 | 22. | controller_A_4 端口 FC-VI b 


| FC_switch_A_2 | 答 | 6. | 29 | 53. | 23 | controller_A_4 端口 FC-VI d 


| FC_switch_B_2 | B | 8. | 24 | 48 | 18 | controller_B_3 端口 FC-VI b 


| FC_switch_B_2 | B | 8. | 25. | 49 | 19 | controller_B_3 端口 FC-VI d 


| FC_switch_B_2 | B | 8. | 28 | 52 | 22. | controller_B_4 端口 FC-VI b 


| FC_switch_B_2 | B | 8. | 29 | 53. | 23 | controller_B_4 端口 FC-VI d 
|===
|===


| Fabric_2 中的分区 | 成员端口 


| QOSH2_MC2_FAB_2_FCVI （ 6510 ） | 6 ， 24 ； 6 ， 25 ； 6 ， 28 ； 6 ， 29 ； 8 ， 24 ； 8 ， 25 ； 8 ， 28 ； 8 ， 29 


| QOSH2_MC2_FAB_2_FCVI （ 6520 ） | 6 ， 48 ； 6 ， 49 ； 6 ， 52 ； 6 ， 53 ； 8 ， 48 ； 8 ， 49 ； 8 ， 52 ； 8 ， 53 
|===
下表汇总了 FC-VI 分区：

|===


| 网络结构 | 分区名称 | 成员端口 


.3+| FC_switch_A_1 和 FC_switch_B_1  a| 
QOSH1_MC1_FAB_1_FCVI
 a| 
5 ， 0 ； 5 ， 1 ； 5 ， 4 ； 5 ， 5 ； 7 ， 0 ； 7 ， 1 ； 7 ， 4 ； 7 ， 5



 a| 
QOSH2_MC1_FAB_1_FCVI （ 6510 ）
 a| 
5 ， 24 ； 5 ， 25 ； 5 ， 28 ； 5 ， 29 ； 7 ， 24 ； 7 ， 25 ； 7 ， 28 ； 7 ， 29



 a| 
QOSH2_MC1_FAB_1_FCVI （ 6520 ）
 a| 
5 ， 48 ； 5 ， 49 ； 5 ， 52 ； 5 ， 53 ； 7 ， 48 ； 7 ， 49 ； 7 ， 52 ； 7 ， 53



.3+| FC_switch_A_2 和 FC_switch_B_2  a| 
QOSH1_MC1_FAB_2_FCVI
 a| 
6 ， 0 ； 6 ， 1 ； 6 ， 4 ； 6 ， 5 ； 8 ， 0 ； 8 ， 1 ； 8 ， 4 ； 8 ， 5



 a| 
QOSH2_MC1_FAB_2_FCVI （ 6510 ）
 a| 
6 ， 24 ； 6 ， 25 ； 6 ， 28 ； 6 ， 29 ； 8 ， 24 ； 8 ， 25 ； 8 ， 28 ； 8 ， 29



 a| 
QOSH2_MC1_FAB_2_FCVI （ 6520 ）
 a| 
6 ， 48 ； 6 ， 49 ； 6 ， 52 ； 6 ， 53 ； 8 ， 48 ； 8 ， 49 ； 8 ， 52 ； 8 ， 53

|===


=== 使用一个 FC 端口为 FibreBridge 6500N 网桥， FibreBridge 7500N 或 7600N 网桥分区

如果您仅使用两个 FC 端口之一使用 FibreBridge 6500N 网桥，或 FibreBridge 7500N 或 7600N 网桥，则需要为网桥端口创建存储分区。在配置分区之前，您应了解分区和关联的端口。

这些示例仅显示 DR 组 1 的分区。如果您的配置包含第二个 DR 组，请使用控制器和网桥的相应端口以相同的方式为第二个 DR 组配置分区。



==== 所需分区

您必须为每个 FC-SAS 网桥 FC 端口配置一个分区，以允许每个控制器模块上的启动程序与该 FC-SAS 网桥之间的流量。

每个存储分区包含九个端口：

* 八个 HBA 启动程序端口（每个控制器两个连接）
* 一个端口连接到 FC-SAS 网桥 FC 端口


存储分区使用标准分区。

这些示例显示了两对网桥，用于连接每个站点的两个堆栈组。由于每个网桥使用一个 FC 端口，因此每个网络结构共有四个存储分区（共八个）。



==== 网桥命名

网桥使用以下命名示例： bridge_site_stack groupocation in pair

|===


| 名称的这一部分 ... | 标识 ... | 可能值 ... 


 a| 
站点
 a| 
网桥对实际所在的站点。
 a| 
A 或 B



 a| 
堆栈组
 a| 
网桥对连接到的堆栈组的编号。

* FibreBridge 7600N 或 7500N 网桥最多支持堆栈组中的四个堆栈。
+
堆栈组包含的存储架不能超过 10 个。

* FibreBridge 6500N 网桥仅支持堆栈组中的一个堆栈。

 a| 
1 ， 2 等



 a| 
成对位置
 a| 
网桥对中的网桥。一对网桥连接到特定的堆栈组。
 a| 
a 或 b

|===
每个站点上一个堆栈组的网桥名称示例：

* bridge_A_1a
* bridge_A_1b
* bridge_B_1a
* bridge_B_1b




==== DR 组 1 — Site_A 上的堆栈 1

* DR 组 1 ： MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1 ： *

|===
| FC 交换机 | 站点 | 交换机域 | Brocade 6505 ， 6510 ， 6520 ， G620 或 G610 交换机端口 | 连接到 ... 


| FC_switch_A_1 | 答 | 5. | 2. | controller_A_1 端口 0a 


| FC_switch_A_1 | 答 | 5. | 3. | controller_A_1 端口 0c 


| FC_switch_A_1 | 答 | 5. | 6. | controller_A_2 端口 0a 


| FC_switch_A_1 | 答 | 5. | 7. | controller_A_2 端口 0c 


| FC_switch_A_1 | 答 | 5. | 8. | bridge_A_1a FC1 


| FC_switch_B_1 | B | 7. | 2. | controller_B_1 端口 0a 


| FC_switch_B_1 | B | 7. | 3. | controller_B_1 端口 0c 


| FC_switch_B_1 | B | 7. | 6. | controller_B_2 端口 0a 


| FC_switch_B_1 | B | 7. | 7. | controller_B_2 端口 0c 
|===
|===


| Fabric_1 中的分区 | 成员端口 


| MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1 | 5 ， 2 ； 5 ， 3 ； 5 ， 6 ； 5 ， 7 ； 7 ， 2 ； 7 ， 3 ； 7 ， 6 ； 7 ， 7 ； 5 ， 8 
|===
* DR 组 1 ： MC1_INIT_GRP_1_SITE_A_STK_GRP_1_BOT_FC1 ： *

|===
| FC 交换机 | 站点 | 交换机域 | Brocade 6505 ， 6510 ， 6520 ， G620 或 G610 交换机端口 | 连接到 ... 


| FC_switch_A_1 | 答 | 6. | 2. | controller_A_1 端口 0b 


| FC_switch_A_1 | 答 | 6. | 3. | controller_A_1 端口 0d 


| FC_switch_A_1 | 答 | 6. | 6. | controller_A_2 端口 0b 


| FC_switch_A_1 | 答 | 6. | 7. | controller_A_2 端口 0d 


| FC_switch_A_1 | 答 | 6. | 8. | bridge_A_1b FC1 


| FC_switch_B_1 | B | 8. | 2. | controller_B_1 端口 0b 


| FC_switch_B_1 | B | 8. | 3. | controller_B_1 端口 0d 


| FC_switch_B_1 | B | 8. | 6. | controller_B_2 端口 0b 


| FC_switch_B_1 | B | 8. | 7. | controller_B_2 端口 0d 
|===
|===


| Fabric_2 中的分区 | 成员端口 


| MC1_INIT_GRP_1_SITE_A_STK_GRP_1_BOT_FC1 | 6 ， 2 ； 6 ， 3 ； 6 ， 6 ； 6 ， 7 ； 8 ， 2 ； 8 ， 3 ； 8 ， 6 ； 8 ， 7 ； 6 ， 8 
|===


==== DR 组 1 — Site_A 上的堆栈 2

* DR 组 1 ： MC1_INIT_GRP_1_SITE_A_STK_GRP_2_TOP_FC1 ： *

|===
| FC 交换机 | 站点 | 交换机域 | Brocade 6505 ， 6510 ， 6520 ， G620 或 G610 交换机端口 | 连接到 ... 


| FC_switch_A_1 | 答 | 5. | 2. | controller_A_1 端口 0a 


| FC_switch_A_1 | 答 | 5. | 3. | controller_A_1 端口 0c 


| FC_switch_A_1 | 答 | 5. | 6. | controller_A_2 端口 0a 


| FC_switch_A_1 | 答 | 5. | 7. | controller_A_2 端口 0c 


| FC_switch_A_1 | 答 | 5. | 9 | bridge_A_2a FC1 


| FC_switch_B_1 | B | 7. | 2. | controller_B_1 端口 0a 


| FC_switch_B_1 | B | 7. | 3. | controller_B_1 端口 0c 


| FC_switch_B_1 | B | 7. | 6. | controller_B_2 端口 0a 


| FC_switch_B_1 | B | 7. | 7. | controller_B_2 端口 0c 
|===
|===


| Fabric_1 中的分区 | 成员端口 


| MC1_INIT_GRP_1_SITE_A_STK_GRP_2_TOP_FC1 | 5 ， 2 ； 5 ， 3 ； 5 ， 6 ； 5 ， 7 ； 7 ， 2 ； 7 ， 3 ； 7 ， 6 ； 7 ， 7 ； 5 ， 9 
|===
* DR 组 1 ： MC1_INIT_GRP_1_SITE_A_STK_GRP_2_BOT_FC1 ： *

|===
| FC 交换机 | 站点 | 交换机域 | Brocade 6505 ， 6510 ， 6520 ， G620 或 G610 交换机端口 | 连接到 ... 


| FC_switch_A_1 | 答 | 6. | 2. | controller_A_1 端口 0b 


| FC_switch_A_1 | 答 | 6. | 3. | controller_A_1 端口 0d 


| FC_switch_A_1 | 答 | 6. | 6. | controller_A_2 端口 0b 


| FC_switch_A_1 | 答 | 6. | 7. | controller_A_2 端口 0d 


| FC_switch_A_1 | 答 | 6. | 9 | bridge_A_2b FC1 


| FC_switch_B_1 | B | 8. | 2. | controller_B_1 端口 0b 


| FC_switch_B_1 | B | 8. | 3. | controller_B_1 端口 0d 


| FC_switch_B_1 | B | 8. | 6. | controller_B_2 端口 0b 


| FC_switch_B_1 | B | 8. | 7. | controller_B_2 端口 0d 
|===
|===


| Fabric_2 中的分区 | 成员端口 


| MC1_INIT_GRP_1_SITE_A_STK_GRP_2_BOT_FC1 | 6 ， 2 ； 6 ， 3 ； 6 ， 6 ； 6 ， 7 ； 8 ， 2 ； 8 ， 3 ； 8 ， 6 ； 8 ， 7 ； 6 ， 9 
|===


==== DR 组 1 — Site_B 上的堆栈 1

* MC1_INIT_GRP_1_SITE_B_STK_GRP_1_TOP_FC1 ： *

|===
| FC 交换机 | 站点 | 交换机域 | Brocade 6505 ， 6510 ， 6520 ， G620 或 G610 交换机 | 连接到 ... 


| FC_switch_A_1 | 答 | 5. | 2. | controller_A_1 端口 0a 


| FC_switch_A_1 | 答 | 5. | 3. | controller_A_1 端口 0c 


| FC_switch_A_1 | 答 | 5. | 6. | controller_A_2 端口 0a 


| FC_switch_A_1 | 答 | 5. | 7. | controller_A_2 端口 0c 


| FC_switch_B_1 | B | 7. | 2. | controller_B_1 端口 0a 


| FC_switch_B_1 | B | 7. | 3. | controller_B_1 端口 0c 


| FC_switch_B_1 | B | 7. | 6. | controller_B_2 端口 0a 


| FC_switch_B_1 | B | 7. | 7. | controller_B_2 端口 0c 


| FC_switch_B_1 | B | 7. | 8. | bridge_B_1a FC1 
|===
|===


| Fabric_1 中的分区 | 成员端口 


| MC1_INIT_GRP_1_SITE_B_STK_GRP_1_TOP_FC1 | 5 ， 2 ； 5 ， 3 ； 5 ， 6 ； 5 ， 7 ； 7 ， 2 ； 7 ， 3 ； 7 ， 6 ； 7 ， 7 ； 7 ， 8 
|===
* DR 组 1 ： MC1_INIT_GRP_1_SITE_B_STK_GRP_1_BOT_FC1 ： *

|===
| FC 交换机 | 站点 | 交换机域 | Brocade 6505 ， 6510 ， 6520 ， G620 或 G610 交换机 | 连接到 ... 


| FC_switch_A_1 | 答 | 6. | 2. | controller_A_1 端口 0b 


| FC_switch_A_1 | 答 | 6. | 3. | controller_A_1 端口 0d 


| FC_switch_A_1 | 答 | 6. | 6. | controller_A_2 端口 0b 


| FC_switch_A_1 | 答 | 6. | 7. | controller_A_2 端口 0d 


| FC_switch_B_1 | B | 8. | 2. | controller_B_1 端口 0b 


| FC_switch_B_1 | B | 8. | 3. | controller_B_1 端口 0d 


| FC_switch_B_1 | B | 8. | 6. | controller_B_2 端口 0b 


| FC_switch_B_1 | B | 8. | 7. | controller_B_2 端口 0d 


| FC_switch_B_1 | B | 8. | 8. | Bridge_B_1b FC1 
|===
|===


| Fabric_2 中的分区 | 成员端口 


| MC1_INIT_GRP_1_SITE_B_STK_GRP_1_BOT_FC1 | 5 ， 2 ； 5 ， 3 ； 5 ， 6 ； 5 ， 7 ； 7 ， 2 ； 7 ， 3 ； 7 ， 6 ； 7 ， 7 ； 8 
|===


==== DR 组 1 — Site_B 上的堆栈 2

* DR 组 1 ： MC1_INIT_GRP_1_SITE_B_STK_GRP_2_TOP_FC1 ： *

|===
| FC 交换机 | 站点 | 交换机域 | Brocade 6505 ， 6510 ， 6520 ， G620 或 G610 交换机端口 | 连接到 ... 


| FC_switch_A_1 | 答 | 5. | 2. | controller_A_1 端口 0a 


| FC_switch_A_1 | 答 | 5. | 3. | controller_A_1 端口 0c 


| FC_switch_A_1 | 答 | 5. | 6. | controller_A_2 端口 0a 


| FC_switch_A_1 | 答 | 5. | 7. | controller_A_2 端口 0c 


| FC_switch_B_1 | B | 7. | 2. | controller_B_1 端口 0a 


| FC_switch_B_1 | B | 7. | 3. | controller_B_1 端口 0c 


| FC_switch_B_1 | B | 7. | 6. | controller_B_2 端口 0a 


| FC_switch_B_1 | B | 7. | 7. | controller_B_2 端口 0c 


| FC_switch_B_1 | B | 7. | 9 | bridge_b_2a FC1 
|===
|===


| Fabric_1 中的分区 | 成员端口 


| MC1_INIT_GRP_1_SITE_b_STK_GRP_2_TOP_FC1 | 5 ， 2 ； 5 ， 3 ； 5 ， 6 ； 5 ， 7 ； 7 ， 2 ； 7 ， 3 ； 7 ， 6 ； 7 ， 7 ； 7 ， 9 
|===
* DR 组 1 ： MC1_INIT_GRP_1_SITE_B_STK_GRP_2_BOT_FC1 ： *

|===
| FC 交换机 | 站点 | 交换机域 | Brocade 6505 ， 6510 ， 6520 ， G620 或 G610 交换机端口 | 连接到 ... 


| FC_switch_A_1 | 答 | 6. | 2. | controller_A_1 端口 0b 


| FC_switch_A_1 | 答 | 6. | 3. | controller_A_1 端口 0d 


| FC_switch_A_1 | 答 | 6. | 6. | controller_A_2 端口 0b 


| FC_switch_A_1 | 答 | 6. | 7. | controller_A_2 端口 0d 


| FC_switch_B_1 | B | 8. | 2. | controller_B_1 端口 0b 


| FC_switch_B_1 | B | 8. | 3. | controller_B_1 端口 0d 


| FC_switch_B_1 | B | 8. | 6. | controller_B_2 端口 0b 


| FC_switch_B_1 | B | 8. | 7. | controller_B_2 端口 0d 


| FC_switch_B_1 | B | 8. | 9 | Bridge_B_1b FC1 
|===
|===


| Fabric_2 中的分区 | 成员端口 


| MC1_INIT_GRP_1_SITE_B_STK_GRP_2_BOT_FC1 | 6 ， 2 ； 6 ， 3 ； 6 ， 6 ； 6 ， 7 ； 8 ， 2 ； 8 ， 3 ； 8 ， 6 ； 8 ， 7 ； 8 ， 9 
|===


==== 存储分区摘要

|===


| 网络结构 | 分区名称 | 成员端口 


.4+| FC_switch_A_1 和 FC_switch_B_1 | MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1 | 5 ， 2 ； 5 ， 3 ； 5 ， 6 ； 5 ， 7 ； 7 ， 2 ； 7 ， 3 ； 7 ， 6 ； 7 ， 7 ； 5 ， 8 


| MC1_INIT_GRP_1_SITE_A_STK_GRP_2_TOP_FC1 | 5 ， 2 ； 5 ， 3 ； 5 ， 6 ； 5 ， 7 ； 7 ， 2 ； 7 ， 3 ； 7 ， 6 ； 7 ， 7 ； 5 ， 9 


| MC1_INIT_GRP_1_SITE_B_STK_GRP_1_TOP_FC1 | 5 ， 2 ； 5 ， 3 ； 5 ， 6 ； 5 ， 7 ； 7 ， 2 ； 7 ， 3 ； 7 ， 6 ； 7 ， 7 ； 7 ， 8 


| MC1_INIT_GRP_1_SITE_B_STK_GRP_2_TOP_FC1 | 5 ， 2 ； 5 ， 3 ； 5 ， 6 ； 5 ， 7 ； 7 ， 2 ； 7 ， 3 ； 7 ， 6 ； 7 ， 7 ； 7 ， 9 


.4+| FC_switch_A_2 和 FC_switch_B_2 | MC1_INIT_GRP_1_SITE_A_STK_GRP_1_BOT_FC1 | 6 ， 2 ； 6 ， 3 ； 6 ， 6 ； 6 ， 7 ； 8 ， 2 ； 8 ， 3 ； 8 ， 6 ； 8 ， 7 ； 6 ， 8 


| MC1_INIT_GRP_1_SITE_A_STK_GRP_2_BOT_FC1 | 6 ， 2 ； 6 ， 3 ； 6 ， 6 ； 6 ， 7 ； 8 ， 2 ； 8 ， 3 ； 8 ， 6 ； 8 ， 7 ； 6 ， 9 


| MC1_INIT_GRP_1_SITE_B_STK_GRP_1_BOT_FC1 | 6 ， 2 ； 6 ， 3 ； 6 ， 6 ； 6 ， 7 ； 8 ， 2 ； 8 ， 3 ； 8 ， 6 ； 8 ， 7 ； 8 ， 8 


| MC1_INIT_GRP_1_SITE_B_STK_GRP_2_BOT_FC1 | 6 ， 2 ； 6 ， 3 ； 6 ， 6 ； 6 ， 7 ； 8 ， 2 ； 8 ， 3 ； 8 ， 6 ； 8 ， 7 ； 8 ， 9 
|===


=== 使用两个 FC 端口的 FibreBridge 7500N 网桥的分区

如果您使用的是具有两个 FC 端口的 FibreBridge 7500N 网桥，则需要为网桥端口创建存储分区。在配置分区之前，您应了解分区和关联的端口。



==== 所需分区

您必须为每个 FC-SAS 网桥 FC 端口配置一个分区，以允许每个控制器模块上的启动程序与该 FC-SAS 网桥之间的流量。

每个存储分区包含五个端口：

* 四个 HBA 启动程序端口（每个控制器一个连接）
* 一个端口连接到 FC-SAS 网桥 FC 端口


存储分区使用标准分区。

这些示例显示了两对网桥，用于连接每个站点的两个堆栈组。由于每个网桥使用一个 FC 端口，因此每个网络结构共有八个存储分区（总共十六个）。



==== 网桥命名

网桥使用以下命名示例： bridge_site_stack groupocation in pair

|===


| 名称的这一部分 ... | 标识 ... | 可能值 ... 


 a| 
站点
 a| 
网桥对实际所在的站点。
 a| 
A 或 B



 a| 
堆栈组
 a| 
网桥对连接到的堆栈组的编号。

* FibreBridge 7600N 或 7500N 网桥最多支持堆栈组中的四个堆栈。
+
堆栈组包含的存储架不能超过 10 个。

* FibreBridge 6500N 网桥仅支持堆栈组中的一个堆栈。

 a| 
1 ， 2 等



 a| 
成对位置
 a| 
网桥对中的网桥。一对网桥连接到特定堆栈组。
 a| 
a 或 b

|===
每个站点上一个堆栈组的网桥名称示例：

* bridge_A_1a
* bridge_A_1b
* bridge_B_1a
* bridge_B_1b




==== DR 组 1 — Site_A 上的堆栈 1

* DR 组 1 ： MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1 ： *

|===


| FC 交换机 | 站点 | 交换机域 | 6505/6510/G610/G620 端口 | 6520 端口 | 连接到 ... 


 a| 
FC_switch_A_1
 a| 
答
 a| 
5.
 a| 
2.
 a| 
2.
 a| 
controller_A_1 端口 0a



 a| 
FC_switch_A_1
 a| 
答
 a| 
5.
 a| 
6.
 a| 
6.
 a| 
controller_A_2 端口 0a



 a| 
FC_switch_A_1
 a| 
答
 a| 
5.
 a| 
8.
 a| 
8.
 a| 
bridge_A_1a FC1



 a| 
FC_switch_B_1
 a| 
B
 a| 
7.
 a| 
2.
 a| 
2.
 a| 
controller_B_1 端口 0a



 a| 
FC_switch_B_1
 a| 
B
 a| 
7.
 a| 
6.
 a| 
6.
 a| 
controller_B_2 端口 0a

|===
|===


| Fabric_1 中的分区 | 成员端口 


 a| 
MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1
 a| 
5 ， 2 ； 5 ， 6 ； 7 ， 2 ； 7 ， 6 ； 5 ， 8

|===
* DR 组 1 ： MC1_INIT_GRP_2_SITE_A_STK_GRP_1_TOP_FC1 ： *

|===


| FC 交换机 | 站点 | 交换机域 | 6505/6510/G610 端口 | 6520 端口 | G620 端口 | 连接到 ... 


 a| 
FC_switch_A_1
 a| 
答
 a| 
5.
 a| 
3.
 a| 
3.
 a| 
3.
 a| 
controller_A_1 端口 0c



 a| 
FC_switch_A_1
 a| 
答
 a| 
5.
 a| 
7.
 a| 
7.
 a| 
7.
 a| 
controller_A_2 端口 0c



 a| 
FC_switch_A_1
 a| 
答
 a| 
5.
 a| 
9
 a| 
9
 a| 
9
 a| 
bridge_A_1b FC1



 a| 
FC_switch_B_1
 a| 
B
 a| 
7.
 a| 
3.
 a| 
3.
 a| 
3.
 a| 
controller_B_1 端口 0c



 a| 
FC_switch_B_1
 a| 
B
 a| 
7.
 a| 
7.
 a| 
7.
 a| 
7.
 a| 
controller_B_2 端口 0c

|===
|===


| Fabric_2 中的分区 | 成员端口 


 a| 
MC1_INIT_GRP_2_SITE_A_STK_GRP_1_BOT_FC1
 a| 
5 ， 3 ； 5 ， 7 ； 7 ， 3 ； 7 ， 7 ； 5 ， 9

|===
* DR 组 1 ： MC1_INIT_GRP_1_SITE_A_STK_GRP_1_BOT_FC1 ： *

|===


| FC 交换机 | 站点 | 交换机域 | 6505/6510/G610 | 6520 | G620 | 连接到 ... 


 a| 
FC_switch_A_2
 a| 
答
 a| 
6.
 a| 
2.
 a| 
2.
 a| 
2.
 a| 
controller_A_1 端口 0d



 a| 
FC_switch_A_2
 a| 
答
 a| 
6.
 a| 
6.
 a| 
6.
 a| 
6.
 a| 
controller_A_2 端口 0d



 a| 
FC_switch_A_2
 a| 
答
 a| 
6.
 a| 
8.
 a| 
8.
 a| 
8.
 a| 
bridge_A_1a FC2



 a| 
FC_switch_B_2
 a| 
B
 a| 
8.
 a| 
2.
 a| 
2.
 a| 
2.
 a| 
controller_B_1 端口 0b



 a| 
FC_switch_B_2
 a| 
B
 a| 
8.
 a| 
6.
 a| 
6.
 a| 
6.
 a| 
controller_B_2 端口 0b

|===
|===


| Fabric_1 中的分区 | 成员端口 


 a| 
MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC2
 a| 
6 ， 2 ； 6 ， 6 ； 8 ， 2 ； 8 ， 6 ； 6 ， 8

|===
* DR 组 1 ： MC1_INIT_GRP_2_SITE_A_STK_GRP_1_BOT_FC2 ： *

|===


| FC 交换机 | 站点 | 交换机域 | 6505/6510/G610 | 6520 | G620 | 连接到 ... 


 a| 
FC_switch_A_2
 a| 
答
 a| 
6.
 a| 
3.
 a| 
3.
 a| 
3.
 a| 
controller_A_1 端口 0d



 a| 
FC_switch_A_2
 a| 
答
 a| 
6.
 a| 
7.
 a| 
7.
 a| 
7.
 a| 
controller_A_2 端口 0d



 a| 
FC_switch_A_2
 a| 
答
 a| 
6.
 a| 
9
 a| 
9
 a| 
9
 a| 
bridge_A_1b FC2



 a| 
FC_switch_B_2
 a| 
B
 a| 
8.
 a| 
3.
 a| 
3.
 a| 
3.
 a| 
controller_B_1 端口 0b



 a| 
FC_switch_B_2
 a| 
B
 a| 
8.
 a| 
7.
 a| 
7.
 a| 
7.
 a| 
controller_B_2 端口 0b

|===
|===


| Fabric_2 中的分区 | 成员端口 


 a| 
MC1_INIT_GRP_2_SITE_A_STK_GRP_1_BOT_FC2
 a| 
6 ， 3 ； 6 ， 7 ； 8 ， 3 ； 8 ， 7 ； 6 ， 9

|===


==== DR 组 1 — Site_A 上的堆栈 2

* DR 组 1 ： MC1_INIT_GRP_1_SITE_A_STK_GRP_2_TOP_FC1 ： *

|===


| FC 交换机 | 站点 | 交换机域 | 6505/6510/G610 端口 | 6520 端口 | G620 端口 | 连接到 ... 


 a| 
FC_switch_A_1
 a| 
答
 a| 
5.
 a| 
2.
 a| 
2.
 a| 
2.
 a| 
controller_A_1 端口 0a



 a| 
FC_switch_A_1
 a| 
答
 a| 
5.
 a| 
6.
 a| 
6.
 a| 
6.
 a| 
controller_A_2 端口 0a



 a| 
FC_switch_A_1
 a| 
答
 a| 
5.
 a| 
10
 a| 
10
 a| 
10
 a| 
bridge_A_2a FC1



 a| 
FC_switch_B_1
 a| 
B
 a| 
7.
 a| 
2.
 a| 
2.
 a| 
2.
 a| 
controller_B_1 端口 0a



 a| 
FC_switch_B_1
 a| 
B
 a| 
7.
 a| 
6.
 a| 
6.
 a| 
6.
 a| 
controller_B_2 端口 0a

|===
|===


| Fabric_1 hh 中的分区 | 成员端口 


 a| 
MC1_INIT_GRP_1_SITE_A_STK_GRP_2_TOP_FC1
 a| 
5 ， 2 ； 5 ， 6 ； 7 ， 2 ； 7 ， 6 ； 5 ， 10

|===
* DR 组 1 ： MC1_INIT_GRP_2_SITE_A_STK_GRP_2_TOP_FC1 ： *

|===


| FC 交换机 | 站点 | 交换机域 | 6505/6510/G610 端口 | 6520 端口 | G620 端口 | 连接到 ... 


 a| 
FC_switch_A_1
 a| 
答
 a| 
5.
 a| 
3.
 a| 
3.
 a| 
3.
 a| 
controller_A_1 端口 0c



| FC_switch_A_1  a| 
答
 a| 
5.
 a| 
7.
 a| 
7.
 a| 
7.
 a| 
controller_A_2 端口 0c



| FC_switch_A_1  a| 
答
 a| 
5.
 a| 
11.
 a| 
11.
 a| 
11.
 a| 
bridge_A_2b FC1



 a| 
FC_switch_B_1
 a| 
B
 a| 
7.
 a| 
3.
 a| 
3.
 a| 
3.
 a| 
controller_B_1 端口 0c



 a| 
FC_switch_B_1
 a| 
B
 a| 
7.
 a| 
7.
 a| 
7.
 a| 
7.
 a| 
controller_B_2 端口 0c

|===
|===


| Fabric_2 中的分区 | 成员端口 


 a| 
MC1_INIT_GRP_2_SITE_A_STK_GRP_2_BOT_FC1
 a| 
5 ， 3 ； 5 ， 7 ； 7 ， 3 ； 7 ， 7 ； 5 ， 11

|===
* DR 组 1 ： MC1_INIT_GRP_1_SITE_A_STK_GRP_2_BOT_FC2 ： *

|===


| FC 交换机 | 站点 | 交换机域 | 6505/6510/G610 端口 | 6520 端口 | G620 端口 | 连接到 ... 


 a| 
FC_switch_A_2
 a| 
答
 a| 
6.
 a| 
2.
 a| 
0
 a| 
0
 a| 
controller_A_1 端口 0d



 a| 
FC_switch_A_2
 a| 
答
 a| 
6.
 a| 
6.
 a| 
4.
 a| 
4.
 a| 
controller_A_2 端口 0b



 a| 
FC_switch_A_2
 a| 
答
 a| 
6.
 a| 
10
 a| 
10
 a| 
10
 a| 
bridge_A_2a FC2



 a| 
FC_switch_B_2
 a| 
B
 a| 
8.
 a| 
2.
 a| 
2.
 a| 
2.
 a| 
controller_B_1 端口 0b



 a| 
FC_switch_B_2
 a| 
B
 a| 
8.
 a| 
6.
 a| 
6.
 a| 
6.
 a| 
controller_B_2 端口 0b

|===
|===


| Fabric_1 中的分区 | 成员端口 


 a| 
MC1_INIT_GRP_1_SITE_A_STK_GRP_2_TOP_FC2
 a| 
6 ， 2 ； 6 ， 6 ； 8 ， 2 ； 8 ， 6 ； 6 ， 10

|===
* DR 组 1 ： MC1_INIT_GRP_2_SITE_A_STK_GRP_2_BOT_FC2 ： *

|===


| FC 交换机 | 站点 | 交换机域 | 6505/6510/G610 端口 | 6520 端口 | G620 端口 | 连接到 ... 


 a| 
FC_switch_A_2
 a| 
答
 a| 
6.
 a| 
3.
 a| 
3.
 a| 
3.
 a| 
controller_A_1 端口 0d



 a| 
FC_switch_A_2
 a| 
答
 a| 
6.
 a| 
7.
 a| 
7.
 a| 
7.
 a| 
controller_A_2 端口 0b



 a| 
FC_switch_A_2
 a| 
答
 a| 
6.
 a| 
11.
 a| 
11.
 a| 
11.
 a| 
bridge_A_2b FC2



 a| 
FC_switch_B_2
 a| 
B
 a| 
8.
 a| 
3.
 a| 
3.
 a| 
3.
 a| 
controller_B_1 端口 0b\



 a| 
FC_switch_B_2
 a| 
B
 a| 
8.
 a| 
7.
 a| 
7.
 a| 
7.
 a| 
controller_B_2 端口 0b

|===
|===


| Fabric_2 中的分区 | 成员端口 


 a| 
MC1_INIT_GRP_2_SITE_A_STK_GRP_2_BOT_FC2
 a| 
6 ， 3 ； 6 ， 7 ； 8 ， 3 ； 8 ， 7 ； 6 ， 11

|===


==== DR 组 1 — Site_B 上的堆栈 1

* DR 组 1 ： MC1_INIT_GRP_1_SITE_B_STK_GRP_1_TOP_FC1 ： *

|===


| FC 交换机 | 站点 | 交换机域 | 6505/6510/G610 端口 | 6520 端口 | G620 端口 | 连接到 ... 


 a| 
FC_switch_A_1
 a| 
答
 a| 
5.
 a| 
2.
 a| 
2.
 a| 
2.
 a| 
controller_A_1 端口 0a



 a| 
FC_switch_A_1
 a| 
答
 a| 
5.
 a| 
6.
 a| 
6.
 a| 
6.
 a| 
controller_A_2 端口 0a



 a| 
FC_switch_B_1
 a| 
B
 a| 
7.
 a| 
2.
 a| 
2.
 a| 
8.
 a| 
controller_B_1 端口 0a



 a| 
FC_switch_B_1
 a| 
B
 a| 
7.
 a| 
6.
 a| 
6.
 a| 
2.
 a| 
controller_B_2 端口 0a



 a| 
FC_switch_B_1
 a| 
B
 a| 
7.
 a| 
8.
 a| 
8.
 a| 
6.
 a| 
bridge_B_1a FC1

|===
|===


| Fabric_1 中的分区 | 成员端口 


 a| 
MC1_INIT_GRP_1_SITE_B_STK_GRP_1_TOP_FC1
 a| 
5 ， 2 ； 5 ， 6 ； 7 ， 2 ； 7 ， 6 ； 7 ， 8

|===
* DR 组 1 ： MC1_INIT_GRP_2_SITE_B_STK_GRP_1_TOP_FC1 ： *

|===


| FC 交换机 | 站点 | 交换机域 | 6505/6510/G610 端口 | 6520 端口 | G620 端口 | 连接到 ... 


 a| 
FC_switch_A_1
 a| 
答
 a| 
5.
 a| 
3.
 a| 
3.
 a| 
3.
 a| 
controller_A_1 端口 0c



 a| 
FC_switch_A_1
 a| 
答
 a| 
5.
 a| 
7.
 a| 
7.
 a| 
7.
 a| 
controller_A_2 端口 0c



 a| 
FC_switch_B_1
 a| 
B
 a| 
7.
 a| 
3.
 a| 
3.
 a| 
9
 a| 
controller_B_1 端口 0c



 a| 
FC_switch_B_1
 a| 
B
 a| 
7.
 a| 
7.
 a| 
7.
 a| 
3.
 a| 
controller_B_2 端口 0c



 a| 
FC_switch_B_1
 a| 
B
 a| 
7.
 a| 
9
 a| 
9
 a| 
7.
 a| 
Bridge_B_1b FC1

|===
|===


| Fabric_2 中的分区 | 成员端口 


 a| 
MC1_INIT_GRP_2_SITE_B_STK_GRP_1_BOT_FC1
 a| 
5 ， 3 ； 5 ， 7 ； 7 ， 3 ； 7 ， 7 ； 7 ， 9

|===
* DR 组 1 ： MC1_INIT_GRP_1_SITE_B_STK_GRP_1_BOT_FC2 ： *

|===


| FC 交换机 | 站点 | 交换机域 | 6505/6510/G610 端口 | 6520 端口 | G620 端口 | 连接到 ... 


 a| 
FC_switch_A_2
 a| 
答
 a| 
6.
 a| 
2.
 a| 
2.
 a| 
2.
 a| 
controller_A_1 端口 0d



 a| 
FC_switch_A_2
 a| 
答
 a| 
6.
 a| 
6.
 a| 
6.
 a| 
6.
 a| 
controller_A_2 端口 0b



 a| 
FC_switch_B_2
 a| 
B
 a| 
8.
 a| 
2.
 a| 
2.
 a| 
2.
 a| 
controller_B_1 端口 0b



 a| 
FC_switch_B_2
 a| 
B
 a| 
8.
 a| 
6.
 a| 
6.
 a| 
6.
 a| 
controller_B_2 端口 0b



 a| 
FC_switch_B_2
 a| 
B
 a| 
8.
 a| 
8.
 a| 
8.
 a| 
8.
 a| 
bridge_B_1a FC2

|===
|===
| Fabric_1 中的分区 | 成员端口 


 a| 
MC1_INIT_GRP_1_SITE_B_STK_GRP_1_TOP_FC2
 a| 
6 ， 2 ； 6 ， 6 ； 8 ， 2 ； 8 ， 6 ； 8 ， 8

|===
* DR 组 1 ： MC1_INIT_GRP_2_SITE_B_STK_GRP_1_BOT_FC2 ： *

|===


| FC 交换机 | 站点 | 交换机域 | 6505/6510/G610 端口 | 6520 端口 | G620 端口 | 连接到 ... 


 a| 
FC_switch_A_2
 a| 
答
 a| 
6.
 a| 
3.
 a| 
3.
 a| 
3.
 a| 
controller_A_1 端口 0d



 a| 
FC_switch_A_2
 a| 
答
 a| 
6.
 a| 
7.
 a| 
7.
 a| 
7.
 a| 
controller_A_2 端口 0b



 a| 
FC_switch_B_2
 a| 
B
 a| 
8.
 a| 
3.
 a| 
3.
 a| 
3.
 a| 
controller_B_1 端口 0b



 a| 
FC_switch_B_2
 a| 
B
 a| 
8.
 a| 
7.
 a| 
7.
 a| 
7.
 a| 
controller_B_2 端口 0b



 a| 
FC_switch_B_2
 a| 
B
 a| 
8.
 a| 
9
 a| 
9
 a| 
9
 a| 
bridge_A_1b FC2

|===
|===


| Fabric_2 中的分区 | 成员端口 


 a| 
MC1_INIT_GRP_2_SITE_B_STK_GRP_1_BOT_FC2
 a| 
6 ， 3 ； 6 ， 7 ； 8 ， 3 ； 8 ， 7 ； 8 ， 9

|===


==== DR 组 1 — Site_B 上的堆栈 2

* DR 组 1 ： MC1_INIT_GRP_1_SITE_B_STK_GRP_2_TOP_FC1 ： *

|===


| FC 交换机 | 站点 | 交换机域 | 6505/6510/G610 端口 | 6520 端口 | G620 端口 | 连接到 ... 


 a| 
FC_switch_A_1
 a| 
答
 a| 
5.
 a| 
2.
 a| 
2.
 a| 
2.
 a| 
controller_A_1 端口 0a



 a| 
FC_switch_A_1
 a| 
答
 a| 
5.
 a| 
6.
 a| 
6.
 a| 
6.
 a| 
controller_A_2 端口 0a



 a| 
FC_switch_B_1
 a| 
B
 a| 
7.
 a| 
2.
 a| 
2.
 a| 
2.
 a| 
controller_B_1 端口 0a



 a| 
FC_switch_B_1
 a| 
B
 a| 
7.
 a| 
6.
 a| 
6.
 a| 
6.
 a| 
controller_B_2 端口 0a



 a| 
FC_switch_B_1
 a| 
B
 a| 
7.
 a| 
10
 a| 
10
 a| 
10
 a| 
bridge_B_2a FC1

|===
|===


| Fabric_1 中的分区 | 成员端口 


 a| 
MC1_INIT_GRP_1_SITE_B_STK_GRP_2_TOP_FC1
 a| 
5 ， 2 ； 5 ， 6 ； 7 ， 2 ； 7 ， 6 ； 7 ， 10

|===
* DR 组 1 ： MC1_INIT_GRP_2_SITE_B_STK_GRP_2_TOP_FC1 ： *

|===


| FC 交换机 | 站点 | 交换机域 | 6505/6510/G610 端口 | 6520 端口 | G620 端口 | 连接到 ... 


 a| 
FC_switch_A_1
 a| 
答
 a| 
5.
 a| 
3.
 a| 
3.
 a| 
3.
 a| 
controller_A_1 端口 0c



 a| 
FC_switch_A_1
 a| 
答
 a| 
5.
 a| 
7.
 a| 
7.
 a| 
7.
 a| 
controller_A_2 端口 0c



 a| 
FC_switch_B_1
 a| 
B
 a| 
7.
 a| 
3.
 a| 
3.
 a| 
3.
 a| 
controller_B_1 端口 0c



 a| 
FC_switch_B_1
 a| 
B
 a| 
7.
 a| 
7.
 a| 
7.
 a| 
7.
 a| 
controller_B_2 端口 0c



 a| 
FC_switch_B_1
 a| 
B
 a| 
7.
 a| 
11.
 a| 
11.
 a| 
11.
 a| 
bridge_B_2b FC1

|===
|===


| Fabric_2 hh 中的分区 | 成员端口 


 a| 
MC1_INIT_GRP_2_SITE_B_STK_GRP_2_BOT_FC1
 a| 
5 ， 3 ； 5 ， 7 ； 7 ， 3 ； 7 ， 7 ； 7 ， 11

|===
* DR 组 1 ： MC1_INIT_GRP_1_SITE_B_STK_GRP_2_BOT_FC2 ： *

|===


| FC 交换机 | 站点 | 交换机域 | 6505/6510/G610 端口 | 6520 端口 | G620 端口 | 连接到 ... 


 a| 
FC_switch_A_2
 a| 
答
 a| 
6.
 a| 
2.
 a| 
2.
 a| 
2.
 a| 
controller_A_1 端口 d



 a| 
FC_switch_A_2
 a| 
答
 a| 
6.
 a| 
6.
 a| 
6.
 a| 
6.
 a| 
controller_A_2 端口 0b



 a| 
FC_switch_B_2
 a| 
B
 a| 
8.
 a| 
2.
 a| 
2.
 a| 
2.
 a| 
controller_B_1 端口 0b



 a| 
FC_switch_B_2
 a| 
B
 a| 
8.
 a| 
6.
 a| 
6.
 a| 
6.
 a| 
controller_B_2 端口 0b



 a| 
FC_switch_B_2
 a| 
B
 a| 
8.
 a| 
10
 a| 
10
 a| 
10
 a| 
bridge_B_2a FC2

|===
|===


| Fabric_1 中的分区 | 成员端口 


 a| 
MC1_INIT_GRP_1_SITE_B_STK_GRP_2_TOP_FC2
 a| 
6 ， 2 ； 6 ， 6 ； 8 ， 2 ； 8 ， 6 ； 8 ， 10

|===
* DR 组 1 ： MC1_INIT_GRP_2_SITE_B_STK_GRP_2_BOT_FC2 ： *

|===


| FC 交换机 | 站点 | 交换机域 | 6505/6510/G610 端口 | 6520 端口 | G620 端口 | 连接到 ... 


 a| 
FC_switch_A_2
 a| 
答
 a| 
6.
 a| 
3.
 a| 
3.
 a| 
3.
 a| 
controller_A_1 端口 0d



 a| 
FC_switch_A_2
 a| 
答
 a| 
6.
 a| 
7.
 a| 
7.
 a| 
7.
 a| 
controller_A_2 端口 0b



 a| 
FC_switch_B_2
 a| 
B
 a| 
8.
 a| 
3.
 a| 
3.
 a| 
3.
 a| 
controller_B_1 端口 0b



 a| 
FC_switch_B_2
 a| 
B
 a| 
8.
 a| 
7.
 a| 
7.
 a| 
7.
 a| 
controller_B_2 端口 0b



 a| 
FC_switch_B_2
 a| 
B
 a| 
8.
 a| 
11.
 a| 
11.
 a| 
11.
 a| 
bridge_B_2b FC2

|===
|===


| Fabric_2 中的分区 | 成员端口 


 a| 
MC1_INIT_GRP_2_SITE_B_STK_GRP_2_BOT_FC2
 a| 
6 ， 3 ； 6 ， 7 ； 8 ， 3 ； 8 ， 7 ； 8 ， 11

|===


==== 存储分区摘要

|===


| 网络结构 | 分区名称 | 成员端口 


 a| 
FC_switch_A_1 和 FC_switch_B_1
 a| 
MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1
 a| 
5 ， 2 ； 5 ， 6 ； 7 ， 2 ； 7 ， 6 ； 5 ， 8



 a| 
FC_switch_A_1 和 FC_switch_B_1
 a| 
MC1_INIT_GRP_2_SITE_A_STK_GRP_1_BOT_FC1
 a| 
5 ， 3 ； 5 ， 7 ； 7 ， 3 ； 7 ， 7 ； 5 ， 9



 a| 
FC_switch_A_1 和 FC_switch_B_1
 a| 
MC1_INIT_GRP_1_SITE_A_STK_GRP_2_TOP_FC1
 a| 
5 ， 2 ； 5 ， 6 ； 7 ， 2 ； 7 ， 6 ； 5 ， 10



 a| 
FC_switch_A_1 和 FC_switch_B_1
 a| 
MC1_INIT_GRP_2_SITE_A_STK_GRP_2_BOT_FC1
 a| 
5 ， 3 ； 5 ， 7 ； 7 ， 3 ； 7 ， 7 ； 5 ， 11



 a| 
FC_switch_A_1 和 FC_switch_B_1
 a| 
MC1_INIT_GRP_1_SITE_B_STK_GRP_1_TOP_FC1
 a| 
5 ， 2 ； 5 ， 6 ； 7 ， 2 ； 7 ， 6 ； 7 ， 8



 a| 
FC_switch_A_1 和 FC_switch_B_1
 a| 
MC1_INIT_GRP_2_SITE_B_STK_GRP_1_BOT_FC1
 a| 
5 ， 3 ； 5 ， 7 ； 7 ， 3 ； 7 ， 7 ； 7 ， 9



 a| 
FC_switch_A_1 和 FC_switch_B_1
 a| 
MC1_INIT_GRP_1_SITE_B_STK_GRP_2_TOP_FC1
 a| 
5 ， 2 ； 5 ， 6 ； 7 ， 2 ； 7 ， 6 ； 7 ， 10



 a| 
FC_switch_A_1 和 FC_switch_B_1
 a| 
MC1_INIT_GRP_2_SITE_B_STK_GRP_2_BOT_FC1
 a| 
5 ， 3 ； 5 ， 7 ； 7 ， 3 ； 7 ， 7 ； 7 ， 11



 a| 
FC_switch_A_2 和 FC_switch_B_2
 a| 
MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC2
 a| 
6 ， 2 ； 6 ， 6 ； 8 ， 2 ； 8 ， 6 ； 6 ， 8



 a| 
FC_switch_A_2 和 FC_switch_B_2
 a| 
MC1_INIT_GRP_2_SITE_A_STK_GRP_1_BOT_FC2
 a| 
6 ， 3 ； 6 ， 7 ； 8 ， 3 ； 8 ， 7 ； 6 ， 9



 a| 
FC_switch_A_2 和 FC_switch_B_2
 a| 
MC1_INIT_GRP_1_SITE_A_STK_GRP_2_TOP_FC2
 a| 
6 ， 2 ； 6 ， 6 ； 8 ， 2 ； 8 ， 6 ； 6 ， 10



 a| 
FC_switch_A_2 和 FC_switch_B_2
 a| 
MC1_INIT_GRP_2_SITE_A_STK_GRP_2_BOT_FC2
 a| 
6 ， 3 ； 6 ， 7 ； 8 ， 3 ； 8 ， 7 ； 6 ， 11



 a| 
FC_switch_A_2 和 FC_switch_B_2
 a| 
MC1_INIT_GRP_1_SITE_B_STK_GRP_1_TOP_FC2
 a| 
6 ， 2 ； 6 ， 6 ； 8 ， 2 ； 8 ， 6 ； 8 ， 8



 a| 
FC_switch_A_2 和 FC_switch_B_2
 a| 
MC1_INIT_GRP_2_SITE_B_STK_GRP_1_BOT_FC2
 a| 
6 ， 3 ； 6 ， 7 ； 8 ， 3 ； 8 ， 7 ； 8 ， 9



 a| 
FC_switch_A_2 和 FC_switch_B_2
 a| 
MC1_INIT_GRP_1_SITE_B_STK_GRP_2_TOP_FC2
 a| 
6 ， 2 ； 6 ， 6 ； 8 ， 2 ； 8 ， 6 ； 8 ， 10



 a| 
FC_switch_A_2 和 FC_switch_B_2
 a| 
MC1_INIT_GRP_2_SITE_B_STK_GRP_2_BOT_FC2
 a| 
6 ， 3 ； 6 ， 7 ； 8 ， 3 ； 8 ， 7 ； 8 ， 11

|===


=== 在 Brocade FC 交换机上配置分区

您必须将交换机端口分配给不同的分区，以隔离控制器和存储流量，并为 FC-VI 端口分配分区，为存储端口分配分区。

以下步骤对 MetroCluster 配置使用标准分区。

link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["FC-VI 端口的分区"]

link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["使用一个 FC 端口为 FibreBridge 6500N 网桥， FibreBridge 7500N 或 7600N 网桥分区"]

link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["使用两个 FC 端口的 FibreBridge 7500N 网桥的分区"]

.步骤
. 在每个交换机上创建 FC-VI 分区：
+
`zonecreate "QOSH1_FCVI_1" ， member ； member ...`

+
在此示例中，创建了一个 QoS FCVI 区域，其中包含端口 5 ， 0 ； 5 ， 1 ； 5 ， 4 ； 5 ， 5 ； 7 ， 0 ； 7 ， 1 ； 7 ， 4 ； 7 ， 5 ：

+
[listing]
----
Switch_A_1:admin> zonecreate "QOSH1_FCVI_1", "5,0;5,1;5,4;5,5;7,0;7,1;7,4;7,5"
----
. 在每个交换机上配置存储分区。
+
您可以从网络结构中的一个交换机为网络结构配置分区。在以下示例中，分区是在 Switch_A_1 上配置的。

+
.. 为交换机网络结构中的每个交换机域创建存储分区：
+
`zonecreate name ， member ； member ...`

+
在此示例中，正在为使用两个 FC 端口的 FibreBridge 7500N 创建存储分区。这些分区包含端口 5 ， 2 ； 5 ， 6 ； 7 ， 2 ； 7 ， 6 ； 5 ， 16 ：

+
[listing]
----
Switch_A_1:admin> zonecreate "MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1", "5,2;5,6;7,2;7,6;5,16"
----
.. 在第一个交换机网络结构中创建配置：
+
`cfgcreate config_name ， zone ； zone...`

+
在此示例中，将创建一个名为 CFG_1 的配置，并创建两个分区 QOSH1_MC1_FAB_1_FCVI 和 MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1

+
[listing]
----
Switch_A_1:admin> cfgcreate "CFG_1", "QOSH1_MC1_FAB_1_FCVI; MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1"
----
.. 根据需要向配置中添加分区：
+
`cfgadd config_namezone ； zone...`

.. 启用配置：
+
`cfgenable config_name`

+
[listing]
----
Switch_A_1:admin> cfgenable "CFG_1"
----
.. 保存配置：
+
`cfgsave`

+
[listing]
----
Switch_A_1:admin> cfgsave
----
.. 验证分区配置：
+
`zone -validate`

+
[listing]
----
Switch_A_1:admin> zone --validate
Defined configuration:
cfg: CFG_1 QOSH1_MC1_FAB_1_FCVI ; MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1
zone: QOSH1_MC1_FAB_1_FCVI
5,0;5,1;5,4;5,5;7,0;7,1;7,4;7,5
zone: MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1
5,2;5,6;7,2;7,6;5,16
Effective configuration:
cfg: CFG_1
zone: QOSH1_MC1_FAB_1_FCVI
5,0
5,1
5,4
5,5
7,0
7,1
7,4
7,5
zone: MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1
5,2
5,6
7,2
7,6
5,16
------------------------------------
~ - Invalid configuration
* - Member does not exist
# - Invalid usage of broadcast zone
----






== 在 Brocade 6510 或 G620 交换机上设置 ISL 加密

在 Brocade 6510 或 G620 交换机上，您可以选择在 ISL 连接上使用 Brocade 加密功能。如果要使用加密功能，必须对 MetroCluster 配置中的每个交换机执行其他配置步骤。

.开始之前
* 您必须具有 Brocade 6510 或 G620 交换机。
+

NOTE: 只有 ONTAP 9.4 及更高版本才支持在 Brocade G620 交换机上使用 ISL 加密。

* 您必须已从同一网络结构中选择两个交换机。
* 您必须已查看适用于您的交换机和网络结构操作系统版本的 Brocade 文档，以确认带宽和端口限制。


必须对同一网络结构中的两个交换机执行这些步骤。



=== 正在禁用虚拟网络结构

要设置 ISL 加密，必须在 MetroCluster 配置中使用的所有四个交换机上禁用虚拟网络结构。

.步骤
. 在交换机控制台中输入以下命令，以禁用虚拟网络结构：
+
`fosconfig -disable vf`

. 重新启动交换机。




=== 设置有效负载

禁用虚拟网络结构后，必须在网络结构中的两个交换机上设置有效负载或数据字段大小。

数据字段大小不得超过 2048 。

.步骤
. 禁用交换机：
+
`sswitchdisable`

. 配置和设置有效负载：
+
`配置`

. 设置以下交换机参数：
+
.. 将 Fabric 参数设置为： `y`
.. 设置其他参数，例如域，基于 WWN 的永久性 PID 等。
.. 设置数据字段大小： `2048`






=== 设置身份验证策略

您必须设置身份验证策略和关联参数。

必须在交换机控制台上执行这些命令。

.步骤
. 设置身份验证密钥：
+
.. 开始设置过程：
+
`secAuthSecret — -set`

+
此命令将启动一系列提示，您可以在以下步骤中对其做出响应：

.. 为 "Enter peer WWN ， Domain ， or switch name" 参数提供网络结构中另一个交换机的全球通用名称（ WWN ）。
.. 为 "Enter peer secret" 参数提供对等密钥。
.. 为 "Enter local secret" 参数提供本地密钥。
.. 为 "Are you done" 参数输入 `Y` 。
+
--
以下是设置身份验证密钥的示例：

[listing]
----
brcd> secAuthSecret --set

This command is used to set up secret keys for the DH-CHAP authentication.
The minimum length of a secret key is 8 characters and maximum 40
characters. Setting up secret keys does not initiate DH-CHAP
authentication. If switch is configured to do DH-CHAP, it is performed
whenever a port or a switch is enabled.

Warning: Please use a secure channel for setting secrets. Using
an insecure channel is not safe and may compromise secrets.

Following inputs should be specified for each entry.

1. WWN for which secret is being set up.
2. Peer secret: The secret of the peer that authenticates to peer.
3. Local secret: The local secret that authenticates peer.

Press enter to start setting up secrets > <cr>

Enter peer WWN, Domain, or switch name (Leave blank when done): 10:00:00:05:33:76:2e:99
Enter peer secret: <hidden>
Re-enter peer secret: <hidden>
Enter local secret: <hidden>
Re-enter local secret: <hidden>

Enter peer WWN, Domain, or switch name (Leave blank when done):
Are you done? (yes, y, no, n): [no] yes
Saving data to key store... Done.
----
--


. 将身份验证组设置为 4 ：
+
`authUtil -set -g 4`

. 将身份验证类型设置为 "dhchap" ：
+
`authUtil -set -a dhchap`

+
系统将显示以下输出：

+
[listing]
----
Authentication is set to dhchap.
----
. 将交换机上的身份验证策略设置为 on ：
+
`authUtil -policy -sw on`

+
系统将显示以下输出：

+
[listing]
----
Warning: Activating the authentication policy requires either DH-CHAP secrets or PKI certificates depending on the protocol selected. Otherwise, ISLs will be segmented during next E-port bring-up.
ARE YOU SURE  (yes, y, no, n): [no] yes
Auth Policy is set to ON
----




=== 在 Brocade 交换机上启用 ISL 加密

设置身份验证策略和身份验证密钥后，必须在端口上启用 ISL 加密，才能使其生效。

.关于此任务
* 这些步骤应一次对一个交换机网络结构执行。
* 这些命令必须在交换机控制台运行。


.步骤
. 在所有 ISL 端口上启用加密：
+
`portCfgEncrypt -enable port_number`

+
在以下示例中，在端口 8 和 12 上启用加密：

+
`portCfgEncrypt —启用 8`

+
`portCfgEncrypt —启用 12`

. 启用交换机：
+
`sswitchenable`

. 验证 ISL 是否已启动且正常工作：
+
`islshow`

. 验证是否已启用加密：
+
`portenccompshow`

+
以下示例显示已在端口 8 和 12 上启用加密：

+
[listing]
----

User Encryption
Port  configured     Active
----   ----------    ------
 8      yes          yes
 9      No           No
 10     No           No
 11     No           No
 12     yes          yes
----


对 MetroCluster 配置中另一个网络结构中的交换机执行所有步骤。
