---
permalink: install-fc/task_download_and_install_the_cisco_fc_switch_rcf_files.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, download, install, cisco, fc, rcf, files 
summary: 您必须将 RCF 文件下载到 MetroCluster 网络结构配置中的每个交换机。 
---
= 在 MetroCluster FC 配置中下载并安装 Cisco FC 交换机 RCF 文件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
必须将参考配置文件 (RCF) 下载到 MetroCluster 结构配置中的每个交换机。

.开始之前
此任务需要使用 FTP ，简单文件传输协议（ Trivial File Transfer Protocol ， TFTP ）， SFTP 或安全复制协议（ Secure Copy Protocol ， SCP ）等文件传输软件将文件复制到交换机。

.关于此任务
必须对 MetroCluster 网络结构配置中的每个 Cisco FC 交换机重复执行这些步骤。

您必须使用支持的交换机软件版本。

https://hwu.netapp.com["NetApp Hardware Universe"]

共有四个 RCF，分别对应 MetroCluster fabric 配置中的四个交换机。您必须使用适用于您所使用的交换机型号的正确 RCF。

|===


| 交换机 | RCF 


 a| 
FC_switch_A_1
 a| 
`NX3232_v1.80% Switch-A1.txt`



 a| 
FC_switch_A_2
 a| 
`NX3232_v1.80% 交换机 -a2.txt`



 a| 
FC_switch_B_1
 a| 
`NX3232_v1.80% Switch-B1.txt`



 a| 
FC_switch_B_2
 a| 
`NX3232_v1.80% Switch-B2.txt`

|===

NOTE: 显示的输出适用于 Cisco IP 交换机；但是，这些步骤也适用于 Cisco FC 交换机。

.步骤
. 从 https://mysupport.netapp.com/site/products/all/details/metrocluster-rcf/downloads-tab["MetroCluster RCF 下载页面"]下载 Cisco FC RCF。
. 将 RCF 复制到交换机。
+
.. 将 RCF 复制到第一个交换机：
+
`copy sftp ： //_root@ftp-server-ip-address/tftpboot/switch-specific RCF_ bootflash ： vRF management`

+
在此示例中， `NX3232_v1.80_Switch-A1.txt` RCF 从位于  `10.10.99.99` 的 SFTP 服务器复制到本地引导闪存。您必须使用 TFTP/SFTP 服务器的 IP 地址以及需要安装的 RCF 的文件名。

+
[listing]
----
IP_switch_A_1# copy sftp://root@10.10.99.99/tftpboot/NX3232_v1.8T-X1_Switch-A1.txt bootflash: vrf management
root@10.10.99.99's password: password
sftp> progress
Progress meter enabled
sftp> get   /tftpboot/NX3232_v1.80_Switch-A1.txt /bootflash/NX3232_v1.80_Switch-A1.txt
Fetching /tftpboot/NX3232_v1.80_Switch-A1.txt to /bootflash/NX3232_v1.80_Switch-A1.txt
/tftpboot/NX3232_v1.80_Switch-A1.txt          100% 5141     5.0KB/s   00:00
sftp> exit
Copy complete, now saving to disk (please wait)...
IP_switch_A_1#
----
.. 对其他三台交换机中的每台交换机重复前面的子步骤，确保将匹配的 RCF 复制到相应的交换机。


. 在每台交换机上验证 RCF 是否存在于每台交换机的 `bootflash`目录中：
+
`d的 bootflash ：`

+
以下示例显示文件位于 ip_switch_A_1 上：

+
[listing]
----
IP_switch_A_1# dir bootflash:
                  .
                  .
                  .
       5514    Jun 13 22:09:05 2017  NX3232_v1.80_Switch-A1.txt
                  .
                  .
                  .

Usage for bootflash://sup-local
 1779363840 bytes used
13238841344 bytes free
15018205184 bytes total
IP_switch_A_1#
----
. 将匹配的 RCF 从本地引导闪存复制到每台交换机上的运行配置：
+
`copy bootflash ： __switch-specific-RCF__.txt running-config`

. 将每台交换机上的 RCF 从运行配置复制到启动配置：
+
`copy running-config startup-config`

+
您应看到类似于以下内容的输出：

+
[listing]
----
IP_switch_A_1# copy bootflash:NX3232_v1.80_Switch-A1.txt running-config
IP_switch_A_1# copy running-config startup-config
----
. 重新加载交换机：
+
`re负载`

+
[listing]
----
IP_switch_A_1# reload
----
. 对 MetroCluster IP 配置中的其他三台交换机重复上述步骤。

