= 集群对等的前提条件
:allow-uri-read: 


每个 MetroCluster 站点都配置为其配对站点的对等站点。您必须熟悉配置对等关系的前提条件和准则。在决定是对这些关系使用共享端口还是专用端口时，这一点非常重要。

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-clus-peer/home.html["集群和 SVM 对等快速配置"]



== 集群对等的前提条件

在设置集群对等之前，您应确认满足端口， IP 地址，子网，防火墙和集群命名要求之间的连接。



=== 连接要求

本地集群上的每个集群间 LIF 都必须能够与远程集群上的每个集群间 LIF 进行通信。

虽然不需要，但在同一子网中配置用于集群间 LIF 的 IP 地址通常会更简单。这些 IP 地址可以与数据 LIF 位于同一子网中，也可以位于不同子网中。每个集群中使用的子网必须满足以下要求：

* 子网必须具有足够的可用 IP 地址，以便为每个节点分配一个集群间 LIF 。
+
例如，在四节点集群中，用于集群间通信的子网必须具有四个可用 IP 地址。



每个节点都必须具有一个集群间 LIF ，并在集群间网络上具有一个 IP 地址。

集群间 LIF 可以具有 IPv4 地址或 IPv6 地址。


NOTE: 通过 ONTAP 9 ，您可以选择在集群间 LIF 上同时使用这两种协议，从而将对等网络从 IPv4 迁移到 IPv6 。在早期版本中，整个集群的所有集群间关系均为 IPv4 或 IPv6 。这意味着更改协议可能会造成中断。



=== 端口要求

您可以使用专用端口进行集群间通信，也可以共享数据网络使用的端口。端口必须满足以下要求：

* 用于与给定远程集群通信的所有端口必须位于同一 IP 空间中。
+
您可以使用多个 IP 空间与多个集群建立对等关系。只有在 IP 空间中才需要成对的全网状连接。

* 用于集群间通信的广播域必须在每个节点上至少包含两个端口，以便集群间通信可以从一个端口故障转移到另一个端口。
+
添加到广播域的端口可以是物理网络端口， VLAN 或接口组（ ifgrp ）。

* 必须为所有端口布线。
* 所有端口都必须处于运行状况良好的状态。
* 端口的 MTU 设置必须一致。




=== 防火墙要求

防火墙和集群间防火墙策略必须支持以下协议：

* ICMP 服务
* 通过 TCP 通过端口 10000 ， 11104 和 11105 连接到所有集群间 LIF 的 IP 地址
* 集群间 LIF 之间的双向 HTTPS


默认的集群间防火墙策略允许通过 HTTPS 协议以及从所有 IP 地址（ 0.0.0.0/0 ）进行访问。如有必要，您可以修改或替换此策略。



== 使用专用端口时的注意事项

在确定使用专用端口进行集群间复制是否是正确的集群间网络解决方案时，您应考虑 LAN 类型，可用 WAN 带宽，复制间隔，更改率和端口数等配置和要求。

请考虑网络的以下方面，以确定使用专用端口是否是最佳集群间网络解决方案：

* 如果可用的 WAN 带宽量与 LAN 端口的带宽量类似，并且复制间隔使复制在存在常规客户端活动时进行，则应将以太网端口专用于集群间复制，以避免复制和数据协议之间发生争用。
* 如果数据协议（ CIFS ， NFS 和 iSCSI ）生成的网络利用率高于 50% ，则在发生节点故障转移时，可以使用专用端口进行复制，以确保性能不会下降。
* 如果将物理 10 GbE 或更快的端口用于数据和复制，则可以创建用于复制的 VLAN 端口，并将逻辑端口专用于集群间复制。
+
端口的带宽在所有 VLAN 和基础端口之间共享。

* 请考虑数据更改率和复制间隔，以及每个间隔必须复制的数据量是否需要足够的带宽。如果共享数据端口，则发生原因可能会与数据协议争用。




== 共享数据端口时的注意事项

在确定共享数据端口以进行集群间复制是否是正确的集群间网络解决方案时，您应考虑 LAN 类型，可用 WAN 带宽，复制间隔，更改率和端口数等配置和要求。

请考虑网络的以下方面，以确定共享数据端口是否是最佳的集群间连接解决方案：

* 对于 40 千兆以太网（ 40-GbE ）等高速网络，可能有足够的本地 LAN 带宽可用于在用于数据访问的相同 40-GbE 端口上执行复制。
+
在许多情况下，可用的 WAN 带宽远低于 10 GbE LAN 带宽。

* 集群中的所有节点可能都必须复制数据并共享可用的 WAN 带宽，从而使数据端口共享更可接受。
* 用于数据和复制的共享端口消除了专用于复制的端口所需的额外端口数。
* 复制网络的最大传输单元（ MTU ）大小将与数据网络上使用的大小相同。
* 请考虑数据更改率和复制间隔，以及每个间隔必须复制的数据量是否需要足够的带宽。如果共享数据端口，则发生原因可能会与数据协议争用。
* 共享用于集群间复制的数据端口后，可以将集群间 LIF 迁移到同一节点上任何其他支持集群间的端口，以控制用于复制的特定数据端口。

