= 


要确保 MetroCluster 安装成功，请重置和还原控制器模块上的默认值。只有使用 FC-SAS 网桥的延伸型配置才需要执行此任务。

.步骤
. 在 LOADER 提示符处，将环境变量返回到其默认设置：
+
`set-defaults`

. 将节点启动至维护模式，然后为系统中的任何 HBA 配置设置：
+
.. 启动至维护模式：
+
`boot_ontap maint`

.. 检查端口的当前设置：
+
`ucadmin show`

.. 根据需要更新端口设置。


+
|===
| 如果您具有此类型的 HBA 和所需模式 ... | 使用此命令 ... 


| CNA FC | `ucadmin modify -m fc -t initiator _adapter_name_` 


| CNA 以太网 | `ucadmin modify -mode cna _adapter_name_` 


| FC 目标 | `fcadmin config -t target _adapter_name_` 


| FC 启动程序 | `fcadmin config -t initiator _adapter_name_` 
|===
. 退出维护模式：
+
`halt`

+
运行此命令后，请等待，直到节点停留在 LOADER 提示符处。

. 将节点重新启动至维护模式，以使配置更改生效：
+
`boot_ontap maint`

. 验证所做的更改：
+
|===
| 如果您使用的是此类型的 HBA... | 使用此命令 ... 


 a| 
CNA
 a| 
`ucadmin show`



 a| 
FC
 a| 
`fcadmin show`

|===
. 退出维护模式：
+
`halt`

+
运行此命令后，请等待，直到节点停留在 LOADER 提示符处。

. 将节点启动至启动菜单：
+
`boot_ontap 菜单`

+
运行此命令后，请等待，直到显示启动菜单为止。

. 在启动菜单提示符处键入 wipeconfig 以清除节点配置，然后按 Enter 键。
+
以下屏幕将显示启动菜单提示符：

+
[listing]
----
Please choose one of the following:

     (1) Normal Boot.
     (2) Boot without /etc/rc.
     (3) Change password.
     (4) Clean configuration and initialize all disks.
     (5) Maintenance mode boot.
     (6) Update flash from backup config.
     (7) Install new software first.
     (8) Reboot node.
     (9) Configure Advanced Drive Partitioning.
     Selection (1-9)?  wipeconfig
 This option deletes critical system configuration, including cluster membership.
 Warning: do not run this option on a HA node that has been taken over.
 Are you sure you want to continue?: yes
 Rebooting to finish wipeconfig request.
----

