---
permalink: releasenotes/mcc-config-support-features.html 
sidebar: sidebar 
keywords: metrocluster, configuration, support for ontap features 
summary:  
---
= MetroCluster配置中的新增功能支持ONTAP功能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9数据管理软件的每个版本都提供了一些新增功能和增强功能、可提高ONTAP MetroCluster配置的功能、易管理性和性能。

有关影响ONTAP MetroCluster配置的已知问题、限制和升级注意事项的详细信息、请参阅 https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["《 ONTAP 9 发行说明》"^]。您必须使用NetApp帐户登录或创建帐户才能访问发行说明。

[cols="20,65,15"]
|===
| MetroCluster配置中支持的功能 | 说明 | 可从一开始使用 


 a| 
支持迁移MetroCluster配置的SVM数据移动性
 a| 
ONTAP支持以下MetroCluster SVM迁移：

* 在非MetroCluster HA对和MetroCluster IP配置之间迁移SVM
* 在两个MetroCluster IP配置之间迁移SVM
* 在MetroCluster FC配置和MetroCluster IP配置之间迁移SVM


link:https://docs.netapp.com/us-en/ontap/svm-migrate/index.html["SVM 数据移动性"^]
 a| 
ONTAP 9.16.1.



 a| 
为BGP对等组提供MD5身份验证支持
 a| 
ONTAP支持对BGP对等组进行MD5身份验证、以保护BGP会话。启用MD5后、只能在授权对等方之间建立和处理BGP会话、从而防止未经授权的行为者可能中断会话。

link:https://docs.netapp.com/us-en/ontap/networking/configure_virtual_ip_@vip@_lifs.html["配置虚拟 IP （ VIP ） LIF"^]
 a| 
ONTAP 9.16.1.



 a| 
NVMe的MetroCluster IP支持
 a| 
四节点MetroCluster IP配置支持NVMe/TCP前端主机协议。

link:https://docs.netapp.com/us-en/ontap/san-admin/san-config-mcc-concept.html["MetroCluster 环境中的SAN配置"^]
 a| 
ONTAP 9.15.1.



 a| 
镜像和未镜像聚合上的S3对象存储支持
 a| 
您可以在MetroCluster IP和FC配置中的镜像或未镜像聚合中的SVM上启用S3对象存储服务器。

https://docs.netapp.com/us-en/ontap/s3-config/index.html["S3配置概述"^]
 a| 
ONTAP 9.14.1



 a| 
支持在MetroCluster集群中的镜像和未镜像聚合上配置S3存储分段
 a| 
您可以在MetroCluster配置中的镜像或未镜像聚合上创建分段。

https://docs.netapp.com/us-en/ontap/s3-config/create-bucket-mcc-task.html["在MetroCluster配置中的镜像或未镜像聚合上创建分段"^]
 a| 
ONTAP 9.12.1



 a| 
NVMe的MetroCluster IP支持
 a| 
四节点MetroCluster IP配置支持NVMe/FC协议。

link:https://docs.netapp.com/us-en/ontap/san-admin/san-config-mcc-concept.html["MetroCluster 环境中的SAN配置"^]
 a| 
ONTAP 9.12.1



 a| 
IPSEC支持在MetroCluster IP和MetroCluster光纤连接配置中使用前端主机协议
 a| 
在MetroCluster IP和MetroCluster光纤连接配置中、可以为前端主机协议(例如NFS和iSCSI)提供IPSEC支持。

https://docs.netapp.com/us-en/ontap/networking/configure_ip_security_@ipsec@_over_wire_encryption.html["通过线缆加密配置 IP 安全性（ IP security ， IPsec ）"^]
 a| 
ONTAP 9.11.1



 a| 
一致性组
 a| 
MetroCluster配置支持一致性组。
 a| 
ONTAP 9.7



 a| 
MetroCluster 配置上的 FabricPool 镜像
 a| 
您可以在MetroCluster配置上设置镜像FabricPool、以便将冷数据分层到两个不同的故障分区。

https://docs.netapp.com/us-en/ontap/fabricpool/setup-object-stores-mcc-task.html["在 MetroCluster 配置中为 FabricPool 设置对象存储"^]
 a| 
ONTAP 9.7



 a| 
SVM 灾难恢复
 a| 
MetroCluster配置中的活动Storage Virtual Machine (SVM)可用作SnapMirror SVM灾难恢复功能的源。
 a| 
ONTAP 9.5

|===