---
permalink: releasenotes/mcc-config-support-features.html 
sidebar: sidebar 
keywords: metrocluster, configuration, support for ontap features 
summary:  
---
= MetroCluster配置中的新增功能支持ONTAP功能
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[cols="20,65,15"]
|===
| MetroCluster配置中支持的功能 | 说明 | 可从一开始使用 


 a| 
镜像和未镜像聚合上的S3对象存储支持
 a| 
您可以在MetroCluster IP和FC配置中的镜像或未镜像聚合中的SVM上启用S3对象存储服务器。

https://docs.netapp.com/us-en/ontap/s3-config/index.html["S3配置概述"]
 a| 
ONTAP 9.14.1



 a| 
支持在MetroCluster集群中的镜像和未镜像聚合上配置S3存储分段
 a| 
您可以在MetroCluster配置中的镜像或未镜像聚合上创建分段。

https://docs.netapp.com/us-en/ontap/s3-config/create-bucket-mcc-task.html["在MetroCluster配置中的镜像或未镜像聚合上创建分段"]
 a| 
ONTAP 9.14.1



 a| 
MetroCluster IP配置支持ONTAP调解器1.5
 a| 
ONTAP调解器1.5可用于监控MetroCluster IP配置。

https://docs.netapp.com/us-en/ontap/mediator/index.html["安装或升级 ONTAP 调解器服务"]
 a| 
ONTAP 9.12.1



 a| 
IPSEC支持在MetroCluster IP和MetroCluster光纤连接配置中使用前端主机协议
 a| 
在MetroCluster IP和MetroCluster光纤连接配置中、可以为前端主机协议(例如NFS和iSCSI)提供IPSEC支持。

https://docs.netapp.com/us-en/ontap/networking/configure_ip_security_@ipsec@_over_wire_encryption.html["通过线缆加密配置 IP 安全性（ IP security ， IPsec ）"]
 a| 
ONTAP 9.12.1



 a| 
ONTAP调解器1.4
 a| 
MetroCluster IP配置支持ONTAP调解器软件1.4版。

https://docs.netapp.com/us-en/ontap/mediator/index.html["安装或升级 ONTAP 调解器服务"]
 a| 
ONTAP 9.11.1



 a| 
一致性组
 a| 
MetroCluster配置支持一致性组。

https://docs.netapp.com/us-en/ontap/mediator/index.html["安装或升级 ONTAP 调解器服务"]
 a| 
ONTAP 9.11.1



 a| 
MetroCluster IP配置支持ONTAP调解器
 a| 
ONTAP调解器服务可通过为状态信息提供物理上单独的存储库来协助MetroCluster IP配置执行自动计划外切换。

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html["为计划外自动切换配置 ONTAP 调解器服务"]
 a| 
ONTAP 9.7



 a| 
MetroCluster 配置上的 FabricPool 镜像
 a| 
您可以在MetroCluster配置上设置镜像FabricPool、以便将冷数据分层到两个不同的故障分区。

https://docs.netapp.com/us-en/ontap/fabricpool/setup-object-stores-mcc-task.html["在 MetroCluster 配置中为 FabricPool 设置对象存储"]
 a| 
ONTAP 9.7



 a| 
SVM 灾难恢复
 a| 
MetroCluster配置中的活动Storage Virtual Machine (SVM)可用作SnapMirror SVM灾难恢复功能的源。
 a| 
ONTAP 9.5

|===