---
permalink: releasenotes/mcc-new-features.html 
sidebar: sidebar 
keywords: new metrocluster features 
summary:  
---
= MetroCluster功能中的新增功能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9数据管理软件的每个版本都提供了一些新增功能和增强功能、可提高ONTAP MetroCluster配置的功能、易管理性和性能。

有关影响ONTAP MetroCluster配置的已知问题、限制和升级注意事项的详细信息、请参阅 https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["《 ONTAP 9 发行说明》"^]。您必须使用NetApp帐户登录或创建帐户才能访问发行说明。

[cols="20,65,15"]
|===
| MetroCluster配置中支持的功能 | 问题描述 以及从何处了解更多信息 | 可从一开始使用 


 a| 
MetroCluster IP 配置中 FAS50 系统的闪存缓存支持
 a| 
在MetroCluster IP 配置中，FAS50 系统支持闪存缓存。

link:../install-ip/concept_considerations_drive_assignment.html#disk-assignment-on-fas50-systems-with-flash-cache["在配备闪存缓存的 FAS50 系统上进行磁盘分配"]
 a| 
ONTAP 9.18.1



 a| 
MetroCluster IP支持端到端加密
 a| 
以下系统支持端到端加密，以加密MetroCluster IP 配置中的站点之间的后端流量，例如 NVlog 和存储复制数据。

* AFF A800和AFF C800
* AFF A20、 AFF A30、 AFF C30、 AFF A50、 AFF C60
* AFF A70、AFF A90、AFF A1K、AFF C80
* FAS50、FAS70、FAS90


link:../maintain/task-configure-encryption.html["在MetroCluster IP配置中配置端到端加密"]
 a| 
ONTAP 9.17.1



 a| 
限制MetroCluster IP 配置的更改
 a| 
ONTAP 9.17.1 包括针对四节点MetroCluster IP 配置的以下限制更新：

* AFF C800、 AFF A800、 AFF A900、 AFF A90和AFF A1K系统具有以下更新的限制：
+
** 每个节点的FlexVol volume限制：1250
** SVM 限制：每个集群 64 个 SVM
** LIF 数量：每个集群 256 个 LIF


* AFF A400、 AFF C400、 ASA A400、 ASA C400、 AFF C80、 AFF A70和AFF A50 系统具有以下更新的限制：
+
** 每个聚合体（单个或多个）的FlexVol volume限制：625
** 每个节点的FlexVol volume限制：1250
** 每个高可用性 (HA) 对的FlexVol volume限制：2500
** 每个集群的FlexVol volume限制：5000
** SVM 限制：每个集群 64 个 SVM
** LIF 数量：每个集群 256 个 LIF




请参阅link:https://hwu.netapp.com["Hardware Universe"^]了解更多信息。
 a| 
ONTAP 9.17.1



 a| 
使用凭据更新 FibreBridge 固件
 a| 
如果服务器需要凭据来下载固件包，您可以使用凭据来更新 FibreBridge 网桥上的固件。

link:../maintain/task_update_firmware_on_a_fibrebridge_bridge_parent_topic.html["更新 FibreBridge 网桥上的固件"]
 a| 
ONTAP 9.16.1.



 a| 
支持迁移MetroCluster配置的SVM数据移动性
 a| 
ONTAP支持以下MetroCluster SVM迁移：

* 在非MetroCluster HA对和MetroCluster IP配置之间迁移SVM
* 在两个MetroCluster IP配置之间迁移SVM
* 在MetroCluster FC配置和MetroCluster IP配置之间迁移SVM


link:https://docs.netapp.com/us-en/ontap/svm-migrate/index.html["SVM 数据移动性"^]
 a| 
ONTAP 9.16.1.



 a| 
为BGP对等组提供MD5身份验证支持
 a| 
ONTAP支持对BGP对等组进行MD5身份验证、以保护BGP会话。启用MD5后、只能在授权对等方之间建立和处理BGP会话、从而防止未经授权的行为者可能中断会话。

link:https://docs.netapp.com/us-en/ontap/networking/configure_virtual_ip_@vip@_lifs.html["配置虚拟 IP （ VIP ） LIF"^]
 a| 
ONTAP 9.16.1.



 a| 
MetroCluster IP支持端到端加密
 a| 
AFF A400、FAS9300和FAS4700系统支持端到端加密、用于加密MetroCluster IP配置中站点之间的后端流量、例如NVlog和存储复制数据。

link:../maintain/task-configure-encryption.html["在MetroCluster IP配置中配置端到端加密"]
 a| 
ONTAP 9.15.1.



 a| 
提高AFF A800和AFF C800系统上四节点MetroCluster IP配置的卷限制
 a| 
在四节点MetroCluster IP配置中、AFF A800和AFF C800系统的以下卷限制已增加：

* 每个聚合的最大FlexVol卷数从200增加到625。
* 每个节点的最大FlexVol卷数从800增加到1250。
* 每个 HA 对的最大FlexVol卷数从 1600 个增加到 2500 个。

 a| 
ONTAP 9.15.1.



 a| 
NVMe的MetroCluster IP支持
 a| 
四节点MetroCluster IP配置支持NVMe/TCP前端主机协议。

link:https://docs.netapp.com/us-en/ontap/san-admin/san-config-mcc-concept.html["MetroCluster 环境中的SAN配置"^]
 a| 
ONTAP 9.15.1.



 a| 
提高AFF A900系统上四节点MetroCluster IP配置的卷限制
 a| 
在四节点MetroCluster IP配置中、AFF A900系统的以下卷限制已增加：

* 每个聚合的最大FlexVol卷数从200增加到625。
* 每个节点的最大FlexVol卷数从800增加到1250。
* 每个 HA 对的最大FlexVol卷数从 1600 个增加到 2500 个。

 a| 
ONTAP 9.14.1



 a| 
镜像和未镜像聚合上的S3对象存储支持
 a| 
您可以在MetroCluster IP和FC配置中的镜像或未镜像聚合中的SVM上启用S3对象存储服务器。

https://docs.netapp.com/us-en/ontap/s3-config/ontap-version-support-s3-concept.html#s3-support-with-metrocluster["MetroCluster支持S3"^]
 a| 
ONTAP 9.14.1



 a| 
支持在MetroCluster集群中的镜像和未镜像聚合上配置S3存储分段
 a| 
您可以在MetroCluster配置中的镜像或未镜像聚合上创建分段。

link:https://docs.netapp.com/us-en/ontap/s3-config/create-bucket-mcc-task.html#process-to-create-buckets["在MetroCluster配置中的镜像或未镜像聚合上创建ONTAP S3存储分段"^]
 a| 
ONTAP 9.14.1



 a| 
使用MetroCluster IP和以太网连接存储的共享交换机从MetroCluster FC过渡到MetroCluster IP
 a| 
您可以使用共享存储交换机从MetroCluster FC无故障过渡到MetroCluster IP配置。

https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html["无中断地从 MetroCluster FC 过渡到 MetroCluster IP 配置（ ONTAP 9.8 及更高版本）"]
 a| 
ONTAP 9.13.1



 a| 
从八节点MetroCluster FC配置无中断过渡到MetroCluster IP配置
 a| 
您可以无系统地将工作负载和数据从现有八节点MetroCluster FC配置过渡到新的MetroCluster IP配置。

https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html["无故障从MetroCluster FC过渡到MetroCluster IP配置"]
 a| 
ONTAP 9.13.1



 a| 
通过切换和切回升级四节点MetroCluster IP配置
 a| 
您可以使用切换和切回升级四节点MetroCluster IP配置中的控制器 `system controller replace` 命令

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_controllers_system_control_commands_in_a_four_node_mcc_ip.html["升级四节点MetroCluster IP配置中的控制器"]
 a| 
ONTAP 9.13.1



 a| 
在环境关闭时触发调解器辅助的自动计划外切换(MAUSO)
 a| 
如果一个站点因环境关闭而正常关闭、则会触发MAUSO。

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-ontap-mediator-supports-automatic-unplanned-switchover.html["ONTAP 调解器如何支持自动计划外切换"]
 a| 
ONTAP 9.13.1



 a| 
支持八节点MetroCluster IP配置
 a| 
您可以通过将八节点MetroCluster IP配置扩展为临时十二节点配置、然后删除旧的DR组来升级该配置中的控制器和存储。

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_refresh_4n_mcc_ip.html["刷新四节点 MetroCluster IP 配置"]
 a| 
ONTAP 9.13.1



 a| 
将MetroCluster IP配置转换为共享存储MetroCluster交换机配置
 a| 
您可以将MetroCluster IP配置转换为共享存储MetroCluster交换机配置。

https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_replace_an_ip_switch.html["更换 IP 交换机"]
 a| 
ONTAP 9.13.1



 a| 
MetroCluster IP配置中的MetroCluster自动强制切换功能
 a| 
您可以在MetroCluster IP配置中启用MetroCluster自动强制切换功能。此功能是调解器辅助计划外切换(MAUSO)功能的扩展。

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-risks-limitations-automatic-switchover.html["自动切换限制"]
 a| 
ONTAP 9.12.1



 a| 
MetroCluster IP配置中未镜像聚合上的SVM上的S3
 a| 
您可以在MetroCluster IP配置中未镜像聚合的SVM上启用ONTAP简单存储服务(S3)对象存储服务器。

https://docs.netapp.com/us-en/ontap/s3-config/ontap-version-support-s3-concept.html#s3-support-with-metrocluster["MetroCluster支持S3"^]
 a| 
ONTAP 9.12.1



 a| 
NVMe的MetroCluster IP支持
 a| 
四节点MetroCluster IP配置支持NVMe/FC协议。

link:https://docs.netapp.com/us-en/ontap/san-admin/san-config-mcc-concept.html["MetroCluster 环境中的SAN配置"^]
 a| 
ONTAP 9.12.1



 a| 
IPSEC支持在MetroCluster IP和MetroCluster光纤连接配置中使用前端主机协议
 a| 
在MetroCluster IP和MetroCluster光纤连接配置中、可以为前端主机协议(例如NFS和iSCSI)提供IPSEC支持。

https://docs.netapp.com/us-en/ontap/networking/configure_ip_security_@ipsec@_over_wire_encryption.html["通过线缆加密配置 IP 安全性（ IP security ， IPsec ）"^]
 a| 
ONTAP 9.12.1



 a| 
从MetroCluster FC配置过渡到AFF A250或FAS500f MetroCluster IP配置
 a| 
您可以从MetroCluster FC配置过渡到AFF A250或FAS500f MetroCluster IP配置。

https://docs.netapp.com/us-en/ontap-metrocluster/transition/task_move_cluster_connections.html#which-connections-to-move["移动本地集群连接"]
 a| 
ONTAP 9.11.1



 a| 
一致性组
 a| 
MetroCluster配置支持一致性组。

https://docs.netapp.com/us-en/ontap/consistency-groups/index.html#multi-admin-verification-support-for-consistency-groups["MetroCluster 配置中的一致性组"^]
 a| 
ONTAP 9.11.1



 a| 
简化了MetroCluster FC配置中节点的控制器升级
 a| 
通过切换和切回执行升级过程的升级操作步骤已得到简化。

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_controllers_in_a_four_node_fc_mcc_us_switchover_and_switchback_mcc_fc_4n_cu.html["使用切换和切回升级 MetroCluster FC 配置中的控制器"]
 a| 
ONTAP 9.10.1



 a| 
第3层共享链路的IP支持
 a| 
MetroCluster IP配置可通过IP路由(第3层)后端连接来实施。

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_layer_3.html["第 3 层广域网的注意事项"]
 a| 
ONTAP 9.9.1



 a| 
支持八节点MetroCluster配置
 a| 
IP和光纤连接MetroCluster配置支持永久八节点集群。

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_install_and_cable_the_mcc_components.html["安装 MetroCluster 组件并为其布线"]
 a| 
ONTAP 9.9.1

|===