---
permalink: releasenotes/mcc-mediator-whats-new.html 
sidebar: sidebar 
keywords: metrocluster, mediator, new, release, update, install, 
summary: 每个版本都提供了ONTAP 调解器的新功能。  下面是新增功能。 
---
= ONTAP Mediator 对MetroCluster IP 的支持有哪些新特性
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
了解MetroCluster IP 的新功能和增强功能，以支持ONTAP Mediator。

有关ONTAP Mediator 每个版本的功能和增强特性的详细信息，请参阅：link:https://docs.netapp.com/us-en/ontap/mediator/whats-new-concept.html["ONTAP Mediator 的新增功能"^] 。

[cols="4,1"]
|===
| ONTAP调解器功能 | 可从一开始使用 


 a| 
从 ONTAP Mediator 1.12.1 开始，配置了 HTTPS 的单个 ONTAP Mediator 实例可以同时监控以下配置：

* 如果安装在具有至少 8 个 CPU 内核和至少 16GB RAM 的主机上，则最多可安装 10 个四节点或 5 个八节点 MetroCluster IP 配置。
* 一个四节点 MetroCluster IP 配置和一个 SnapMirror 活动同步对等关系（如果安装在具有双核 CPU 的主机操作系统上）。


link:../install-ip/concept_mediator_requirements.html#mediator-multiple-mccip["详细了解 ONTAP Mediator 对多个 MetroCluster IP 配置的支持"]。
 a| 
ONTAP 9.19.1



 a| 
ONTAP Mediator 1.12 支持配置使用 HTTPS 进行 MetroCluster IP 配置通信的 ONTAP Mediator。HTTPS 通过使用 SSL/TLS 加密整个会话来提高安全性。您可以选择安装仅使用 HTTPS 协议的 ONTAP Mediator。如果使用此安装方法，则不会安装 SCST 包。有关安装仅使用 HTTPS 协议的 ONTAP Mediator 的详细信息，请参见 link:https://docs.netapp.com/us-en/ontap/mediator/index.html#https-iscsi-installation["适用于 ONTAP Mediator 的 HTTPS 和 iSCSI 安装选项"^]。

link:../install-ip/concept_mediator_requirements.html#select-a-communication-protocol-for-ontap-mediator["详细了解 ONTAP Mediator 中的 iSCSI 和 HTTPS 协议"]。
 a| 
ONTAP 9.19.1



 a| 
在MetroCluster IP 配置中， ONTAP Mediator 1.11 或更高版本支持 IPv6。

link:../install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html["为MetroCluster IP 配置设置ONTAP调解器"]
 a| 
ONTAP 9.18.1



 a| 
ONTAP Mediator 1.11 增加了对使用单个ONTAP Mediator 实例管理多达 10 个MetroCluster IP 配置的支持。

link:../install-ip/concept_mediator_requirements.html["准备在MetroCluster IP 配置中安装ONTAP Mediator"]
 a| 
ONTAP 9.18.1



 a| 
在环境关闭时、支持调解器辅助的自动计划外切换(MAUSO)。

如果一个站点因环境关闭而正常关闭、则会触发MAUSO。

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-ontap-mediator-supports-automatic-unplanned-switchover.html["ONTAP 调解器如何支持自动计划外切换"]
 a| 
ONTAP 9.13.1



 a| 
MetroCluster IP 配置中对 ONTAP 调解器的初步支持
 a| 
ONTAP 9.7

|===