---
permalink: maintain/concept_using_fibrebridge_7600n_bridges_in_mcc_configurations.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, support, fibrebridge, bridges, configurations 
summary: ONTAP 9.5 及更高版本支持 FibreBridge 7600N 网桥，以替代 FibreBridge 7500N 或 6500N 网桥，或者在向 MetroCluster 配置添加新存储时。使用网桥 FC 端口时的分区要求和限制与 FibreBridge 7500N 网桥相同。 
---
= 支持 MetroCluster 配置中的 FibreBridge 7600N 网桥
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.5 及更高版本支持 FibreBridge 7600N 网桥，以替代 FibreBridge 7500N 或 6500N 网桥，或者在向 MetroCluster 配置添加新存储时。与使用网桥 FC 端口相关的分区要求和限制与 FibreBridge 7500N 网桥相同。

https://mysupport.netapp.com/matrix["NetApp 互操作性表工具"^]


NOTE: 运行 ONTAP 9.8 及更高版本的配置不支持 FibreBridge 6500N 网桥。

[cols="27,19,27,27"]
|===


| 用例 | 是否需要更改分区？ | 限制 | 操作步骤 


 a| 
将一个 FibreBridge 7500N 网桥更换为一个 FibreBridge 7600N 网桥
 a| 
否
 a| 
FibreBridge 7600N 网桥的配置必须与 FibreBridge 7500N 网桥完全相同。
 a| 
link:task_replace_a_sle_fc_to_sas_bridge.html#hot-swapping-a-fibrebridge-7500n-with-a-7600n-bridge["热插拔 FibreBridge 7500N 和 7600N 网桥"]



 a| 
将一个 FibreBridge 6500N 网桥更换为一个 FibreBridge 7600N 网桥
 a| 
否
 a| 
FibreBridge 7600N 网桥的配置必须与 FibreBridge 6500N 网桥完全相同。
 a| 
link:task_replace_a_sle_fc_to_sas_bridge.html#hot-swapping-a-fibrebridge-6500n-bridge-with-a-fibrebridge-7600n-or-7500n-bridge["热插拔 FibreBridge 6500N 网桥和 FibreBridge 7600N 或 7500N 网桥"]



 a| 
通过添加新的一对 FibreBridge 7600N 网桥来添加新存储
 a| 
是的。

您必须为新网桥的每个 FC 端口添加存储分区。
 a| 
您必须在 FC 交换机网络结构（在光纤连接的 MetroCluster 配置中）或存储控制器（在延伸型 MetroCluster 配置中）上具有可用端口。每对 FibreBridge 7500N 或 7600N 网桥最多可支持四个堆栈。
 a| 
link:task_fb_hot_add_stack_of_shelves_and_bridges.html["将 SAS 磁盘架和网桥堆栈热添加到 MetroCluster 系统"]

|===