---
permalink: maintain/concept_where_to_find_procedures_for_mcc_maintenance_tasks.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, find, procedures, maintenance, tasks 
summary: 在执行 MetroCluster 硬件维护任务时，您应确保选择正确的操作步骤。 
---
= 从何处查找 MetroCluster 维护任务的过程
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在执行 MetroCluster 硬件维护任务时，您应确保选择正确的操作步骤。

.不同类型MetroCluster配置的维护过程
* 如果您使用的是MetroCluster IP配置，请查看中的过程link:task-modify-ip-netmask-properties.html["MetroCluster IP配置的维护过程"]。
* 如果您使用的是MetroCluster FC配置，请查看中的过程link:task_modify_switch_or_bridge_ip_address_for_health_monitoring.html["MetroCluster FC配置的维护过程"]。
* 如果在特定章节中找不到适用于您的配置的过程，请查看中的过程link:task_replace_a_shelf_nondisruptively_in_a_stretch_mcc_configuration.html["所有MetroCluster配置的维护过程"]。


.所有其他维护程序
下表提供了上述三节中未介绍的与MetroCluster维护相关的步骤的链接：

|===


| 组件 | MetroCluster 类型（ FC 或 IP ） | 任务 | 操作步骤 


 a| 
ONTAP 软件
 a| 
两者
 a| 
ONTAP 软件升级
 a| 
https://docs.netapp.com/us-en/ontap/upgrade/index.html["升级，还原或降级"^]



 a| 
控制器模块
 a| 
两者
 a| 
FRU 更换（包括控制器模块， PCIe 卡， FC-VI 卡等）


NOTE: 不支持在 MetroCluster 存储系统之间移动存储控制器模块或 NVRAM 卡。
 a| 
https://docs.netapp.com/platstor/index.jsp["ONTAP硬件系统文档"^]



 a| 
升级和扩展
 a| 
link:../upgrade/concept_choosing_an_upgrade_method_mcc.html["MetroCluster 升级和扩展"]



 a| 
从 FC 连接过渡到 IP 连接
 a| 
link:../transition/concept_choosing_your_transition_procedure_mcc_transition.html["从 MetroCluster FC 过渡到 MetroCluster IP"]



 a| 
驱动器架
 a| 
FC
 a| 
所有其他磁盘架维护过程。可以使用标准过程。
 a| 
https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-sas3-service/home.html["维护 DS460C DS224C 和 DS212C 磁盘架"^]



 a| 
IP
 a| 
所有磁盘架维护过程。可以使用标准过程。

如果要为未镜像聚合添加磁盘架，请参见 http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-ip/GUID-EA385AF8-7786-4C3C-B5AE-1B4CFD3AD2EE.html["使用未镜像聚合时的注意事项"^]
 a| 
https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-sas3-service/home.html["维护 DS460C DS224C 和 DS212C 磁盘架"^]



 a| 
两者
 a| 
将 IOM12 磁盘架热添加到 IOM6 磁盘架堆栈中
 a| 
https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-mix-hotadd/home.html["将带有 IOM12 模块的磁盘架热添加到带有 IOM6 模块的磁盘架堆栈中"^]

|===