---
permalink: maintain/task_add_remove_or_change_isl_ports_nondisruptively.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, add, remove, change, isl, ports, nondisruptively 
summary: 您可能需要添加，删除或更改 ISL 端口。您可以将专用 ISL 端口转换为共享 ISL 端口，也可以更改交换机上 ISL 端口的速度。传输距离较远的 ISL 可能需要较低的速度来提高质量。如果要添加或升级硬件，您可能还需要提高 ISL 端口的速度以利用系统升级并将 ISL 添加到 Cisco IP 交换机。 
---
= 无中断地添加，删除或更改 ISL 端口
:icons: font
:imagesdir: ../media/


[role="lead"]
您可能需要添加，删除或更改 ISL 端口。您可以将专用 ISL 端口转换为共享 ISL 端口，也可以更改交换机上 ISL 端口的速度。传输距离较远的 ISL 可能需要较低的速度来提高质量。如果要添加或升级硬件，您可能还需要提高 ISL 端口的速度以利用系统升级并将 ISL 添加到 Cisco IP 交换机。

如果要将专用 ISL 端口转换为共享 ISL 端口，请确保新端口满足要求 link:../install-ip/concept_considerations_layer_2.html["共享 ISL 端口的要求"]。

您必须在两台交换机上完成所有步骤，以确保 ISL 连接。

以下操作步骤假定您要将在交换机端口 Eth1/24/1 上连接的一个 10-Gb ISL 替换为连接到交换机端口 17 和 18 的两个 100-Gb ISL 。

.步骤
. 在网络结构中要更改的两个交换机上禁用 ISL 的 ISL 端口。
+

NOTE: 只有在将当前 ISL 端口移动到其他端口或 ISL 速度发生变化时，才需要禁用这些端口。如果要添加速度与现有 ISL 相同的 ISL 端口，请转至步骤 3 。

+
每行只能输入一个配置命令，并在输入完所有命令后按 Ctrl-Z ，如以下示例所示：

+
[listing]
----

switch_A_1# conf t
switch_A_1(config)# int eth1/24/1
switch_A_1(config-if)# shut
switch_A_1(config-if)#
switch_A_1#

switch_B_1# conf t
switch_B_1(config)# int eth1/24/1
switch_B_1(config-if)# shut
switch_B_1(config-if)#
switch_B_1#
----
. 拆下现有缆线和收发器。
. 根据需要更改 ISL 端口。
+
|===
| 选项 | 步骤 


 a| 
要更改 ISL 端口的速度 ...
 a| 
根据速度将新 ISL 连接到指定端口。您必须确保您的交换机的这些 ISL 端口已在 _ISL MetroCluster IP 安装和配置指南 _ 中列出。



 a| 
要添加 ISL ...
 a| 
将 QMSP 插入要添加为 ISL 端口的端口。确保它们列在 _IP MetroCluster 安装和配置指南中，并根据此指南为其布线。

|===
. 从以下命令开始，在网络结构中的两个交换机上启用所有 ISL 端口（如果未启用）：
+
` * 交换机 _A_1# 配置 t*`

+
每行只能输入一个配置命令，输入完所有命令后按 Ctrl-Z ：

+
[listing]
----
switch_A_1# conf t
switch_A_1(config)# int eth1/17
switch_A_1(config-if)# no shut
switch_A_1(config-if)# int eth1/18
switch_A_1(config-if)# no shut
switch_A_1(config-if)#
switch_A_1#
switch_A_1# copy running-config startup-config

switch_B_1# conf t
switch_B_1(config)# int eth1/17
switch_B_1(config-if)# no shut
switch_B_1(config-if)# int eth1/18
switch_B_1(config-if)# no shut
switch_B_1(config-if)#
switch_B_1#
switch_B_1# copy running-config startup-config
----
. 验证是否已在两个交换机之间建立 ISL ：
+
` * switch_A_1# show int eth1/17 ， eth1/18 brief *`

+
您应在命令输出中看到 ISL 接口，如以下示例所示：

+
[listing]
----
switch_A_1# show int eth1/17,eth1/18 brief
--------------------------------------------------------------------------------
Ethernet      VLAN    Type Mode   Status  Reason                   Speed     Port
Interface                                                                                                        Ch #
--------------------------------------------------------------------------------
Eth1/17       10         eth     access    up      none                       100G(D) 10
Eth1/18       10         eth     access    up      none                       100G(D) 10

switch_B_1# show int eth1/17,eth1/18 brief
--------------------------------------------------------------------------------
Ethernet      VLAN    Type Mode   Status  Reason                   Speed     Port
Interface                                                                                                        Ch #
--------------------------------------------------------------------------------
Eth1/17       10         eth     access    up      none                       100G(D) 10
Eth1/18       10         eth     access    up      none                       100G(D) 10
----
. 对网络结构 2 重复操作步骤。

