---
permalink: maintain/task_upgrade_rcf_files_on_mcc_ip_switches.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, upgrade, rcf, files, ip, switches 
summary: 您可能需要升级 MetroCluster IP 交换机上的 RCF 文件。例如， ONTAP 升级或交换机固件升级都需要新的 RCF 文件。 
---
= 升级 MetroCluster IP 交换机上的 RCF 文件
:icons: font
:imagesdir: ../media/


[role="lead"]
您可能需要升级 MetroCluster IP 交换机上的 RCF 文件。例如， ONTAP 升级或交换机固件升级都需要新的 RCF 文件。

如果要安装新的交换机固件，则必须先安装交换机固件，然后再升级 RCF 文件。

此操作步骤会中断升级 RCF 文件的交换机上的流量。应用新 RCF 文件后，流量将恢复。

.步骤
. 验证配置的运行状况。
+
.. 验证 MetroCluster 组件是否运行正常：
+
` * MetroCluster check run*`

+
[listing]
----
cluster_A::*> metrocluster check run

----


+
此操作将在后台运行。

+
.. 在 `MetroCluster check run` 操作完成后，运行 `MetroCluster check show` 以查看结果。
+
大约五分钟后，将显示以下结果：

+
[listing]
----
-----------
::*> metrocluster check show

Last Checked On: 4/7/2019 21:15:05

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          warning
clusters            ok
connections         not-applicable
volumes             ok
7 entries were displayed.
----
.. 要检查正在运行的 MetroCluster 检查操作的状态，请使用以下命令： + ` * MetroCluster operation history show -job-id 38*`
.. 验证是否没有运行状况警报： + ` * system health alert show*`


. 准备 IP 交换机以应用新的 RCF 文件。
+
按照 _IP MetroCluster 安装和配置指南 _ 中适用于您的交换机供应商一节中的步骤进行操作。

+
https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/index.html["MetroCluster IP 安装和配置"]

+
** 将 Broadcom IP 交换机重置为出厂默认设置 _
** 将 Cisco IP 交换机重置为出厂默认值 _


. 根据交换机供应商的不同，下载并安装 IP RCF 文件。
+
按照 _IP MetroCluster 安装和配置指南 _ 中适用于您的交换机供应商一节中的步骤进行操作。

+
https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/index.html["MetroCluster IP 安装和配置"]

+
** 下载并安装 Broadcom IP RCF 文件 _
** 下载和安装 Cisco IP RCF 文件 _
+
... 按以下顺序更新交换机： switch_A_1 ， Switch_B_1 ， Switch_A_2 ， Switch_B_2 。





