---
permalink: maintain/task_change_isl_properties_isl_ports_or_the_iod_ood_configuration_on_a_brocade_switch.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, change, isl, properties, isl, ports, iod, configuration, brocade, switch 
summary: 如果要添加或升级硬件，例如其他或更快的控制器或交换机，则可能需要向交换机添加 ISL 。 
---
= 更改 Brocade 交换机上的 ISL 属性， ISL 端口或 IOD/OOD 配置
:icons: font
:imagesdir: ../media/


[role="lead"]
如果要添加或升级硬件，例如其他或更快的控制器或交换机，则可能需要向交换机添加 ISL 。

确保系统已正确配置，所有网络结构交换机均正常运行，并且不存在任何错误。

如果 ISL 链路上的设备发生变化，而新的链路配置不再支持当前配置—中继和有序交付—则需要根据正确的路由策略重新配置网络结构：按顺序交付（ IOD ）或无序交付（ OOD ）。


NOTE: 要使用 ONTAP 软件更改 OOD ，请执行以下步骤： link:https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/concept_configure_the_mcc_software_in_ontap.html#configuring-in-order-delivery-or-out-of-order-delivery-of-frames-on-ontap-software#configuring-in-order-delivery-or-out-of-order-delivery-of-frames-on-ontap-software["在 ONTAP 软件上配置帧的按顺序交付或无序交付"]

.步骤
. 禁用 FCVI 和存储 HBA 端口：
+
` * portcfgpersistentdisable _port number_*`

+
默认情况下，前 8 个端口（端口 0 到 7 ）用于 FCVI 和存储 HBA 。必须持久禁用这些端口，以便在交换机重新启动时，这些端口仍保持禁用状态。

+
以下示例显示了两台交换机上的 ISL 端口 0-7 均已禁用：

+
[listing]
----

    Switch_A_1:admin> portcfgpersistentdisable 0-7
    Switch_B_1:admin> portcfgpersistentdisable 0-7
----
. 根据需要更改 ISL 端口。
+
|===
| 选项 | 步骤 


 a| 
要更改 ISL 端口的速度 ...
 a| 
在网络结构上的两台交换机上使用 ` * portcfgspeed _port number port speed_*` 命令。

在以下示例中，将 ISL 端口速度从 40 Gbps 更改为 16 Gbps ：

` * Brocade_switch_A_1 ： admin> portcfgspeed 40 16*`

您可以使用 `sswitchshow` 命令验证速度是否已更改：

` * Brocade_switch_A_1 ： admin> switchshow*`

您应看到以下输出：

[listing]
----
    . . .
    	   40  40   062800   id    16G	   No_Sync     FC  Disabled
    	. . .
----


 a| 
更改 ISL 端口的距离
 a| 
对网络结构中的两个交换机使用 ` * portcfglongdistance _port number port distance_*` 命令。



 a| 
要删除 ISL ...
 a| 
断开链路（缆线）。



 a| 
要添加 ISL ...
 a| 
将 SFP 插入要添加为 ISL 端口的端口。确保这些端口列在要添加到的交换机的 * 光纤连接 MetroCluster 安装和配置指南 * 中，并根据本指南为其布线。



 a| 
重新定位 ISL
 a| 
重新定位 ISL 与删除然后添加 ISL 相同。首先，断开链路以删除 ISL ，然后将 SFP 插入要添加为 ISL 端口的端口。

|===
. 重新配置无序交付（ OOD ）或按顺序交付（ IOD ）。
+

NOTE: 如果路由策略保持不变，则无需重新配置，可以忽略此步骤。ONTAP 配置需要与网络结构配置匹配。如果为网络结构配置了 OOD ，则还必须为 ONTAP 配置 OOD 。IOD 也是如此。

+
应在以下情况下执行此步骤：

+
** 更改前，多个 ISL 构成一个中继，但更改后，不再支持中继。在这种情况下，您必须为 OOD 配置网络结构。
** 更改前有一个 ISL ，更改后有多个 ISL 。
** 如果多个 ISL 构成一个中继，请为 IOD 配置网络结构。如果多个 ISL 不能构成中继，请为网络结构配置 OOD 。
** 使用 ` * switchcfgpersistentdisable*` 命令持久禁用交换机，如以下示例所示：
+
[listing]
----

Switch_A_1:admin> switchcfgpersistentdisable
Switch_B_1:admin> switchcfgpersistentdisable
----
+
... 为每个 ISL ` * 端口 cfgtrunkport _port number_*` 配置中继模式，如下表所示：
+
|===
| 场景 | 步骤 


 a| 
为 ISL 配置中继 \ （ IOD\ ）
 a| 
将 ` * portcfgtrunkport _port number_*` 设置为 1 ：

....
FC_switch_A_1:admin> portcfgtrunkport 20 1
FC_switch_A_1:admin> portcfgtrunkport 21 1
FC_switch_B_1:admin> portcfgtrunkport 20 1
FC_switch_B_1:admin> portcfgtrunkport 21 1
....


 a| 
为 ISL 配置中继 \ （ OOD \ ）
 a| 
将 ` * portcfgtrunkport _port number_*`` 设置为 0 ： ```

....
FC_switch_A_1:admin> portcfgtrunkport 20 0
FC_switch_A_1:admin> portcfgtrunkport 21 0
FC_switch_B_1:admin> portcfgtrunkport 20 0
FC_switch_B_1:admin> portcfgtrunkport 21 0
```
....
|===
... 根据需要为网络结构配置 IOD 或 OOD 。
+
|===


| 场景 | 步骤 


 a| 
为 IOD 配置网络结构
 a| 
使用 ` * iodset*` ， ` * aptpolicy*` 和 ` * dlsreset*` 命令设置 IOD ， APT 和 DLS 的三个设置，如以下示例所示：

....
Switch_A_1:admin> iodset
Switch_A_1:admin> aptpolicy 1
Policy updated successfully.
Switch_A_1:admin> dlsreset
FC_switch_A_1:admin>portcfgtrunkport 40 1
FC_switch_A_1:admin>portcfgtrunkport 41 1
....
....
Switch_B_1:admin> iodset
Switch_B_1:admin> aptpolicy 1
Policy updated successfully.
Switch_B_1:admin> dlsreset
FC_switch_B_1:admin>portcfgtrunkport 20 1
FC_switch_B_1:admin>portcfgtrunkport 21 1
....


 a| 
为网络结构配置 OOD
 a| 
使用 ` * iodreset*` ， ` * aptpolicy__policy___*` 和 ` * dlsset*` 命令设置 IOD ， APT 和 DLS 的三个设置，如以下示例所示：

....
Switch_A_1:admin> iodreset
Switch_A_1:admin> aptpolicy 3
Policy updated successfully.
Switch_A_1:admin> dlsset
FC_switch_A_1:admin> portcfgtrunkport 40 0
FC_switch_A_1:admin> portcfgtrunkport 41 0
....
....
Switch_B_1:admin> iodreset
Switch_B_1:admin> aptpolicy 3
Policy updated successfully.
Switch_B_1:admin> dlsset
FC_switch_B_1:admin> portcfgtrunkport 40 0
FC_switch_B_1:admin> portcfgtrunkport 41 0
....
|===
... 使用 ` * switchcfgpersistentenable*` 命令持久启用交换机。
+
[listing]
----
switch_A_1:admin>switchcfgpersistentenable
switch_B_1:admin>switchcfgpersistentenable
----
+
如果此命令不存在，请使用 `sswitchm enable` 命令，如以下示例所示：

+
[listing]
----
brocade_switch_A_1:admin>
switchenable
----
... 使用 ` * iodshow*` ， ` * aptpolicy*` 和 ` * dlsshow*` 命令验证 OOD 设置，如以下示例所示：
+
[listing]
----
switch_A_1:admin> iodshow
IOD is not set

switch_A_1:admin> aptpolicy

                Current Policy: 3 0(ap)

                3 0(ap) : Default Policy
                1: Port Based Routing Policy
                3: Exchange Based Routing Policy
                     0: AP Shared Link Policy
                     1: AP Dedicated Link Policy
                command aptpolicy completed

switch_A_1:admin> dlsshow
DLS is set by default with current routing policy
----
+

NOTE: 您必须在两台交换机上运行这些命令。

... 使用 ` * iodshow*` ， ` * aptpolicy*` 和 ` * dlsshow*` 命令验证 IOD 设置，如以下示例所示：
+
[listing]
----
switch_A_1:admin> iodshow
IOD is set

switch_A_1:admin> aptpolicy
                    Current Policy: 1 0(ap)

                    3 0(ap) : Default Policy
                    1: Port Based Routing Policy
                    3: Exchange Based Routing Policy
                         0: AP Shared Link Policy
                         1: AP Dedicated Link Policy
                    command aptpolicy completed

switch_A_1:admin> dlsshow
DLS is not set
----
+

NOTE: 您必须在两台交换机上运行这些命令。





. 使用 ` * islshow*` 和 ` * trunkshow*` 命令验证 ISL 是否联机并已中继（如果链路设备支持中继）。
+

NOTE: 如果启用了 FEC ，则中继组的最后一个联机端口的 deskew 值可能会显示多达 36 的差异，尽管所有缆线的长度都相同。

+
|===
| ISL 是否已中继？ | 您将看到以下系统输出 ... 


 a| 
是的。
 a| 
如果 ISL 已中继，则 ` * islshow*` 命令的输出中仅显示一个 ISL 。根据中继主端口的类型，可以显示端口 40 或 41 。` * trunkshow*` 的输出应包含一个 ID 为 "1" 的中继，其中列出了端口 40 和 41 上的两个物理 ISL 。在以下示例中，端口 40 和 41 配置为用作 ISL ：

[listing]
----
switch_A_1:admin> islshow 1:
40-> 40 10:00:00:05:33:88:9c:68 2 switch_B_1 sp: 16.000G bw: 32.000G TRUNK CR_RECOV FEC
switch_A_1:admin> trunkshow
1: 40-> 40 10:00:00:05:33:88:9c:68 2 deskew 51 MASTER
41-> 41 10:00:00:05:33:88:9c:68 2 deskew 15
----


 a| 
否
 a| 
如果 ISL 未中继，则两个 ISL 会分别显示在 ` * islshow*` 和 ` * trunkshow*` 的输出中。这两个命令都会列出 ID 为 "1" 和 "2" 的 ISL 。在以下示例中，端口 40 和 41 配置为用作 ISL ：

[listing]
----
switch_A_1:admin> islshow
1: 40-> 40 10:00:00:05:33:88:9c:68 2 switch_B_1 sp: 16.000G bw: 16.000G TRUNK CR_RECOV FEC
2: 41-> 41 10:00:00:05:33:88:9c:68 2 switch_B_1 sp: 16.000G bw: 16.000G TRUNK CR_RECOV FEC
switch_A_1:admin> trunkshow
1: 40-> 40 10:00:00:05:33:88:9c:68 2 deskew 51 MASTER
2: 41-> 41 10:00:00:05:33:88:9c:68 2 deskew 48 MASTER
----
|===
. 在两个交换机上运行 ` * spinfoab*` 命令，以验证 ISL 是否运行正常：
+
[listing]
----
switch_A_1:admin> spinfab -ports 0/40 - 0/41
----
. 启用步骤 1 中禁用的端口：
+
` * 端口启用 _port number_*`

+
以下示例显示 ISL 端口 0-7 已启用：

+
[listing]
----
brocade_switch_A_1:admin> portenable 0-7
----

