---
permalink: maintain/task_update_firmware_on_a_fibrebridge_bridge_parent_topic.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, update, firmware, fibrebridge, bridge, update, configuration 
summary: 用于更新网桥固件的操作步骤取决于您的网桥型号和 ONTAP 版本。 
---
= 更新 FibreBridge 网桥上的固件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
用于更新网桥固件的操作步骤取决于您的网桥型号和 ONTAP 版本。

.关于此任务
link:enable-console-logging-before-maintenance.html["启用控制台日志记录"] 执行此任务之前。



== 更新运行 ONTAP 9.4 及更高版本的配置中 FibreBridge 7600N 或 7500N 网桥上的固件

您可能需要更新 FibreBridge 网桥上的固件，以确保具有最新功能或解决可能的问题。在运行 ONTAP 9.4 及更高版本的配置中，应将此操作步骤用于 FibreBridge 7600N 或 7500N 网桥。

* MetroCluster 配置必须运行正常。
* MetroCluster 配置中的所有 FibreBridge 网桥都必须已启动且正常运行。
* 所有存储路径都必须可用。
* 您需要管理员密码以及对 HTTP、FTP 或简单文件传输协议 (TFTP) 服务器的访问权限。
* 您必须使用受支持的固件版本。
+
https://mysupport.netapp.com/matrix["NetApp 互操作性表工具"^]

+
在 IMT 中，您可以使用 Storage 解决方案字段选择 MetroCluster 解决方案。您可以使用 * 组件资源管理器 * 来选择组件和 ONTAP 版本以细化搜索范围。您可以单击 * 显示结果 * 以显示与此条件匹配的受支持配置列表。

* 只能在运行 ONTAP 9.4 或更高版本的配置中的 FibreBridge 7600N 或 7500N 网桥上使用此任务。
* 您必须对 MetroCluster 配置中的每个 FibreBridge 网桥执行此任务，以使所有网桥都运行相同版本的固件。



NOTE: 此操作步骤不会造成系统中断，大约需要 30 分钟才能完成。


NOTE: 从ONTAP 9．8开始，此 `system bridge`命令将取代 `storage bridge`。以下步骤显示了 `system bridge`命令、但如果您运行的版本早于ONTAP 9。8、则应使用命令。 `storage bridge`

.步骤
. 调用指示维护开始的 AutoSupport 消息：
+
`ssystem node AutoSupport invoke -node * -type all -message MAIN=_maintenance-window-in-hours_`

+
" `maintenance-window-in-hours` " 指定维护时段的长度，最长为 72 小时。如果在该时间过后完成维护，您可以调用一条 AutoSupport 消息，指示维护期结束：

+
`ssystem node AutoSupport invoke -node * -type all -message MAINT=end`

. 转至 ATTO FibreBridge 页面，然后为网桥选择适当的固件。
+
https://mysupport.netapp.com/site/products/all/details/atto-fibrebridge/downloads-tab["ATTO FibreBridge 固件下载页面"^]

. 查看 Caution/MustRead 和最终用户协议，然后单击复选框以指示接受并继续。
. 将固件文件置于控制器模块可通过网络访问的网络位置。
+
您可以从任一控制器模块的控制台输入其余步骤中的命令。

. 更改为高级权限级别：
+
`set -privilege advanced`

+
在系统提示您继续进入高级模式并查看高级模式提示符（ * > ）时，您必须回答 "`y` " 。

. 更新网桥固件。
+
从ONTAP 9．16．1开始，如果服务器需要使用凭据来下载固件包，则可以使用凭据来更新网桥固件。

+
[role="tabbed-block"]
====
.如果不需要凭据：
--
.. 更新网桥固件：


[source, cli]
----
system bridge firmware update -bridge <name> -uri <URL-of-firmware-package>
----
.示例
[listing]
----
cluster_A> system bridge firmware update -bridge bridge_A_1a -uri http://192.168.132.97/firmware.ZBD
----
--
.如果需要凭据：
--
.. 更新网桥固件并指定所需的用户名：
+
[source, cli]
----
system bridge firmware update -bridge <name> -uri <URL-of-firmware-package> -username <name>
----
.. 在输出中出现提示时输入密码、如以下示例所示：


.示例
[listing]
----
cluster_A> system bridge firmware update -bridge bridge_A_1a -uri http://192.168.132.97/firmware.ZBD -username abc

(system bridge)

Enter the password:

[Job 70] Job is queued: System bridge firmware update job.
----
--
====
. 返回到管理权限级别：
+
`set -privilege admin`

. 验证固件升级是否已完成：
+
`job show -name "<job_name>"`

+
以下示例显示作业"`ssystem bridge固件更新`"仍在运行：

+
[listing]
----
cluster_A> job show -name "system bridge firmware update"
Owning

Job ID Name                 Vserver    Node           State
------ -------------------- ---------- -------------- ----------
2246   job-name
                            cluster_A
                                       node_A_1
                                                      Running
Description: System bridge firmware update job
----
+
大约 10 分钟后，新固件将完全安装完毕，作业状态将为成功：

+
[listing]
----
cluster_A> job show -name "system bridge firmware update"

                            Owning
Job ID Name                 Vserver    Node           State
------ -------------------- ---------- -------------- ----------
2246   System bridge firmware update
                            cluster_A
                                       node_A_1
                                                      Success
Description: System bridge firmware update job
----
. 根据是否已启用带内管理以及您的系统运行的 ONTAP 版本完成以下步骤：
+
** 如果您运行的是 ONTAP 9.4 ，则不支持带内管理，并且必须从网桥控制台发出命令：
+
... 在网桥的控制台上运行 `flashimages` 命令，并确认显示的固件版本正确。
+

NOTE: 此示例显示主闪存映像显示新固件映像，而二级闪存映像显示旧映像。





+
[listing]
----
flashimages

 ;Type Version
;=====================================================
Primary 3.16 001H
Secondary 3.15 002S
Ready.
----
+
.. 在网桥上运行 `firmwarerestart` 命令，以重新启动网桥。
+
*** 如果您运行的是 ONTAP 9.5 或更高版本，则支持带内管理，并且可以从集群提示符处发出命令：


.. 运行 `system bridge run-cli -name <bridge_name> -command FlashImages`命令。
+

NOTE: 此示例显示主闪存映像显示新固件映像，而二级闪存映像显示旧映像。

+
[listing]
----
cluster_A> system bridge run-cli -name ATTO_7500N_IB_1 -command FlashImages

[Job 2257]

;Type         Version
;=====================================================
Primary 3.16 001H
Secondary 3.15 002S
Ready.


[Job 2257] Job succeeded.
----
.. 如有必要，重新启动网桥：
+
`system bridge run-cli -name ATTO_7500N_IB_1 -command FirmwareRestart`

+

NOTE: 从 ATTO 固件版本 2.95 开始，网桥将自动重新启动，不需要执行此步骤。



. 验证网桥是否已正确重新启动：
+
`ssysconfig`

+
系统布线时应使用多路径高可用性（两个控制器均可通过网桥访问每个堆栈中的磁盘架）。

+
[listing]
----
cluster_A> node run -node cluster_A-01 -command sysconfig
NetApp Release 9.6P8: Sat May 23 16:20:55 EDT 2020
System ID: 1234567890 (cluster_A-01); partner ID: 0123456789 (cluster_A-02)
System Serial Number: 200012345678 (cluster_A-01)
System Rev: A4
System Storage Configuration: Quad-Path HA
----
. 验证 FibreBridge 固件是否已更新：
+
`system bridge show -fields fw-version,symbolic-name`

+
[listing]
----
cluster_A> system bridge show -fields fw-version,symbolic-name
name fw-version symbolic-name
----------------- ----------------- -------------
ATTO_20000010affeaffe 3.10 A06X bridge_A_1a
ATTO_20000010affeffae 3.10 A06X bridge_A_1b
ATTO_20000010affeafff 3.10 A06X bridge_A_2a
ATTO_20000010affeaffa 3.10 A06X bridge_A_2b
4 entries were displayed.
----
. 从网桥的提示符处验证分区是否已更新：
+
`闪存映像`

+
主闪存映像显示新固件映像，而二级闪存映像显示旧映像。

+
[listing]
----
Ready.
flashimages

;Type         Version
;=====================================================
   Primary    3.16 001H
 Secondary    3.15 002S

 Ready.
----
. 重复步骤 5 至 10 ，以确保两个闪存映像均已更新到同一版本。
. 验证两个闪存映像是否已更新到同一版本。
+
`闪存映像`

+
对于这两个分区，输出应显示相同的版本。

+
[listing]
----
Ready.
flashimages

;Type         Version
;=====================================================
   Primary    3.16 001H
 Secondary    3.16 001H

 Ready.
----
. 对下一个网桥重复步骤 5 到 13 ，直到 MetroCluster 配置中的所有网桥都已更新为止。

