---
permalink: maintain/task_upgrade_or_downgrad_the_firmware_on_a_brocade_fc_switch_mcc.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, upgrade, downgrade, firmware, brocade, fc, switch 
summary: 要升级或降级 Brocade FC 交换机上的固件，必须使用 Brocade 专用命令禁用交换机，执行并验证固件更改，然后重新启动并重新启用交换机。 
---
= 升级或降级 Brocade FC 交换机上的固件
:icons: font
:imagesdir: ../media/


[role="lead"]
要升级或降级 Brocade FC 交换机上的固件，必须使用 Brocade 专用命令禁用交换机，执行并验证固件更改，然后重新启动并重新启用交换机。

* 您必须具有固件文件。
* 系统必须已正确布线。
* 存储架的所有路径都必须可用。
* 磁盘架堆栈必须稳定。
* FC 交换机网络结构必须运行状况良好。
* 系统中不能存在任何故障组件。
* 系统必须正常运行。
* 您必须具有管理员密码并能够访问 FTP 或 SCP 服务器。


在固件升级或降级期间，交换机网络结构将被禁用， MetroCluster 配置将依靠第二个网络结构继续运行。

必须连续对每个交换机网络结构执行此任务，以使所有交换机运行相同版本的固件。


NOTE: 此操作步骤不会造成系统中断，大约需要一小时才能完成。

.步骤
. 登录到网络结构中的每个交换机。
+
以下步骤中的示例使用交换机 `FC_switch_A_1` 。

. 禁用网络结构中的每个交换机：
+
` * switchCfgPersistentDisable*`

+
如果此命令不可用，请运行 `sswitch- Disable` 命令。

+
[listing]
----
FC_switch_A_1:admin> switchCfgPersistentDisable
----
. 下载所需的固件版本：
+
` * firmwaredownload*`

+
当系统提示您输入文件名时，您必须指定固件文件的子目录或相对路径。

+
您可以在两台交换机上同时运行 `firmwaredownload` 命令，但必须先允许固件正确下载并提交，然后再继续下一步。

+
[listing]
----
FC_switch_A_1:admin> firmwaredownload
Server Name or IP Address: 10.64.203.188
User Name: test
File Name: v7.3.1b
Network Protocol(1-auto-select, 2-FTP, 3-SCP, 4-SFTP) [1]: 2
Password:
Server IP: 10.64.203.188, Protocol IPv4
Checking system settings for firmwaredownload...
System settings check passed.
----
. 验证固件是否已下载并提交到两个分区：
+
` * 固件 *`

+
以下示例显示固件下载已完成，因为两个映像均已更新：

+
[listing]
----
FC_switch_A_1:admin> firmwareShow
Appl     Primary/Secondary Versions

------------------------------------------

FOS      v7.3.1b

         v7.3.1b
----
. 重新启动交换机：
+
` * 重新启动 *`

+
某些固件版本会在固件下载完成后自动执行 haReboot 操作。即使执行了 haReboot ，也需要在此步骤中重新启动。

+
[listing]
----
FC_switch_A_1:admin> reboot
----
. 检查新固件是适用于中间固件级别还是适用于最终指定版本。
+
如果下载适用于中间固件级别，请执行上述两个步骤，直到安装指定版本为止。

. 启用交换机：
+
` * switchCfgPersistentEnable*`

+
如果此命令不可用，则在执行 `reboot` 命令后，交换机应处于 `enabled` 状态。

+
[listing]
----
FC_switch_A_1:admin> switchCfgPersistentEnable
----
. 验证交换机是否联机以及所有设备是否均已正确登录：
+
` * switchshow*`

+
[listing]
----
FC_switch_A_1:admin> switchShow
----
. 验证交换机中某个端口组或所有端口组的缓冲区使用情况信息是否显示正确：
+
` * portbuffershow*`

+
[listing]
----
FC_switch_A_1:admin> portbuffershow
----
. 验证是否正确显示端口的当前配置：
+
` * portcfgshow*`

+
[listing]
----
FC_switch_A_1:admin> portcfgshow
----
+
验证端口设置，例如速度，模式，中继，加密， 和数据压缩，在交换机间链路（ ISL ）输出中。验证端口设置是否不受固件下载的影响。

. 在 ONTAP 中验证 MetroCluster 配置的运行情况：
+
.. 检查系统是否为多路径： + ` * node run -node _node-name_ sysconfig -A*`
.. 检查两个集群上是否存在任何运行状况警报： + ` * system health alert show*`
.. 确认 MetroCluster 配置以及操作模式是否正常： + ` * MetroCluster show*`
.. 执行 MetroCluster 检查： + ` * MetroCluster check run*`
.. 显示 MetroCluster 检查的结果： + ` * MetroCluster check show*`
.. 检查交换机上是否存在任何运行状况警报（如果存在）： + ` * storage switch show*`
.. 运行 Config Advisor 。
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp 下载： Config Advisor"]

.. 运行 Config Advisor 后，查看该工具的输出并按照输出中的建议解决发现的任何问题。


. 等待 15 分钟，然后对第二个交换机网络结构重复此操作步骤。

