---
permalink: maintain/task_migrating_root_agg_with_adp.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, migrate, root, aggregate, adp, disks, partition, advanced, disk, partitioning 
summary: '您可以无系统地迁移使用高级磁盘分区(ADP)的现有根聚合。' 
---
= 迁移在MetroCluster IP配置中使用ADP配置的根聚合
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


如果根聚合即将用尽空间、或者您希望从使用低容量SSD切换到使用大容量SSD、则可以无系统运行地迁移使用高级磁盘分区(ADP)的现有根聚合。

.关于此任务
* 必须启用本地高可用性(HA)对才能进行存储故障转移。
* 此操作步骤无中断。
* 此配置应处于稳定状态、并正常提供数据、而不会频繁中断。
* 在此操作步骤期间、请勿执行任何可能导致发生原因中断的硬件升级或任何其他操作。
* 一次只能迁移一个根聚合。请勿尝试同时迁移两个根聚合。


.步骤
. [[STEP_1、验证配置的运行状况]]检查配置的运行状况。
+
.. 检查每个集群上是否已配置 MetroCluster 并处于正常模式：
 +
`metrocluster show`
+
[listing]
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
----
.. 检查是否已在每个节点上启用镜像：
+
`MetroCluster node show`

+
[listing]
----
cluster_A::> metrocluster node show
DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------
1     cluster_A
              node_A_1       configured     enabled   normal
      cluster_B
              node_B_1       configured     enabled   normal
2 entries were displayed.
----
.. 检查 MetroCluster 组件是否运行正常：
+
`MetroCluster check run`

+
[listing]
----
cluster_A::> metrocluster check run

Last Checked On: 10/1/2014 16:03:37

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
4 entries were displayed.

Command completed. Use the "metrocluster check show -instance" command or sub-commands in "metrocluster check" directory for detailed results.
To check if the nodes are ready to do a switchover or switchback operation, run "metrocluster switchover -simulate" or "metrocluster switchback -simulate", respectively.
----
.. 检查是否没有运行状况警报：
+
`s系统运行状况警报显示`



. 确认已为本地HA对启用存储故障转移：
+
`s存储故障转移显示`

+
输出应指示两个节点均可进行接管：

+
[listing]
----
cluster_A::> storage failover show
                              Takeover
Node           Partner        Possible State Description
-------------- -------------- -------- ---------------------------
cluster-01     cluster-02      true     Connected to cluster-02

cluster-02     cluster-01      true     Connected to cluster-01
2 entries were displayed.
----
. 将备用磁盘置零：
+
`run * disk zero spares`

. 确定根聚合大小：
+
`node run local aggr status -r <root_agg_name>`

+
在以下示例中、根聚合的"Pool0"中有十个磁盘、"Pool1"中有十个磁盘。

+
[listing]
----
cluster_A::*> node run local aggr status -r <root_agg_name>
Aggregate <root_agg_name> (online, raid_dp, mirrored, fast zeroed) (block checksums)
  Plex /<root_agg_name>/plex0 (online, normal, active, pool0)
    RAID group /<root_agg_name>/plex0/rg0 (normal, block checksums, max_wdbn 5767167)

      RAID Disk Device  HA  SHELF BAY CHAN Pool Type  RPM  Used (MB/blks)    Phys (MB/blks)
      --------- ------  ------------- ---- ---- ---- ----- --------------    --------------
      dparity   e2a.11.0.0P3    e2a   11  0   NV:A   0 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      parity    e10b.11.3.1P3   e10b  11  1   NV:B   0 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      e2a.11.0.2P3    e2a   11  2   NV:A   0 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      e2a.11.0.3P3    e2a   11  3   NV:A   0 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      e2a.11.0.4P3    e2a   11  4   NV:A   0 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      e10b.11.3.5P3   e10b  11  5   NV:B   0 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      e10b.11.3.12P3  e10b  11  12  NV:B   0 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      e10b.11.3.13P3  e10b  11  13  NV:B   0 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      e10b.11.3.14P3  e10b  11  14  NV:B   0 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      e10b.11.3.15P3  e10b  11  15  NV:B   0 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)

  Plex /<root_agg_name>/plex2 (online, normal, active, pool1)
    RAID group /<root_agg_name>/plex2/rg0 (normal, block checksums, max_wdbn 5767167)

      RAID Disk Device  HA  SHELF BAY CHAN Pool Type  RPM  Used (MB/blks)    Phys (MB/blks)
      --------- ------  ------------- ---- ---- ---- ----- --------------    --------------
      dparity   0m.i2.2L1P3     0m    22  5          1 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      parity    0m.i1.0L36P3    0m    22  14         1 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      0v.i2.2L18P3    0v    22  12         1 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      0v.i2.3L17P3    0v    22  2          1 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      0v.i1.0L25P3    0v    22  13         1 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      0v.i1.0L40P3    0v    22  4          1 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      0m.i1.1L39P3    0m    22  17         1 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      0m.i1.1L46P3    0m    22  15         1 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      0m.i2.3L13P3    0m    22  0          1 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      0v.i1.1L26P3    0v    22  1          1 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)

cluster_A::*>
----
. 分配容器磁盘。
+
在分配磁盘之前、请确认已为每个节点分配建议数量的备用驱动器。这些驱动器在迁移根聚合之前进行分区。有关详细信息，请参见 link:https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_drive_assignment.html["ONTAP 9.4 及更高版本中的自动驱动器分配和 ADP 系统注意事项"]。

+
运行以下命令以分配磁盘：

+
`storage disk assign -disklist 1.11.0,1.11.1,…  -owner cluster-01 -pool 0`

. 确定根分区大小。
+
根分区大小取决于每个节点上可用于分区的磁盘数。NetApp建议每个节点至少有12个驱动器可用于分区。

+
您可以使用下表确定根聚合布局：

+
[cols="25,75"]
|===
| 要分区的磁盘数 | 根聚合布局 


| 每个节点4个磁盘 | 2个数据驱动器和2个奇偶校验驱动器 


| 每个节点12个磁盘 | 8个数据驱动器、2个奇偶校验驱动器和2个备用驱动器 


| 每个节点24个磁盘 | 20个数据驱动器、2个奇偶校验驱动器和2个备用驱动器 
|===
+
为了确定根分区大小、您需要在所有数据驱动器之间平均划分4 k块的总数。

+
例如、如果根聚合布局包含8个数据驱动器、2个奇偶校验驱动器和2个备用驱动器、并且根聚合大小为112958795块、则必须将112958795除以8才能获得根分区大小。

+
(112958795/8)= 14119849.375

+
将此数字取整后、根分区大小为14119850。

. 对根聚合中的每个磁盘进行分区：
+
`cluster_A*> disk partition -n 3 -i 3 -b <root_partition_size> <disk_id>`

. 分配分区。
+

NOTE: 在使用 ADP 的系统中，聚合是使用分区创建的，其中每个驱动器都分区为 P1 ， P2 和 P3 分区。

+
.. 将P3分区分配给拥有容器磁盘的同一节点：
+
`storage disk assign -disk <disk_id> -root true -pool 0 -owner cluster-01`

.. 将P1分区分配给HA对中系统ID编号较低的系统：
+
`storage disk assign -disk <disk_id> -data1 true -pool 0 -owner cluster-01`

.. 将P2分区分配给HA对中系统ID编号较高的系统：
+
`storage disk assign -disk <disk_name> -data2 true -pool 0 -owner cluster-02`

+
对每个分区磁盘重复此步骤。



. 确认可以接管：
+
`s存储故障转移显示`

+
[listing]
----
cluster_A::> storage failover show
                              Takeover
Node           Partner        Possible State Description
-------------- -------------- -------- ---------------------------
cluster-01     cluster-02      true     Connected to cluster-02

cluster-02     cluster-01      true     Connected to cluster-01
2 entries were displayed.
----
. 迁移根聚合。
+
对于每个节点、执行迁移、并将Pool0中的磁盘列表和目标RAID类型指定为参数：

+
`system node migrate-root -node cluster-01 -disklist <pool0_disk_list> -raid-type <target_raid_type>`

+
例如、如果"cluster-01"的根聚合包含十个带有"Raif_DP"的磁盘、则以下命令将迁移根聚合：

+
[listing]
----
system node migrate-root -node cluster-01 -disklist 1.11.1.P3,1.11.2.P3,1.11.3.P3,1.11.4.P3,1.11.5.P3,1.11.6.P3,1.11.7.P3,1.11.8.P3,1.11.9.P3,1.11.10.P3 -raid-type raid_dp

Warning: This is a partially automated and guided procedure for migrating the
         root aggregate on the node "cluster-01".
         Negotiated switchover is about to start.
         Warning: This operation will create a new root aggregate and replace
         the existing root on the node "cluster-01". The existing root
         aggregate will be discarded.
Do you want to continue? {y|n}: y

Info: Started migrate-root job. Run "job show -id 51 -instance" command to
      check the progress of the job.
      Once the job is complete, mirror the root aggregate using the "storage
      aggregate mirror" command
----
+

IMPORTANT: 如果磁盘数量不足、请添加更多磁盘或选择其他RAID类型。

+
此迁移过程可能需要几分钟才能完成。迁移期间、节点会重新启动几次、而其他节点上可能会出现错误、您可以安全地忽略这些错误、并等待迁移过程完成。

. (可选)监控迁移进度。
+
从第二个站点运行：

+
`job show -id 51 -instance`

. 为所有MetroCluster IP节点重新启用RAID自动分区：
+
`storage raidlm policy modify -node <node> -policy-name auto_partition_ssds_post_init -policy-type Shared-Disk -is-enable true`

. 验证迁移是否成功：
+
`run local aggr status -r <root_agg_name>`

+
[listing]
----
cluster_A::*> node run local aggr status -r <root_agg_name>
Aggregate <root_agg_name> (online, raid0, fast zeroed) (block checksums)
  Plex /<root_agg_name>/plex0 (online, normal, active, pool0)
    RAID group /<root_agg_name>/plex0/rg0 (normal, block checksums, max_wdbn 6127616)

      RAID Disk Device  HA  SHELF BAY CHAN Pool Type  RPM  Used (MB/blks)    Phys (MB/blks)
      --------- ------  ------------- ---- ---- ---- ----- --------------    --------------
      data      e2a.11.0.16P3   e2a   11  16  NV:A   0 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      e10b.11.3.17P3  e10b  11  17  NV:B   0 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)

cluster_A::*>
----
. 重复步骤至 <<step_1,验证配置的运行状况>>。

