---
permalink: maintain/task_do_not_use_for_9_8_and_later_reconfigure_the_fc_switch_layout_for_ontap_9_1_or_later.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, reconfigure, fc, switch, layout, configured 
summary: 如果现有 FC 交换机布局是在 ONTAP 9.1 之前配置的，则必须重新配置端口布局并应用最新的参考配置文件（ Reference Configuration Files ， RCF ）。此操作步骤仅适用于 MetroCluster FC 配置。 
---
= 重新配置在 ONTAP 9.x 之前配置的 FC 交换机布局
:icons: font
:imagesdir: ../media/


[role="lead"]
如果现有 FC 交换机布局是在 ONTAP 9.1 之前配置的，则必须重新配置端口布局并应用最新的参考配置文件（ Reference Configuration Files ， RCF ）。此操作步骤仅适用于 MetroCluster FC 配置。

您必须确定网络结构域中存在的 FC 交换机。

您需要管理员密码以及对 FTP 或 SCP 服务器的访问权限。

如果现有 FC 交换机布局是在 ONTAP 9.1 之前配置的，则必须执行此任务。如果要从为 ONTAP 9.1 或更高版本配置的现有交换机布局进行升级，则需要 _not_ 。

此操作步骤不会造成系统中断，在磁盘置零后，大约需要 4 小时才能完成（不包括机架和堆栈）。



== 在重新配置交换机之前发送自定义 AutoSupport 消息

在重新配置交换机问题描述之前，您应发送 AutoSupport 消息以通知 NetApp 技术支持正在进行维护。告知技术支持正在进行维护，可防止他们在假定已发生中断的情况下创建案例。

必须在每个 MetroCluster 站点上执行此任务。

.步骤
. 登录到集群。
. 调用指示维护开始的 AutoSupport 消息：
+
`ssystem node AutoSupport invoke -node * -type all -message MAIN=_maintenance-window-in-hours__*`

+
maintenance-window-in-hours 指定维护时段的长度，最长为 72 小时。如果在该时间过后完成维护，您可以调用一条 AutoSupport 消息，指示维护期结束：

+
`ssystem node AutoSupport invoke -node * -type all -message MAINT=end`

. 在配对站点上重复上述步骤。




== 验证 MetroCluster 配置的运行状况

您应检查 MetroCluster 配置的运行状况以验证是否正常运行。

.步骤
. 验证 MetroCluster 组件是否运行正常：
+
`MetroCluster check run`

+
[listing]
----
cluster_A::*> metrocluster check run

----
+
此操作将在后台运行。

. 在 `MetroCluster check run` 操作完成后，运行 `MetroCluster check show` 以查看结果。
+
大约五分钟后，将显示以下结果：

+
[listing]
----
-----------
cluster_A::*> metrocluster check show

Last Checked On: 4/7/2019 21:15:05

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          warning
clusters            ok
connections         not-applicable
volumes             ok
7 entries were displayed.
----
. 要检查正在运行的 MetroCluster 检查操作的状态，请使用命令：
+
MetroCluster 操作历史记录显示 -job-id 38`

. 验证是否没有运行状况警报：
+
`s系统运行状况警报显示`





== 正在检查 MetroCluster 配置错误

您可以使用 NetApp 支持站点上提供的 Config Advisor 工具检查常见配置错误。

Config Advisor 是一款配置验证和运行状况检查工具。您可以将其部署在安全站点和非安全站点上，以便进行数据收集和系统分析。


NOTE: 对 Config Advisor 的支持是有限的，并且只能联机使用。

. 下载 Config Advisor 工具。
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp 下载： Config Advisor"^]

. 运行 Config Advisor ，查看输出并按照其建议解决任何问题。




== 持久禁用交换机

您必须持久禁用网络结构中的交换机，以便修改其配置。

您可以通过在交换机命令行上运行命令来禁用交换机；用于此操作的命令不是 ONTAP 命令。

.步骤
. 持久禁用交换机：
+
** 使用以下命令持久禁用 Brocade 交换机：
+
`FC_switch_A_1 ： admin> switchCfgPersistentDisable`

** 使用以下命令持久禁用 Cisco 交换机：
+
`vsan vsna #] suspend`







== 确定新的布线布局

您必须确定新控制器模块和任何新磁盘架到现有 FC 交换机的布线。

必须在每个 MetroCluster 站点上执行此任务。

.步骤
. 使用 ... https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/index.html["光纤连接的 MetroCluster 安装和配置"^] 要确定交换机类型的布线布局，请使用八节点 MetroCluster 配置的端口使用情况。
+
FC 交换机端口使用情况必须与指南中所述的使用情况匹配，才能使用参考配置文件（ Reference Configuration Files ， RCF ）。

+

NOTE: 如果您的环境无法使用 RCF 进行布线，请联系技术支持。如果布线无法使用操作步骤，请勿使用此 RCF 。





== 应用 RCF 文件并重新为交换机布线

您必须应用适当的参考配置（ RCF ）文件来重新配置交换机以容纳新节点。应用 RCF 文件后，您可以对交换机进行重新布线。

FC 交换机端口使用情况必须与中所述的使用情况匹配 https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/index.html["光纤连接的 MetroCluster 安装和配置"^] 以便可以使用 RCF 。

.步骤
. 找到适用于您的配置的 RCF 文件。
+
您必须使用与您的交换机型号匹配的 RCF 文件。

. 按照下载页面上的说明应用 RCF 文件，并根据需要调整 ISL 设置。
. 验证是否已保存交换机配置。
. 使用在 " `D指定新布线布局` " 一节中创建的布线布局，将两个 FC-SAS 网桥连接到 FC 交换机。
. 验证端口是否联机：
+
** 对于 Brocade 交换机，请使用 `sswitchshow` 命令。
** 对于 Cisco 交换机，请使用 `show interface brief` 命令。


. 使用缆线将控制器中的 FC-VI 端口连接到交换机。
. 从现有节点中，验证 FC-VI 端口是否联机：
+
`MetroCluster 互连适配器 show`

+
`MetroCluster 互连镜像显示`





== 持久启用交换机

您必须持久启用网络结构中的交换机。

.步骤
. 持久启用交换机：
+
** 对于 Brocade 交换机，请使用 `sswitch/CfgPersistentenable` 命令。
** 对于 Cisco 交换机，请使用 no `susPEND` 命令。以下命令将持久启用 Brocade 交换机：
+
[listing]
----
FC_switch_A_1:admin> switchCfgPersistentenable
----
+
以下命令将启用 Cisco 交换机：

+
[listing]
----
vsan [vsna #]no suspend
----






== 验证切换，修复和切回

您应验证 MetroCluster 配置的切换，修复和切回操作。

. 使用中所述的协商切换，修复和切回过程 https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/index.html["MetroCluster 管理和灾难恢复"^]。

