---
permalink: maintain/task_disable_encryption_on_brocade_fc_switches.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, disable, encryption, brocade, fc, switch 
summary: 您可能需要在 Brocade FC 交换机上禁用加密。 
---
= 在 Brocade FC 交换机上禁用加密
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可能需要在 Brocade FC 交换机上禁用加密。

.步骤
. 从两个站点发送一条 AutoSupport 消息，指示开始维护。
+
[listing]
----
cluster_A::> autosupport invoke -node * -type all -message MAINT=4h
----
+
[listing]
----
cluster_B::> autosupport invoke -node * -type all -message MAINT=4h
----
. 从集群 A 验证 MetroCluster 配置的运行情况
+
.. 确认 MetroCluster 配置以及操作模式是否正常： + ` * MetroCluster show*`
+
[listing]
----
cluster_A::> metrocluster show
----
.. 执行 MetroCluster 检查： + ` * MetroCluster check run*`
+
[source, nolinebreak]
----
cluster_A::> metrocluster check run
----
.. 显示 MetroCluster 检查的结果： + ` * MetroCluster check show*`
+
[source, nolinebreak]
----
cluster_A::> metrocluster check show
----


. 检查两个交换机的状态：
+
` * 网络结构显示 *`

+
[listing]
----
switch_A_1:admin> fabric show
----
+
[listing]
----
switch_B_1:admin> fabric show
----
. 禁用两个交换机：
+
` * 交换机禁用 *`

+
[listing]
----
switch_A_1:admin> switchdisable
----
+
[listing]
----
switch_B_1:admin> switchdisable
----
. 检查每个集群上节点的可用路径：
+
` * sysconfig*`

+
[listing]
----
cluster_A::> system node run -node node-name -command sysconfig -a
----
+
[listing]
----
cluster_B::> system node run -node node-name -command sysconfig -a
----
+
由于交换机网络结构现在已禁用，因此系统存储配置应为单路径 HA 。

. 检查两个集群的聚合状态。
+
[listing]
----
cluster_A::> aggr status
----
+
[listing]
----
cluster_B::> aggr status
----
+
系统输出应显示两个集群的聚合均已镜像且正常：

+
[listing]
----
mirrored,normal
----
. 在两台交换机上的管理提示符处重复以下子步骤。
+
.. 显示哪些端口已加密： + ` * portenccompshow*`
+
[listing]
----
switch_A_1:admin> portenccompshow
----
.. 在加密端口上禁用加密： + ` * portcfgencrypt – disable _port-number_*`
+
[listing]
----
switch_A_1:admin> portcfgencrypt --disable 40
switch_A_1:admin> portcfgencrypt --disable 41
switch_A_1:admin> portcfgencrypt --disable 42
switch_A_1:admin> portcfgencrypt --disable 43
----
.. 将身份验证类型设置为 all ：
+
` * authUtil -set -a all*`

+
[listing]
----
switch_A_1:admin> authUtil --set -a all
----
.. 在交换机上设置身份验证策略。to off ： + ` * authutil -policy -sw off*`
+
[listing]
----
switch_A_1:admin> authutil --policy -sw off
----
.. 将身份验证 Diffie-hellman 组设置为 +++ ： + ` * authutil -set -g`
+
[listing]
----
switch_A_1:admin> authUtil --set -g *
----
.. 删除密钥数据库： + ` * secAuthSecret -remove -all*`
+
[listing]
----
switch_A_1:admin> secAuthSecret --remove -all
----
.. 确认已在以下端口上禁用加密： + ` * portenccompshow*`
+
[listing]
----
switch_A_1:admin> portenccompshow
----
.. 启用交换机： + ` * switchenable*`
+
[listing]
----
switch_A_1:admin> switchenable
----
.. 确认 ISL 的状态： + ` * islshow*`
+
[listing]
----
switch_A_1:admin> islshow
----


. 检查每个集群上节点的可用路径：
+
` * sysconfig*`

+
[listing]
----
cluster_A::> system node run -node * -command sysconfig -a
----
+
[listing]
----
cluster_B::> system node run -node * -command sysconfig -a
----
+
系统输出应指示系统存储配置已改回四路径 HA 。

. 检查两个集群的聚合状态。
+
[listing]
----
cluster_A::> aggr status
----
+
[listing]
----
cluster_B::> aggr status
----
+
系统应显示两个集群的聚合均已镜像且正常运行，如以下系统输出所示：

+
[listing]
----
mirrored,normal
----
. 从集群 A 验证 MetroCluster 配置的运行情况
+
.. 执行 MetroCluster 检查： + ` * MetroCluster check run*`
+
[listing]
----
cluster_A::> metrocluster check run
----
.. 显示 MetroCluster 检查的结果： + ` * MetroCluster check show*`
+
[listing]
----
cluster_A::> metrocluster check show
----


. 从两个站点发送一条 AutoSupport 消息，指示维护结束。
+
[listing]
----
cluster_A::> autosupport invoke -node node-name -type all -message MAINT=END
----
+
[listing]
----
cluster_B::> autosupport invoke -node node-name -type all -message MAINT=END
----

