---
permalink: maintain/task_upgrade_firmware_on_mcc_ip_switches.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, upgrade, firmware. ip, switches, cisco, broadcom, efos, nxos, nx-os, software, install 
summary: 升级 MetroCluster IP 交换机上的固件。 
---
= 升级 MetroCluster IP 交换机上的固件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可能需要升级 MetroCluster IP 交换机上的固件。



== 验证RC框架 是否受支持

更改ONTAP版本或交换机固件版本时、您应验证是否具有该版本支持的参考配置文件(Reference Configuration File、RCF)。如果使用link:https://mysupport.netapp.com/site/tools/tool-eula/rcffilegenerator["RcfFileGenerator"^]工具、则会为您的配置生成正确的RCIF。

.步骤
. 从交换机使用以下命令验证RC框架 的版本：
+
[cols="30,70"]
|===


| 从此交换机 ... | 问题描述此命令 ... 


 a| 
Broadcom交换机
 a| 
` （ IP_switch_A_1 ） # show clibanner`



 a| 
Cisco 交换机
 a| 
`IP_switch_A_1# show banner motd`



 a| 
NVIDIA SN2100交换机
 a| 
`cumulus@mcc1:mgmt:~$ nv config find message`

|===
+
在命令输出中找到指示RCF版本的行。例如、Cisco交换机的以下输出指示RCF版本为"`v1．0"`。

+
....
Filename : NX3232_v1.80_Switch-A2.txt
....
. 要检查特定ONTAP版本、交换机和平台支持哪些文件，请使用link:https://mysupport.netapp.com/site/tools/tool-eula/rcffilegenerator["适用于 MetroCluster IP 的 RcfFileGenerator"^]。如果您可以为已有或要升级到的配置生成RCN、则它受支持。
. 要验证是否支持交换机固件，请参阅以下内容：
+
** https://hwu.netapp.com["Hardware Universe"]
** https://imt.netapp.com/matrix/["NetApp 互操作性表"^]






== 升级交换机固件

.关于此任务
您必须连续对每个交换机重复此任务。

link:enable-console-logging-before-maintenance.html["启用控制台日志记录"] 执行此任务之前。

[[step_1_fw_upgrade]]
.步骤
. 检查配置的运行状况。
+
.. 检查每个集群上是否已配置 MetroCluster 并处于正常模式：
+
`MetroCluster show`

+
[listing]
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
----
.. 检查是否已在每个节点上启用镜像：
+
`MetroCluster node show`

+
[listing]
----
cluster_A::> metrocluster node show
DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              node_A_1       configured     enabled   normal
      cluster_B
              node_B_1       configured     enabled   normal
2 entries were displayed.
----
.. 检查 MetroCluster 组件是否运行正常：
+
`MetroCluster check run`

+
[listing]
----
cluster_A::*> metrocluster check run
----
+
此操作将在后台运行。

.. 在之后 `metrocluster check run` 操作完成、运行：
+
MetroCluster check show`

+
大约五分钟后，将显示以下结果：

+
[listing]
----
cluster_A:::*> metrocluster check show

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
clusters            ok
connections         ok
volumes             ok
7 entries were displayed.
----
.. 检查是否没有运行状况警报：
+
`s系统运行状况警报显示`



. 在第一台交换机上安装软件。
+

NOTE: 您必须按以下顺序在交换机上安装交换机软件： switch_A_1 ， switch_B_1 ， switch_A_2 ， switch_B_2 。

+
根据交换机类型是Broadcom、Cisco还是NVIDIA、按照相关主题中的步骤安装交换机软件：

+
** link:../install-ip/task_switch_config_broadcom.html#downloading-and-installing-the-broadcom-switch-efos-software["下载并安装Broadcom交换机EFOS软件"]
** link:../install-ip/task_switch_config_cisco.html#downloading-and-installing-the-cisco-switch-nx-os-software["下载并安装Cisco交换机NX-OS软件"]
** link:../install-ip/task_switch_config_nvidia.html#download-and-install-the-cumulus-software["下载并安装NVIDIA SN2100交换机Cumulus软件"]


. 对每个交换机重复上述步骤。
. 重复 <<step_1_fw_upgrade,第 1 步>> 以检查配置的运行状况。

