---
permalink: maintain/task_hot_add_a_stack_to_exist_7500n_pair.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, hot, add, stack, sas, disk, shelves, existing, pair, fibrebridge, bridge 
summary: 您可以将 SAS 磁盘架堆栈热添加到具有可用端口的一对现有 FibreBridge 7500N 网桥中。 
---
= 将 SAS 磁盘架堆栈热添加到一对现有 FibreBridge 7500N 网桥中
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以将 SAS 磁盘架堆栈热添加到具有可用端口的一对现有 FibreBridge 7500N 网桥中。

.开始之前
* 您必须已下载最新的磁盘和磁盘架固件。
* MetroCluster 配置中的所有磁盘架（现有磁盘架）必须运行相同版本的固件。如果一个或多个磁盘或磁盘架未运行最新固件版本，请在连接新磁盘或磁盘架之前更新固件。
+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["NetApp 下载：磁盘驱动器固件"^]

+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["NetApp 下载：磁盘架固件"^]

* FibreBridge 7500N 网桥必须已连接并具有可用的 SAS 端口。


编写此操作步骤时假定您使用的是建议的网桥管理界面： ATTO ExpressNAV 图形用户界面和 ATTO QuickNAV 实用程序。

您可以使用 ATTO ExpressNAV 图形用户界面配置和管理网桥，以及更新网桥固件。您可以使用 ATTO QuickNAV 实用程序配置网桥以太网管理 1 端口。

如果需要，您可以使用其他管理界面。这些选项包括使用串行端口或 Telnet 配置和管理网桥，配置以太网管理 1 端口，以及使用 FTP 更新网桥固件。如果您选择其中任何一个管理界面，则必须满足中的适用要求 link:reference_requirements_for_using_other_interfaces_to_configure_and_manage_fibrebridge_bridges.html["其他网桥管理接口"]。


IMPORTANT: 如果将 SAS 缆线插入错误的端口，则在从 SAS 端口拔下缆线时，必须至少等待 120 秒，然后再将缆线插入其他 SAS 端口。如果您未能执行此操作，系统将无法识别此缆线已移至其他端口。

.步骤
. 正确接地。
. 从任一控制器的控制台中，验证您的系统是否已启用磁盘自动分配：
+
`s存储磁盘选项 show`

+
自动分配列指示是否已启用磁盘自动分配。

+
[listing]
----

Node        BKg. FW. Upd.  Auto Copy   Auto Assign  Auto Assign Policy
----------  -------------  ----------  -----------  ------------------
node_A_1             on           on           on           default
node_A_2             on           on           on           default
2 entries were displayed.
----
. 禁用新堆栈的交换机端口。
. 更新每个网桥上的 FibreBridge 固件。
+
如果新网桥与配对网桥的类型相同，请升级到与配对网桥相同的固件。如果新网桥与配对网桥的类型不同，请升级到该网桥支持的最新固件以及 ONTAP 版本。请参见 _FibreBridge MetroCluster 维护指南 _ 中的 " 更新 FibreBridge 网桥上的固件 " 一节。

. 在对中的每个网桥上，启用要连接到新堆栈的 SAS 端口：
+
`sasportEnable _port-letter_`

+
两个网桥上必须使用相同的 SAS 端口（ B ， C 或 D ）。

. 保存配置并重新启动每个网桥：
+
`saveConfiguration Restart`

. 使用缆线将磁盘架连接到网桥：
+
.. 以菊花链方式连接每个堆栈中的磁盘架。
+
适用于您的磁盘架型号的《安装和服务指南》提供了有关以菊花链方式连接磁盘架的详细信息。

.. 对于每个磁盘架堆栈，使用缆线将第一个磁盘架的 IOM A 连接到 FibreBridge A 上的 SAS 端口 A ，然后使用缆线将最后一个磁盘架的 IOM B 连接到 FibreBridge B 上的 SAS 端口 A
+
link:../install-fc/index.html["光纤连接的 MetroCluster 安装和配置"]

+
link:../install-stretch/concept_considerations_differences.html["延伸型 MetroCluster 安装和配置"]

+
每个网桥都有一条路径通往其磁盘架堆栈；网桥 A 通过第一个磁盘架连接到堆栈的 A 侧，网桥 B 通过最后一个磁盘架连接到堆栈的 B 侧。

+

NOTE: 网桥 SAS 端口 B 已禁用。



. 验证每个网桥是否可以检测到网桥所连接的所有磁盘驱动器和磁盘架。
+
[cols="30,70"]
|===


| 如果您使用的是 ... | 那么 ... 


 a| 
ATTO ExpressNAV 图形用户界面
 a| 
.. 在支持的 Web 浏览器中，在浏览器框中输入网桥的 IP 地址。
+
此时将转到 ATTO FibreBridge 主页，其中包含一个链接。

.. 单击此链接，然后输入您的用户名以及在配置网桥时指定的密码。
+
此时将显示 ATTO FibreBridge 状态页面，左侧有一个菜单。

.. 单击菜单中的 * 高级 * 。
.. 查看已连接的设备：
+
`s星网`

.. 单击 * 提交 * 。




 a| 
串行端口连接
 a| 
查看已连接的设备：

`s星网`

|===
+
输出将显示网桥所连接的设备（磁盘和磁盘架）。输出行按顺序编号，以便您可以快速统计设备数量。

+

NOTE: 如果输出开头显示文本 `reonse truncated` ，则可以使用 Telnet 连接到网桥，然后使用 `sasargets` 命令查看所有输出。

+
以下输出显示已连接 10 个磁盘：

+
[listing]
----
Tgt VendorID ProductID        Type        SerialNumber
  0 NETAPP   X410_S15K6288A15 DISK        3QP1CLE300009940UHJV
  1 NETAPP   X410_S15K6288A15 DISK        3QP1ELF600009940V1BV
  2 NETAPP   X410_S15K6288A15 DISK        3QP1G3EW00009940U2M0
  3 NETAPP   X410_S15K6288A15 DISK        3QP1EWMP00009940U1X5
  4 NETAPP   X410_S15K6288A15 DISK        3QP1FZLE00009940G8YU
  5 NETAPP   X410_S15K6288A15 DISK        3QP1FZLF00009940TZKZ
  6 NETAPP   X410_S15K6288A15 DISK        3QP1CEB400009939MGXL
  7 NETAPP   X410_S15K6288A15 DISK        3QP1G7A900009939FNTT
  8 NETAPP   X410_S15K6288A15 DISK        3QP1FY0T00009940G8PA
  9 NETAPP   X410_S15K6288A15 DISK        3QP1FXW600009940VERQ
----
. 验证命令输出是否显示网桥已连接到堆栈中所有适当的磁盘和磁盘架。
+
[cols="30,70"]
|===


| 如果输出为 ... | 那么 ... 


 a| 
正确
 a| 
对其余每个网桥重复上述步骤。



 a| 
不正确
 a| 
.. 重复此步骤，使用缆线将磁盘架连接到网桥，以检查 SAS 缆线是否松动或更正 SAS 布线。
.. 对其余每个网桥重复上述步骤。


|===
. 从系统控制台将磁盘驱动器固件更新为最新版本：
+
`disk_FW_update`

+
您必须在两个控制器上运行此命令。

+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["NetApp 下载：磁盘驱动器固件"^]

. 按照所下载固件的说明将磁盘架固件更新为最新版本。
+
您可以从任一控制器的系统控制台中运行操作步骤中的命令。

+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["NetApp 下载：磁盘架固件"^]

. 如果您的系统未启用磁盘自动分配，请分配磁盘驱动器所有权。
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html["磁盘和聚合管理"^]

+

NOTE: 如果要在多个控制器之间拆分一个磁盘架堆栈的所有权，则必须在分配磁盘所有权之前禁用磁盘自动分配（ `s存储磁盘选项 modify -autodassign off *` from both nodes in the cluster ）； 否则，在分配任何一个磁盘驱动器时，其余磁盘驱动器可能会自动分配给同一个控制器和池。

+

NOTE: 在更新磁盘驱动器固件和磁盘架固件并完成此任务中的验证步骤之前，不得向聚合或卷添加磁盘驱动器。

. 为新堆栈启用交换机端口。
. 在 ONTAP 中验证 MetroCluster 配置的运行情况：
+
.. 检查系统是否为多路径：
+
`node run -node _node-name_ sysconfig -a`

.. 检查两个集群上是否存在任何运行状况警报：
+
`s系统运行状况警报显示`

.. 确认 MetroCluster 配置以及操作模式是否正常：
+
`MetroCluster show`

.. 执行 MetroCluster 检查：
+
`MetroCluster check run`

.. 显示 MetroCluster 检查的结果：
+
MetroCluster check show`

.. 检查交换机上是否存在任何运行状况警报（如果存在）：
+
`s存储开关显示`

.. 运行 Config Advisor 。
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp 下载： Config Advisor"^]

.. 运行 Config Advisor 后，查看该工具的输出并按照输出中的建议解决发现的任何问题。


. 如果适用，请对配对站点重复此操作步骤。

