---
permalink: maintain/task_upgrade_rcf_files_on_mcc_ip_switches.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, upgrade, rcf, files, ip, switches 
summary: 您可能需要升级 MetroCluster IP 交换机上的 RCF 文件。例如， ONTAP 升级或交换机固件升级都需要新的 RCF 文件。 
---
= 升级 MetroCluster IP 交换机上的 RCF 文件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可能需要升级 MetroCluster IP 交换机上的 RCF 文件。例如， ONTAP 升级或交换机固件升级都需要新的 RCF 文件。



== 确保 RCF 文件受支持

如果要更改交换机上运行的 ONTAP 版本，则应确保具有该版本支持的 RCF 文件。如果使用 RCF 生成器，则会为您生成正确的 RCF 文件。

.步骤
. 使用交换机上的以下命令验证 RCF 文件的版本：
+
[cols="30,70"]
|===


| 从此交换机 ... | 问题描述此命令 ... 


 a| 
Brocade 交换机
 a| 
` （ IP_switch_A_1 ） # show clibanner`



 a| 
Cisco 交换机
 a| 
`IP_switch_A_1# show banner motd`

|===
+
对于任一交换机，请在输出中找到指示 RCF 文件版本的行。例如，以下输出来自 Cisco 交换机，表示 RCF 文件版本为 "`v1.80` " 。

+
....
Filename : NX3232_v1.80_Switch-A2.txt
....
. 要检查特定 ONTAP 版本，交换机和平台支持哪些文件，请使用 RcfFileGenerator 。如果您可以为所拥有或要升级到的配置生成 RCF 文件，则支持此文件。
. 要验证是否支持交换机固件，请参阅以下内容：
+
** https://hwu.netapp.com["Hardware Universe"]
** https://mysupport.netapp.com/NOW/products/interoperability["NetApp 互操作性"]






== 升级 RCF 文件

如果要安装新的交换机固件，则必须先安装交换机固件，然后再升级 RCF 文件。

此操作步骤会中断升级 RCF 文件的交换机上的流量。应用新 RCF 文件后，流量将恢复。

.步骤
. 验证配置的运行状况。
+
.. 验证 MetroCluster 组件是否运行正常：
+
`MetroCluster check run`

+
[listing]
----
cluster_A::*> metrocluster check run

----


+
此操作将在后台运行。

+
.. 在 `MetroCluster check run` 操作完成后，运行 `MetroCluster check show` 以查看结果。
+
大约五分钟后，将显示以下结果：

+
[listing]
----
-----------
::*> metrocluster check show

Last Checked On: 4/7/2019 21:15:05

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          warning
clusters            ok
connections         not-applicable
volumes             ok
7 entries were displayed.
----
.. 检查正在运行的 MetroCluster 检查操作的状态：
+
MetroCluster 操作历史记录显示 -job-id 38`

.. 验证是否没有运行状况警报：
+
`s系统运行状况警报显示`



. 准备 IP 交换机以应用新的 RCF 文件。
+
按照适用于您的交换机供应商的步骤进行操作：

+
** link:../install-ip/task_switch_config_broadcom.html["将 Broadcom IP 交换机重置为出厂默认值"]
** link:../install-ip/task_switch_config_cisco.html["将 Cisco IP 交换机重置为出厂默认值"]


. 根据交换机供应商的不同、下载并安装IP RCF文件。
+

NOTE: 按以下顺序更新交换机：switch_A_1、Switch_B_1、Switch_A_2、Switch_B_2

+
** link:../install-ip/task_switch_config_broadcom.html#downloading-and-installing-the-broadcom-rcf-files["下载并安装 Broadcom IP RCF 文件"]
** link:../install-ip/task_switch_config_cisco.html#downloading-and-installing-the-cisco-ip-rcf-files["下载并安装 Cisco IP RCF 文件"]
+

NOTE: 如果您使用的是L2共享或L3网络配置、则可能需要调整中间/客户交换机上的ISL端口。交换机端口模式可能会从"访问"模式更改为"中继"模式。只有在交换机A_1和B_1之间的网络连接完全正常且网络运行状况良好的情况下、才能继续升级第二个交换机对(A_2、B_2)。




