---
permalink: maintain/task_upgrade_firmware_on_mcc_ip_switches.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, upgrade, firmware. ip, switches, cisco, broadcom, efos, nxos, nx-os, software, install 
summary: 升级 MetroCluster IP 交换机上的固件。 
---
= 升级 MetroCluster IP 交换机上的固件
:icons: font
:imagesdir: ../media/


[role="lead"]
您可能需要升级 MetroCluster IP 交换机上的固件。

您必须连续对每个交换机重复此任务。

.步骤
. 检查配置的运行状况。
+
.. 检查每个集群上是否已配置 MetroCluster 并处于正常模式：
+
`MetroCluster show`

+
[listing]
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
----
.. 检查是否已在每个节点上启用镜像：
+
`MetroCluster node show`

+
[listing]
----
cluster_A::> metrocluster node show
DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              node_A_1       configured     enabled   normal
      cluster_B
              node_B_1       configured     enabled   normal
2 entries were displayed.
----
.. 检查 MetroCluster 组件是否运行正常：
+
`MetroCluster check run`

+
[listing]
----
cluster_A::> metrocluster check run

Last Checked On: 10/1/2014 16:03:37

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
4 entries were displayed.

Command completed. Use the "metrocluster check show -instance" command or sub-commands in "metrocluster check" directory for detailed results.
To check if the nodes are ready to do a switchover or switchback operation, run "metrocluster switchover -simulate" or "metrocluster switchback -simulate", respectively.
----
.. 检查是否没有运行状况警报：
+
`s系统运行状况警报显示`



. 在第一台交换机上安装软件。
+

NOTE: 您必须按以下顺序在交换机上安装交换机软件： switch_A_1 ， switch_B_1 ， switch_A_2 ， switch_B_2 。

+
根据交换机类型是 Broadcom 还是 MetroCluster ，按照 _Broadcom IP 安装和配置 _ 信息相关主题中有关安装交换机软件的步骤进行操作：

+
** link:../install-ip/task_switch_config_broadcom.html#downloading-and-installing-the-broadcom-switch-efos-software["下载并安装 Broadcom 交换机 EFOS 软件"]
** link:../install-ip/task_switch_config_cisco.html#downloading-and-installing-the-cisco-switch-nx-os-software["下载并安装 Cisco 交换机 NX-OS 软件"]


. 对每个交换机重复上述步骤。
. 重复步骤 1 以检查配置的运行状况。

