---
permalink: maintain/verify-health-mcc-config.html 
sidebar: sidebar 
keywords: metrocluster, ip, fc, verify, health, troubleshoot, cli, system manager, error, event, problem, maintenance, fix, correction, check 
summary: 了解如何验证MetroCluster组件是否运行正常。 
---
= 验证MetroCluster配置的运行状况
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
了解如何验证MetroCluster组件是否运行正常。

.关于此任务
* 在MetroCluster IP和FC配置中、您可以使用命令行界面运行运行状况检查命令并验证MetroCluster组件的状态。
* 在运行ONTAP 9™8或更高版本的MetroCluster IP配置中，您还可以使用ONTAP系统管理器来监控运行状况检查警报并对其进行故障排除。


.步骤
根据您使用的是命令行界面还是System Manager、验证MetroCluster配置的运行状况。

[role="tabbed-block"]
====
.命令行界面
--
按照以下步骤使用命令行界面检查MetroCluster配置的运行状况。

.步骤
. 验证 MetroCluster 组件是否运行正常：
+
[source, cli]
----
metrocluster check run
----
+
[listing]
----
cluster_A::*> metrocluster check run
----
+
此操作将在后台运行。

. 操作完成后 `metrocluster check run`、显示结果：
+
[source, cli]
----
metrocluster check show
----
+
大约五分钟后，将显示以下结果：

+
[listing]
----
cluster_A:::*> metrocluster check show

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
clusters            ok
connections         ok
volumes             ok
7 entries were displayed.
----
. 检查正在运行的 MetroCluster 检查操作的状态：
+
[source, cli]
----
metrocluster operation history show -job-id <id>
----
. 验证是否没有运行状况警报：
+
[source, cli]
----
system health alert show
----


--
.ONTAP系统管理器(仅限MetroCluster IP)
--
从ONTAP 9．8开始，System Manager可以监控MetroCluster IP配置的运行状况，并帮助您识别和更正可能出现的问题。

System Manager会定期检查MetroCluster IP配置的运行状况。在信息板中查看 MetroCluster 部分时，通常会显示消息 MetroCluster systems are healthy 。

但是，发生问题时，此消息将显示事件数量。您可以单击此消息并查看以下组件的运行状况检查结果：

* 节点
* 网络接口
* 层（存储）
* 集群
* 连接
* 卷
* 配置复制


"* 状态 * " 列用于标识存在问题的组件， "* 详细信息 * " 列用于建议如何更正问题。

.步骤
. 在 System Manager 中，选择 * 信息板 * 。
. 在*Windows* MetroCluster部分中查看消息：
+
.. 如果此消息指示您的 MetroCluster 配置运行状况良好，并且集群与 ONTAP 调解器之间的连接运行状况良好（显示时带有复选标记），则表示您没有问题需要更正。
.. 如果消息列出了事件数量，或者连接已断开（显示为 "X" ），则继续执行下一步。


. 单击显示事件数量的消息。
+
此时将显示 MetroCluster 运行状况报告。

. 使用 * 详细信息 * 列中的建议对报告中显示的问题进行故障排除。
. 更正完所有问题后，单击 * 检查 MetroCluster 运行状况 * 。
+

NOTE: 在运行检查之前、您应执行所有故障排除任务、因为MetroCluster运行状况检查会占用大量资源。

+
MetroCluster 运行状况检查在后台运行。您可以在等待其他任务完成的同时处理这些任务。



--
====