---
permalink: install-stretch/concept_required_mcc_components_and_naming_conventions_for_two_node_bridge_attached_stretch_configurations_mcc.html 
sidebar: sidebar 
keywords: metrocluster, stretch, installation, required, hardware, components, naming, conventions, two, node, stretch, bridge 
summary: 在规划 MetroCluster 配置时，您必须了解所需的和支持的硬件和软件组件。为了方便和清晰起见，您还应了解整个文档中的示例中用于组件的命名约定。例如，一个站点称为站点 A ，另一个站点称为站点 B 
---
= 双节点桥接延伸型配置所需的 MetroCluster 硬件组件和命名约定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在规划 MetroCluster 配置时，您必须了解所需的和支持的硬件和软件组件。为了方便和清晰起见，您还应了解整个文档中的示例中用于组件的命名约定。例如，一个站点称为站点 A ，另一个站点称为站点 B



== 支持的软件和硬件

MetroCluster FC 配置必须支持硬件和软件。

https://hwu.netapp.com["NetApp Hardware Universe"]

使用 AFF 系统时，必须将 MetroCluster 配置中的所有控制器模块配置为 AFF 系统。



== MetroCluster 配置中的硬件冗余

由于 MetroCluster 配置中的硬件冗余，因此每个站点上的每个组件都有两个。随机地为站点分配字母 A 和 B ，并为各个组件分配编号 1 和 2 。



== 两个单节点 ONTAP 集群的要求

桥接延伸型 MetroCluster 配置需要两个单节点 ONTAP 集群。

在 MetroCluster 配置中，命名必须是唯一的。

示例名称：

* 站点 A ： cluster_A
* 站点 B ： cluster_B




== 需要两个存储控制器模块

桥接延伸型 MetroCluster 配置需要两个存储控制器模块。

控制器必须满足以下要求：

* 在 MetroCluster 配置中，命名必须是唯一的。
* MetroCluster 配置中的所有控制器模块都必须运行相同版本的 ONTAP 。
* 一个灾难恢复组中的所有控制器模块必须具有相同的型号。
* 一个 DR 组中的所有控制器模块都必须使用相同的 FC-VI 配置。
+
某些控制器模块支持两个 FC-VI 连接选项：

+
** 板载 FC-VI 端口
** 插槽 1 中的 FC-VI 卡
+
不支持一个控制器模块使用板载 FC-VI 端口，另一个控制器模块使用附加 FC-VI 卡。例如，如果一个节点使用板载 FC-VI 配置，则 DR 组中的所有其他节点也必须使用板载 FC-VI 配置。





示例名称：

* 站点 A ： controller_A_1
* 站点 B ： controller_B_1




== FC-SAS 网桥的要求

网桥连接的延伸型 MetroCluster 配置要求每个站点上有两个或更多 FC-SAS 网桥。

这些网桥用于将 SAS 磁盘架连接到控制器模块。


NOTE: 运行 ONTAP 9.8 及更高版本的配置不支持 FibreBridge 6500N 网桥。

* FibreBridge 7600N 和 7500N 网桥最多支持四个 SAS 堆栈。
* 每个堆栈可以使用不同型号的 IOM ，但一个堆栈中的所有磁盘架都必须使用相同型号。
+
支持的 IOM 型号取决于您运行的 ONTAP 版本。

* 在 MetroCluster 配置中，命名必须是唯一的。


此操作步骤中用作示例的建议名称用于标识网桥连接到的控制器模块和端口。

示例名称：

* 站点 A ：
+
** bridge_A_1_`` _ port-number_ _``
** bridge_A_2_`` _ port-number_ _``


* 站点 B ：
+
** Bridge_B_1_`` _ 端口编号 _ _``
** bridge_B_2_`` _ port-number_ _``






== 至少需要四个 SAS 磁盘架（建议）

桥接延伸型 MetroCluster 配置至少需要两个 SAS 磁盘架。但是，建议每个站点使用两个磁盘架，以便每个磁盘架都有磁盘所有权，总共四个 SAS 磁盘架。

每个站点至少支持一个磁盘架。

示例名称：

* 站点 A ：
+
** shelf_A_1_1
** shelf_A_1_2


* 站点 B ：
+
** shelf_B_1_1
** shelf_B_1_2






== 在一个堆栈中混用 IOM12 和 IOM 6 模块

您的 ONTAP 版本必须支持混用磁盘架。请参见互操作性表工具（ IMT ），了解您的 ONTAP 版本是否支持混用磁盘架。 https://mysupport.netapp.com/NOW/products/interoperability["NetApp 互操作性"^]

有关混用磁盘架的更多详细信息，请参见： https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-mix-hotadd/home.html["将带有 IOM12 模块的磁盘架热添加到带有 IOM6 模块的磁盘架堆栈中"^]
