---
permalink: manage/task_verify_a_successful_switchback.html 
sidebar: sidebar 
keywords: perform, switchback, aggregate, storage, virtual, machine, svm, switch, back, online, verify, successful 
summary: 执行切回后，您需要确认所有聚合和 Storage Virtual Machine \ （ SVM\ ）均已切回并联机。 
---
= 验证切回是否成功
:icons: font
:imagesdir: ../media/


[role="lead"]
执行切回后，您需要确认所有聚合和 Storage Virtual Machine （ SVM ）均已切回并联机。

. 验证切换后的数据聚合是否已切回：
+
`s存储聚合显示`

+
在以下示例中，节点 B2 上的 aggr_b2 已切回：

+
[listing]
----
node_B_1::> storage aggregate show
Aggregate     Size Available Used% State   #Vols  Nodes            RAID Status
--------- -------- --------- ----- ------- ------ ---------------- ------------
...
aggr_b2    227.1GB   227.1GB    0% online       0 node_B_2   raid_dp,
                                                                   mirrored,
                                                                   normal

node_A_1::> aggr show
Aggregate     Size Available Used% State   #Vols  Nodes            RAID Status
--------- -------- --------- ----- ------- ------ ---------------- ------------
...
aggr_b2          -         -     - unknown      - node_A_1
----
+
如果灾难站点包含未镜像聚合且未镜像聚合不再存在，则聚合可能会在 `storage aggregate show` 命令的输出中显示为 "`unknown` " 。请联系技术支持以删除未镜像聚合的过期条目。

. 验证运行正常的集群上的所有 sync-destination SVM 是否均处于休眠状态（显示管理状态为 `sstopped` ），以及灾难集群上的 sync-source SVM 是否已启动且正在运行：
+
`vserver show -subtype sync-source`

+
[listing]
----
node_B_1::> vserver show -subtype sync-source
                               Admin      Root                       Name    Name
Vserver     Type    Subtype    State      Volume     Aggregate       Service Mapping
----------- ------- ---------- ---------- ---------- ----------      ------- -------
...
vs1a        data    sync-source
                               running    vs1a_vol   node_B_2        file    file
                                                                     aggr_b2

node_A_1::> vserver show -subtype sync-destination
                               Admin      Root                         Name    Name
Vserver            Type    Subtype    State      Volume     Aggregate  Service Mapping
-----------        ------- ---------- ---------- ---------- ---------- ------- -------
...
cluster_A-vs1a-mc  data    sync-destination
                                      stopped    vs1a_vol   sosb_      file    file
                                                                       aggr_b2
----
+
MetroCluster 配置中的 sync-destination 聚合会在其名称中自动附加后缀 "` -mc` " ，以帮助标识它们。

. 使用 `MetroCluster operation show` 命令确认切回操作成功。
+
|===


| 如果命令输出显示 ... | 那么 ... 


 a| 
切回操作状态为成功。
 a| 
切回过程已完成，您可以继续操作系统。



 a| 
切回操作或切回 - 继续 - 代理操作已部分成功。
 a| 
执行 `MetroCluster operation show` 命令输出中建议的修复操作。

|===


您必须重复前面的部分，以反向执行切回。如果 site_A 已切换 site_B ，请让 site_B 切换 site_A
